Repository OCA/sale-workflow, pull requests merged in 2018-12, with the labels that each got.

#583 10 sale exception mig
  sale_exception/migrations/10.0.2.0.0/pre-migration.py
Labels: approved, needs review, ready to merge

#723 [11.0][FIX] sale_order_secondary_unit: define sale secondary uom in this module instead of product_secondary_unit
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/views/product_views.xml
Labels: approved

#716 [10.0][IMP] sale_order_type: find type by rule
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/models/__init__.py
  sale_order_type/models/account_invoice.py
  sale_order_type/models/sale_order.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/models/sale_order_type_rule.py
  sale_order_type/readme/CONFIGURE.rst
  sale_order_type/readme/CONTRIBUTORS.rst
  sale_order_type/readme/DESCRIPTION.rst
  sale_order_type/readme/ROADMAP.rst
  sale_order_type/readme/USAGE.rst
  sale_order_type/security/ir.model.access.csv
  sale_order_type/static/description/index.html
  sale_order_type/tests/__init__.py
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/tests/test_sale_order_type_rule.py
  sale_order_type/views/account_invoice_view.xml
  sale_order_type/views/sale_order_type_rule_view.xml
  sale_order_type/views/sale_order_type_view.xml
  sale_order_type/views/sale_order_view.xml
Labels: approved, ready to merge

#741 [IMP] sale_order_action_invoice_create_hook: Add more options to the hook
  sale_order_action_invoice_create_hook/__manifest__.py
  sale_order_action_invoice_create_hook/hooks.py
  sale_order_action_invoice_create_hook/model/sale_order.py
Labels: approved

#758 [11.0][MIG] sale_procurement_group_by_line
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved
