Repository OCA/sale-workflow, pull requests merged in 2018-04, with the labels that each got.

#626 [MIG] sale_order_invoicing_finished_task: Migration to 11.0
  sale_order_invoicing_finished_task/README.rst
  sale_order_invoicing_finished_task/__init__.py
  sale_order_invoicing_finished_task/__manifest__.py
  sale_order_invoicing_finished_task/i18n/ca.po
  sale_order_invoicing_finished_task/i18n/de.po
  sale_order_invoicing_finished_task/i18n/el_GR.po
  sale_order_invoicing_finished_task/i18n/es.po
  sale_order_invoicing_finished_task/i18n/es_ES.po
  sale_order_invoicing_finished_task/i18n/es_VE.po
  sale_order_invoicing_finished_task/i18n/fi.po
  sale_order_invoicing_finished_task/i18n/fr.po
  sale_order_invoicing_finished_task/i18n/hr.po
  sale_order_invoicing_finished_task/i18n/hr_HR.po
  sale_order_invoicing_finished_task/i18n/hu.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_invoicing_finished_task/i18n/nl.po
  sale_order_invoicing_finished_task/i18n/nl_NL.po
  sale_order_invoicing_finished_task/i18n/pt.po
  sale_order_invoicing_finished_task/i18n/pt_BR.po
  sale_order_invoicing_finished_task/i18n/ro.po
  sale_order_invoicing_finished_task/i18n/sk.po
  sale_order_invoicing_finished_task/i18n/sl.po
  sale_order_invoicing_finished_task/i18n/tr.po
  sale_order_invoicing_finished_task/i18n/tr_TR.po
  sale_order_invoicing_finished_task/i18n/vi_VN.po
  sale_order_invoicing_finished_task/i18n/zh_CN.po
  sale_order_invoicing_finished_task/models/__init__.py
  sale_order_invoicing_finished_task/models/product.py
  sale_order_invoicing_finished_task/models/project.py
  sale_order_invoicing_finished_task/models/sale_order.py
  sale_order_invoicing_finished_task/static/description/icon.png
  sale_order_invoicing_finished_task/static/description/product_view_invoicefinishedtask.png
  sale_order_invoicing_finished_task/static/description/task_view_invoicefinishedtask.png
  sale_order_invoicing_finished_task/tests/__init__.py
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
  sale_order_invoicing_finished_task/views/product_view.xml
  sale_order_invoicing_finished_task/views/project_view.xml
Labels: approved, needs review

#620 [8.0][ADD] sale_delivery_split_date module
  sale_delivery_split_date/README.rst
  sale_delivery_split_date/__init__.py
  sale_delivery_split_date/__openerp__.py
  sale_delivery_split_date/i18n/it.po
  sale_delivery_split_date/models/__init__.py
  sale_delivery_split_date/models/sale_order.py
  sale_delivery_split_date/models/sale_order_line.py
  sale_delivery_split_date/models/stock_picking.py
  sale_delivery_split_date/static/description/icon.png
  sale_delivery_split_date/tests/__init__.py
  sale_delivery_split_date/tests/test_sale_delivery.py
  sale_delivery_split_date/views/stock_picking.xml
Labels: 8.0, approved, needs review

#597 [10.0][FIX] Automatic sale workflow - Register payment multi-currency
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
Labels: needs review
