Repository OCA/sale-workflow, pull requests merged in 2018-11, with the labels that each got.

#732 [11.0][MIG] sales_team_security: Adaptation to v11 + enhancement
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
Labels: needs review

#738 [FIX] security
  sale_invoice_group_method/__manifest__.py
  sale_invoice_group_method/security/ir.model.access.csv
Labels: approved

#724 [11.0] [MIG] sale_order_line_sequence
  sale_order_line_sequence/README.rst
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/i18n/ca.po
  sale_order_line_sequence/i18n/de.po
  sale_order_line_sequence/i18n/el_GR.po
  sale_order_line_sequence/i18n/es.po
  sale_order_line_sequence/i18n/es_ES.po
  sale_order_line_sequence/i18n/es_VE.po
  sale_order_line_sequence/i18n/fi.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_line_sequence/i18n/hr.po
  sale_order_line_sequence/i18n/hr_HR.po
  sale_order_line_sequence/i18n/hu.po
  sale_order_line_sequence/i18n/it.po
  sale_order_line_sequence/i18n/nl.po
  sale_order_line_sequence/i18n/nl_NL.po
  sale_order_line_sequence/i18n/pt.po
  sale_order_line_sequence/i18n/pt_BR.po
  sale_order_line_sequence/i18n/ro.po
  sale_order_line_sequence/i18n/sale_order_line_sequence.pot
  sale_order_line_sequence/i18n/sk.po
  sale_order_line_sequence/i18n/sl.po
  sale_order_line_sequence/i18n/tr.po
  sale_order_line_sequence/i18n/tr_TR.po
  sale_order_line_sequence/i18n/vi_VN.po
  sale_order_line_sequence/i18n/zh_CN.po
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/__init__.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/readme/CONTRIBUTORS.rst
  sale_order_line_sequence/readme/CREDITS.rst
  sale_order_line_sequence/readme/DESCRIPTION.rst
  sale_order_line_sequence/static/description/index.html
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
Labels: approved, ready to merge

#747 avoid breaking inheritance
  sale_order_type/models/account_invoice.py
Labels: approved
