Repository OCA/sale-workflow, pull requests merged in 2019-09, with the labels that each got.

#865 [11.0][add][sale_stock_sourcing_address]
  sale_stock_sourcing_address/README.rst
  sale_stock_sourcing_address/__init__.py
  sale_stock_sourcing_address/__manifest__.py
  sale_stock_sourcing_address/models/__init__.py
  sale_stock_sourcing_address/models/account_invoice_line.py
  sale_stock_sourcing_address/models/sale_order_line.py
  sale_stock_sourcing_address/readme/CONFIGURE.rst
  sale_stock_sourcing_address/readme/CONTRIBUTORS.rst
  sale_stock_sourcing_address/readme/DESCRIPTION.rst
  sale_stock_sourcing_address/security/security.xml
  sale_stock_sourcing_address/static/description/icon.png
  sale_stock_sourcing_address/static/description/index.html
  sale_stock_sourcing_address/tests/__init__.py
  sale_stock_sourcing_address/tests/test_sale_stock_sourcing_address.py
  sale_stock_sourcing_address/views/account_invoice_view.xml
  sale_stock_sourcing_address/views/sale_order_view.xml
Labels: approved, ready to merge

#423 [9.0] [NEW] sale_double_validation
  sale_double_validation/README.rst
  sale_double_validation/__init__.py
  sale_double_validation/__openerp__.py
  sale_double_validation/models/__init__.py
  sale_double_validation/models/company.py
  sale_double_validation/models/sale.py
  sale_double_validation/static/description/icon.png
  sale_double_validation/tests/__init__.py
  sale_double_validation/tests/test_double_validation.py
  sale_double_validation/views/company.xml
  sale_double_validation/views/sale.xml
Labels: needs review

#748 [10.0] sale_force_invoiced: improve help message to help users
  sale_force_invoiced/model/sale_order.py
Labels: needs review

#941 [10.0][FIX] sale_exception: Add savepoint with assertRaise() + save time in tests
  sale_exception/tests/test_multi_records.py
  sale_exception/tests/test_sale_exception.py
Labels: approved

#531 [FIX][9.0] sale_automatic_workflow: Singleton error on automatic work…
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: needs review

#897 [12.0][ADD] product_form_sale_link
  product_form_sale_link/README.rst
  product_form_sale_link/__init__.py
  product_form_sale_link/__manifest__.py
  product_form_sale_link/readme/CONTRIBUTORS.rst
  product_form_sale_link/readme/DESCRIPTION.rst
  product_form_sale_link/readme/USAGE.rst
  product_form_sale_link/static/description/icon.png
  product_form_sale_link/static/description/index.html
  product_form_sale_link/static/description/product_sale.png
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
  setup/product_form_sale_link/odoo/addons/product_form_sale_link
  setup/product_form_sale_link/setup.py
Labels: approved, needs review, ready to merge

#540 [FIX] sale_rental: use v10 version for stock.location.path function
  sale_rental/models/stock.py
Labels: merged 🎉, needs review

#520 [9.0] ADD sequence to order sale order type in tree view
  sale_order_type/__openerp__.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/views/sale_order_type_view.xml
Labels: needs review

#916 [10.0] sale_exception: Remove side effect from api.constrains
  sale_exception/models/sale.py
Labels: approved, ready to merge
