Repository OCA/sale-workflow, pull requests merged in 2019-11, with the labels that each got.

#975 [10.0][FIX]sale_promotion_rule_assortment: return all lines if promotion rule is not limited to an assortment
  sale_promotion_rule_assortment/models/sale_promotion_rule.py
Labels: approved, ready to merge

#932 [10.0][ADD] Add behavior to auto-fill the automatic workflow with the payment mode (like sale order)
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/account_invoice.py
  sale_automatic_workflow_payment_mode/tests/__init__.py
  sale_automatic_workflow_payment_mode/tests/test_account_invoice.py
  sale_automatic_workflow_payment_mode/views/account_invoice.xml
Labels: approved, needs review, ready to merge

#986 [10.0][FIX] sale_stock_picking_note remove view who add twice note field into stock.picking
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/views/stock_picking_view.xml
Labels: approved, ready to merge

#991 [12.0][FIX] enable sale_merge_draft_invoice boolean
  sale_merge_draft_invoice/model/__init__.py
  sale_merge_draft_invoice/model/res_config_settings.py
  sale_merge_draft_invoice/readme/CONTRIBUTORS.rst
Labels: approved

#977 [ADD] sale_order_product_recommendation_secondary_unit: New module
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/__init__.py
  sale_order_product_recommendation_secondary_unit/__manifest__.py
  sale_order_product_recommendation_secondary_unit/i18n/es.po
  sale_order_product_recommendation_secondary_unit/i18n/sale_order_product_recommendation_secondary_unit.pot
  sale_order_product_recommendation_secondary_unit/readme/CONFIGURE.rst
  sale_order_product_recommendation_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation_secondary_unit/readme/DESCRIPTION.rst
  sale_order_product_recommendation_secondary_unit/readme/USAGE.rst
  sale_order_product_recommendation_secondary_unit/wizards/__init__.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
Labels: approved, needs review

#877 [10.0][FIX] Fix sale_promotion_rule in case of multi rules
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/tests/test_promotion.py
Labels: approved, needs review, ready to merge
