Repository OCA/sale-workflow, pull requests merged in 2019-05, with the labels that each got.

#833 [11.0][FIX] sale_order_price_recalculation: set discount from pricelist with discount_policy without_discount
  sale_fixed_discount/models/sale_order.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
Labels: needs review

#839 [12.0][MIG] sale_order_line_price_history
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: approved

#804 [11.0][IMP] sale_order_secondary_unit: add secondary unit to sale report
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/report/sale_report_templates.xml
Labels: approved

#750 [11.0][MIG] sale_blanket_order
  sale_blanket_order/README.rst
  sale_blanket_order/__init__.py
  sale_blanket_order/__manifest__.py
  sale_blanket_order/data/ir_cron.xml
  sale_blanket_order/data/sequence.xml
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/DESCRIPTION.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/report/report.xml
  sale_blanket_order/report/templates.xml
  sale_blanket_order/security/ir.model.access.csv
  sale_blanket_order/security/security.xml
  sale_blanket_order/static/description/BO_actions.png
  sale_blanket_order/static/description/BO_form.png
  sale_blanket_order/static/description/BO_lines.png
  sale_blanket_order/static/description/BO_menu.png
  sale_blanket_order/static/description/PO_BOLine.png
  sale_blanket_order/static/description/PO_from_BO.png
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/__init__.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/views/sale_order_views.xml
  sale_blanket_order/wizard/__init__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order/wizard/create_sale_orders.xml
Labels: approved

#773 [MIG] sale_order_price_recalculation: Migration to 12.0
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
Labels: approved, ready to merge

#852 [FIX] product_supplierinfo_for_customer_sale: TypeError: unorderable types: int() >= NoneType()
  product_supplierinfo_for_customer_sale/models/product_product.py
Labels: approved
