Repository OCA/sale-workflow, pull requests merged in 2019-02, with the labels that each got.

#770 [11.0][IMP] sale_order_type: Find sale order type based on the products of the sale order
  sale_order_type/README.rst
  sale_order_type/__manifest__.py
  sale_order_type/models/__init__.py
  sale_order_type/models/account_invoice.py
  sale_order_type/models/sale_order.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/models/sale_order_type_rule.py
  sale_order_type/readme/CONFIGURE.rst
  sale_order_type/readme/CONTRIBUTORS.rst
  sale_order_type/readme/DESCRIPTION.rst
  sale_order_type/readme/ROADMAP.rst
  sale_order_type/readme/USAGE.rst
  sale_order_type/security/ir.model.access.csv
  sale_order_type/static/description/index.html
  sale_order_type/tests/__init__.py
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/tests/test_sale_order_type_rule.py
  sale_order_type/views/account_invoice_view.xml
  sale_order_type/views/sale_order_type_rule_view.xml
  sale_order_type/views/sale_order_type_view.xml
  sale_order_type/views/sale_order_view.xml
Labels: approved, needs review

#729 [10.0] add new module to manage sale promotion based on rules
  sale_promotion_rule/README.rst
  sale_promotion_rule/__init__.py
  sale_promotion_rule/__manifest__.py
  sale_promotion_rule/i18n/fr.po
  sale_promotion_rule/models/__init__.py
  sale_promotion_rule/models/sale_order.py
  sale_promotion_rule/models/sale_order_line.py
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/readme/CONTRIBUTORS.rst
  sale_promotion_rule/readme/DESCRIPTION.rst
  sale_promotion_rule/readme/ROADMAP.rst
  sale_promotion_rule/security/ir.model.access.csv
  sale_promotion_rule/static/description/index.html
  sale_promotion_rule/static/description/promotion_rule.png
  sale_promotion_rule/tests/__init__.py
  sale_promotion_rule/tests/test_promotion.py
  sale_promotion_rule/views/sale_order.xml
  sale_promotion_rule/views/sale_promotion_rule.xml
  sale_promotion_rule/wizards/__init__.py
  sale_promotion_rule/wizards/sale_order_add_coupon.py
  sale_promotion_rule/wizards/sale_order_add_coupon.xml
  setup/sale_promotion_rule/odoo/__init__.py
  setup/sale_promotion_rule/odoo/addons/__init__.py
  setup/sale_promotion_rule/odoo/addons/sale_promotion_rule
  setup/sale_promotion_rule/setup.py
Labels: approved, ready to merge

#768 [10.0][FIX] sale_triple_discount: Correctly compute taxes with round_globally configuration
  sale_triple_discount/README.rst
  sale_triple_discount/__manifest__.py
  sale_triple_discount/models/__init__.py
  sale_triple_discount/models/sale_order.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/tests/test_sale_triple_discount.py
Labels: approved, ready to merge

#797 [11.0][FIX] sale_order_type: Remove hard dependency from l10n_generic_coa
  sale_order_type/tests/test_sale_order_type_rule.py
Labels: approved

#784 [11.0][IMP] sale_secondary_unit: Set secondary uom quantity as 1.0 by default
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/tests/test_sale_order_secondary_unit.py
Labels: approved, needs review

#800 [11.0][ADD] sale_stock_secondary_unit: New module for store secondary unit in stock moves when a sale order is confirmed
  oca_dependencies.txt
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/procurement_rule.py
  sale_stock_secondary_unit/readme/CONTRIBUTORS.rst
  sale_stock_secondary_unit/readme/DESCRIPTION.rst
  sale_stock_secondary_unit/readme/USAGE.rst
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
Labels: approved

#779 [11.0][IMP/FIX] sale_secondary_unit limit secondary uom in order line
  sale_order_secondary_unit/views/sale_order_views.xml
Labels: approved

#799 [12.0][MIG] sale double validation
  sale_double_validation/README.rst
  sale_double_validation/__init__.py
  sale_double_validation/__manifest__.py
  sale_double_validation/models/__init__.py
  sale_double_validation/models/company.py
  sale_double_validation/models/sale.py
  sale_double_validation/readme/CONFIGURE.rst
  sale_double_validation/readme/CONTRIBUTORS.rst
  sale_double_validation/readme/DESCRIPTION.rst
  sale_double_validation/readme/USAGE.rst
  sale_double_validation/static/description/icon.png
  sale_double_validation/tests/__init__.py
  sale_double_validation/tests/test_double_validation.py
  sale_double_validation/views/company.xml
  sale_double_validation/views/sale.xml
Labels: approved, ready to merge
