Repository OCA/sale-workflow, pull requests merged in 2019-06, with the labels that each got.

#844 [12.0][ADD] sale_milestone_profile_invoicing
  sale_milestone_profile_invoicing/__init__.py
  sale_milestone_profile_invoicing/__manifest__.py
  sale_milestone_profile_invoicing/models/__init__.py
  sale_milestone_profile_invoicing/models/sale_order_line.py
  sale_milestone_profile_invoicing/readme/CONFIGURE.rst
  sale_milestone_profile_invoicing/readme/CONTRIBUTORS.rst
  sale_milestone_profile_invoicing/readme/DESCRIPTION.rst
  sale_milestone_profile_invoicing/readme/USAGE.rst
  sale_milestone_profile_invoicing/static/description/icon.png
  sale_milestone_profile_invoicing/tests/__init__.py
  sale_milestone_profile_invoicing/tests/test_sale_milestone_profile_invoicing.py
  sale_milestone_profile_invoicing/views/sale_milestone_profile_invoicing.xml
Labels: approved, ready to merge

#862 [12.0][sale_product_set][IMP] - Add multi-company to product set
  sale_product_set/__manifest__.py
  sale_product_set/models/product_set.py
  sale_product_set/security/rule_product_set.xml
  sale_product_set/security/rule_product_set_line.xml
  sale_product_set/views/product_set.xml
Labels: approved, ready to merge

#854 11.0 mig sale order digitized signature
  oca_dependencies.txt
  sale_order_digitized_signature/README.rst
  sale_order_digitized_signature/__init__.py
  sale_order_digitized_signature/__manifest__.py
  sale_order_digitized_signature/i18n/es.po
  sale_order_digitized_signature/i18n/sale_order_digitized_signature.pot
  sale_order_digitized_signature/models/__init__.py
  sale_order_digitized_signature/models/sale.py
  sale_order_digitized_signature/readme/CONTRIBUTORS.rst
  sale_order_digitized_signature/readme/DESCRIPTION.rst
  sale_order_digitized_signature/readme/INSTALL.rst
  sale_order_digitized_signature/readme/USAGE.rst
  sale_order_digitized_signature/report/report_saleorder.xml
  sale_order_digitized_signature/static/description/icon.png
  sale_order_digitized_signature/static/description/index.html
  sale_order_digitized_signature/views/sale_views.xml
Labels: approved

#855 [10.0][sale_exception] Refactore : Adapt sale_exception to base_exception simplification
  sale_exception/data/sale_exception_data.xml
  sale_exception/models/__init__.py
  sale_exception/models/sale.py
  sale_exception/models/sale_order_line.py
  sale_exception/views/sale_view.xml
Labels: approved

#860 [12.0][sale_exception] refactore sale exception to adapt it to base_exception refactore.
  sale_exception/data/sale_exception_data.xml
  sale_exception/models/__init__.py
  sale_exception/models/sale.py
  sale_exception/models/sale_order_line.py
  sale_exception/views/sale_view.xml
Labels: approved

#867 [12.0][MIG] sale_force_invoiced
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/readme/DESCRIPTION.rst
  sale_force_invoiced/readme/USAGE.rst
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_view.xml
Labels: approved

#873 [12.0][sale_exception] Fix error when checking sale order sans sale order line exception rules
  sale_exception/__manifest__.py
  sale_exception/demo/sale_exception_demo.xml
  sale_exception/models/sale_order_line.py
  sale_exception/readme/CONTRIBUTORS.rst
  sale_exception/tests/__init__.py
  sale_exception/tests/test_multi_records.py
Labels: approved

#882 [11.0][FIX] sale_order_invoicing_finished_task: Test
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
Labels: approved, needs review

#884 [12.0][FIX][sale_stock_picking_blocking] the _commercial_fields method shoud return something
  sale_stock_picking_blocking/models/res_partner.py
Labels: merged 🎉
