Repository OCA/sale-workflow, pull requests merged in 2019-04, with the labels that each got.

#824 [11.0][FIX] sale_elaboration should't be auto installed
  sale_elaboration/__manifest__.py
Labels: approved

#772 [MIG] sale_order_general_discount: Migration to 12.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
Labels: needs review

#774 [MIG] sale_order_action_invoice_create_hook: Migration to 12.0
  sale_order_action_invoice_create_hook/README.rst
  sale_order_action_invoice_create_hook/__init__.py
  sale_order_action_invoice_create_hook/__manifest__.py
  sale_order_action_invoice_create_hook/i18n/ca_ES.po
  sale_order_action_invoice_create_hook/i18n/de.po
  sale_order_action_invoice_create_hook/i18n/el_GR.po
  sale_order_action_invoice_create_hook/i18n/es.po
  sale_order_action_invoice_create_hook/i18n/es_VE.po
  sale_order_action_invoice_create_hook/i18n/fi.po
  sale_order_action_invoice_create_hook/i18n/fr.po
  sale_order_action_invoice_create_hook/i18n/hr.po
  sale_order_action_invoice_create_hook/i18n/hu.po
  sale_order_action_invoice_create_hook/i18n/it.po
  sale_order_action_invoice_create_hook/i18n/nl.po
  sale_order_action_invoice_create_hook/i18n/pt_BR.po
  sale_order_action_invoice_create_hook/i18n/ro.po
  sale_order_action_invoice_create_hook/i18n/sale_order_action_invoice_create_hook.pot
  sale_order_action_invoice_create_hook/i18n/sl_SI.po
  sale_order_action_invoice_create_hook/i18n/tr.po
  sale_order_action_invoice_create_hook/i18n/vi_VN.po
  sale_order_action_invoice_create_hook/i18n/zh_CN.po
  sale_order_action_invoice_create_hook/model/__init__.py
  sale_order_action_invoice_create_hook/model/sale_order.py
  sale_order_action_invoice_create_hook/readme/CONTRIBUTORS.rst
  sale_order_action_invoice_create_hook/readme/DESCRIPTION.rst
  sale_order_action_invoice_create_hook/readme/USAGE.rst
  sale_order_action_invoice_create_hook/static/description/icon.png
  sale_order_action_invoice_create_hook/static/description/index.html
  sale_order_action_invoice_create_hook/tests/__init__.py
  sale_order_action_invoice_create_hook/tests/test_sale_order_action_create_hook.py
Labels: approved, needs review
