Repository OCA/sale-workflow, pull requests merged in 2019-12, with the labels that each got.

#1009 [11.0] [FIX] sale_order_type: Missing warnings in onchange method
  sale_order_type/models/account_invoice.py
Labels: approved, enhancement

#1011 [12.0] [FIX] sale_order_type: Missing warnings on inv onchange method
  sale_order_type/models/account_invoice.py
Labels: enhancement

#1014 [12.0][ADD] sale_contact_type
  sale_contact_type/README.rst
  sale_contact_type/__init__.py
  sale_contact_type/__manifest__.py
  sale_contact_type/i18n/es.po
  sale_contact_type/i18n/sale_contact_type.pot
  sale_contact_type/models/__init__.py
  sale_contact_type/models/res_partner.py
  sale_contact_type/readme/CONTRIBUTORS.rst
  sale_contact_type/readme/DESCRIPTION.rst
  sale_contact_type/readme/USAGE.rst
  sale_contact_type/static/description/icon.png
  sale_contact_type/static/description/index.html
  sale_contact_type/views/sale_order.xml
Labels: approved
