Repository OCA/sale-workflow, pull requests merged in 2019-10, with the labels that each got.

#730 [10.0] add sale promotion rule based on product assortment
  .travis.yml
  sale_promotion_rule_assortment/README.rst
  sale_promotion_rule_assortment/__init__.py
  sale_promotion_rule_assortment/__manifest__.py
  sale_promotion_rule_assortment/demo/sale_order.xml
  sale_promotion_rule_assortment/demo/sale_promotion_rule.xml
  sale_promotion_rule_assortment/models/__init__.py
  sale_promotion_rule_assortment/models/sale_promotion_rule.py
  sale_promotion_rule_assortment/readme/CONTRIBUTORS.rst
  sale_promotion_rule_assortment/readme/DESCRIPTION.rst
  sale_promotion_rule_assortment/readme/USAGE.rst
  sale_promotion_rule_assortment/static/description/icon.png
  sale_promotion_rule_assortment/static/description/index.html
  sale_promotion_rule_assortment/tests/__init__.py
  sale_promotion_rule_assortment/tests/test_promotion_rule_assortment.py
  sale_promotion_rule_assortment/views/sale_promotion_rule.xml
  setup/sale_promotion_rule_assortment/odoo/__init__.py
  setup/sale_promotion_rule_assortment/odoo/addons/__init__.py
  setup/sale_promotion_rule_assortment/odoo/addons/sale_promotion_rule_assortment
  setup/sale_promotion_rule_assortment/setup.py
Labels: approved, needs review, ready to merge

#549 [9.0][IMP][sale_automatic_workflow_payment_mode] use date invoice as date of payment
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_rental/models/stock.py
Labels: approved, needs review

#954 [FIX] sale_elaboration: Apply force_save for field is_elaboration in sale order view to store the value in onchange method
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/sale_order_views.xml
Labels: approved

#963 remove obsolete base_sale_multi_channel reference
  sale_exception/readme/DESCRIPTION.rst
Labels: approved

#878 [12.0][IMP] sale exception
  sale_exception/README.rst
  sale_exception/__manifest__.py
  sale_exception/readme/CONTRIBUTORS.rst
  sale_exception/views/sale_view.xml
Labels: approved, work in progress

#930 [IMP] sale_order_product_recommendation: Display only active or sale ok products in recommendation wizard
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, needs review

#842 [11.0][FIX] product_supplierinfo_for_customer_sale: Search supplierinfo by product variant first
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/models/sale.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
Labels: approved, needs review, ready to merge
