Repository OCA/sale-workflow, pull requests merged in 2020-11, with the labels that each got.

#1307 [13.0][FIX] sale_order_product_recommendation: show the lines as soon as the wizard is launched
  sale_invoice_plan/__manifest__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳

#1311 [14.0][MIG] sale_last_price_info: Migration to 14.0
  sale_last_price_info/README.rst
  sale_last_price_info/__init__.py
  sale_last_price_info/__manifest__.py
  sale_last_price_info/i18n/de.po
  sale_last_price_info/i18n/es.po
  sale_last_price_info/i18n/fr.po
  sale_last_price_info/i18n/it.po
  sale_last_price_info/i18n/sale_last_price_info.pot
  sale_last_price_info/i18n/sl_SI.po
  sale_last_price_info/i18n/zh_CN.po
  sale_last_price_info/models/__init__.py
  sale_last_price_info/models/product.py
  sale_last_price_info/models/sale.py
  sale_last_price_info/readme/CONTRIBUTORS.rst
  sale_last_price_info/readme/DESCRIPTION.rst
  sale_last_price_info/static/description/icon.png
  sale_last_price_info/static/description/index.html
  sale_last_price_info/tests/__init__.py
  sale_last_price_info/tests/test_sale_last_price_info.py
  sale_last_price_info/views/product_view.xml
  setup/sale_last_price_info/odoo/addons/sale_last_price_info
  setup/sale_last_price_info/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1310 [14.0][MIG] sale_product_category_menu: Migration to 14.0
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/i18n/es.po
  sale_product_category_menu/i18n/sale_product_category_menu.pot
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/static/description/index.html
  sale_product_category_menu/views/sale_views.xml
  setup/sale_product_category_menu/odoo/addons/sale_product_category_menu
  setup/sale_product_category_menu/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1309 [14.0][MIG] sale_commercial_partner: Migration to 14.0
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale.py
  sale_commercial_partner/readme/CONTRIBUTORS.rst
  sale_commercial_partner/readme/DESCRIPTION.rst
  sale_commercial_partner/readme/USAGE.rst
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/views/sale_views.xml
  setup/sale_commercial_partner/odoo/addons/sale_commercial_partner
  setup/sale_commercial_partner/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#1322 [12.0][IMP] Update travis to latest template + lint
  .travis.yml
  sale_invoice_plan/__manifest__.py
Labels: bot is merging ⏳

#1300 [13.0][MIG] sale_stock_picking_note: Migration to 13.0
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/DESCRIPTION.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/sale_order_view.xml
  setup/sale_stock_picking_note/odoo/addons/sale_stock_picking_note
  setup/sale_stock_picking_note/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1318 [13][IMP] product_set also duplicate lines
  sale_product_set/models/product_set.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1328 [13.0] [FIX] sale_order_type: Not allowed to delete a sale order type if them is used in an sale order.
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#1327 [FIX] sale_commercial_partner: compute_sudo
  sale_commercial_partner/models/sale.py
Labels: approved, bot is merging ⏳

#1252 [13.0][IMP] sale_automatic_workflow, add _do function
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: approved, enhancement, merged 🎉, needs review

#1332 [13.0][FIX] sale_order_product_recommendation: Get product image form product.product model instead of product.template in wizard kanban view.
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#1331 [12.0][FIX] sale_order_product_recommendation: Get product image form product.product model instead of product.template in wizard kanban view.
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#1111 [REF] sale_partner_incoterm: Migration to 13.0
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
Labels: approved, bot is merging ⏳

#1213 [13.0] sale_by_packaging: Fix constraint considering variants
  sale_by_packaging/models/product_template.py
Labels: approved, bot is merging ⏳

#1308 [13.0][FIX] sale_stock_delivery_addres: order_partner_id not being stored
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1346 Fixed sale team can't read cancel reason
  sale_cancel_reason/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#1334 [14.0][MIG] sale_product_multi_add: Migration to 14.0
  sale_product_multi_add/README.rst
  sale_product_multi_add/__init__.py
  sale_product_multi_add/__manifest__.py
  sale_product_multi_add/i18n/ca.po
  sale_product_multi_add/i18n/de.po
  sale_product_multi_add/i18n/es.po
  sale_product_multi_add/i18n/sale_product_multi_add.pot
  sale_product_multi_add/readme/CONTRIBUTORS.rst
  sale_product_multi_add/readme/DESCRIPTION.rst
  sale_product_multi_add/readme/USAGE.rst
  sale_product_multi_add/security/ir.model.access.csv
  sale_product_multi_add/static/description/icon.png
  sale_product_multi_add/static/description/index.html
  sale_product_multi_add/static/description/sale_product_multi_add.png
  sale_product_multi_add/tests/__init__.py
  sale_product_multi_add/tests/test_sale.py
  sale_product_multi_add/views/sale_view.xml
  sale_product_multi_add/wizards/__init__.py
  sale_product_multi_add/wizards/sale_import_products.py
  sale_product_multi_add/wizards/sale_import_products_view.xml
  setup/sale_product_multi_add/odoo/addons/sale_product_multi_add
  setup/sale_product_multi_add/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1314 [14.0][MIG] sale_validity: Migration to 14.0
  sale_validity/README.rst
  sale_validity/__init__.py
  sale_validity/__manifest__.py
  sale_validity/i18n/ca.po
  sale_validity/i18n/de.po
  sale_validity/i18n/el_GR.po
  sale_validity/i18n/es.po
  sale_validity/i18n/es_ES.po
  sale_validity/i18n/es_VE.po
  sale_validity/i18n/fi.po
  sale_validity/i18n/fr.po
  sale_validity/i18n/hr.po
  sale_validity/i18n/hr_HR.po
  sale_validity/i18n/hu.po
  sale_validity/i18n/it.po
  sale_validity/i18n/nl.po
  sale_validity/i18n/nl_NL.po
  sale_validity/i18n/pt.po
  sale_validity/i18n/pt_BR.po
  sale_validity/i18n/ro.po
  sale_validity/i18n/sale_validity.pot
  sale_validity/i18n/sk.po
  sale_validity/i18n/sl.po
  sale_validity/i18n/tr.po
  sale_validity/i18n/tr_TR.po
  sale_validity/i18n/vi_VN.po
  sale_validity/i18n/zh_CN.po
  sale_validity/models/__init__.py
  sale_validity/models/company.py
  sale_validity/models/res_config_settings.py
  sale_validity/models/sale_order.py
  sale_validity/readme/CONFIGURE.rst
  sale_validity/readme/CONTRIBUTORS.rst
  sale_validity/readme/DESCRIPTION.rst
  sale_validity/readme/USAGE.rst
  sale_validity/static/description/icon.png
  sale_validity/static/description/index.html
  sale_validity/tests/__init__.py
  sale_validity/tests/test_sale_validity.py
  sale_validity/views/res_config_settings.xml
  setup/sale_validity/odoo/addons/sale_validity
  setup/sale_validity/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1099 [13.0][MIG] sale_isolated_quotation
  sale_isolated_quotation/README.rst
  sale_isolated_quotation/__init__.py
  sale_isolated_quotation/__manifest__.py
  sale_isolated_quotation/data/ir_sequence_data.xml
  sale_isolated_quotation/hooks.py
  sale_isolated_quotation/i18n/ca.po
  sale_isolated_quotation/i18n/de.po
  sale_isolated_quotation/i18n/el_GR.po
  sale_isolated_quotation/i18n/es.po
  sale_isolated_quotation/i18n/es_ES.po
  sale_isolated_quotation/i18n/es_VE.po
  sale_isolated_quotation/i18n/fi.po
  sale_isolated_quotation/i18n/fr.po
  sale_isolated_quotation/i18n/hr.po
  sale_isolated_quotation/i18n/hr_HR.po
  sale_isolated_quotation/i18n/hu.po
  sale_isolated_quotation/i18n/it.po
  sale_isolated_quotation/i18n/nl.po
  sale_isolated_quotation/i18n/nl_NL.po
  sale_isolated_quotation/i18n/pt.po
  sale_isolated_quotation/i18n/pt_BR.po
  sale_isolated_quotation/i18n/ro.po
  sale_isolated_quotation/i18n/sale_isolated_quotation.pot
  sale_isolated_quotation/i18n/sk.po
  sale_isolated_quotation/i18n/sl.po
  sale_isolated_quotation/i18n/tr.po
  sale_isolated_quotation/i18n/tr_TR.po
  sale_isolated_quotation/i18n/vi_VN.po
  sale_isolated_quotation/i18n/zh_CN.po
  sale_isolated_quotation/models/__init__.py
  sale_isolated_quotation/models/sale.py
  sale_isolated_quotation/readme/CONTRIBUTORS.rst
  sale_isolated_quotation/readme/DESCRIPTION.rst
  sale_isolated_quotation/readme/ROADMAP.rst
  sale_isolated_quotation/readme/USAGE.rst
  sale_isolated_quotation/static/description/icon.png
  sale_isolated_quotation/static/description/index.html
  sale_isolated_quotation/tests/__init__.py
  sale_isolated_quotation/tests/test_sale_isolated_quotation.py
  sale_isolated_quotation/views/sale_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1193 [13.0][FIX] sale_order_type: Fix compute writable cache miss error
  sale_order_type/models/account_move.py
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: approved, bot is merging ⏳
