Repository OCA/sale-workflow, pull requests merged in 2020-06, with the labels that each got.

#1100 [12.0][IMP] sale_order_product_recommendation: Mobile views
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  sale_order_product_recommendation_secondary_unit/tests/test_recommendations.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1066 [13.0][MIG] sale_order_product_recommendation_secondary_unit: Migration to 13.0
  sale_order_product_recommendation_secondary_unit/README.rst
  sale_order_product_recommendation_secondary_unit/__init__.py
  sale_order_product_recommendation_secondary_unit/__manifest__.py
  sale_order_product_recommendation_secondary_unit/i18n/es.po
  sale_order_product_recommendation_secondary_unit/i18n/sale_order_product_recommendation_secondary_unit.pot
  sale_order_product_recommendation_secondary_unit/readme/CONFIGURE.rst
  sale_order_product_recommendation_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation_secondary_unit/readme/DESCRIPTION.rst
  sale_order_product_recommendation_secondary_unit/readme/USAGE.rst
  sale_order_product_recommendation_secondary_unit/static/description/icon.png
  sale_order_product_recommendation_secondary_unit/static/description/index.html
  sale_order_product_recommendation_secondary_unit/tests/__init__.py
  sale_order_product_recommendation_secondary_unit/tests/test_recommendations.py
  sale_order_product_recommendation_secondary_unit/wizards/__init__.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
Labels: approved, merged 🎉

#1159 [IMP] sale_order_general_discount: Apply general discount to order lines created without UI form view
  sale_order_general_discount/models/sale.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
Labels: approved, bot is merging ⏳

#1157 [13.0] sale_order_product_recommendation: Forward port of #1100
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  sale_order_product_recommendation_secondary_unit/tests/test_recommendations.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1163 [12.0][FIX] sale_stock_delivery_address: do not limit destination address,
  sale_stock_delivery_address/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1164 [13.0][FIX] sale_stock_delivery_address: do not limit destination address,
  sale_stock_delivery_address/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1135 [13.0][MIG]portal_sale_personal_data_only
  portal_sale_personal_data_only/README.rst
  portal_sale_personal_data_only/__init__.py
  portal_sale_personal_data_only/__manifest__.py
  portal_sale_personal_data_only/data/portal_sale_security.xml
  portal_sale_personal_data_only/hooks.py
  portal_sale_personal_data_only/i18n/de.po
  portal_sale_personal_data_only/i18n/portal_sale_personal_data_only.pot
  portal_sale_personal_data_only/i18n/zh_CN.po
  portal_sale_personal_data_only/readme/CONTRIBUTORS.rst
  portal_sale_personal_data_only/readme/DESCRIPTION.rst
  portal_sale_personal_data_only/readme/USAGE.rst
  portal_sale_personal_data_only/static/description/icon.png
  portal_sale_personal_data_only/static/description/index.html
  setup/portal_sale_personal_data_only/odoo/addons/portal_sale_personal_data_only
  setup/portal_sale_personal_data_only/setup.py
Labels: approved, bot is merging ⏳

#1169 [12.0][IMP] sale_order_line_price_history: Add discount to the history + invisible column
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: approved, bot is merging ⏳

#1097 [12.0][ADD] - Add new module Sale Order Transmit Method
  sale_order_transmit_method/README.rst
  sale_order_transmit_method/__init__.py
  sale_order_transmit_method/__manifest__.py
  sale_order_transmit_method/models/__init__.py
  sale_order_transmit_method/models/sale_order.py
  sale_order_transmit_method/readme/CONTRIBUTORS.rst
  sale_order_transmit_method/readme/DESCRIPTION.rst
  sale_order_transmit_method/static/description/icon.png
  sale_order_transmit_method/static/description/index.html
  sale_order_transmit_method/tests/__init__.py
  sale_order_transmit_method/tests/test_sale_order.py
  sale_order_transmit_method/views/sale_order.xml
  sale_order_transmit_method/wizards/__init__.py
  sale_order_transmit_method/wizards/sale_advance_payment_inv.py
  setup/sale_order_transmit_method/odoo/addons/sale_order_transmit_method
  setup/sale_order_transmit_method/setup.py
Labels: approved, bot is merging ⏳, needs review

#1167 [12.0] Add sale_automatic_workflow_job
  oca_dependencies.txt
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_job/readme/DESCRIPTION.rst
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  setup/sale_automatic_workflow_job/odoo/addons/sale_automatic_workflow_job
  setup/sale_automatic_workflow_job/setup.py
Labels: approved, bot is merging ⏳, needs review

#1139 [FIX] stock_product_returnable
  sale_product_returnable/models/sale_order.py
Labels: approved, bot is merging ⏳, bug, needs review

#1148 [10.0][FIX] sale_promotion_rule: Enable sequence order
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/tests/test_promotion.py
Labels: approved, bot is merging ⏳, ready to merge

#1165 IMP sale_o_lot_select: set lot_id from sale_line_id instead of ctx (v7 inheriting)
  sale_order_lot_selection/models/sale.py
  sale_order_lot_selection/models/stock.py
Labels: approved, bot is merging ⏳, ready to merge

#1172 [12.0][FIX] sale_order_generator: Fix view
  sale_generator/views/sale_order_view.xml
Labels: bot is merging ⏳, enhancement

#1114 [13.0] Create module sale_order_line_packaging_qty
  sale_order_line_packaging_qty/__init__.py
  sale_order_line_packaging_qty/__manifest__.py
  sale_order_line_packaging_qty/models/__init__.py
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/readme/CONTRIBUTORS.rst
  sale_order_line_packaging_qty/readme/DESCRIPTION.rst
  sale_order_line_packaging_qty/tests/__init__.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
  sale_order_line_packaging_qty/views/sale_order.xml
  setup/sale_order_line_packaging_qty/odoo/addons/sale_order_line_packaging_qty
  setup/sale_order_line_packaging_qty/setup.py
Labels: approved, bot is merging ⏳

#1171 [12.0][IMP] sales_team_security: Contacts permissions revamp
  sales_team_security/README.rst
  sales_team_security/__manifest__.py
  sales_team_security/migrations/12.0.2.0.0/pre-migration.py
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/index.html
  sales_team_security/tests/test_sales_team_security.py
Labels: approved, bot is merging ⏳

#1177 [11.0][FIX] sale_global_discount: wrong property name
  sale_global_discount/models/sale_order.py
Labels: bot is merging ⏳

#1174 [IMP][sale_order_line_packaging_qty] Sell product / unit or packaging
  sale_order_line_packaging_qty/__manifest__.py
  sale_order_line_packaging_qty/models/__init__.py
  sale_order_line_packaging_qty/models/product_packaging_type.py
  sale_order_line_packaging_qty/models/product_product.py
  sale_order_line_packaging_qty/models/product_template.py
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
  sale_order_line_packaging_qty/views/product_packaging_type.xml
  sale_order_line_packaging_qty/views/product_template.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge
