Repository OCA/sale-workflow, pull requests merged in 2020-07, with the labels that each got.

#1137 [13.0][MIG] sale_fixed_discount
  oca_dependencies.txt
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  setup/sale_fixed_discount/odoo/addons/sale_fixed_discount
  setup/sale_fixed_discount/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1168 [10.0][IMP] sale_triple_discount: Improve compute_amount perf
  sale_triple_discount/models/sale_order_line.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1190 [13.0][IMP][sale_order_type] Sale Order Type: Fix view and readonly
  sale_order_type/models/account_move.py
  sale_order_type/models/sale.py
  sale_order_type/views/account_move_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1181 [11.0][FIX] sale_global_discount: Constraint tax lines combinations
  sale_global_discount/README.rst
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/ROADMAP.rst
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/test_sale_global_discount.py
Labels: approved, bot is merging ⏳, ready to merge

#1131 [12.0][FIX] sale_commitment_lead_time, unit test error
  sale_commitment_lead_time/tests/test_sale_order_preparation_time.py
Labels: approved, bot is merging ⏳, ready to merge

#1160 [12.0][FIX] sale_cancel_reason: fix access for salesteam salesman users
  sale_cancel_reason/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#1197 [12.0][MIG] sale_global_discount: Migration to 12.0
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/CONTRIBUTORS.rst
  sale_global_discount/readme/DESCRIPTION.rst
  sale_global_discount/readme/ROADMAP.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#503 [9.0][ADD] sale_open_qty
  sale_open_qty/README.rst
  sale_open_qty/__init__.py
  sale_open_qty/__openerp__.py
  sale_open_qty/init_hook.py
  sale_open_qty/models/__init__.py
  sale_open_qty/models/sale_order.py
  sale_open_qty/static/description/icon.png
  sale_open_qty/tests/__init__.py
  sale_open_qty/tests/test_sale_open_qty.py
  sale_open_qty/views/sale_view.xml
Labels: bot is merging ⏳, needs review
