Repository OCA/sale-workflow, pull requests merged in 2020-09, with the labels that each got.

#1196 [12.0][MIG] sale_quotation_number: Migration to 12.0
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1229 [FIX] pep8 and pylint
  portal_sale_personal_data_only/__manifest__.py
  sale_automatic_workflow_payment_mode/views/sale_workflow_process_view.xml
  sale_cancel_reason/__init__.py
  sale_cancel_reason/__manifest__.py
  sale_cancel_reason/model/__init__.py
  sale_cancel_reason/model/sale.py
  sale_cancel_reason/tests/__init__.py
  sale_cancel_reason/tests/test_sale_cancel_reason.py
  sale_cancel_reason/wizard/__init__.py
  sale_cancel_reason/wizard/cancel_reason.py
  sale_exception/models/sale_order_line.py
  sale_invoice_policy/__manifest__.py
  sale_isolated_quotation/readme/ROADMAP.rst
  sale_order_transmit_method/readme/DESCRIPTION.rst
  sale_partner_incoterm/readme/CONTRIBUTORS.rst
  sale_partner_incoterm/readme/DESCRIPTION.rst
  sale_quotation_number/README.rst
  sale_quotation_number/data/data.xml
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/index.html
  sales_team_security/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1228 [13.0][MIG]sale_quotation_number: Migration to 13.0
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/readme/ROADMAP.rst
  sale_quotation_number/readme/USAGE.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: approved, bot is merging ⏳

#1208 [10.0][FIX]sale_procurement_group_by_line
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1237 [FIX] sale_order_product_recommendation: wizard lines without wizard_id reference.
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳

#1218 [11.0] sale_exception: Remove side effect from api.constrains
  sale_exception/models/sale.py
Labels: approved, bot is merging ⏳, ready to merge

#1225 [ADD] New module sale_mrp_bom
  sale_mrp_bom/README.rst
  sale_mrp_bom/__init__.py
  sale_mrp_bom/__manifest__.py
  sale_mrp_bom/i18n/sale_mrp_bom.pot
  sale_mrp_bom/models/__init__.py
  sale_mrp_bom/models/sale_order_line.py
  sale_mrp_bom/models/stock_move.py
  sale_mrp_bom/readme/CONFIGURE.rst
  sale_mrp_bom/readme/CONTRIBUTORS.rst
  sale_mrp_bom/readme/DESCRIPTION.rst
  sale_mrp_bom/readme/INSTALL.rst
  sale_mrp_bom/readme/ROADMAP.rst
  sale_mrp_bom/readme/USAGE.rst
  sale_mrp_bom/security/security.xml
  sale_mrp_bom/static/description/icon.png
  sale_mrp_bom/static/description/index.html
  sale_mrp_bom/static/description/manufacturing_order_1.png
  sale_mrp_bom/static/description/sale_order_1.png
  sale_mrp_bom/tests/__init__.py
  sale_mrp_bom/tests/test_sale_mrp_bom.py
  sale_mrp_bom/views/sale_order.xml
  sale_mrp_bom/views/sale_order_line.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1238 [12.0][IMP] sale_automatic_workflow_job - related_job
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1232 [IMP] : sale_order_price_recalculation : homogenize button displays
  sale_order_price_recalculation/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1236 [12.0][ADD] New module 'sale_product_category_menu': version 12.0
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/views/sale_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1244 [12.0][FIX] fill type if null by default as it is now required
  sale_order_type/__manifest__.py
  sale_order_type/migrations/12.0.1.1.1/post-migration.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1240 [13.0] [FIX] sale_order_type: Only show the type field in sales
  sale_order_type/models/account_move.py
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/views/account_move_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1248 [FIX] sale_order_product_recommendation: Wrong newid comparation
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳

#1250 [13.0][IMP] sale_product_set_packaging_qty
  sale_product_set_packaging_qty/models/product_set.py
Labels: approved, bot is merging ⏳

#1251 [13.0][ADD] sale_order_product_availability_inline: new module
  oca_dependencies.txt
  sale_order_product_availability_inline/README.rst
  sale_order_product_availability_inline/__init__.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/i18n/es.po
  sale_order_product_availability_inline/i18n/sale_order_product_availability_inline.pot
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_availability_inline/readme/USAGE.rst
  sale_order_product_availability_inline/static/description/index.html
  sale_order_product_availability_inline/tests/__init__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_availability_inline/views/sale_views.xml
  setup/sale_order_product_availability_inline/odoo/addons/sale_order_product_availability_inline
  setup/sale_order_product_availability_inline/setup.py
Labels: approved, bot is merging ⏳

#1234 [12.0] [NEW] sale_require_po_doc: Added new module to check sale documentation.
  sale_require_po_doc/README.rst
  sale_require_po_doc/__init__.py
  sale_require_po_doc/__manifest__.py
  sale_require_po_doc/models/__init__.py
  sale_require_po_doc/models/res_partner.py
  sale_require_po_doc/models/sale_order.py
  sale_require_po_doc/readme/CONTRIBUTORS.rst
  sale_require_po_doc/readme/CREDITS.rst
  sale_require_po_doc/readme/DESCRIPTION.rst
  sale_require_po_doc/static/description/index.html
  sale_require_po_doc/views/res_partner_view.xml
  sale_require_po_doc/views/sale_order_view.xml
Labels: bot is merging ⏳

#1258 [13.0][MIG] sales_team_security: Migration to 13.0
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
  setup/sales_team_security/odoo/addons/sales_team_security
  setup/sales_team_security/setup.py
Labels: approved, bot is merging ⏳

#1266 [13.0][UPD] Eficent -> ForgeFlow
  sale_fixed_discount/README.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/static/description/index.html
  sale_order_line_date/__manifest__.py
Labels: approved, bot is merging ⏳
