Repository OCA/sale-workflow, pull requests merged in 2020-05, with the labels that each got.

#1140 *: E741 ambiguous variable name 'l' (greenify repo)
  sale_automatic_workflow/models/sale_order.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_procurement_group_by_line/model/sale.py
Labels: approved, bot is merging ⏳, enhancement

#1023 [13.0][MIG] sale_commercial_partner
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale.py
  sale_commercial_partner/readme/CONTRIBUTORS.rst
  sale_commercial_partner/readme/DESCRIPTION.rst
  sale_commercial_partner/readme/USAGE.rst
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/views/sale_views.xml
  setup/sale_commercial_partner/odoo/addons/sale_commercial_partner
  setup/sale_commercial_partner/setup.py
Labels: approved, merged 🎉, ready to merge

#1007 [10.0][FIX] sale_promotion_rule: Apply coupon to lines if percentage
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/tests/test_promotion.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1145 [IMP] sale_exception: improve instructions
  sale_exception/readme/CONFIGURE.rst
  sale_exception/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1142 [13.0][MIG] sale_force_invoiced
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/readme/DESCRIPTION.rst
  sale_force_invoiced/readme/USAGE.rst
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1152 [MIG][13.0] sale_tier_validation: Migration to v13.0
  sale_tier_validation/README.rst
  sale_tier_validation/__init__.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/__init__.py
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/models/tier_definition.py
  sale_tier_validation/readme/CONFIGURE.rst
  sale_tier_validation/readme/CONTRIBUTORS.rst
  sale_tier_validation/readme/DESCRIPTION.rst
  sale_tier_validation/readme/INSTALL.rst
  sale_tier_validation/readme/USAGE.rst
  sale_tier_validation/static/description/icon.png
  sale_tier_validation/static/description/index.html
  sale_tier_validation/tests/__init__.py
  sale_tier_validation/tests/test_tier_validation.py
  sale_tier_validation/views/sale_order_view.xml
  setup/sale_tier_validation/odoo/addons/sale_tier_validation
  setup/sale_tier_validation/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
