Repository OCA/sale-workflow, pull requests merged in 2020-01, with the labels that each got.

#1035 [FIX] sale_product_returnable: Respect jit conf
  sale_product_returnable/models/sale_order.py
Labels: approved, bug, needs review

#1038 [FIX] sale_fixed_discount: fix missing call to super() in onchange
  sale_fixed_discount/models/sale_order.py
Labels: enhancement, needs review

#1016 [13.0][ADD] sale_automatic_workflow_payment
  sale_automatic_workflow_payment/README.rst
  sale_automatic_workflow_payment/__init__.py
  sale_automatic_workflow_payment/__manifest__.py
  sale_automatic_workflow_payment/models/__init__.py
  sale_automatic_workflow_payment/models/payment_acquirer.py
  sale_automatic_workflow_payment/models/payment_transaction.py
  sale_automatic_workflow_payment/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_payment/readme/DESCRIPTION.rst
  sale_automatic_workflow_payment/readme/USAGE.rst
  sale_automatic_workflow_payment/static/description/icon.png
  sale_automatic_workflow_payment/static/description/index.html
  sale_automatic_workflow_payment/tests/__init__.py
  sale_automatic_workflow_payment/tests/test_automatic_payment.py
  sale_automatic_workflow_payment/views/payment_acquirer.xml
  setup/sale_automatic_workflow_payment/.eggs/README.txt
  setup/sale_automatic_workflow_payment/odoo/addons/sale_automatic_workflow_payment
  setup/sale_automatic_workflow_payment/setup.py
Labels: approved, needs review, ready to merge

#1036 [10.0][FIX] sale_order_price_recalculation: make it compliant with discount policy "Show public price & discount to the customer"
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
Labels: approved, enhancement, needs review

#1042 [13.0][FIX] sale_automatic_workflow: Changed method to create invoices
  sale_automatic_workflow/models/sale_order.py
Labels: approved

#1043 sale_automatic_workflow: improve tests
  .isort.cfg
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
Labels: approved

#1054 [12.0][IMP] sale_elaboration: Allow to archive elaborations
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/views/sale_elaboration_views.xml
Labels: approved
