Repository OCA/sale-workflow, pull requests merged in 2020-04, with the labels that each got.

#1115 [13.0][MIG] sale_order_lot_selection
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/en.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/models/stock.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
Labels: approved, bot is merging ⏳, migration, needs review

#998 [ADD][11.0] sale_stock_return_request: New module
  oca_dependencies.txt
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge, work in progress

#1095 [MIG] sale_stock_return_request: Migration to 12.0
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1112 [ADD] sale_global_discount: New module
  oca_dependencies.txt
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/CONTRIBUTORS.rst
  sale_global_discount/readme/DESCRIPTION.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1105 [12.0][ADD] sale_commitment_lead_time
  sale_commitment_lead_time/README.rst
  sale_commitment_lead_time/__init__.py
  sale_commitment_lead_time/__manifest__.py
  sale_commitment_lead_time/models/__init__.py
  sale_commitment_lead_time/models/res_company.py
  sale_commitment_lead_time/models/res_config_settings.py
  sale_commitment_lead_time/models/sale_order.py
  sale_commitment_lead_time/readme/CONFIGURE.rst
  sale_commitment_lead_time/readme/CONTRIBUTORS.rst
  sale_commitment_lead_time/readme/DESCRIPTION.rst
  sale_commitment_lead_time/static/description/icon.png
  sale_commitment_lead_time/static/description/index.html
  sale_commitment_lead_time/tests/__init__.py
  sale_commitment_lead_time/tests/test_sale_order_preparation_time.py
  sale_commitment_lead_time/views/res_config_settings.xml
  sale_commitment_lead_time/views/sale_order.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1065 [13.0][MIG] sale_order_product_recommendation: Migration to 13.0
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/readme/DESCRIPTION.rst
  sale_order_product_recommendation/readme/USAGE.rst
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  setup/sale_order_product_recommendation/odoo/addons/sale_order_product_recommendation
  setup/sale_order_product_recommendation/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge
