Repository OCA/sale-workflow, pull requests merged in 2020-10, with the labels that each got.

#1246 [MIG]sale_product_category_menu: Migration to 13.0
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/i18n/sale_product_category_menu.pot
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/static/description/index.html
  sale_product_category_menu/views/sale_views.xml
  setup/sale_product_category_menu/odoo/addons/sale_product_category_menu
  setup/sale_product_category_menu/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#805 [11.0][ADD] New Implement on module sale_disable_inventory_check
  sale_disable_inventory_check/__manifest__.py
  sale_disable_inventory_check/data/product_check_stock_data.xml
  sale_disable_inventory_check/models/__init__.py
  sale_disable_inventory_check/models/product_category.py
  sale_disable_inventory_check/models/product_template.py
  sale_disable_inventory_check/models/sale_order_line.py
  sale_disable_inventory_check/tests/test_disable_inventory_check.py
  sale_disable_inventory_check/views/product_category_views.xml
  sale_disable_inventory_check/views/product_template_views.xml
Labels: bot is merging ⏳

#1279 [FIX] sale_order_product_availability_inline: Take into account sale order warehouse
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/views/sale_views.xml
Labels: approved, bot is merging ⏳

#1269 [13.0][FIX] sale_order_product_recommendation: Fix duplicate lines when user change days to recommended products
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳, ready to merge

#1281 [MIG] sale_order_general_discount: Migration to 13.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/sale_order_general_discount/odoo/addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: bot is merging ⏳

#1217 [13.0][MIG] sale sourced by line
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale_order.py
  sale_sourced_by_line/model/sale_order_line.py
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/test/sale_order_multi_source.yml
  sale_sourced_by_line/test/sale_order_not_sourced.yml
  sale_sourced_by_line/test/sale_order_source.yml
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_is_delivered.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
  setup/sale_sourced_by_line/odoo/addons/sale_sourced_by_line
  setup/sale_sourced_by_line/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1278 [12.0][FIX] string duplicated
  sale_double_validation/models/company.py
Labels: approved, bot is merging ⏳, ready to merge

#1222 [13.0][IMP] sale_discount_display_amount. Update hooks
  sale_discount_display_amount/hooks.py
Labels: approved, ready to merge

#881 [10.0] sale_stock_picking_blocking: Do not break recordset (performance)
  sale_stock_picking_blocking/models/sale_order.py
Labels: approved, bot is merging ⏳, needs review

#1259 [12.0][ADD] sale_order_tag
  sale_order_tag/README.rst
  sale_order_tag/__init__.py
  sale_order_tag/__manifest__.py
  sale_order_tag/data/sale_order_tag_data.xml
  sale_order_tag/models/__init__.py
  sale_order_tag/models/sale_order.py
  sale_order_tag/models/sale_order_tag.py
  sale_order_tag/readme/CONTRIBUTORS.rst
  sale_order_tag/readme/DESCRIPTION.rst
  sale_order_tag/readme/USAGE.rst
  sale_order_tag/security/ir.model.access.csv
  sale_order_tag/security/sale_order_tag_security.xml
  sale_order_tag/static/description/icon.png
  sale_order_tag/views/sale_order.xml
  sale_order_tag/views/sale_order_tag.xml
Labels: approved, bot is merging ⏳, ready to merge

#982 [11.0] sale_blanket_order: fix the following use case scenario.
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/wizard/create_sale_orders.py
Labels: approved, bot is merging ⏳

#1247 [12.0] IMP sale_triple_discount adding discounts to sale order document, when discounts are present
  sale_triple_discount/__manifest__.py
  sale_triple_discount/readme/CONTRIBUTORS.rst
  sale_triple_discount/views/sale_order_report.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1206 [10.0][ADD] sale_order_restrict_cancel_existing_invoice
  sale_order_restrict_cancel_existing_invoice/README.rst
  sale_order_restrict_cancel_existing_invoice/__init__.py
  sale_order_restrict_cancel_existing_invoice/__manifest__.py
  sale_order_restrict_cancel_existing_invoice/models/__init__.py
  sale_order_restrict_cancel_existing_invoice/models/sale_order.py
  sale_order_restrict_cancel_existing_invoice/readme/CONTRIBUTORS.rst
  sale_order_restrict_cancel_existing_invoice/readme/DESCRIPTION.rst
  sale_order_restrict_cancel_existing_invoice/readme/USAGE.rst
  sale_order_restrict_cancel_existing_invoice/static/description/icon.png
  sale_order_restrict_cancel_existing_invoice/static/description/index.html
  sale_order_restrict_cancel_existing_invoice/tests/__init__.py
  sale_order_restrict_cancel_existing_invoice/tests/test_sale_cancel_existing_invoice.py
  setup/sale_order_restrict_cancel_existing_invoice/odoo/__init__.py
  setup/sale_order_restrict_cancel_existing_invoice/odoo/addons/__init__.py
  setup/sale_order_restrict_cancel_existing_invoice/odoo/addons/sale_order_restrict_cancel_existing_invoice
  setup/sale_order_restrict_cancel_existing_invoice/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1293 [FIX][12.0] sale_global_discount: sale order templates compatibility
  sale_global_discount/models/sale_order.py
Labels: bot is merging ⏳

#648 [10.0][ADD] sale_procurement_amendment
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/sale_procurement_amendment/odoo/__init__.py
  setup/sale_procurement_amendment/odoo/addons/__init__.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: bot is merging ⏳, needs review

#1298 [14.0][MIG] sale_order_archive
  sale_order_archive/README.rst
  sale_order_archive/__init__.py
  sale_order_archive/__manifest__.py
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/es.po
  sale_order_archive/i18n/sale_order_archive.pot
  sale_order_archive/i18n/zh_CN.po
  sale_order_archive/models/__init__.py
  sale_order_archive/models/sale_order.py
  sale_order_archive/readme/CONTRIBUTORS.rst
  sale_order_archive/readme/DESCRIPTION.rst
  sale_order_archive/readme/INSTALL.rst
  sale_order_archive/readme/USAGE.rst
  sale_order_archive/static/description/icon.png
  sale_order_archive/static/description/index.html
  sale_order_archive/views/sale_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#1305 [13.0][FIX] sale_sourced_by_line: Fix routes
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
Labels: bot is merging ⏳, enhancement

#1292 [FIX] sale_fixed_discount: using `product.group_discount_per_so_line`
  sale_fixed_discount/reports/report_sale_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#1295 [13.0][ADD] sale_by_packaging: add possibility to force the qty during SO line create/update
  sale_by_packaging/models/product_packaging.py
  sale_by_packaging/models/product_product.py
  sale_by_packaging/models/sale_order_line.py
  sale_by_packaging/readme/CONFIGURE.rst
  sale_by_packaging/readme/CONTRIBUTORS.rst
  sale_by_packaging/readme/DESCRIPTION.rst
  sale_by_packaging/tests/test_sale_only_by_packaging.py
  sale_by_packaging/views/product_packaging.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#1287 [IMP] sale_order_line_date: improving commitment_date tree column
  sale_order_line_date/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1299 [12.0][ADD] sale_order_incoterm_place
  sale_order_incoterm_place/README.rst
  sale_order_incoterm_place/__init__.py
  sale_order_incoterm_place/__manifest__.py
  sale_order_incoterm_place/i18n/ja.po
  sale_order_incoterm_place/i18n/sale_order_incoterm_place.pot
  sale_order_incoterm_place/models/__init__.py
  sale_order_incoterm_place/models/sale_order.py
  sale_order_incoterm_place/readme/CONTRIBUTORS.rst
  sale_order_incoterm_place/readme/DESCRIPTION.rst
  sale_order_incoterm_place/report/sale_order_report_templates.xml
  sale_order_incoterm_place/static/description/index.html
  sale_order_incoterm_place/views/sale_order_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1198 [13.0][FIX] sale_stock_delivery_address: do not remove procurements not comming from a SO
  sale_stock_delivery_address/models/procurement_group.py
Labels: approved, enhancement, merged 🎉
