Repository OCA/sale-workflow, pull requests merged in 2021-08, with the labels that each got.

#1395 [14.0][MIG] sale_start_end_dates
  sale_start_end_dates/README.rst
  sale_start_end_dates/__init__.py
  sale_start_end_dates/__manifest__.py
  sale_start_end_dates/i18n/ca.po
  sale_start_end_dates/i18n/de.po
  sale_start_end_dates/i18n/el_GR.po
  sale_start_end_dates/i18n/es.po
  sale_start_end_dates/i18n/es_ES.po
  sale_start_end_dates/i18n/es_VE.po
  sale_start_end_dates/i18n/fi.po
  sale_start_end_dates/i18n/fr.po
  sale_start_end_dates/i18n/hr.po
  sale_start_end_dates/i18n/hr_HR.po
  sale_start_end_dates/i18n/hu.po
  sale_start_end_dates/i18n/it.po
  sale_start_end_dates/i18n/nl.po
  sale_start_end_dates/i18n/nl_NL.po
  sale_start_end_dates/i18n/pt.po
  sale_start_end_dates/i18n/pt_BR.po
  sale_start_end_dates/i18n/ro.po
  sale_start_end_dates/i18n/sale_start_end_dates.pot
  sale_start_end_dates/i18n/sk.po
  sale_start_end_dates/i18n/sl.po
  sale_start_end_dates/i18n/tr.po
  sale_start_end_dates/i18n/tr_TR.po
  sale_start_end_dates/i18n/vi_VN.po
  sale_start_end_dates/i18n/zh_CN.po
  sale_start_end_dates/models/__init__.py
  sale_start_end_dates/models/sale_order.py
  sale_start_end_dates/readme/CONTRIBUTORS.rst
  sale_start_end_dates/readme/DESCRIPTION.rst
  sale_start_end_dates/static/description/icon.png
  sale_start_end_dates/static/description/index.html
  sale_start_end_dates/tests/__init__.py
  sale_start_end_dates/tests/test_sale_start_end_dates.py
  sale_start_end_dates/views/sale_order.xml
  setup/sale_start_end_dates/odoo/addons/sale_start_end_dates
  setup/sale_start_end_dates/setup.py
Labels: approved, bot is merging ⏳

#1546 [12.0] IMP sale_rental allowing to use routes selected in sale order line, if present
  sale_rental/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1667 [13.0][MIG] product_supplierinfo_for_customer_sale
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__init__.py
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/ROADMAP.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  product_supplierinfo_for_customer_sale/static/description/configuration_customer.png
  product_supplierinfo_for_customer_sale/static/description/description_code.png
  product_supplierinfo_for_customer_sale/static/description/description_code_2.png
  product_supplierinfo_for_customer_sale/static/description/icon.png
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/static/description/search_code.png
  product_supplierinfo_for_customer_sale/static/description/search_code_2.png
  product_supplierinfo_for_customer_sale/tests/__init__.py
  product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  product_supplierinfo_for_customer_sale/views/sale_view.xml
  setup/product_supplierinfo_for_customer_sale/odoo/addons/product_supplierinfo_for_customer_sale
  setup/product_supplierinfo_for_customer_sale/setup.py
Labels: approved, bot is merging ⏳, duplicate, migration, needs review, ready to merge

#614 [11.0][ADD] sale_timesheet_project_manual module
  sale_timesheet_project_manual/README.rst
  sale_timesheet_project_manual/__init__.py
  sale_timesheet_project_manual/__manifest__.py
  sale_timesheet_project_manual/i18n/fr.po
  sale_timesheet_project_manual/models/__init__.py
  sale_timesheet_project_manual/models/sale_order.py
  sale_timesheet_project_manual/static/description/icon.png
  sale_timesheet_project_manual/tests/__init__.py
  sale_timesheet_project_manual/tests/test_sale_timesheet_project_manual.py
  sale_timesheet_project_manual/views/sale_order.xml
  setup/sale_timesheet_project_manual/odoo/addons/sale_timesheet_project_manual
  setup/sale_timesheet_project_manual/setup.cfg
  setup/sale_timesheet_project_manual/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1684 [13.0][FIX] partner_sale_pivot: Fix security group
  partner_sale_pivot/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1681 [12.0][IMP] sale_discount_display_amount, add discount amount on document report
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/report/report_sale_order.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1529 [13.0][MIG] product_form_sale_link
  product_form_sale_link/README.rst
  product_form_sale_link/__init__.py
  product_form_sale_link/__manifest__.py
  product_form_sale_link/i18n/ca.po
  product_form_sale_link/i18n/es.po
  product_form_sale_link/i18n/fr.po
  product_form_sale_link/i18n/product_form_sale_link.pot
  product_form_sale_link/readme/CONTRIBUTORS.rst
  product_form_sale_link/readme/DESCRIPTION.rst
  product_form_sale_link/readme/USAGE.rst
  product_form_sale_link/static/description/icon.png
  product_form_sale_link/static/description/index.html
  product_form_sale_link/static/description/product_sale.png
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
  setup/product_form_sale_link/odoo/addons/product_form_sale_link
  setup/product_form_sale_link/setup.py
Labels: duplicate, question, approved, ready to merge, bot is merging ⏳

#1412 [MIG] sale_order_carrier_auto_assign: Migration to 14.0
  sale_order_carrier_auto_assign/README.rst
  sale_order_carrier_auto_assign/__init__.py
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/i18n/es.po
  sale_order_carrier_auto_assign/i18n/sale_order_carrier_auto_assign.pot
  sale_order_carrier_auto_assign/models/__init__.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/readme/CONTRIBUTORS.rst
  sale_order_carrier_auto_assign/readme/CREDITS.rst
  sale_order_carrier_auto_assign/readme/DESCRIPTION.rst
  sale_order_carrier_auto_assign/static/description/icon.png
  sale_order_carrier_auto_assign/static/description/index.html
  sale_order_carrier_auto_assign/tests/__init__.py
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
  setup/sale_order_carrier_auto_assign/odoo/addons/sale_order_carrier_auto_assign
  setup/sale_order_carrier_auto_assign/setup.py
Labels: needs fixing, needs review, approved, migration, ready to merge, bot is merging ⏳

#1680 [14.0][MIG] product_supplierinfo_for_customer_sale
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__init__.py
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/ROADMAP.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  product_supplierinfo_for_customer_sale/static/description/configuration_customer.png
  product_supplierinfo_for_customer_sale/static/description/description_code.png
  product_supplierinfo_for_customer_sale/static/description/description_code_2.png
  product_supplierinfo_for_customer_sale/static/description/icon.png
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/static/description/search_code.png
  product_supplierinfo_for_customer_sale/static/description/search_code_2.png
  product_supplierinfo_for_customer_sale/tests/__init__.py
  product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  product_supplierinfo_for_customer_sale/views/sale_view.xml
  setup/product_supplierinfo_for_customer_sale/odoo/addons/product_supplierinfo_for_customer_sale
  setup/product_supplierinfo_for_customer_sale/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1665 [13.0] sale_discount_display_amount: fix init hook
  sale_discount_display_amount/hooks.py
Labels: bot is merging ⏳

#1693 [14.0][ADD] sale_mail_autosubscribe
  sale_mail_autosubscribe/__init__.py
  sale_mail_autosubscribe/__manifest__.py
  sale_mail_autosubscribe/data/mail_autosubscribe.xml
  sale_mail_autosubscribe/readme/CONFIGURE.rst
  sale_mail_autosubscribe/readme/CONTRIBUTORS.rst
  sale_mail_autosubscribe/readme/DESCRIPTION.rst
  setup/sale_mail_autosubscribe/odoo/addons/sale_mail_autosubscribe
  setup/sale_mail_autosubscribe/setup.py
Labels: needs review, approved, merged 🎉

#1695 [14.0][ADD] sale_transaction_form_link
  sale_transaction_form_link/README.rst
  sale_transaction_form_link/__init__.py
  sale_transaction_form_link/__manifest__.py
  sale_transaction_form_link/demo/payment_transaction.xml
  sale_transaction_form_link/models/__init__.py
  sale_transaction_form_link/models/sale_order.py
  sale_transaction_form_link/readme/CONTRIBUTORS.rst
  sale_transaction_form_link/readme/DESCRIPTION.rst
  sale_transaction_form_link/readme/USAGE.rst
  sale_transaction_form_link/static/description/icon.png
  sale_transaction_form_link/static/description/index.html
  sale_transaction_form_link/views/sale_order.xml
  setup/sale_transaction_form_link/odoo/addons/sale_transaction_form_link
  setup/sale_transaction_form_link/setup.py
Labels: needs review, approved, bot is merging ⏳
