Repository OCA/sale-workflow, pull requests merged in 2021-03, with the labels that each got.

#1323 [ADD] sale_coupon_multi_use: init
  sale_coupon_multi_currency/README.rst
  sale_coupon_multi_currency/__init__.py
  sale_coupon_multi_currency/__manifest__.py
  sale_coupon_multi_currency/i18n/fr.po
  sale_coupon_multi_currency/models/__init__.py
  sale_coupon_multi_currency/models/sale_coupon_program.py
  sale_coupon_multi_currency/readme/CONTRIBUTORS.rst
  sale_coupon_multi_currency/readme/DESCRIPTION.rst
  sale_coupon_multi_currency/tests/__init__.py
  sale_coupon_multi_currency/tests/common.py
  sale_coupon_multi_currency/tests/test_sale_coupon_multi_currency.py
  sale_coupon_multi_currency/views/sale_coupon_program_views.xml
  sale_coupon_multi_use/README.rst
  sale_coupon_multi_use/__init__.py
  sale_coupon_multi_use/__manifest__.py
  sale_coupon_multi_use/i18n/fr.po
  sale_coupon_multi_use/models/__init__.py
  sale_coupon_multi_use/models/sale_coupon.py
  sale_coupon_multi_use/models/sale_coupon_consumption_line.py
  sale_coupon_multi_use/models/sale_coupon_program.py
  sale_coupon_multi_use/models/sale_order.py
  sale_coupon_multi_use/models/sale_order_line.py
  sale_coupon_multi_use/readme/CONTRIBUTORS.rst
  sale_coupon_multi_use/readme/DESCRIPTION.rst
  sale_coupon_multi_use/security/ir.model.access.csv
  sale_coupon_multi_use/tests/__init__.py
  sale_coupon_multi_use/tests/common.py
  sale_coupon_multi_use/tests/test_sale_coupon_use.py
  sale_coupon_multi_use/views/sale_coupon_program_views.xml
  sale_coupon_multi_use/views/sale_coupon_views.xml
  sale_coupon_multi_use/wizards/__init__.py
  sale_coupon_multi_use/wizards/sale_coupon_apply_code.py
  sale_coupon_multi_use_currency/README.rst
  sale_coupon_multi_use_currency/__init__.py
  sale_coupon_multi_use_currency/__manifest__.py
  sale_coupon_multi_use_currency/i18n/fr.po
  sale_coupon_multi_use_currency/models/__init__.py
  sale_coupon_multi_use_currency/models/sale_coupon_program.py
  sale_coupon_multi_use_currency/readme/CONTRIBUTORS.rst
  sale_coupon_multi_use_currency/readme/DESCRIPTION.rst
  sale_coupon_multi_use_currency/tests/__init__.py
  sale_coupon_multi_use_currency/tests/test_sale_coupon_use_currency.py
  setup/sale_coupon_multi_currency/odoo/addons/sale_coupon_multi_currency
  setup/sale_coupon_multi_currency/setup.py
  setup/sale_coupon_multi_use/odoo/addons/sale_coupon_multi_use
  setup/sale_coupon_multi_use/setup.py
  setup/sale_coupon_multi_use_currency/odoo/addons/sale_coupon_multi_use_currency
  setup/sale_coupon_multi_use_currency/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1342 [ADD] sale_coupon_most_expensive: init
  sale_coupon_most_expensive/README.rst
  sale_coupon_most_expensive/__init__.py
  sale_coupon_most_expensive/__manifest__.py
  sale_coupon_most_expensive/i18n/fr.po
  sale_coupon_most_expensive/models/__init__.py
  sale_coupon_most_expensive/models/sale_coupon_reward.py
  sale_coupon_most_expensive/models/sale_order.py
  sale_coupon_most_expensive/readme/CONTRIBUTORS.rst
  sale_coupon_most_expensive/readme/DESCRIPTION.rst
  sale_coupon_most_expensive/tests/__init__.py
  sale_coupon_most_expensive/tests/test_discount_apply_on.py
  setup/sale_coupon_most_expensive/odoo/addons/sale_coupon_most_expensive
  setup/sale_coupon_most_expensive/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1504 [12.0][FIX] portal_sale_personal_data_only: invalid domain in ir.rule
  portal_sale_personal_data_only/data/portal_sale_security.xml
Labels: approved, bot is merging ⏳

#1505 [13.0][FIX] portal_sale_personal_data_only: invalid domain in ir.rule
  portal_sale_personal_data_only/data/portal_sale_security.xml
Labels: approved, bot is merging ⏳

#1064 [MIG][13.0] partner_sale_pivot: Migration to v13.0
  partner_sale_pivot/README.rst
  partner_sale_pivot/__init__.py
  partner_sale_pivot/__manifest__.py
  partner_sale_pivot/i18n/ca.po
  partner_sale_pivot/i18n/ca_ES.po
  partner_sale_pivot/i18n/es.po
  partner_sale_pivot/i18n/partner_sale_pivot.pot
  partner_sale_pivot/readme/CONTRIBUTORS.rst
  partner_sale_pivot/readme/DESCRIPTION.rst
  partner_sale_pivot/readme/USAGE.rst
  partner_sale_pivot/static/description/icon.png
  partner_sale_pivot/static/description/index.html
  partner_sale_pivot/views/res_partner_views.xml
  partner_sale_pivot/views/sale_report_views.xml
  setup/partner_sale_pivot/odoo/addons/partner_sale_pivot
  setup/partner_sale_pivot/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1496 [12.0][FIX] sale_triple_discount: Cache management
  sale_triple_discount/models/sale_order_line.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1494 Support pricelist with excluded discounts
  sale_product_multi_add/readme/CONTRIBUTORS.rst
  sale_product_multi_add/tests/test_sale.py
  sale_product_multi_add/wizards/sale_import_products.py
Labels: approved, bot is merging ⏳, ready to merge

#1475 [13.0][MIG] sale_stock_return_request: Migration to v13.0
  oca_dependencies.txt
  sale_stock_return_request/README.rst
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/ca.po
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/i18n/fr.po
  sale_stock_return_request/i18n/sale_stock_return_request.pot
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
  setup/sale_stock_return_request/odoo/addons/sale_stock_return_request
  setup/sale_stock_return_request/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1500 [IMP] sale_rental: extract function _run_rental_procurement
  sale_rental/models/sale_order.py
Labels: approved, bot is merging ⏳

#1508 [12.0][ADD] sale_secondary_salesperson: Sale Secondary Salesperson
  sale_secondary_salesperson/README.rst
  sale_secondary_salesperson/__init__.py
  sale_secondary_salesperson/__manifest__.py
  sale_secondary_salesperson/models/__init__.py
  sale_secondary_salesperson/models/sale_order.py
  sale_secondary_salesperson/readme/CONTRIBUTORS.rst
  sale_secondary_salesperson/readme/DESCRIPTION.rst
  sale_secondary_salesperson/readme/USAGE.rst
  sale_secondary_salesperson/report/__init__.py
  sale_secondary_salesperson/report/sale_report.py
  sale_secondary_salesperson/static/description/icon.png
  sale_secondary_salesperson/tests/__init__.py
  sale_secondary_salesperson/tests/test_sale_order.py
  sale_secondary_salesperson/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#1511 [13.0][MIG] sale_secondary_salesperson: Migration to 13.0
  sale_secondary_salesperson/README.rst
  sale_secondary_salesperson/__init__.py
  sale_secondary_salesperson/__manifest__.py
  sale_secondary_salesperson/i18n/sale_secondary_salesperson.pot
  sale_secondary_salesperson/models/__init__.py
  sale_secondary_salesperson/models/sale_order.py
  sale_secondary_salesperson/readme/CONTRIBUTORS.rst
  sale_secondary_salesperson/readme/DESCRIPTION.rst
  sale_secondary_salesperson/readme/USAGE.rst
  sale_secondary_salesperson/report/__init__.py
  sale_secondary_salesperson/report/sale_report.py
  sale_secondary_salesperson/static/description/icon.png
  sale_secondary_salesperson/static/description/index.html
  sale_secondary_salesperson/tests/__init__.py
  sale_secondary_salesperson/tests/test_sale_order.py
  sale_secondary_salesperson/views/sale_order_view.xml
  setup/sale_secondary_salesperson/odoo/addons/sale_secondary_salesperson
  setup/sale_secondary_salesperson/setup.py
Labels: approved, bot is merging ⏳

#1492 [13.0] sale_automatic_workflow: Do not post invoices set back to draft
  sale_automatic_workflow/data/automatic_workflow_data.xml
  sale_automatic_workflow/migrations/13.0.1.2.0/noupdate_changes.xml
  sale_automatic_workflow/migrations/13.0.1.2.0/post.py
Labels: bot is merging ⏳

#1513 [12.0][IMP] sales_team_security: Adjust team according salesman in partners
  sales_team_security/models/res_partner.py
  sales_team_security/tests/test_sales_team_security.py
Labels: approved, bot is merging ⏳

#1507 [12.0][IMP]sale_order_type: update quotation name when user change or…
  sale_order_type/models/sale_order.py
  sale_order_type/tests/test_sale_order_type.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1517 [12.0][FIX] sale_order_type, singleton error on write
  sale_order_type/models/sale_order.py
  sale_order_type/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1469 [12.0][IMP] sale_order_invoicing_finished_task: Avoid cancel SO with invoiced tasks
  sale_order_invoicing_finished_task/i18n/es.po
  sale_order_invoicing_finished_task/i18n/sale_order_invoicing_finished_task.pot
  sale_order_invoicing_finished_task/models/sale_order.py
Labels: bot is merging ⏳

#1478 [14.0][FIX] sale_order_lot_generator: AttributeError: 'stock.move.line' object has no attribute 'restrict_lot_id'
  sale_order_lot_generator/tests/test_sale_order_lot_generator.py
Labels: approved, bot is merging ⏳, ready to merge

#1526 [FIX] sale_automatic_workflow: Fix tests multi-company issues
  sale_automatic_workflow/tests/test_multicompany.py
  sales_team_security/tests/test_sales_team_security.py
Labels: approved, bot is merging ⏳

#1488 [13.0][FIX] sale_product_multi_add
  sale_product_multi_add/wizards/sale_import_products_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1534 [13.0][FIX]sale_procurement_group_by_line: fix fill previous_product_…
  sale_procurement_group_by_line/model/sale.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1531 [FIX] sale_order_type: Non reset the value when it's sitting by the user in the view.
  sale_order_type/models/account_move.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1477 [14.0][FIX] sale_quotation_number: assertRegexpMatches is deprecation
  sale_quotation_number/tests/test_sale_order.py
Labels: approved, bot is merging ⏳, ready to merge

#1522 [12.0][FIX] sale order revision trailing space
  sale_order_revision/models/sale_order.py
Labels: approved, bot is merging ⏳

#1460 [14.0][MIG] sale_order_line_date
  sale_order_line_date/README.rst
  sale_order_line_date/__init__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_date/i18n/ca.po
  sale_order_line_date/i18n/de.po
  sale_order_line_date/i18n/el_GR.po
  sale_order_line_date/i18n/es.po
  sale_order_line_date/i18n/es_ES.po
  sale_order_line_date/i18n/es_VE.po
  sale_order_line_date/i18n/fi.po
  sale_order_line_date/i18n/fr.po
  sale_order_line_date/i18n/hr.po
  sale_order_line_date/i18n/hr_HR.po
  sale_order_line_date/i18n/hu.po
  sale_order_line_date/i18n/it.po
  sale_order_line_date/i18n/nl.po
  sale_order_line_date/i18n/nl_NL.po
  sale_order_line_date/i18n/pt.po
  sale_order_line_date/i18n/pt_BR.po
  sale_order_line_date/i18n/ro.po
  sale_order_line_date/i18n/sale_order_line_date.pot
  sale_order_line_date/i18n/sk.po
  sale_order_line_date/i18n/sl.po
  sale_order_line_date/i18n/tr.po
  sale_order_line_date/i18n/tr_TR.po
  sale_order_line_date/i18n/vi_VN.po
  sale_order_line_date/i18n/zh_CN.po
  sale_order_line_date/models/__init__.py
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/readme/CONTRIBUTORS.rst
  sale_order_line_date/readme/DESCRIPTION.rst
  sale_order_line_date/readme/USAGE.rst
  sale_order_line_date/reports/sale_order_report.xml
  sale_order_line_date/static/description/icon.png
  sale_order_line_date/static/description/index.html
  sale_order_line_date/tests/__init__.py
  sale_order_line_date/tests/test_sale_order_line_date.py
  sale_order_line_date/views/sale_order_view.xml
  setup/sale_order_line_date/odoo/addons/sale_order_line_date
  setup/sale_order_line_date/setup.py
Labels: approved, bot is merging ⏳, ready to merge
