Repository OCA/sale-workflow, pull requests merged in 2021-05, with the labels that each got.

#1366 [14][MIG] sale_shipping_info_helper
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__manifest__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/readme/CONTRIBUTORS.rst
  sale_shipping_info_helper/readme/DESCRIPTION.rst
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/static/description/index.html
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
  setup/sale_shipping_info_helper/odoo/addons/sale_shipping_info_helper
  setup/sale_shipping_info_helper/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1154 12.0 imp sale min qty
  requirements.txt
  sale_order_min_qty/__init__.py
  sale_order_min_qty/models/__init__.py
  sale_order_min_qty/models/product.py
  sale_order_min_qty/models/sale.py
  sale_order_min_qty/readme/DESCRIPTION.rst
  sale_order_min_qty/tests/test_sale.py
  sale_order_min_qty/views/product_views.xml
  sale_restricted_qty/README.rst
  sale_restricted_qty/__init__.py
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/hooks.py
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/models/__init__.py
  sale_restricted_qty/models/product_category.py
  sale_restricted_qty/models/product_product.py
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/product_template.py
  sale_restricted_qty/models/sale.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/icon.png
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/tests/__init__.py
  sale_restricted_qty/tests/test_sale.py
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
  sale_restricted_qty/views/sale_views.xml
  setup/sale_restricted_qty/odoo/addons/sale_restricted_qty
  setup/sale_restricted_qty/setup.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1548 [13.0][FIX] sale_cutoff_time_delivery: fix expected_date computation
  sale_cutoff_time_delivery/models/sale_order.py
  sale_cutoff_time_delivery/tests/test_sale_cutoff_time_delivery.py
  sale_partner_delivery_window/models/sale_order.py
Labels: approved, bot is merging ⏳, ready to merge

#1538 [13.0][ADD] sale_coupon_most_expensive_delivery
  sale_coupon_most_expensive_delivery/README.rst
  sale_coupon_most_expensive_delivery/__init__.py
  sale_coupon_most_expensive_delivery/__manifest__.py
  sale_coupon_most_expensive_delivery/models/__init__.py
  sale_coupon_most_expensive_delivery/models/sale_order.py
  sale_coupon_most_expensive_delivery/readme/CONTRIBUTORS.rst
  sale_coupon_most_expensive_delivery/readme/DESCRIPTION.rst
  sale_coupon_most_expensive_delivery/tests/__init__.py
  sale_coupon_most_expensive_delivery/tests/test_discount_apply_on.py
  setup/sale_coupon_most_expensive_delivery/odoo/addons/sale_coupon_most_expensive_delivery
  setup/sale_coupon_most_expensive_delivery/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1532 13.0 mig sale invoice policy
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/ca.po
  sale_invoice_policy/i18n/es.po
  sale_invoice_policy/i18n/fr.po
  sale_invoice_policy/i18n/pt.po
  sale_invoice_policy/i18n/sale_invoice_policy.pot
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/post_init_hook.py
  sale_invoice_policy/readme/CONTRIBUTORS.rst
  sale_invoice_policy/readme/DESCRIPTION.rst
  sale_invoice_policy/readme/USAGE.rst
  sale_invoice_policy/static/description/icon.png
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/__init__.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/product_template_view.xml
  sale_invoice_policy/views/sale_view.xml
  sale_invoice_policy/wizards/__init__.py
  sale_invoice_policy/wizards/res_config.py
  sale_invoice_policy/wizards/res_config_view.xml
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1545 [12.0] FIX sale_start_end_dates: _check_start_end_dates can be executed on recordsets greater than 1
  sale_start_end_dates/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1554 [13.0][ADD] sale_order_invoice_amount
  sale_order_invoice_amount/__init__.py
  sale_order_invoice_amount/__manifest__.py
  sale_order_invoice_amount/models/__init__.py
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/readme/CONTRIBUTORS.rst
  sale_order_invoice_amount/readme/DESCRIPTION.rst
  sale_order_invoice_amount/tests/__init__.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
  sale_order_invoice_amount/views/sale_order_view.xml
  setup/sale_order_invoice_amount/odoo/addons/sale_order_invoice_amount
  setup/sale_order_invoice_amount/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1510 [14.0][ADD] sale_pricelist_from_commitment_date
  sale_pricelist_from_commitment_date/README.rst
  sale_pricelist_from_commitment_date/__init__.py
  sale_pricelist_from_commitment_date/__manifest__.py
  sale_pricelist_from_commitment_date/models/__init__.py
  sale_pricelist_from_commitment_date/models/product_pricelist.py
  sale_pricelist_from_commitment_date/models/product_product.py
  sale_pricelist_from_commitment_date/models/sale_order.py
  sale_pricelist_from_commitment_date/models/sale_order_line.py
  sale_pricelist_from_commitment_date/readme/CONTRIBUTORS.rst
  sale_pricelist_from_commitment_date/readme/DESCRIPTION.rst
  sale_pricelist_from_commitment_date/tests/__init__.py
  sale_pricelist_from_commitment_date/tests/test_pricelist_from_commitment_date.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1576 [13.0][FIX] sale_automatic_workflow: Change test_create_invoice_from_sale_order to remove mock
  sale_automatic_workflow/tests/test_automatic_workflow.py
Labels: approved, bot is merging ⏳

#1444 [12.0] [IMP] sale_order_general_discount: Add tracking to sale_discount on partners
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, enhancement, needs review

#1130 [12.0][FIX] sale_invoice_plan, fix case advance
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/readme/HISTORY.rst
  sale_invoice_plan/views/sale_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1466 [13.0][MIG]sale_blanket_order: Migration to 13.0
  sale_blanket_order/README.rst
  sale_blanket_order/__init__.py
  sale_blanket_order/__manifest__.py
  sale_blanket_order/data/ir_cron.xml
  sale_blanket_order/data/sequence.xml
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/pt.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/DESCRIPTION.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/report/report.xml
  sale_blanket_order/report/templates.xml
  sale_blanket_order/security/ir.model.access.csv
  sale_blanket_order/security/security.xml
  sale_blanket_order/static/description/BO_actions.png
  sale_blanket_order/static/description/BO_form.png
  sale_blanket_order/static/description/BO_lines.png
  sale_blanket_order/static/description/BO_menu.png
  sale_blanket_order/static/description/PO_BOLine.png
  sale_blanket_order/static/description/PO_from_BO.png
  sale_blanket_order/static/description/icon.png
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/__init__.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/views/sale_order_views.xml
  sale_blanket_order/wizard/__init__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order/wizard/create_sale_orders.xml
  setup/sale_blanket_order/odoo/addons/sale_blanket_order
  setup/sale_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#1083 [12.0][ADD] pricelist_by_category_qty
  pricelist_by_category_qty/README.rst
  pricelist_by_category_qty/__init__.py
  pricelist_by_category_qty/__manifest__.py
  pricelist_by_category_qty/i18n/fr.po
  pricelist_by_category_qty/models/__init__.py
  pricelist_by_category_qty/models/sale.py
  pricelist_by_category_qty/readme/CONTRIBUTORS.rst
  pricelist_by_category_qty/readme/DESCRIPTION.rst
  pricelist_by_category_qty/readme/ROADMAP.rst
  pricelist_by_category_qty/static/description/icon.png
  pricelist_by_category_qty/static/description/index.html
  pricelist_by_category_qty/views/sale_view.xml
Labels: approved, bot is merging ⏳, needs review

#1479 [ADD] sale_coupon_product_management: init
  sale_coupon_product_management/README.rst
  sale_coupon_product_management/__init__.py
  sale_coupon_product_management/__manifest__.py
  sale_coupon_product_management/i18n/fr.po
  sale_coupon_product_management/models/__init__.py
  sale_coupon_product_management/models/product_category.py
  sale_coupon_product_management/models/product_product.py
  sale_coupon_product_management/models/sale_coupon_program.py
  sale_coupon_product_management/readme/CONTRIBUTORS.rst
  sale_coupon_product_management/readme/DESCRIPTION.rst
  sale_coupon_product_management/tests/__init__.py
  sale_coupon_product_management/tests/common.py
  sale_coupon_product_management/tests/test_sale_coupon_manage.py
  sale_coupon_product_management/views/product_category_views.xml
  sale_coupon_product_management/views/product_product_views.xml
  sale_coupon_product_management/views/sale_coupon_program_views.xml
  setup/sale_coupon_product_management/odoo/addons/sale_coupon_product_management
  setup/sale_coupon_product_management/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1415 [MIG][14.0]sale_order_line_description
  sale_order_line_description/README.rst
  sale_order_line_description/__init__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_description/i18n/ca.po
  sale_order_line_description/i18n/de.po
  sale_order_line_description/i18n/en.po
  sale_order_line_description/i18n/es.po
  sale_order_line_description/i18n/es_VE.po
  sale_order_line_description/i18n/fr.po
  sale_order_line_description/i18n/hr.po
  sale_order_line_description/i18n/it.po
  sale_order_line_description/i18n/nl_NL.po
  sale_order_line_description/i18n/pt_BR.po
  sale_order_line_description/i18n/ro.po
  sale_order_line_description/i18n/sale_order_line_description.pot
  sale_order_line_description/i18n/sl.po
  sale_order_line_description/i18n/tr.po
  sale_order_line_description/i18n/tr_TR.po
  sale_order_line_description/i18n/zh_CN.po
  sale_order_line_description/models/__init__.py
  sale_order_line_description/models/res_config_settings.py
  sale_order_line_description/models/sale_order_line.py
  sale_order_line_description/readme/CONFIGURE.rst
  sale_order_line_description/readme/CONTRIBUTORS.rst
  sale_order_line_description/readme/DESCRIPTION.rst
  sale_order_line_description/readme/USAGE.rst
  sale_order_line_description/security/sale_security.xml
  sale_order_line_description/static/description/icon.png
  sale_order_line_description/static/description/index.html
  sale_order_line_description/tests/__init__.py
  sale_order_line_description/tests/test_sale.py
  sale_order_line_description/views/res_config_settings_views.xml
  setup/sale_order_line_description/odoo/addons/sale_order_line_description
  setup/sale_order_line_description/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1551 [13.0][FIX] sale_exception ignore after confirm
  sale_exception/models/sale.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1509 [14.0][ADD] module sale_commitment_date_mandatory
  sale_commitment_date_mandatory/README.rst
  sale_commitment_date_mandatory/__init__.py
  sale_commitment_date_mandatory/__manifest__.py
  sale_commitment_date_mandatory/models/__init__.py
  sale_commitment_date_mandatory/models/sale_order.py
  sale_commitment_date_mandatory/readme/CONTRIBUTORS.rst
  sale_commitment_date_mandatory/readme/DESCRIPTION.rst
  sale_commitment_date_mandatory/views/sale_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#955 [ADD] sale_substate 12.0
  oca_dependencies.txt
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/readme/CONTRIBUTORS.rst
  sale_substate/readme/DESCRIPTION.rst
  sale_substate/readme/USAGE.rst
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#1476 [14.0][FIX] sale_validity: method '_company_default_get' is deprecated
  sale_validity/models/sale_order.py
Labels: approved, bot is merging ⏳

#1588 [13.0][FIX] sale_order_product_recommendation: commercial_partner_id on delivery_address
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳

#1518 [14.0][ADD] sale_advance_payment
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: bot is merging ⏳, needs review

#1573 [13.0][ADD] sale_order_qty_change_no_recompute: Prevent recompute if only quantity has changed in sale order line-
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/models/__init__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: approved, bot is merging ⏳, needs review

#1503 [13.0][FIX] sale_order_warn_message display of warning
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
Labels: approved, bot is merging ⏳, question, ready to merge

#1593 [13.0][IMP] sale_order_qty_change_no_recompute: Improve tests
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: approved, bot is merging ⏳

#1592 [14.0][MIG] sale_order_qty_change_no_recompute: Migration to 14.0
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/models/__init__.py
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.rst
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.rst
  sale_order_qty_change_no_recompute/readme/USAGE.rst
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
  setup/sale_order_qty_change_no_recompute/odoo/addons/sale_order_qty_change_no_recompute
  setup/sale_order_qty_change_no_recompute/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1589 sale_product_set: fix SO line vals get
  sale_product_set/__manifest__.py
  sale_product_set/wizard/product_set_add.py
Labels: bot is merging ⏳

#1595 [ADD] new module sale_invoice_blocking
  sale_invoice_blocking/README.rst
  sale_invoice_blocking/__init__.py
  sale_invoice_blocking/__manifest__.py
  sale_invoice_blocking/i18n/fr.po
  sale_invoice_blocking/models/__init__.py
  sale_invoice_blocking/models/invoice_blocking_reason.py
  sale_invoice_blocking/models/sale_order.py
  sale_invoice_blocking/readme/CONFIGURE.rst
  sale_invoice_blocking/readme/CONTRIBUTORS.rst
  sale_invoice_blocking/readme/DESCRIPTION.rst
  sale_invoice_blocking/readme/USAGE.rst
  sale_invoice_blocking/security/ir.model.access.csv
  sale_invoice_blocking/views/menus.xml
  sale_invoice_blocking/views/sale_invoice_blocking_reason_view.xml
  sale_invoice_blocking/views/sale_order.xml
  setup/sale_invoice_blocking/odoo/addons/sale_invoice_blocking
  setup/sale_invoice_blocking/setup.py
Labels: approved, bot is merging ⏳, needs review

#1402 [MIG] sale_product_set_packaging_qty: Migration to 14.0
  sale_product_set_packaging_qty/README.rst
  sale_product_set_packaging_qty/__init__.py
  sale_product_set_packaging_qty/__manifest__.py
  sale_product_set_packaging_qty/i18n/es.po
  sale_product_set_packaging_qty/i18n/sale_product_set_packaging_qty.pot
  sale_product_set_packaging_qty/models/__init__.py
  sale_product_set_packaging_qty/models/product_set.py
  sale_product_set_packaging_qty/readme/CONTRIBUTORS.rst
  sale_product_set_packaging_qty/readme/CREDITS.rst
  sale_product_set_packaging_qty/readme/DESCRIPTION.rst
  sale_product_set_packaging_qty/static/description/icon.png
  sale_product_set_packaging_qty/static/description/index.html
  sale_product_set_packaging_qty/tests/__init__.py
  sale_product_set_packaging_qty/tests/test_product_set_packaging.py
  sale_product_set_packaging_qty/views/product_set.xml
  setup/sale_product_set_packaging_qty/odoo/addons/sale_product_set_packaging_qty
  setup/sale_product_set_packaging_qty/setup.py
Labels: bot is merging ⏳, migration, needs review

#1599 [13.0] Fix view_sales_order_undelivered_line_filter
  sale_manual_delivery/views/sale_order.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1594 [14.0] Add sale_product_seasonality
  sale_product_seasonality/README.rst
  sale_product_seasonality/__init__.py
  sale_product_seasonality/__manifest__.py
  sale_product_seasonality/i18n/fr.po
  sale_product_seasonality/models/__init__.py
  sale_product_seasonality/models/sale_order.py
  sale_product_seasonality/models/sale_order_line.py
  sale_product_seasonality/readme/CONFIGURE.rst
  sale_product_seasonality/readme/CONTRIBUTORS.rst
  sale_product_seasonality/readme/DESCRIPTION.rst
  sale_product_seasonality/readme/ROADMAP.rst
  sale_product_seasonality/tests/__init__.py
  sale_product_seasonality/tests/common.py
  sale_product_seasonality/tests/test_sale_order.py
  sale_product_seasonality/utils.py
  sale_product_seasonality/views/menu.xml
  sale_product_seasonality/views/sale_order.xml
  setup/sale_product_seasonality/odoo/addons/sale_product_seasonality
  setup/sale_product_seasonality/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1596 [14.0] sale_product_set: forward port improvements from v13
  sale_product_set/__manifest__.py
  sale_product_set/tests/test_product_set.py
  sale_product_set/views/sale_order.xml
  sale_product_set/wizard/product_set_add.py
  sale_product_set/wizard/product_set_add.xml
Labels: approved, bot is merging ⏳, enhancement, needs review
