Repository OCA/sale-workflow, pull requests merged in 2021-07, with the labels that each got.

#1622 [13.0] s_partner_delivery_window: improve err message
  sale_partner_delivery_window/models/res_partner.py
Labels: bot is merging ⏳, needs review

#1641 [14.0] sale_product_seasonality: Add product template management
  sale_product_seasonality/models/sale_order.py
  sale_product_seasonality/tests/test_sale_order.py
Labels: bot is merging ⏳

#1626 [14.0] Add sale_product_brand_exception
  sale_product_brand_exception/README.rst
  sale_product_brand_exception/__init__.py
  sale_product_brand_exception/__manifest__.py
  sale_product_brand_exception/data/exception_rule.xml
  sale_product_brand_exception/demo/exception_rule.xml
  sale_product_brand_exception/models/__init__.py
  sale_product_brand_exception/models/product_brand.py
  sale_product_brand_exception/models/sale_order.py
  sale_product_brand_exception/readme/CONTRIBUTORS.rst
  sale_product_brand_exception/readme/DESCRIPTION.rst
  sale_product_brand_exception/tests/__init__.py
  sale_product_brand_exception/tests/test_product_brand.py
  sale_product_brand_exception/views/product_brand_view.xml
  setup/sale_product_brand_exception/odoo/addons/sale_product_brand_exception
  setup/sale_product_brand_exception/setup.py
Labels: bot is merging ⏳

#1620 [14.0] [mig] sale_order_line_price_history
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/assets.xml
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  setup/sale_order_line_price_history/odoo/addons/sale_order_line_price_history
  setup/sale_order_line_price_history/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1628 [FIX] use same version as other oca projects
  requirements.txt
Labels: bot is merging ⏳

#1352 [14.0][MIG] sales_team_security
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/it.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
  sales_team_security_crm/__init__.py
  sales_team_security_crm/__manifest__.py
  sales_team_security_crm/readme/CONTRIBUTORS.rst
  sales_team_security_crm/readme/DESCRIPTION.rst
  sales_team_security_crm/security/security.xml
  sales_team_security_sale/__init__.py
  sales_team_security_sale/__manifest__.py
  sales_team_security_sale/readme/CONTRIBUTORS.rst
  sales_team_security_sale/readme/DESCRIPTION.rst
  sales_team_security_sale/security/security.xml
  setup/sales_team_security/odoo/addons/sales_team_security
  setup/sales_team_security/setup.py
  setup/sales_team_security_crm/odoo/addons/sales_team_security_crm
  setup/sales_team_security_crm/setup.py
  setup/sales_team_security_sale/odoo/addons/sales_team_security_sale
  setup/sales_team_security_sale/setup.py
Labels: approved, bot is merging ⏳

#1072 12.0-fix-installation-product_form_sale_link
  product_form_sale_link/views/product_template.xml
Labels: approved, bot is merging ⏳, needs fixing

#1644 [13.0][MIG] Migrated partner_prospect to v13
  partner_prospect/README.rst
  partner_prospect/__init__.py
  partner_prospect/__manifest__.py
  partner_prospect/i18n/de.po
  partner_prospect/i18n/es.po
  partner_prospect/i18n/fr.po
  partner_prospect/i18n/partner_prospect.pot
  partner_prospect/i18n/sl.po
  partner_prospect/i18n/zh_CN.po
  partner_prospect/models/__init__.py
  partner_prospect/models/res_partner.py
  partner_prospect/readme/CONTRIBUTORS.rst
  partner_prospect/readme/DESCRIPTION.rst
  partner_prospect/static/description/icon.png
  partner_prospect/static/description/index.html
  partner_prospect/tests/__init__.py
  partner_prospect/tests/test_partner_prospect.py
  partner_prospect/views/res_partner_view.xml
  setup/partner_prospect/odoo/addons/partner_prospect
  setup/partner_prospect/setup.py
Labels: bot is merging ⏳

#1525 [13.0] port forward from 12.0
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
Labels: bot is merging ⏳, enhancement, needs review

#1639 [14.0][FIX] - sale_automatic_workflow: fix method header
  sale_automatic_workflow/models/sale_order.py
Labels: approved, bot is merging ⏳, ready to merge

#1598 [FIX] for drop shipping module
  sale_manual_delivery/models/sale_order_line.py
Labels: bot is merging ⏳, enhancement, needs review

#1590 [14.0][MIG] sale_automatic_workflow_payment_mode
  sale_automatic_workflow_payment_mode/README.rst
  sale_automatic_workflow_payment_mode/__init__.py
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/data/automatic_workflow_data.xml
  sale_automatic_workflow_payment_mode/i18n/ca.po
  sale_automatic_workflow_payment_mode/i18n/de.po
  sale_automatic_workflow_payment_mode/i18n/el_GR.po
  sale_automatic_workflow_payment_mode/i18n/es.po
  sale_automatic_workflow_payment_mode/i18n/es_ES.po
  sale_automatic_workflow_payment_mode/i18n/es_VE.po
  sale_automatic_workflow_payment_mode/i18n/fi.po
  sale_automatic_workflow_payment_mode/i18n/fr.po
  sale_automatic_workflow_payment_mode/i18n/hr.po
  sale_automatic_workflow_payment_mode/i18n/hr_HR.po
  sale_automatic_workflow_payment_mode/i18n/hu.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/nl.po
  sale_automatic_workflow_payment_mode/i18n/nl_NL.po
  sale_automatic_workflow_payment_mode/i18n/pt.po
  sale_automatic_workflow_payment_mode/i18n/pt_BR.po
  sale_automatic_workflow_payment_mode/i18n/ro.po
  sale_automatic_workflow_payment_mode/i18n/sale_automatic_workflow_payment_mode.pot
  sale_automatic_workflow_payment_mode/i18n/sk.po
  sale_automatic_workflow_payment_mode/i18n/sl.po
  sale_automatic_workflow_payment_mode/i18n/tr.po
  sale_automatic_workflow_payment_mode/i18n/tr_TR.po
  sale_automatic_workflow_payment_mode/i18n/vi_VN.po
  sale_automatic_workflow_payment_mode/i18n/zh_CN.po
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/account_payment_mode.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/models/sale_workflow_process.py
  sale_automatic_workflow_payment_mode/readme/CONFIGURE.rst
  sale_automatic_workflow_payment_mode/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_payment_mode/readme/CREDITS.rst
  sale_automatic_workflow_payment_mode/readme/DESCRIPTION.rst
  sale_automatic_workflow_payment_mode/readme/INSTALL.rst
  sale_automatic_workflow_payment_mode/readme/USAGE.rst
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/index.html
  sale_automatic_workflow_payment_mode/tests/__init__.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  sale_automatic_workflow_payment_mode/views/account_payment_mode_views.xml
  sale_automatic_workflow_payment_mode/views/sale_workflow_process_view.xml
  setup/sale_automatic_workflow_payment_mode/odoo/addons/sale_automatic_workflow_payment_mode
  setup/sale_automatic_workflow_payment_mode/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1561 [MIG] sale_global_discount: Migration to 13.0
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/pt.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/CONTRIBUTORS.rst
  sale_global_discount/readme/DESCRIPTION.rst
  sale_global_discount/readme/ROADMAP.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
  setup/sale_global_discount/odoo/addons/sale_global_discount
  setup/sale_global_discount/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1617 [FIX] sale_order_line_date: remove dependency to 'sale_stock' module
  sale_order_line_date/__manifest__.py
Labels: approved, bot is merging ⏳, ready to merge

#1634 [13.0] sale_cutoff_time_delivery: Add expected date on reports
  sale_cutoff_time_delivery/__manifest__.py
  sale_cutoff_time_delivery/i18n/de.po
  sale_cutoff_time_delivery/i18n/fr_CH.po
  sale_cutoff_time_delivery/i18n/it.po
  sale_cutoff_time_delivery/models/sale_order.py
  sale_cutoff_time_delivery/reports/sale_order.xml
  sale_cutoff_time_delivery/reports/stock_picking.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1490 [14.0][ADD] sale_cancel_confirm
  sale_cancel_confirm/__init__.py
  sale_cancel_confirm/__manifest__.py
  sale_cancel_confirm/model/__init__.py
  sale_cancel_confirm/model/sale.py
  sale_cancel_confirm/readme/CONTRIBUTORS.rst
  sale_cancel_confirm/readme/DESCRIPTION.rst
  sale_cancel_confirm/static/description/icon.png
  sale_cancel_confirm/static/description/index.html
  setup/sale_cancel_confirm/odoo/addons/sale_cancel_confirm
  setup/sale_cancel_confirm/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1372 [MIG] 14.0 sale_delivery_state
  sale_automatic_workflow/models/sale_order.py
  sale_automatic_workflow_delivery_state/README.rst
  sale_automatic_workflow_delivery_state/__init__.py
  sale_automatic_workflow_delivery_state/__manifest__.py
  sale_automatic_workflow_delivery_state/models/sale_order.py
  sale_automatic_workflow_delivery_state/readme/DESCRIPTION.rst
  sale_automatic_workflow_delivery_state/readme/ROADMAP.rst
  sale_automatic_workflow_delivery_state/static/description/index.html
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
  setup/sale_automatic_workflow_delivery_state/odoo/addons/sale_automatic_workflow_delivery_state
  setup/sale_automatic_workflow_delivery_state/setup.py
  setup/sale_delivery_state/odoo/addons/sale_delivery_state
  setup/sale_delivery_state/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1649 [13.0] sale_delivery_state: backport to v13
  sale_automatic_workflow_delivery_state/README.rst
  sale_automatic_workflow_delivery_state/__init__.py
  sale_automatic_workflow_delivery_state/__manifest__.py
  sale_automatic_workflow_delivery_state/models/sale_order.py
  sale_automatic_workflow_delivery_state/readme/DESCRIPTION.rst
  sale_automatic_workflow_delivery_state/readme/ROADMAP.rst
  sale_automatic_workflow_delivery_state/static/description/index.html
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
  setup/sale_automatic_workflow_delivery_state/odoo/addons/sale_automatic_workflow_delivery_state
  setup/sale_automatic_workflow_delivery_state/setup.py
  setup/sale_delivery_state/odoo/addons/sale_delivery_state
  setup/sale_delivery_state/setup.py
Labels: bot is merging ⏳, needs review

#1654 [14.0][FIX] sale_order_type: call to create from copy crashes
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#1434 [MIG][14.0] sale_order_general_discount
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/sale_order_general_discount/odoo/addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1502 [13.0] [MIG] sale_order_line_input
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/readme/CONTRIBUTORS.rst
  sale_order_line_input/readme/DESCRIPTION.rst
  sale_order_line_input/readme/USAGE.rst
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
  setup/sale_order_line_input/odoo/addons/sale_order_line_input
  setup/sale_order_line_input/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1656 [13.0][FIX] sale_global_discount: Create pricelist to use in partners in tests to prevent errors if company have default currency distinct to default priceslist
  sale_global_discount/tests/test_sale_global_discount.py
Labels: approved, bot is merging ⏳

#1657 [14.0][FIX] sale_stock_picking_blocking: tests
  sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py
Labels: bot is merging ⏳

#1396 [MIG] sale_order_line_packaging_qty: Migration to 14.0
  sale_order_line_packaging_qty/README.rst
  sale_order_line_packaging_qty/__init__.py
  sale_order_line_packaging_qty/__manifest__.py
  sale_order_line_packaging_qty/i18n/es.po
  sale_order_line_packaging_qty/i18n/sale_order_line_packaging_qty.pot
  sale_order_line_packaging_qty/models/__init__.py
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/readme/CONTRIBUTORS.rst
  sale_order_line_packaging_qty/readme/CREDITS.rst
  sale_order_line_packaging_qty/readme/DESCRIPTION.rst
  sale_order_line_packaging_qty/static/description/icon.png
  sale_order_line_packaging_qty/static/description/index.html
  sale_order_line_packaging_qty/tests/__init__.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
  sale_order_line_packaging_qty/views/sale_order.xml
  setup/sale_order_line_packaging_qty/odoo/addons/sale_order_line_packaging_qty
  setup/sale_order_line_packaging_qty/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1651 sale_discount_display_amount: fix init hook
  sale_discount_display_amount/hooks.py
Labels: bot is merging ⏳

#1527 [14.0][MIG] sale_by_packaging: migration to 14.0
  oca_dependencies.txt
  sale_by_packaging/README.rst
  sale_by_packaging/__init__.py
  sale_by_packaging/__manifest__.py
  sale_by_packaging/i18n/es.po
  sale_by_packaging/i18n/sale_by_packaging.pot
  sale_by_packaging/models/__init__.py
  sale_by_packaging/models/product_packaging.py
  sale_by_packaging/models/product_packaging_type.py
  sale_by_packaging/models/product_product.py
  sale_by_packaging/models/product_template.py
  sale_by_packaging/models/sale_order_line.py
  sale_by_packaging/readme/CONFIGURE.rst
  sale_by_packaging/readme/CONTRIBUTORS.rst
  sale_by_packaging/readme/DESCRIPTION.rst
  sale_by_packaging/readme/ROADMAP.rst
  sale_by_packaging/static/description/icon.png
  sale_by_packaging/static/description/index.html
  sale_by_packaging/tests/__init__.py
  sale_by_packaging/tests/test_packaging_type_can_be_sold.py
  sale_by_packaging/tests/test_sale_only_by_packaging.py
  sale_by_packaging/views/product_packaging.xml
  sale_by_packaging/views/product_packaging_type.xml
  sale_by_packaging/views/product_template.xml
  sale_by_packaging/views/sale_order_line.xml
  setup/sale_by_packaging/odoo/addons/sale_by_packaging
  setup/sale_by_packaging/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, migration, needs review

#1668 [12.0][ADD] sale_stock_last_date: New module. Display last delivery date in sale order lines
  sale_stock_last_date/README.rst
  sale_stock_last_date/__init__.py
  sale_stock_last_date/__manifest__.py
  sale_stock_last_date/hooks.py
  sale_stock_last_date/i18n/es.po
  sale_stock_last_date/i18n/sale_stock_last_date.pot
  sale_stock_last_date/models/__init__.py
  sale_stock_last_date/models/sale.py
  sale_stock_last_date/readme/CONTRIBUTORS.rst
  sale_stock_last_date/readme/DESCRIPTION.rst
  sale_stock_last_date/readme/USAGE.rst
  sale_stock_last_date/reports/__init__.py
  sale_stock_last_date/reports/sale_report.py
  sale_stock_last_date/reports/sale_report_view.xml
  sale_stock_last_date/static/description/icon.png
  sale_stock_last_date/static/description/index.html
  sale_stock_last_date/tests/__init__.py
  sale_stock_last_date/tests/test_sale_stock_last_date.py
  sale_stock_last_date/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#1642 [10.0][FIX] sale_procurement_group_by_line
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved, bot is merging ⏳

#1659 [12.0] Fix sale_automatic_workflow: on some cases you ship more products than planned. You want to consider them as fully shipped
  sale_automatic_workflow/models/sale_order.py
Labels: approved, bot is merging ⏳, ready to merge

#1565 [14.0][ADD] sale_product_rating_verified
  sale_product_rating_verified/README.rst
  sale_product_rating_verified/__init__.py
  sale_product_rating_verified/__manifest__.py
  sale_product_rating_verified/models/__init__.py
  sale_product_rating_verified/models/rating.py
  sale_product_rating_verified/readme/CONTRIBUTORS.rst
  sale_product_rating_verified/readme/DESCRIPTION.rst
  sale_product_rating_verified/readme/USAGE.rst
  sale_product_rating_verified/static/description/index.html
  sale_product_rating_verified/static/description/rating_moderation_verified.png
  sale_product_rating_verified/tests/__init__.py
  sale_product_rating_verified/tests/test_verified.py
  sale_product_rating_verified/views/rating_view.xml
  setup/sale_product_rating_verified/odoo/addons/sale_product_rating_verified
  setup/sale_product_rating_verified/setup.py
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#1557 [ADD] Sale Order Weight: New module to 12.0
  __init__.py
  sale_order_weight/README.rst
  sale_order_weight/__init__.py
  sale_order_weight/__manifest__.py
  sale_order_weight/i18n/es.po
  sale_order_weight/i18n/pt.po
  sale_order_weight/i18n/sale_order_weight.pot
  sale_order_weight/models/__init__.py
  sale_order_weight/models/sale_order.py
  sale_order_weight/models/sale_order_line.py
  sale_order_weight/post_init_hook.py
  sale_order_weight/readme/CONTRIBUTORS.rst
  sale_order_weight/readme/DESCRIPTION.rst
  sale_order_weight/static/description/icon.png
  sale_order_weight/static/description/index.html
  sale_order_weight/tests/__init__.py
  sale_order_weight/tests/test_sale_order_weight.py
  sale_order_weight/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, needs review
