Repository OCA/sale-workflow, pull requests merged in 2021-10, with the labels that each got.

#1661 [14.0] Fix sale_automatic_workflow: on some cases you ship more products than planned. You want to consider them as fully shipped
  sale_automatic_workflow/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1662 [13.0] Add sale_product_set_sale_by_packaging
  sale_product_set/__manifest__.py
  sale_product_set/readme/CONTRIBUTORS.rst
  sale_product_set/views/product_set_line.xml
  sale_product_set_packaging_qty/__manifest__.py
  sale_product_set_packaging_qty/readme/CONTRIBUTORS.rst
  sale_product_set_packaging_qty/views/product_set_line.xml
  sale_product_set_sale_by_packaging/README.rst
  sale_product_set_sale_by_packaging/__init__.py
  sale_product_set_sale_by_packaging/__manifest__.py
  sale_product_set_sale_by_packaging/models/__init__.py
  sale_product_set_sale_by_packaging/models/product_product.py
  sale_product_set_sale_by_packaging/models/product_set_line.py
  sale_product_set_sale_by_packaging/models/product_template.py
  sale_product_set_sale_by_packaging/readme/CONTRIBUTORS.rst
  sale_product_set_sale_by_packaging/readme/DESCRIPTION.rst
  sale_product_set_sale_by_packaging/tests/__init__.py
  sale_product_set_sale_by_packaging/tests/test_product_set_packaging.py
  sale_product_set_sale_by_packaging/views/product_set.xml
  sale_product_set_sale_by_packaging/views/product_set_line.xml
  sale_product_set_sale_by_packaging/views/product_template.xml
  setup/sale_product_set_sale_by_packaging/odoo/addons/sale_product_set_sale_by_packaging
  setup/sale_product_set_sale_by_packaging/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1523 [ADD] sale_resource_booking: sell booking products
  oca_dependencies.txt
  sale_resource_booking/README.rst
  sale_resource_booking/__init__.py
  sale_resource_booking/__manifest__.py
  sale_resource_booking/i18n/es.po
  sale_resource_booking/i18n/sale_resource_booking.pot
  sale_resource_booking/models/__init__.py
  sale_resource_booking/models/product_template.py
  sale_resource_booking/models/resource_booking.py
  sale_resource_booking/models/resource_booking_type.py
  sale_resource_booking/models/sale_order.py
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/readme/CONFIGURE.rst
  sale_resource_booking/readme/CONTRIBUTORS.rst
  sale_resource_booking/readme/DESCRIPTION.rst
  sale_resource_booking/readme/INSTALL.rst
  sale_resource_booking/readme/USAGE.rst
  sale_resource_booking/static/description/icon.png
  sale_resource_booking/static/description/index.html
  sale_resource_booking/tests/__init__.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/views/product_template_views.xml
  sale_resource_booking/views/resource_booking_type_views.xml
  sale_resource_booking/views/resource_booking_views.xml
  sale_resource_booking/views/sale_order_views.xml
  sale_resource_booking/wizards/__init__.py
  sale_resource_booking/wizards/resource_booking_sale.py
  sale_resource_booking/wizards/resource_booking_sale_views.xml
  sale_resource_booking/wizards/sale_order_booking_confirm.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1734 [12.0][IMP] sale_force_whole_invoiceability: allow forcing in done state too; fix invisibility domain
  sale_force_whole_invoiceability/models/sale_order.py
  sale_force_whole_invoiceability/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#1733 [13.0][ADD] sale_order_line_delivery_state
  sale_order_line_delivery_state/README.rst
  sale_order_line_delivery_state/__init__.py
  sale_order_line_delivery_state/__manifest__.py
  sale_order_line_delivery_state/models/__init__.py
  sale_order_line_delivery_state/models/sale_order_line.py
  sale_order_line_delivery_state/readme/CONTRIBUTORS.rst
  sale_order_line_delivery_state/readme/DESCRIPTION.rst
  sale_order_line_delivery_state/static/description/icon.png
  sale_order_line_delivery_state/static/description/index.html
  sale_order_line_delivery_state/tests/__init__.py
  sale_order_line_delivery_state/tests/test_sale_line_delivery_state.py
  sale_order_line_delivery_state/views/sale_order_views.xml
  setup/sale_order_line_delivery_state/odoo/addons/sale_order_line_delivery_state
  setup/sale_order_line_delivery_state/setup.py
Labels: approved, bot is merging ⏳
