Repository OCA/sale-workflow, pull requests merged in 2021-09, with the labels that each got.

#1688 [14.0][IMP] sale_order_type: add sale order type to sales and invoice analysis reports
  sale_order_type/__init__.py
  sale_order_type/__manifest__.py
  sale_order_type/reports/__init__.py
  sale_order_type/reports/account_invoice_report.py
  sale_order_type/reports/account_invoice_report_view.xml
  sale_order_type/reports/sale_report.py
  sale_order_type/reports/sale_report_view.xml
  sale_order_type/tests/__init__.py
  sale_order_type/tests/test_account_invoice_report.py
  sale_order_type/tests/test_sale_order_report.py
Labels: approved, ready to merge, bot is merging ⏳

#1706 [12.0][FIX] sale_order_line_date depends on sale_stock
  sale_order_line_date/__manifest__.py
Labels: approved, bot is merging ⏳

#1692 [13.0][IMP] sale_exception: Add customer sale warning + product warning exceptions
  sale_exception/README.rst
  sale_exception/data/sale_exception_data.xml
  sale_exception/readme/CONFIGURE.rst
  sale_exception/readme/USAGE.rst
  sale_exception/static/description/index.html
  sale_exception/tests/test_sale_exception.py
Labels: bot is merging ⏳

#1712 [13.0][IMP] sale_order_qty_change_no_recompute: Add context in test to prevent onchange quantity and some possible related error in another addons
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: approved, bot is merging ⏳

#1714 [14.0][IMP] sale_order_qty_change_no_recompute: Add context in test to prevent onchange quantity and some possible related error in another addons
  sale_order_qty_change_no_recompute/models/sale_order.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: approved, bot is merging ⏳

#1698 [13.0][IMP] sale_stock_picking_note: Add Picking comments in sale orders to use in pickings
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/DESCRIPTION.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/report_deliveryslip.xml
  sale_stock_picking_note/views/sale_order_view.xml
  sale_stock_picking_note/views/stock_picking_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1673 [13.0][MIG] sale_automatic_workflow_payment_mode: Migration to 13.0
  oca_dependencies.txt
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/views/sale_workflow_process_view.xml
  sale_automatic_workflow_payment_mode/README.rst
  sale_automatic_workflow_payment_mode/__init__.py
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/data/automatic_workflow_data.xml
  sale_automatic_workflow_payment_mode/i18n/ca.po
  sale_automatic_workflow_payment_mode/i18n/de.po
  sale_automatic_workflow_payment_mode/i18n/el_GR.po
  sale_automatic_workflow_payment_mode/i18n/es.po
  sale_automatic_workflow_payment_mode/i18n/es_ES.po
  sale_automatic_workflow_payment_mode/i18n/es_VE.po
  sale_automatic_workflow_payment_mode/i18n/fi.po
  sale_automatic_workflow_payment_mode/i18n/fr.po
  sale_automatic_workflow_payment_mode/i18n/hr.po
  sale_automatic_workflow_payment_mode/i18n/hr_HR.po
  sale_automatic_workflow_payment_mode/i18n/hu.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/nl.po
  sale_automatic_workflow_payment_mode/i18n/nl_NL.po
  sale_automatic_workflow_payment_mode/i18n/pt.po
  sale_automatic_workflow_payment_mode/i18n/pt_BR.po
  sale_automatic_workflow_payment_mode/i18n/ro.po
  sale_automatic_workflow_payment_mode/i18n/sale_automatic_workflow_payment_mode.pot
  sale_automatic_workflow_payment_mode/i18n/sk.po
  sale_automatic_workflow_payment_mode/i18n/sl.po
  sale_automatic_workflow_payment_mode/i18n/tr.po
  sale_automatic_workflow_payment_mode/i18n/tr_TR.po
  sale_automatic_workflow_payment_mode/i18n/vi_VN.po
  sale_automatic_workflow_payment_mode/i18n/zh_CN.po
  sale_automatic_workflow_payment_mode/migrations/13.0.1.0.0/noupdate_changes.xml
  sale_automatic_workflow_payment_mode/migrations/13.0.1.0.0/post-migration.py
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/account_payment_mode.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/models/sale_workflow_process.py
  sale_automatic_workflow_payment_mode/readme/CONFIGURE.rst
  sale_automatic_workflow_payment_mode/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_payment_mode/readme/DESCRIPTION.rst
  sale_automatic_workflow_payment_mode/readme/INSTALL.rst
  sale_automatic_workflow_payment_mode/readme/USAGE.rst
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/index.html
  sale_automatic_workflow_payment_mode/tests/__init__.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  sale_automatic_workflow_payment_mode/views/account_payment_mode_views.xml
  setup/sale_automatic_workflow_payment_mode/odoo/addons/sale_automatic_workflow_payment_mode
  setup/sale_automatic_workflow_payment_mode/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1707 [14.0] [MIG] sale_order_disable_user_autosubscribe
  sale_order_disable_user_autosubscribe/README.rst
  sale_order_disable_user_autosubscribe/__init__.py
  sale_order_disable_user_autosubscribe/__manifest__.py
  sale_order_disable_user_autosubscribe/i18n/sale_order_disable_user_autosubscribe.pot
  sale_order_disable_user_autosubscribe/models/__init__.py
  sale_order_disable_user_autosubscribe/models/sale_order.py
  sale_order_disable_user_autosubscribe/readme/CONTRIBUTORS.rst
  sale_order_disable_user_autosubscribe/readme/CREDITS.rst
  sale_order_disable_user_autosubscribe/readme/DESCRIPTION.rst
  sale_order_disable_user_autosubscribe/readme/ROADMAP.rst
  sale_order_disable_user_autosubscribe/static/description/icon.png
  sale_order_disable_user_autosubscribe/static/description/index.html
  setup/sale_order_disable_user_autosubscribe/odoo/addons/sale_order_disable_user_autosubscribe
  setup/sale_order_disable_user_autosubscribe/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1716 [14.0][FIX] sale_order_type: default value is 'New' not '/'
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#1715 [IMP] 13.0: Extract delivery date logic to specific methods
  sale_cutoff_time_delivery/models/sale_order.py
  sale_partner_delivery_window/models/sale_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1660 [13.0] Fix sale_automatic_workflow: on some cases you ship more products than planned. You want to consider them as fully shipped
  sale_automatic_workflow/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1348 [14.0][MIG] sale_partner_version: Migration to v14.0
  .travis.yml
  sale_partner_version/README.rst
  sale_partner_version/__init__.py
  sale_partner_version/__manifest__.py
  sale_partner_version/i18n/sale_partner_version.pot
  sale_partner_version/models/__init__.py
  sale_partner_version/models/sale.py
  sale_partner_version/readme/CONTRIBUTORS.rst
  sale_partner_version/readme/DESCRIPTION.rst
  sale_partner_version/static/description/icon.png
  sale_partner_version/static/description/index.html
  sale_partner_version/tests/__init__.py
  sale_partner_version/tests/test_sale_partner_version.py
  setup/sale_partner_version/odoo/addons/sale_partner_version
  setup/sale_partner_version/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1677 [13.0][IMP] sale_automatic_workflow: Send order confirmation mail option in Sale Workflow Process
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/data/automatic_workflow_data.xml
  sale_automatic_workflow/i18n/es.po
  sale_automatic_workflow/i18n/sale_automatic_workflow.pot
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/readme/DESCRIPTION.rst
  sale_automatic_workflow/static/description/index.html
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/views/sale_workflow_process_view.xml
Labels: enhancement, needs review, bot is merging ⏳

#1719 [14.0][IMP] sale_automatic_workflow: Use with_company instead of user…
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: approved, bot is merging ⏳

#1728 [13.0][MIG] partner_contact_sale_info_propagation: Migration to 13.0
  partner_contact_sale_info_propagation/README.rst
  partner_contact_sale_info_propagation/__init__.py
  partner_contact_sale_info_propagation/__manifest__.py
  partner_contact_sale_info_propagation/i18n/ca.po
  partner_contact_sale_info_propagation/i18n/de.po
  partner_contact_sale_info_propagation/i18n/es.po
  partner_contact_sale_info_propagation/i18n/fr.po
  partner_contact_sale_info_propagation/i18n/partner_contact_sale_info_propagation.pot
  partner_contact_sale_info_propagation/models/__init__.py
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/readme/CONTRIBUTORS.rst
  partner_contact_sale_info_propagation/readme/DESCRIPTION.rst
  partner_contact_sale_info_propagation/readme/USAGE.rst
  partner_contact_sale_info_propagation/static/description/icon.png
  partner_contact_sale_info_propagation/static/description/index.html
  partner_contact_sale_info_propagation/tests/__init__.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  partner_contact_sale_info_propagation/views/res_partner_view.xml
  setup/partner_contact_sale_info_propagation/odoo/addons/partner_contact_sale_info_propagation
  setup/partner_contact_sale_info_propagation/setup.py
Labels: approved, bot is merging ⏳
