Repository OCA/sale-workflow, pull requests merged in 2021-11, with the labels that each got.

#1750 [14.0] Add pricelist_cache
  pricelist_cache/README.rst
  pricelist_cache/__init__.py
  pricelist_cache/__manifest__.py
  pricelist_cache/data/base_automation.xml
  pricelist_cache/data/demo.xml
  pricelist_cache/data/ir_cron.xml
  pricelist_cache/data/ir_filters_data.xml
  pricelist_cache/data/queue_job.xml
  pricelist_cache/hooks.py
  pricelist_cache/models/__init__.py
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/models/product_pricelist_item.py
  pricelist_cache/models/product_product.py
  pricelist_cache/models/res_partner.py
  pricelist_cache/readme/CONTRIBUTORS.rst
  pricelist_cache/readme/CREDITS.rst
  pricelist_cache/readme/DESCRIPTION.rst
  pricelist_cache/security/ir.model.access.csv
  pricelist_cache/static/description/index.html
  pricelist_cache/tests/__init__.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
  pricelist_cache/tests/test_pricelist_cache.py
  pricelist_cache/views/product_pricelist.xml
  pricelist_cache/views/product_pricelist_cache.xml
  pricelist_cache/views/res_partner.xml
  pricelist_cache/wizards/__init__.py
  pricelist_cache/wizards/pricelist_cache_wizard.py
  pricelist_cache/wizards/pricelist_cache_wizard.xml
  setup/pricelist_cache/odoo/addons/pricelist_cache
  setup/pricelist_cache/setup.py
Labels: approved, bot is merging ⏳

#1757 [13.0][FIX] sale_order_product_recommendation: Fix tests. Not order recommendations found due to date data
  sale_global_discount/readme/CONFIGURE.rst
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
Labels: approved, bot is merging ⏳

#1439 [12.0][IMP] sales_team_security: Auto-followers (create and remove) in child partners
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  sales_team_security/README.rst
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/migrations/12.0.3.0.0/pre-migration.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/index.html
  sales_team_security/tests/test_sales_team_security.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1765 [13.0][IMP] sale_blanket_order: use default terms, multi-company and analytic
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/security/security.xml
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/wizard/create_sale_orders.py
Labels: approved, bot is merging ⏳

#1770 [13.0][IMP] sale_order_qty_change_no_recompute: Block also uom onchange
  sale_order_qty_change_no_recompute/models/sale_order.py
Labels: approved, bot is merging ⏳

#1764 [ADD] pricelist_cache_rest
  pricelist_cache_rest/README.rst
  pricelist_cache_rest/__init__.py
  pricelist_cache_rest/__manifest__.py
  pricelist_cache_rest/controllers/__init__.py
  pricelist_cache_rest/controllers/main.py
  pricelist_cache_rest/data/ir_exports_data.xml
  pricelist_cache_rest/demo/auth_api_key_demo.xml
  pricelist_cache_rest/models/__init__.py
  pricelist_cache_rest/models/res_company.py
  pricelist_cache_rest/models/res_config_settings.py
  pricelist_cache_rest/readme/CONFIGURATION.rst
  pricelist_cache_rest/readme/CONTRIBUTORS.rst
  pricelist_cache_rest/readme/CREDITS.rst
  pricelist_cache_rest/readme/DESCRIPTION.rst
  pricelist_cache_rest/readme/USAGE.rst
  pricelist_cache_rest/static/description/index.html
  pricelist_cache_rest/tests/__init__.py
  pricelist_cache_rest/tests/test_pricelist_cache_rest.py
  pricelist_cache_rest/wizards/res_config_settings.xml
  setup/pricelist_cache_rest/odoo/addons/pricelist_cache_rest
  setup/pricelist_cache_rest/setup.py
Labels: approved, bot is merging ⏳

#1767 [FIX] sale_order_lot_selection: Avoid missing warning in the product selection.
  sale_order_lot_selection/models/sale_order_line.py
Labels: enhancement, needs review, bot is merging ⏳

#1771 [14.0][FIX] sale_order_lot_selection: Avoid missing warning in the product selection.
  sale_order_lot_selection/models/sale_order_line.py
Labels: enhancement, needs review, bot is merging ⏳

#1648 [13.0][IMP] sale_order_product_assortment: Use product_assortment domain and only one field to get allowed products result from whitelist and blacklist
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/models/sale_order_line.py
  sale_order_product_assortment/readme/CONFIGURE.rst
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
  sale_order_product_assortment/views/sale_order_view.xml
Labels: enhancement, needs review, bot is merging ⏳

#1774 [13.0][ADD] sale_partner_selectable_option: This module limits the partners to be selected in the sales orders.
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__init__.py
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/__init__.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/readme/CONTRIBUTORS.rst
  sale_partner_selectable_option/readme/DESCRIPTION.rst
  sale_partner_selectable_option/readme/USAGE.rst
  sale_partner_selectable_option/static/description/icon.png
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/__init__.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
  sale_partner_selectable_option/views/sale_order_view.xml
  setup/sale_partner_selectable_option/odoo/addons/sale_partner_selectable_option
  setup/sale_partner_selectable_option/setup.py
Labels: approved, bot is merging ⏳

#1780 [FIX] sale_automatic_workflow_mode: missing super()
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
Labels: bot is merging ⏳

#1782 [FIX] sale_automatic_workflow: incorrect fields
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: bot is merging ⏳

#1779 [MIG] sale_order_warn_message: Migration to 14.0
  sale_order_warn_message/README.rst
  sale_order_warn_message/__init__.py
  sale_order_warn_message/__manifest__.py
  sale_order_warn_message/i18n/sale_order_warn_message.pot
  sale_order_warn_message/models/__init__.py
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/readme/CONTRIBUTORS.rst
  sale_order_warn_message/readme/DESCRIPTION.rst
  sale_order_warn_message/static/description/icon.png
  sale_order_warn_message/static/description/index.html
  sale_order_warn_message/tests/__init__.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
  sale_order_warn_message/views/sale_order.xml
Labels: approved, bot is merging ⏳

#1769 [14.0][MIG] sale_stock_picking_note: Migration to 14.0
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/DESCRIPTION.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/report_deliveryslip.xml
  sale_stock_picking_note/views/sale_order_view.xml
  sale_stock_picking_note/views/stock_picking_view.xml
  setup/sale_stock_picking_note/odoo/addons/sale_stock_picking_note
  setup/sale_stock_picking_note/setup.py
Labels: duplicate, approved, migration, ready to merge, bot is merging ⏳

#1704 [14.0][IMP] sale_discount_display_amount: Adds hook for depends
  sale_discount_display_amount/models/sale_order.py
  sale_discount_display_amount/models/sale_order_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1753 [13.0][FW][IMP] sales_team_security: Auto-followers (create and remove) in child partners
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  sales_team_security/README.rst
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/migrations/13.0.2.0.0/pre-migration.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/index.html
  sales_team_security/tests/test_sales_team_security.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1742 [13.0][FIX] sale_coupon_multi_use: Add missing check of reward line
  sale_coupon_multi_use/models/sale_coupon.py
Labels: approved, bot is merging ⏳

#1745 [14.0][ADD] sale_amount_payment_link
  sale_amount_payment_link/__init__.py
  sale_amount_payment_link/__manifest__.py
  sale_amount_payment_link/readme/CONTRIBUTORS.rst
  sale_amount_payment_link/readme/DESCRIPTION.rst
  sale_amount_payment_link/readme/USAGE.rst
  sale_amount_payment_link/static/description/icon.png
  sale_amount_payment_link/static/description/index.html
  sale_amount_payment_link/tests/__init__.py
  sale_amount_payment_link/tests/test_sale_amount_payment_link.py
  sale_amount_payment_link/wizards/__init__.py
  sale_amount_payment_link/wizards/sale_amount_payment_link.py
Labels: approved, ready to merge, bot is merging ⏳

#1367 [13.0][ADD] sale_payment_sheet: New module
  sale_payment_sheet/README.rst
  sale_payment_sheet/__init__.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/models/__init__.py
  sale_payment_sheet/models/res_users.py
  sale_payment_sheet/models/sale_payment_sheet.py
  sale_payment_sheet/readme/CONFIGURE.rst
  sale_payment_sheet/readme/CONTRIBUTORS.rst
  sale_payment_sheet/readme/DESCRIPTION.rst
  sale_payment_sheet/readme/USAGE.rst
  sale_payment_sheet/report/report_sale_payment_sheet_summary.xml
  sale_payment_sheet/report/sale_payment_sheet_report.xml
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/security/security.xml
  sale_payment_sheet/static/description/icon.png
  sale_payment_sheet/static/description/index.html
  sale_payment_sheet/tests/__init__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_payment_sheet/views/res_users_views.xml
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
  sale_payment_sheet/views/sale_payment_sheet_views.xml
  sale_payment_sheet/wizards/__init__.py
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
  setup/sale_payment_sheet/odoo/addons/sale_payment_sheet
  setup/sale_payment_sheet/setup.py
  test-requirements.txt
Labels: needs review, bot is merging ⏳

#1572 [14.0][MIG] sale_order_line_chained_move
  sale_order_line_chained_move/README.rst
  sale_order_line_chained_move/__init__.py
  sale_order_line_chained_move/__manifest__.py
  sale_order_line_chained_move/demo/sale_order.xml
  sale_order_line_chained_move/hooks.py
  sale_order_line_chained_move/models/__init__.py
  sale_order_line_chained_move/models/sale_order_line.py
  sale_order_line_chained_move/models/stock_move.py
  sale_order_line_chained_move/models/stock_rule.py
  sale_order_line_chained_move/readme/CONTRIBUTORS.rst
  sale_order_line_chained_move/readme/DESCRIPTION.rst
  sale_order_line_chained_move/static/description/icon.png
  sale_order_line_chained_move/static/description/index.html
  sale_order_line_chained_move/tests/__init__.py
  sale_order_line_chained_move/tests/test_chained_move.py
  setup/sale_order_line_chained_move/odoo/addons/sale_order_line_chained_move
  setup/sale_order_line_chained_move/setup.py
Labels: needs review, migration, bot is merging ⏳

#1796 [13.0][FIX] sales_team_security: Rule domain corrections.
  sales_team_security/__manifest__.py
  sales_team_security/migrations/13.0.3.0.0/pre-migration.py
  sales_team_security/security/sales_team_security.xml
Labels: approved, bot is merging ⏳
