Repository OCA/sale-workflow, pull requests merged in 2022-04, with the labels that each got.

#1960 [14.0] [FIX] sale_partner_approval: Fixed Can Sale is lazy updated
  sale_partner_approval/__manifest__.py
  sale_partner_approval/data/exception_rule.xml
  sale_partner_approval/data/init_sale_ok.xml
  sale_partner_approval/models/res_partner.py
  sale_partner_approval/readme/DESCRIPTION.rst
  sale_partner_approval/readme/USAGE.rst
  sale_partner_approval/tests/test_product_approval.py
  sale_partner_approval/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1961 [MIG] sale_restricted_qty to 14.0
  sale_restricted_qty/README.rst
  sale_restricted_qty/__init__.py
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/hooks.py
  sale_restricted_qty/i18n/it.po
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/i18n/sale_restricted_qty.pot
  sale_restricted_qty/models/__init__.py
  sale_restricted_qty/models/product_category.py
  sale_restricted_qty/models/product_product.py
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/product_template.py
  sale_restricted_qty/models/sale.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/icon.png
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/tests/__init__.py
  sale_restricted_qty/tests/test_sale.py
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
  sale_restricted_qty/views/sale_views.xml
  setup/sale_restricted_qty/odoo/addons/sale_restricted_qty
  setup/sale_restricted_qty/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1971 [14.0][IMP] sale_blanket_order: Add prepare SO values hook
  sale_blanket_order/wizard/create_sale_orders.py
Labels: approved, bot is merging ⏳

#1862 [FIX] sale_product_set: fixed issue with wizard lines delete
  sale_product_set/README.rst
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1727 [14.0][MIG] sale_triple_discount: Migration to V14
  sale_triple_discount/README.rst
  sale_triple_discount/__init__.py
  sale_triple_discount/__manifest__.py
  sale_triple_discount/i18n/ca.po
  sale_triple_discount/i18n/de.po
  sale_triple_discount/i18n/es.po
  sale_triple_discount/i18n/es_VE.po
  sale_triple_discount/i18n/fr.po
  sale_triple_discount/i18n/hr.po
  sale_triple_discount/i18n/it.po
  sale_triple_discount/i18n/nl_NL.po
  sale_triple_discount/i18n/pt_BR.po
  sale_triple_discount/i18n/ro.po
  sale_triple_discount/i18n/sale_triple_discount.pot
  sale_triple_discount/i18n/sl.po
  sale_triple_discount/i18n/tr.po
  sale_triple_discount/i18n/tr_TR.po
  sale_triple_discount/models/__init__.py
  sale_triple_discount/models/sale_order.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/readme/CONFIGURE.rst
  sale_triple_discount/readme/CONTRIBUTORS.rst
  sale_triple_discount/readme/DESCRIPTION.rst
  sale_triple_discount/readme/USAGE.rst
  sale_triple_discount/static/description/icon.png
  sale_triple_discount/static/description/index.html
  sale_triple_discount/tests/__init__.py
  sale_triple_discount/tests/test_sale_triple_discount.py
  sale_triple_discount/views/sale_order_report.xml
  sale_triple_discount/views/sale_order_view.xml
  setup/sale_triple_discount/odoo/addons/sale_triple_discount
  setup/sale_triple_discount/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1830 [13.0][ADD]sale_advance_payment: Backport from 14.0
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: bot is merging ⏳

#1985 [13.0][ADD] sale_order_pricelist_tracking: New module
  sale_order_pricelist_tracking/README.rst
  sale_order_pricelist_tracking/__init__.py
  sale_order_pricelist_tracking/__manifest__.py
  sale_order_pricelist_tracking/models/__init__.py
  sale_order_pricelist_tracking/models/sale_order.py
  sale_order_pricelist_tracking/readme/CONTRIBUTORS.rst
  sale_order_pricelist_tracking/readme/DESCRIPTION.rst
  sale_order_pricelist_tracking/static/description/index.html
  setup/sale_order_pricelist_tracking/odoo/addons/sale_order_pricelist_tracking
  setup/sale_order_pricelist_tracking/setup.py
Labels: approved, bot is merging ⏳

#1984 [IMP] sale_order_secondary_unit: promote to Stable
  sale_order_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/__manifest__.py
Labels: approved, bot is merging ⏳

#1989 [14.0][TEST] sale_amount_payment_link sale_invoice_plan Fix tests
  sale_amount_payment_link/tests/test_sale_amount_payment_link.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
Labels: bot is merging ⏳

#1995 [14.0] [FIX] sale_automatic_workflow_payment_mode: avoid overwritting/removing SO's workflow if payment.mode hasn't one set
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
Labels: approved, bot is merging ⏳

#1990 [14.0][ADD] sale_quotation_template_product_multi_add
  sale_quotation_template_product_multi_add/README.rst
  sale_quotation_template_product_multi_add/__init__.py
  sale_quotation_template_product_multi_add/__manifest__.py
  sale_quotation_template_product_multi_add/readme/CONTRIBUTORS.rst
  sale_quotation_template_product_multi_add/readme/DESCRIPTION.rst
  sale_quotation_template_product_multi_add/readme/USAGE.rst
  sale_quotation_template_product_multi_add/security/ir.model.access.csv
  sale_quotation_template_product_multi_add/static/description/icon.png
  sale_quotation_template_product_multi_add/tests/__init__.py
  sale_quotation_template_product_multi_add/tests/test_sale.py
  sale_quotation_template_product_multi_add/views/sale_view.xml
  sale_quotation_template_product_multi_add/wizards/__init__.py
  sale_quotation_template_product_multi_add/wizards/sale_template_add_products.py
  sale_quotation_template_product_multi_add/wizards/sale_template_add_products_view.xml
  setup/sale_quotation_template_product_multi_add/odoo/addons/sale_quotation_template_product_multi_add
  setup/sale_quotation_template_product_multi_add/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2001 [13.0][FIX] sale_stock_delivery_address: Incompatible license
  sale_by_packaging/__manifest__.py
  sale_procurement_amendment/__manifest__.py
  sale_stock_delivery_address/__manifest__.py
  sale_stock_return_request/__manifest__.py
Labels: bot is merging ⏳

#2000 [13.0][FIX] sale_isolated_quotation: "sent" state is added to "Convert to Order" and "Cancel" buttons
  sale_isolated_quotation/views/sale_views.xml
Labels: bot is merging ⏳
