Repository OCA/sale-workflow, pull requests merged in 2022-12, with the labels that each got.

#2255 [15.0][FIX] sale_procurement_group_by_line
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
  sale_sourced_by_line/model/sale.py
Labels: approved, bot is merging ⏳

#2291 [14.0][IMP] sale_restricted_qty: Change dp.get_precision digits
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/sale.py
Labels: bot is merging ⏳

#2290 [14.0][IMP] sale_order_type: Misc changes in tests
  sale_order_type/tests/test_sale_order_type.py
Labels: bot is merging ⏳

#2244 [15.0][ADD] sale_planner_calendar: New module to manage commercial visits
  sale_planner_calendar/README.rst
  sale_planner_calendar/__init__.py
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/data/sale_planner_calendar_action_server.xml
  sale_planner_calendar/data/sale_planner_calendar_cron.xml
  sale_planner_calendar/data/sale_planner_calendar_data.xml
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/models/__init__.py
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/calendar_event_type.py
  sale_planner_calendar/models/res_config_settings.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/models/sale_order.py
  sale_planner_calendar/models/sale_payment_sheet.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/models/sale_planner_calendar_issue_type.py
  sale_planner_calendar/models/sale_planner_calendar_summary.py
  sale_planner_calendar/readme/CONFIGURE.rst
  sale_planner_calendar/readme/CONTRIBUTORS.rst
  sale_planner_calendar/readme/DESCRIPTION.rst
  sale_planner_calendar/readme/USAGE.rst
  sale_planner_calendar/security/ir.model.access.csv
  sale_planner_calendar/security/sale_planner_calendar_security.xml
  sale_planner_calendar/static/description/icon.png
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/static/img/menu_entry.png
  sale_planner_calendar/static/img/smart_button.png
  sale_planner_calendar/static/src/scss/sale_planner_calendar.scss
  sale_planner_calendar/tests/__init__.py
  sale_planner_calendar/tests/test_sale_planner_calendar.py
  sale_planner_calendar/views/calendar_event_type_view.xml
  sale_planner_calendar/views/calendar_view.xml
  sale_planner_calendar/views/res_config_settings_views.xml
  sale_planner_calendar/views/res_partner_view.xml
  sale_planner_calendar/views/sale_planner_calendar_event_view.xml
  sale_planner_calendar/views/sale_planner_calendar_menu.xml
  sale_planner_calendar/views/sale_planner_calendar_summary_view.xml
  sale_planner_calendar/wizard/__init__.py
  sale_planner_calendar/wizard/sale_invoice_payment.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.xml
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.xml
  setup/sale_planner_calendar/odoo/addons/sale_planner_calendar
  setup/sale_planner_calendar/setup.py
Labels: approved, bot is merging ⏳

#2293 [15.0][IMP] sale_order_type: Add post_install tag in tests to prevent test errors
  sale_order_type/tests/test_sale_order_type.py
Labels: bot is merging ⏳

#2286 [15.0][IMP] sale_order_product_recommendation: Change context value to avoid warning logs
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, ready to merge, bot is merging ⏳

#2279 [15.0][MIG] sale_order_general_discount: Migration to version 15.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/sale_order_general_discount/odoo/addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2093 [13.0][ADD] sale_attached_product: New module
  sale_attached_product/README.rst
  sale_attached_product/__init__.py
  sale_attached_product/__manifest__.py
  sale_attached_product/models/__init__.py
  sale_attached_product/models/product_template.py
  sale_attached_product/models/sale_attached_product_mixin.py
  sale_attached_product/models/sale_order.py
  sale_attached_product/readme/CONFIGURE.rst
  sale_attached_product/readme/CONTRIBUTORS.rst
  sale_attached_product/readme/DESCRIPTION.rst
  sale_attached_product/readme/USAGE.rst
  sale_attached_product/static/description/index.html
  sale_attached_product/tests/__init__.py
  sale_attached_product/tests/test_sale_attached_product.py
  sale_attached_product/views/product_template_views.xml
  setup/sale_attached_product/odoo/addons/sale_attached_product
  setup/sale_attached_product/setup.py
Labels: bot is merging ⏳

#2282 [16.0][MIG] sale_order_lot_selection
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2302 [12.0][IMP] copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  portal_sale_personal_data_only/__manifest__.py
  requirements.txt
  sale_force_whole_invoiceability/__manifest__.py
  sale_generator/__manifest__.py
  sale_invoice_plan/__manifest__.py
  sale_manual_delivery/__manifest__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_priority/__manifest__.py
  sale_order_weight/__manifest__.py
  sale_partner_incoterm/__manifest__.py
  sale_product_category_menu/__manifest__.py
  sale_quotation_number/__manifest__.py
  sale_resource_booking/__manifest__.py
  sale_restricted_qty/__manifest__.py
  sale_start_end_dates/i18n/de.po
  sale_start_end_dates/i18n/fr.po
  sale_start_end_dates/i18n/it.po
  sale_start_end_dates/i18n/nl_NL.po
  sale_stock_delivery_address/__manifest__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_sourcing_address/__manifest__.py
  sale_substate/__manifest__.py
Labels: bot is merging ⏳

#2310 [13.0][ADD] sale_order_product_assortment_availability_inline: New module to display stock inline in sale orders
  sale_order_product_assortment_availability_inline/README.rst
  sale_order_product_assortment_availability_inline/__init__.py
  sale_order_product_assortment_availability_inline/__manifest__.py
  sale_order_product_assortment_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_assortment_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_assortment_availability_inline/readme/USAGE.rst
  sale_order_product_assortment_availability_inline/static/description/icon.png
  sale_order_product_assortment_availability_inline/static/description/index.html
  sale_order_product_assortment_availability_inline/tests/__init__.py
  sale_order_product_assortment_availability_inline/tests/test_sale_order_product_assortment_availability_inline.py
  sale_order_product_assortment_availability_inline/views/sale_order_view.xml
  setup/sale_order_product_assortment_availability_inline/odoo/addons/sale_order_product_assortment_availability_inline
  setup/sale_order_product_assortment_availability_inline/setup.py
Labels: approved, bot is merging ⏳

#2110 [13.0][FIX] sale_order_line_sequence: assure sequence is reset correctly
  sale_order_line_sequence/model/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2313 [15.0][IMP] sale_elaboration: Add pre-init hooks to quickly install
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/hooks.py
Labels: bot is merging ⏳

#2312 [13.0][IMP] sale_elaboration: Add pre-init hooks to quickly install
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/hooks.py
Labels: approved, bot is merging ⏳

#2303 [15.0][FIX] sale_planner_calendar: Use same domain in Sales Follower Orders…
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/migrations/15.0.1.0.1/noupdate_changes.xml
  sale_planner_calendar/migrations/15.0.1.0.1/post-migration.py
  sale_planner_calendar/security/sale_planner_calendar_security.xml
Labels: approved, ready to merge, bot is merging ⏳

#2314 [13.0][FIX] sale_order_type: use date_order with order sequence
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#2315 [16.0] [MIG] sale_order_line_menu
  sale_order_line_menu/README.rst
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/i18n/es.po
  sale_order_line_menu/i18n/fr.po
  sale_order_line_menu/i18n/fr_BE.po
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.rst
  sale_order_line_menu/readme/USAGE.rst
  sale_order_line_menu/static/description/icon.png
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/views/sale_order_line_views.xml
  setup/sale_order_line_menu/odoo/addons/sale_order_line_menu
  setup/sale_order_line_menu/setup.py
Labels: approved, bot is merging ⏳

#2299 [16.0][MIG] sale_commercial_partner
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca.po
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_MX.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/fr_FR.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale_order.py
  sale_commercial_partner/readme/CONTRIBUTORS.rst
  sale_commercial_partner/readme/DESCRIPTION.rst
  sale_commercial_partner/readme/USAGE.rst
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/views/sale_order.xml
  sale_commercial_partner/views/sale_report.xml
  setup/sale_commercial_partner/odoo/addons/sale_commercial_partner
  setup/sale_commercial_partner/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2297 12.0 fix issue2296 - Discount 2 and 3 missing in invoice view/report but are calculated correctly
  sale_triple_discount/__manifest__.py
  sale_triple_discount/views/sale_group_invoice_discount.xml
Labels: approved, ready to merge, bot is merging ⏳

#2229 [15.0][MIG] sale_credit_point: Migrate to version 15.0
  sale_credit_point/README.rst
  sale_credit_point/__init__.py
  sale_credit_point/__manifest__.py
  sale_credit_point/data/res_currency.xml
  sale_credit_point/i18n/fr.po
  sale_credit_point/models/__init__.py
  sale_credit_point/models/partner.py
  sale_credit_point/models/point_history.py
  sale_credit_point/models/sale_order.py
  sale_credit_point/security/groups.xml
  sale_credit_point/security/ir.model.access.csv
  sale_credit_point/tests/__init__.py
  sale_credit_point/tests/test_credit.py
  sale_credit_point/tests/test_credit_history.py
  sale_credit_point/tests/test_sale_order.py
  sale_credit_point/tests/test_wizard.py
  sale_credit_point/views/partner.xml
  sale_credit_point/views/point_history.xml
  sale_credit_point/wizards/__init__.py
  sale_credit_point/wizards/manage_credit_point.py
  sale_credit_point/wizards/manage_credit_point.xml
  setup/sale_credit_point/odoo/addons/sale_credit_point
  setup/sale_credit_point/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2285 [13.0][ADD] sale_order_partner_no_autofollow:Expands the sale module, disab…
  sale_order_partner_no_autofollow/README.rst
  sale_order_partner_no_autofollow/__init__.py
  sale_order_partner_no_autofollow/__manifest__.py
  sale_order_partner_no_autofollow/models/__init__.py
  sale_order_partner_no_autofollow/models/res_config_settings.py
  sale_order_partner_no_autofollow/models/sale_order.py
  sale_order_partner_no_autofollow/readme/CONFIGURE.rst
  sale_order_partner_no_autofollow/readme/DESCRIPTION.rst
  sale_order_partner_no_autofollow/tests/__init__.py
  sale_order_partner_no_autofollow/tests/common.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_disabled.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_enabled.py
  sale_order_partner_no_autofollow/views/res_config_settings.xml
  setup/sale_order_partner_no_autofollow/odoo/addons/sale_order_partner_no_autofollow
  setup/sale_order_partner_no_autofollow/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1129 [13.0][MIG] sale_procurement_group_by_commitment_date
  sale_procurement_group_by_commitment_date/README.rst
  sale_procurement_group_by_commitment_date/__init__.py
  sale_procurement_group_by_commitment_date/__manifest__.py
  sale_procurement_group_by_commitment_date/i18n/ca.po
  sale_procurement_group_by_commitment_date/i18n/de.po
  sale_procurement_group_by_commitment_date/i18n/el_GR.po
  sale_procurement_group_by_commitment_date/i18n/es.po
  sale_procurement_group_by_commitment_date/i18n/es_ES.po
  sale_procurement_group_by_commitment_date/i18n/es_VE.po
  sale_procurement_group_by_commitment_date/i18n/fi.po
  sale_procurement_group_by_commitment_date/i18n/fr.po
  sale_procurement_group_by_commitment_date/i18n/hr.po
  sale_procurement_group_by_commitment_date/i18n/hr_HR.po
  sale_procurement_group_by_commitment_date/i18n/hu.po
  sale_procurement_group_by_commitment_date/i18n/it.po
  sale_procurement_group_by_commitment_date/i18n/nl.po
  sale_procurement_group_by_commitment_date/i18n/nl_NL.po
  sale_procurement_group_by_commitment_date/i18n/pt.po
  sale_procurement_group_by_commitment_date/i18n/pt_BR.po
  sale_procurement_group_by_commitment_date/i18n/ro.po
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_commitment_date.pot
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_requested_date.pot
  sale_procurement_group_by_commitment_date/i18n/sl.po
  sale_procurement_group_by_commitment_date/i18n/tr.po
  sale_procurement_group_by_commitment_date/i18n/tr_TR.po
  sale_procurement_group_by_commitment_date/i18n/vi_VN.po
  sale_procurement_group_by_commitment_date/i18n/zh_CN.po
  sale_procurement_group_by_commitment_date/models/__init__.py
  sale_procurement_group_by_commitment_date/models/sale_order.py
  sale_procurement_group_by_commitment_date/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_commitment_date/readme/DESCRIPTION.rst
  sale_procurement_group_by_commitment_date/readme/INSTALL.rst
  sale_procurement_group_by_commitment_date/readme/ROADMAP.rst
  sale_procurement_group_by_commitment_date/readme/USAGE.rst
  sale_procurement_group_by_commitment_date/static/description/icon.png
  sale_procurement_group_by_commitment_date/static/description/index.html
  sale_procurement_group_by_commitment_date/tests/__init__.py
  sale_procurement_group_by_commitment_date/tests/test_sale_procurement_group_by_commitment_date.py
  setup/sale_procurement_group_by_commitment_date/odoo/addons/sale_procurement_group_by_commitment_date
  setup/sale_procurement_group_by_commitment_date/setup.py
Labels: needs fixing, approved, bot is merging ⏳

#2120 [14.0][FIX] product_form_sale_link: replace sales_count by a coherent one
  product_form_sale_link/__init__.py
  product_form_sale_link/models/__init__.py
  product_form_sale_link/models/product_product.py
  product_form_sale_link/models/product_template.py
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2276 [14.0][FIX] sale_procurement_group_by_line
  sale_delivery_split_date/models/__init__.py
  sale_delivery_split_date/models/sale_order.py
  sale_delivery_split_date/models/sale_order_line.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
  sale_stock_delivery_address/models/__init__.py
  sale_stock_delivery_address/models/sale_order.py
  sale_stock_delivery_address/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#2217 [14.0][IMP] sale_partner_incoterm
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1956 [13.0][FIX] sale_coupon_product_management constrains
  sale_coupon_product_management/models/sale_coupon_program.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1840 [15.0][MIG] sale_substate
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/readme/CONTRIBUTORS.rst
  sale_substate/readme/DESCRIPTION.rst
  sale_substate/readme/USAGE.rst
  sale_substate/static/description/icon.png
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
  setup/sale_substate/odoo/addons/sale_substate
  setup/sale_substate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1917 [MIG][15.0]sale_last_price_info: migration v15
  sale_last_price_info/README.rst
  sale_last_price_info/__init__.py
  sale_last_price_info/__manifest__.py
  sale_last_price_info/i18n/ca.po
  sale_last_price_info/i18n/de.po
  sale_last_price_info/i18n/es.po
  sale_last_price_info/i18n/fr.po
  sale_last_price_info/i18n/fr_FR.po
  sale_last_price_info/i18n/it.po
  sale_last_price_info/i18n/nl.po
  sale_last_price_info/i18n/sale_last_price_info.pot
  sale_last_price_info/i18n/sl_SI.po
  sale_last_price_info/i18n/zh_CN.po
  sale_last_price_info/models/__init__.py
  sale_last_price_info/models/product.py
  sale_last_price_info/models/sale.py
  sale_last_price_info/readme/CONTRIBUTORS.rst
  sale_last_price_info/readme/DESCRIPTION.rst
  sale_last_price_info/static/description/icon.png
  sale_last_price_info/static/description/index.html
  sale_last_price_info/tests/__init__.py
  sale_last_price_info/tests/test_sale_last_price_info.py
  sale_last_price_info/views/product_view.xml
  setup/sale_last_price_info/odoo/addons/sale_last_price_info
  setup/sale_last_price_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2005 [15.0][MIG] sale_automatic_workflow_payment_mode
  sale_automatic_workflow_payment_mode/README.rst
  sale_automatic_workflow_payment_mode/__init__.py
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/i18n/ca.po
  sale_automatic_workflow_payment_mode/i18n/de.po
  sale_automatic_workflow_payment_mode/i18n/el_GR.po
  sale_automatic_workflow_payment_mode/i18n/es.po
  sale_automatic_workflow_payment_mode/i18n/es_ES.po
  sale_automatic_workflow_payment_mode/i18n/es_VE.po
  sale_automatic_workflow_payment_mode/i18n/fi.po
  sale_automatic_workflow_payment_mode/i18n/fr.po
  sale_automatic_workflow_payment_mode/i18n/hr.po
  sale_automatic_workflow_payment_mode/i18n/hr_HR.po
  sale_automatic_workflow_payment_mode/i18n/hu.po
  sale_automatic_workflow_payment_mode/i18n/it.po
  sale_automatic_workflow_payment_mode/i18n/nl.po
  sale_automatic_workflow_payment_mode/i18n/nl_NL.po
  sale_automatic_workflow_payment_mode/i18n/pt.po
  sale_automatic_workflow_payment_mode/i18n/pt_BR.po
  sale_automatic_workflow_payment_mode/i18n/ro.po
  sale_automatic_workflow_payment_mode/i18n/sale_automatic_workflow_payment_mode.pot
  sale_automatic_workflow_payment_mode/i18n/sk.po
  sale_automatic_workflow_payment_mode/i18n/sl.po
  sale_automatic_workflow_payment_mode/i18n/tr.po
  sale_automatic_workflow_payment_mode/i18n/tr_TR.po
  sale_automatic_workflow_payment_mode/i18n/vi_VN.po
  sale_automatic_workflow_payment_mode/i18n/zh_CN.po
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/account_payment_mode.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_automatic_workflow_payment_mode/models/sale_order.py
  sale_automatic_workflow_payment_mode/readme/CONFIGURE.rst
  sale_automatic_workflow_payment_mode/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_payment_mode/readme/CREDITS.rst
  sale_automatic_workflow_payment_mode/readme/DESCRIPTION.rst
  sale_automatic_workflow_payment_mode/readme/INSTALL.rst
  sale_automatic_workflow_payment_mode/readme/USAGE.rst
  sale_automatic_workflow_payment_mode/static/description/icon.png
  sale_automatic_workflow_payment_mode/static/description/index.html
  sale_automatic_workflow_payment_mode/tests/__init__.py
  sale_automatic_workflow_payment_mode/tests/test_automatic_workflow_payment_mode.py
  sale_automatic_workflow_payment_mode/views/account_payment_mode_views.xml
  setup/sale_automatic_workflow_payment_mode/odoo/addons/sale_automatic_workflow_payment_mode
  setup/sale_automatic_workflow_payment_mode/setup.py
Labels: approved, ready to merge, bot is merging ⏳
