Repository OCA/sale-workflow, pull requests merged in 2022-03, with the labels that each got.

#1935 [12.0][FIX] sale_product_set: Add invisible field order_id to wizard view
  sale_product_set/wizard/product_set_add.xml
Labels: approved, bot is merging ⏳

#1885 [ADD] sale_default_uom
  sale_default_uom/README.rst
  sale_default_uom/__init__.py
  sale_default_uom/__manifest__.py
  sale_default_uom/i18n/it.po
  sale_default_uom/models/__init__.py
  sale_default_uom/models/product_template.py
  sale_default_uom/models/sale_order_line.py
  sale_default_uom/readme/CONTRIBUTORS.rst
  sale_default_uom/readme/DESCRIPTION.rst
  sale_default_uom/readme/HISTORY.rst
  sale_default_uom/readme/USAGE.rst
  sale_default_uom/static/description/icon.png
  sale_default_uom/static/description/index.html
  sale_default_uom/tests/__init__.py
  sale_default_uom/tests/test_sale_order_line.py
  sale_default_uom/views/product_template_view.xml
  setup/sale_default_uom/odoo/addons/sale_default_uom
  setup/sale_default_uom/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1932 [14.0][ADD] sale_partner_approval: only allow approved customers in Sales Orders
  sale_partner_approval/README.rst
  sale_partner_approval/__init__.py
  sale_partner_approval/__manifest__.py
  sale_partner_approval/data/exception_rule.xml
  sale_partner_approval/models/__init__.py
  sale_partner_approval/models/res_partner.py
  sale_partner_approval/models/res_partner_stage.py
  sale_partner_approval/models/sale_order.py
  sale_partner_approval/readme/CONFIGURE.rst
  sale_partner_approval/readme/CONTRIBUTORS.rst
  sale_partner_approval/readme/DESCRIPTION.rst
  sale_partner_approval/readme/USAGE.rst
  sale_partner_approval/tests/__init__.py
  sale_partner_approval/tests/test_product_approval.py
  sale_partner_approval/views/res_partner.xml
  sale_partner_approval/views/res_partner_stage.xml
Labels: bot is merging ⏳

#1739 [13.0][FIX] sale_product_set: fix sequence during set_apply on SO.
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/product_set_add.py
Labels: enhancement, needs review, bot is merging ⏳

#1943 [13.0][FIX] sale_product_set: Change toggle_active button to web_ribbon widget in form view.
  sale_product_set/views/product_set.xml
Labels: approved, bot is merging ⏳

#1239 [13.0][MIG] sale_order_price_recalculation: Migration to 13.0
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: needs review, migration, bot is merging ⏳

#1303 [13.0][ADD] sale_stock_picking_validation_blocking
  sale_stock_picking_validation_blocking/README.rst
  sale_stock_picking_validation_blocking/__init__.py
  sale_stock_picking_validation_blocking/__manifest__.py
  sale_stock_picking_validation_blocking/models/__init__.py
  sale_stock_picking_validation_blocking/models/sale_order.py
  sale_stock_picking_validation_blocking/models/stock_picking.py
  sale_stock_picking_validation_blocking/readme/CONTRIBUTORS.rst
  sale_stock_picking_validation_blocking/readme/DESCRIPTION.rst
  sale_stock_picking_validation_blocking/readme/USAGE.rst
  sale_stock_picking_validation_blocking/static/description/icon.png
  sale_stock_picking_validation_blocking/static/description/index.html
  sale_stock_picking_validation_blocking/tests/__init__.py
  sale_stock_picking_validation_blocking/tests/test_sale_stock.py
  sale_stock_picking_validation_blocking/views/sale_order.xml
  sale_stock_picking_validation_blocking/views/stock_picking.xml
  setup/sale_stock_picking_validation_blocking/odoo/addons/sale_stock_picking_validation_blocking
  setup/sale_stock_picking_validation_blocking/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1949 [14.0][FIX] sale_product_set: Add company_id from order
  sale_product_set/models/product_set_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1927 [11.0][MIG] sale_sourced_by_line
  .travis.yml
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale.py
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/test/sale_order_multi_source.yml
  sale_sourced_by_line/test/sale_order_not_sourced.yml
  sale_sourced_by_line/test/sale_order_source.yml
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_is_delivered.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1951 [14.0] sale_commitment_date_mandatory: know issue
  sale_commitment_date_mandatory/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1941 [14.0][FIX] sale_order_lot_selection: add company ctx
  sale_order_lot_selection/view/sale_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1933 [13.0][FIX] sale_order_line_packaging_qty: fix decimal precision to check if qty packaged must be reset
  sale_order_line_packaging_qty/models/sale_order_line.py
  sale_order_line_packaging_qty/tests/test_sale_order_line_packaging_qty.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1937 [15.0][FIX] sale_order_line_date: Same operation as v13 and v14
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1959 [FIX] sale_order_type: Force company in default values to improve multi-company uses
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#1574 [14.0][MIG] sale_procurement_amendment
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/ca.po
  sale_procurement_amendment/i18n/es.po
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: needs review, migration, bot is merging ⏳

#1755 FIX sale_pricelist_from_commitment_date
  sale_pricelist_from_commitment_date/models/sale_order.py
  sale_pricelist_from_commitment_date/tests/test_pricelist_from_commitment_date.py
Labels: approved, bot is merging ⏳

#1958 [13.0][FIX] sale_order_line_input: Force company in sale order creation to improve multi-company uses
  sale_order_line_input/models/sale_order.py
Labels: approved, bot is merging ⏳

#1806 [14.0][ADD] sale_order_line_initial_quantity module
  sale_order_line_initial_quantity/README.rst
  sale_order_line_initial_quantity/__init__.py
  sale_order_line_initial_quantity/__manifest__.py
  sale_order_line_initial_quantity/models/__init__.py
  sale_order_line_initial_quantity/models/sale_order.py
  sale_order_line_initial_quantity/models/sale_order_line.py
  sale_order_line_initial_quantity/readme/CONFIGURE.rst
  sale_order_line_initial_quantity/readme/CONTRIBUTORS.rst
  sale_order_line_initial_quantity/readme/DESCRIPTION.rst
  sale_order_line_initial_quantity/readme/USAGE.rst
  sale_order_line_initial_quantity/static/description/index.html
  sale_order_line_initial_quantity/tests/__init__.py
  sale_order_line_initial_quantity/tests/test_sale_order_line_initial_quantity.py
  sale_order_line_initial_quantity/views/sale.xml
  setup/sale_order_line_initial_quantity/odoo/addons/sale_order_line_initial_quantity
  setup/sale_order_line_initial_quantity/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1533 [13.0][MIG] sale_procurement_amendment
  sale_procurement_amendment/README.rst
  sale_procurement_amendment/__init__.py
  sale_procurement_amendment/__manifest__.py
  sale_procurement_amendment/i18n/ca.po
  sale_procurement_amendment/i18n/es.po
  sale_procurement_amendment/i18n/sale_procurement_amendment.pot
  sale_procurement_amendment/models/__init__.py
  sale_procurement_amendment/models/sale_order_line.py
  sale_procurement_amendment/models/stock_move.py
  sale_procurement_amendment/models/stock_picking.py
  sale_procurement_amendment/readme/CONTRIBUTORS.rst
  sale_procurement_amendment/readme/DESCRIPTION.rst
  sale_procurement_amendment/readme/HISTORY.rst
  sale_procurement_amendment/readme/INSTALL.rst
  sale_procurement_amendment/readme/USAGE.rst
  sale_procurement_amendment/static/description/icon.png
  sale_procurement_amendment/static/description/index.html
  sale_procurement_amendment/tests/__init__.py
  sale_procurement_amendment/tests/test_sale_procurement_amendment.py
  setup/sale_procurement_amendment/odoo/addons/sale_procurement_amendment
  setup/sale_procurement_amendment/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳
