Repository OCA/sale-workflow, pull requests merged in 2022-09, with the labels that each got.

#2179 [13.0][FIX] product_supplierinfo_for_customer_sale: Use the same ACL's to sale module for supplierinfo model
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2173 [IMP] Add section note to sale blanket order
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/report/templates.xml
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/wizard/create_sale_orders.py
Labels: approved, bot is merging ⏳

#2140 [15.0] [MIG] sale_shipping_info_helper
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__manifest__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/readme/CONTRIBUTORS.rst
  sale_shipping_info_helper/readme/DESCRIPTION.rst
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/static/description/index.html
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
  setup/sale_shipping_info_helper/odoo/addons/sale_shipping_info_helper
  setup/sale_shipping_info_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2135 [15.0] [MIG] sale_order_partner_restrict
  sale_order_partner_restrict/README.rst
  sale_order_partner_restrict/__init__.py
  sale_order_partner_restrict/__manifest__.py
  sale_order_partner_restrict/i18n/sale_order_partner_restrict.pot
  sale_order_partner_restrict/models/__init__.py
  sale_order_partner_restrict/models/res_company.py
  sale_order_partner_restrict/models/res_config_settings.py
  sale_order_partner_restrict/models/sale.py
  sale_order_partner_restrict/readme/CONTRIBUTORS.rst
  sale_order_partner_restrict/readme/DESCRIPTION.rst
  sale_order_partner_restrict/readme/USAGE.rst
  sale_order_partner_restrict/static/description/icon.png
  sale_order_partner_restrict/static/description/index.html
  sale_order_partner_restrict/tests/__init__.py
  sale_order_partner_restrict/tests/test_sale_order_partner_restrict.py
  sale_order_partner_restrict/views/res_config_settings_views.xml
  sale_order_partner_restrict/views/sale_order_view.xml
  setup/sale_order_partner_restrict/odoo/addons/sale_order_partner_restrict
  setup/sale_order_partner_restrict/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2139 [15.0] [MIG] sale_order_price_recalculation
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2087 [ADD] product_supplierinfo_for_customer_elaboration: New module to set default elaborations
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__init__.py
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/models/__init__.py
  product_supplierinfo_for_customer_elaboration/models/product_customerinfo.py
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONFIGURE.rst
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_elaboration/readme/USAGE.rst
  product_supplierinfo_for_customer_elaboration/security/ir.model.access.csv
  product_supplierinfo_for_customer_elaboration/static/description/icon.png
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  product_supplierinfo_for_customer_elaboration/tests/__init__.py
  product_supplierinfo_for_customer_elaboration/tests/test_customerinfo_elaboration.py
  product_supplierinfo_for_customer_elaboration/views/product_views.xml
  setup/product_supplierinfo_for_customer_elaboration/odoo/addons/product_supplierinfo_for_customer_elaboration
  setup/product_supplierinfo_for_customer_elaboration/setup.py
Labels: approved, bot is merging ⏳

#2083 [15.0][MIG] product_supplierinfo_for_customer_sale
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__init__.py
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/ROADMAP.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  product_supplierinfo_for_customer_sale/static/description/configuration_customer.png
  product_supplierinfo_for_customer_sale/static/description/description_code.png
  product_supplierinfo_for_customer_sale/static/description/description_code_2.png
  product_supplierinfo_for_customer_sale/static/description/icon.png
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/static/description/search_code.png
  product_supplierinfo_for_customer_sale/static/description/search_code_2.png
  product_supplierinfo_for_customer_sale/tests/__init__.py
  product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  product_supplierinfo_for_customer_sale/views/sale_view.xml
  setup/product_supplierinfo_for_customer_sale/odoo/addons/product_supplierinfo_for_customer_sale
  setup/product_supplierinfo_for_customer_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2181 [12.0][FIX] sale_invoice_plan: rounds the value to the rounding precision of the product's unit of measure
  sale_invoice_plan/models/sale.py
Labels: approved, bot is merging ⏳

#2180 [14.0][FIX] product_supplierinfo_for_customer_sale: Use the same ACL's to sale module for supplierinfo model
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2078 [15.0][IMP] sale_invoice_plan: miscellaneous improvements
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/data/sale_data.xml
  sale_invoice_plan/i18n/es.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
Labels: enhancement, needs review, bot is merging ⏳

#2195 [15.0][IMP] sale_payment_sheet: Display partner shipping as optional in invoices tree view
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#2197 [14.0][IMP] sale_global_discount: improve README with reference to the one of base_global_discount
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#2114 [15.0][MIG] sale_order_line_input: Migration to 15.0
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/it.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/readme/CONTRIBUTORS.rst
  sale_order_line_input/readme/DESCRIPTION.rst
  sale_order_line_input/readme/USAGE.rst
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
  setup/sale_order_line_input/odoo/addons/sale_order_line_input
  setup/sale_order_line_input/setup.py
Labels: approved, bot is merging ⏳

#2144 [15.0] [MIG] sale_wishlist
  sale_wishlist/README.rst
  sale_wishlist/__init__.py
  sale_wishlist/__manifest__.py
  sale_wishlist/i18n/es.po
  sale_wishlist/i18n/fr_FR.po
  sale_wishlist/i18n/sale_wishlist.pot
  sale_wishlist/models/__init__.py
  sale_wishlist/models/product_set.py
  sale_wishlist/models/res_partner.py
  sale_wishlist/readme/CONTRIBUTORS.rst
  sale_wishlist/readme/CREDITS.rst
  sale_wishlist/readme/DESCRIPTION.rst
  sale_wishlist/readme/USAGE.rst
  sale_wishlist/static/description/icon.png
  sale_wishlist/static/description/index.html
  sale_wishlist/tests/__init__.py
  sale_wishlist/tests/test_wishlist.py
  sale_wishlist/views/partner.xml
  sale_wishlist/views/product_set.xml
  setup/sale_wishlist/odoo/addons/sale_wishlist
  setup/sale_wishlist/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2184 [14.0][FIX] sale_invoice_plan: product qtd round precision - Ref. 2181
  sale_invoice_plan/models/sale_invoice_plan.py
Labels: approved, bot is merging ⏳

#2183 [13.0][FIX] sale_invoice_plan: product quantity round precision - Ref. PR 2181
  sale_invoice_plan/models/sale.py
Labels: enhancement, needs fixing, approved, bot is merging ⏳

#2182 [12.0][IMP] sale_invoice_plan: enable more than one invoice
  sale_invoice_plan/models/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2189 [15.0][IMP] sale_invoice_plan: enable more than one invoice
  sale_invoice_plan/models/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2188 [14.0][IMP] sale_invoice_plan: enable more than one invoice
  sale_invoice_plan/models/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2111 [14.0][IMP] sale_automatic_workflow_job: Refactor and fix
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
Labels: approved, bot is merging ⏳

#2103 [IMP] sale_manual_delivery: Avoid onchange function collisions
  sale_manual_delivery/models/sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2190 [15.0][FIX] sale_invoice_plan: product qtd round precision - Ref. 2181
  sale_invoice_plan/models/sale_invoice_plan.py
Labels: approved, bot is merging ⏳

#2187 [13.0][IMP] sale_invoice_plan: enable more than one invoice
  sale_invoice_plan/models/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2177 [15.0][MIG] sale_order_line_delivery_state
  sale_order_line_delivery_state/README.rst
  sale_order_line_delivery_state/__init__.py
  sale_order_line_delivery_state/__manifest__.py
  sale_order_line_delivery_state/i18n/sale_order_line_delivery_state.pot
  sale_order_line_delivery_state/models/__init__.py
  sale_order_line_delivery_state/models/sale_order_line.py
  sale_order_line_delivery_state/readme/CONTRIBUTORS.rst
  sale_order_line_delivery_state/readme/DESCRIPTION.rst
  sale_order_line_delivery_state/static/description/icon.png
  sale_order_line_delivery_state/static/description/index.html
  sale_order_line_delivery_state/tests/__init__.py
  sale_order_line_delivery_state/tests/test_sale_line_delivery_state.py
  sale_order_line_delivery_state/views/sale_order_views.xml
  setup/sale_order_line_delivery_state/odoo/addons/sale_order_line_delivery_state
  setup/sale_order_line_delivery_state/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2176 [15.0][MIG] sale_order_carrier_auto_assign: Migration to 15.0
  sale_order_carrier_auto_assign/README.rst
  sale_order_carrier_auto_assign/__init__.py
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/i18n/es.po
  sale_order_carrier_auto_assign/i18n/sale_order_carrier_auto_assign.pot
  sale_order_carrier_auto_assign/models/__init__.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/readme/CONTRIBUTORS.rst
  sale_order_carrier_auto_assign/readme/CREDITS.rst
  sale_order_carrier_auto_assign/readme/DESCRIPTION.rst
  sale_order_carrier_auto_assign/static/description/icon.png
  sale_order_carrier_auto_assign/static/description/index.html
  sale_order_carrier_auto_assign/tests/__init__.py
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
  setup/sale_order_carrier_auto_assign/odoo/addons/sale_order_carrier_auto_assign
  setup/sale_order_carrier_auto_assign/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1324 [12.0] [IMP] sale_require_po_doc
  sale_require_po_doc/models/sale_order.py
Labels: needs review, bot is merging ⏳

#2208 [13.0][IMP] sale_tier_validation: Make subtypes internal
  sale_tier_validation/data/mail_data.xml
Labels: approved, bot is merging ⏳

#1849 [15.0][MIG] sale_order_line_description
  sale_order_line_description/README.rst
  sale_order_line_description/__init__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_description/i18n/ca.po
  sale_order_line_description/i18n/de.po
  sale_order_line_description/i18n/en.po
  sale_order_line_description/i18n/es.po
  sale_order_line_description/i18n/es_VE.po
  sale_order_line_description/i18n/fr.po
  sale_order_line_description/i18n/fr_FR.po
  sale_order_line_description/i18n/hr.po
  sale_order_line_description/i18n/it.po
  sale_order_line_description/i18n/nl_NL.po
  sale_order_line_description/i18n/pt_BR.po
  sale_order_line_description/i18n/ro.po
  sale_order_line_description/i18n/sale_order_line_description.pot
  sale_order_line_description/i18n/sl.po
  sale_order_line_description/i18n/tr.po
  sale_order_line_description/i18n/tr_TR.po
  sale_order_line_description/i18n/zh_CN.po
  sale_order_line_description/models/__init__.py
  sale_order_line_description/models/res_config_settings.py
  sale_order_line_description/models/sale_order_line.py
  sale_order_line_description/readme/CONFIGURE.rst
  sale_order_line_description/readme/CONTRIBUTORS.rst
  sale_order_line_description/readme/DESCRIPTION.rst
  sale_order_line_description/readme/USAGE.rst
  sale_order_line_description/security/sale_security.xml
  sale_order_line_description/static/description/icon.png
  sale_order_line_description/static/description/index.html
  sale_order_line_description/tests/__init__.py
  sale_order_line_description/tests/test_sale.py
  sale_order_line_description/views/res_config_settings_views.xml
  setup/sale_order_line_description/odoo/addons/sale_order_line_description
  setup/sale_order_line_description/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2209 [14.0][IMP] sale_tier_validation: Missing commits from 13
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/tests/test_tier_validation.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2147 [IMP][14.0][sale_order_general_discount] propagate discounts to contacts
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#1853 [14.0][ADD] sale_automatic_workflow_invoice_default_value
  sale_automatic_workflow_invoice_default_value/README.rst
  sale_automatic_workflow_invoice_default_value/__init__.py
  sale_automatic_workflow_invoice_default_value/__manifest__.py
  sale_automatic_workflow_invoice_default_value/i18n/fr.po
  sale_automatic_workflow_invoice_default_value/models/__init__.py
  sale_automatic_workflow_invoice_default_value/models/automatic_workflow_invoice_default_value.py
  sale_automatic_workflow_invoice_default_value/models/automatic_workflow_job.py
  sale_automatic_workflow_invoice_default_value/models/sale_workflow_process.py
  sale_automatic_workflow_invoice_default_value/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_invoice_default_value/readme/DESCRIPTION.rst
  sale_automatic_workflow_invoice_default_value/security/ir.model.access.csv
  sale_automatic_workflow_invoice_default_value/tests/__init__.py
  sale_automatic_workflow_invoice_default_value/tests/test_automatic_workflow_invoice_default_value.py
  sale_automatic_workflow_invoice_default_value/views/sale_workflow_process.xml
  setup/sale_automatic_workflow_invoice_default_value/odoo/addons/sale_automatic_workflow_invoice_default_value
  setup/sale_automatic_workflow_invoice_default_value/setup.py
Labels: approved, bot is merging ⏳

#2116 [13.0][ADD] sale_invoice_no_mail: new module
  sale_invoice_no_mail/README.rst
  sale_invoice_no_mail/__init__.py
  sale_invoice_no_mail/__manifest__.py
  sale_invoice_no_mail/readme/CONTRIBUTORS.rst
  sale_invoice_no_mail/readme/DESCRIPTION.rst
  sale_invoice_no_mail/readme/USAGE.rst
  sale_invoice_no_mail/static/description/index.html
  sale_invoice_no_mail/tests/__init__.py
  sale_invoice_no_mail/tests/test_sale_invoice_no_mail.py
  sale_invoice_no_mail/wizard/__init__.py
  sale_invoice_no_mail/wizard/sale_make_invoice_advance.py
  setup/sale_invoice_no_mail/odoo/addons/sale_invoice_no_mail
  setup/sale_invoice_no_mail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2134 [14.0] [MIG] sale_order_partner_restrict
  sale_order_partner_restrict/README.rst
  sale_order_partner_restrict/__init__.py
  sale_order_partner_restrict/__manifest__.py
  sale_order_partner_restrict/i18n/sale_order_partner_restrict.pot
  sale_order_partner_restrict/models/__init__.py
  sale_order_partner_restrict/models/res_company.py
  sale_order_partner_restrict/models/res_config_settings.py
  sale_order_partner_restrict/models/sale.py
  sale_order_partner_restrict/readme/CONTRIBUTORS.rst
  sale_order_partner_restrict/readme/DESCRIPTION.rst
  sale_order_partner_restrict/readme/USAGE.rst
  sale_order_partner_restrict/static/description/icon.png
  sale_order_partner_restrict/static/description/index.html
  sale_order_partner_restrict/tests/__init__.py
  sale_order_partner_restrict/tests/test_sale_order_partner_restrict.py
  sale_order_partner_restrict/views/res_config_settings_views.xml
  sale_order_partner_restrict/views/sale_order_view.xml
  setup/sale_order_partner_restrict/odoo/addons/sale_order_partner_restrict
  setup/sale_order_partner_restrict/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1869 [14.0][ADD] sale_automatic_workflow_ignore_exception
  sale_automatic_workflow_ignore_exception/README.rst
  sale_automatic_workflow_ignore_exception/__init__.py
  sale_automatic_workflow_ignore_exception/__manifest__.py
  sale_automatic_workflow_ignore_exception/i18n/fr.po
  sale_automatic_workflow_ignore_exception/models/__init__.py
  sale_automatic_workflow_ignore_exception/models/automatic_workflow_job.py
  sale_automatic_workflow_ignore_exception/models/sale_order.py
  sale_automatic_workflow_ignore_exception/models/sale_workflow_process.py
  sale_automatic_workflow_ignore_exception/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_ignore_exception/readme/DESCRIPTION.rst
  sale_automatic_workflow_ignore_exception/tests/__init__.py
  sale_automatic_workflow_ignore_exception/tests/test_automatic_workflow_ignore_exception.py
  sale_automatic_workflow_ignore_exception/views/sale_workflow_process.xml
  setup/sale_automatic_workflow_ignore_exception/odoo/addons/sale_automatic_workflow_ignore_exception
  setup/sale_automatic_workflow_ignore_exception/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2117 [14.0][MIG] sale_invoice_no_mail
  sale_invoice_no_mail/README.rst
  sale_invoice_no_mail/__init__.py
  sale_invoice_no_mail/__manifest__.py
  sale_invoice_no_mail/readme/CONTRIBUTORS.rst
  sale_invoice_no_mail/readme/DESCRIPTION.rst
  sale_invoice_no_mail/readme/USAGE.rst
  sale_invoice_no_mail/static/description/index.html
  sale_invoice_no_mail/tests/__init__.py
  sale_invoice_no_mail/tests/test_sale_invoice_no_mail.py
  sale_invoice_no_mail/wizard/__init__.py
  sale_invoice_no_mail/wizard/sale_make_invoice_advance.py
  setup/sale_invoice_no_mail/odoo/addons/sale_invoice_no_mail
  setup/sale_invoice_no_mail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2210 [15.0][IMP] sale_tier_validation: Missing commits from 13.0
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#2212 [UPD] Switch to Github Actions / Copier update
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_commercial_partner/__manifest__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_revision/__manifest__.py
  sale_product_multi_add/__manifest__.py
  sale_quotation_number/__manifest__.py
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/models/procurement_group.py
  sale_stock_delivery_address/models/sale_order.py
  sale_stock_delivery_address/models/sale_order_line.py
  sale_stock_delivery_address/tests/test_sale_stock_delivery_address.py
  sale_stock_return_request/__manifest__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_sourcing_address/__manifest__.py
Labels: bot is merging ⏳

#2118 [15.0][MIG] sale_invoice_no_mail
  sale_invoice_no_mail/README.rst
  sale_invoice_no_mail/__init__.py
  sale_invoice_no_mail/__manifest__.py
  sale_invoice_no_mail/readme/CONTRIBUTORS.rst
  sale_invoice_no_mail/readme/DESCRIPTION.rst
  sale_invoice_no_mail/readme/USAGE.rst
  sale_invoice_no_mail/static/description/index.html
  sale_invoice_no_mail/tests/__init__.py
  sale_invoice_no_mail/tests/test_sale_invoice_no_mail.py
  sale_invoice_no_mail/wizard/__init__.py
  sale_invoice_no_mail/wizard/sale_make_invoice_advance.py
  setup/sale_invoice_no_mail/odoo/addons/sale_invoice_no_mail
  setup/sale_invoice_no_mail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2203 [14.0][MIG] sale_elaboration: Migration to v14
  sale_elaboration/README.rst
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/readme/CONFIGURE.rst
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/readme/DESCRIPTION.rst
  sale_elaboration/readme/USAGE.rst
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/security/ir.model.access.csv
  sale_elaboration/static/description/icon.png
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/__init__.py
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_views.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_elaboration/views/sale_order_views.xml
  setup/sale_elaboration/odoo/addons/sale_elaboration
  setup/sale_elaboration/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
