Repository OCA/sale-workflow, pull requests merged in 2022-11, with the labels that each got.

#2254 [15.0][DCK] Updated from template
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#2243 [15.0][MIG+REF] portal_sale_personal_data_only: Migration to 15.0 and split in two
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pylintrc
  .pylintrc-mandatory
  README.md
  portal_sale_personal_data_only/README.rst
  portal_sale_personal_data_only/__init__.py
  portal_sale_personal_data_only/__manifest__.py
  portal_sale_personal_data_only/hooks.py
  portal_sale_personal_data_only/i18n/de.po
  portal_sale_personal_data_only/i18n/es.po
  portal_sale_personal_data_only/i18n/portal_sale_personal_data_only.pot
  portal_sale_personal_data_only/i18n/zh_CN.po
  portal_sale_personal_data_only/readme/CONTRIBUTORS.rst
  portal_sale_personal_data_only/readme/DESCRIPTION.rst
  portal_sale_personal_data_only/readme/USAGE.rst
  portal_sale_personal_data_only/security/security.xml
  portal_sale_personal_data_only/static/description/icon.png
  portal_sale_personal_data_only/static/description/index.html
  portal_sale_personal_data_only/tests/__init__.py
  portal_sale_personal_data_only/tests/test_partner_access.py
  sale_stock_invoice_plan/readme/CONTRIBUTORS.rst
  sale_stock_invoice_plan/tests/test_sale_invoice_plan.py
  setup/portal_sale_personal_data_only/odoo/addons/portal_sale_personal_data_only
  setup/portal_sale_personal_data_only/setup.py
Labels: approved, bot is merging ⏳

#2245 [14.0] [FIX] `sale_quick`: put warehouse and to_date in context
  sale_quick/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2246 [14.0][IMP] sale_restricted_qty: show sale_min sale_max optionally
  sale_restricted_qty/views/sale_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1624 [14.0][MIG] sale_order_digitized_signature
  sale_order_digitized_signature/README.rst
  sale_order_digitized_signature/__init__.py
  sale_order_digitized_signature/__manifest__.py
  sale_order_digitized_signature/i18n/es.po
  sale_order_digitized_signature/i18n/sale_order_digitized_signature.pot
  sale_order_digitized_signature/i18n/zh_CN.po
  sale_order_digitized_signature/migrations/13.0.1.0.0/post-migration.py
  sale_order_digitized_signature/migrations/13.0.1.0.0/pre-migration.py
  sale_order_digitized_signature/models/__init__.py
  sale_order_digitized_signature/models/sale.py
  sale_order_digitized_signature/readme/CONTRIBUTORS.rst
  sale_order_digitized_signature/readme/DESCRIPTION.rst
  sale_order_digitized_signature/readme/INSTALL.rst
  sale_order_digitized_signature/readme/USAGE.rst
  sale_order_digitized_signature/report/report_saleorder.xml
  sale_order_digitized_signature/static/description/icon.png
  sale_order_digitized_signature/static/description/index.html
  sale_order_digitized_signature/views/sale_views.xml
  setup/sale_order_digitized_signature/odoo/addons/sale_order_digitized_signature
  setup/sale_order_digitized_signature/setup.py
Labels: needs review, migration, bot is merging ⏳

#1787 [14.0][MIG] sale_invoice_policy
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/ca.po
  sale_invoice_policy/i18n/es.po
  sale_invoice_policy/i18n/es_MX.po
  sale_invoice_policy/i18n/fr.po
  sale_invoice_policy/i18n/pt.po
  sale_invoice_policy/i18n/sale_invoice_policy.pot
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/pre_init_hook.py
  sale_invoice_policy/readme/CONTRIBUTORS.rst
  sale_invoice_policy/readme/DESCRIPTION.rst
  sale_invoice_policy/readme/USAGE.rst
  sale_invoice_policy/static/description/icon.png
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/__init__.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/product_template_view.xml
  sale_invoice_policy/views/sale_view.xml
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2259 [15.0][MIG] sale_force_whole_invoiceability: Migration to 15.0
  sale_force_whole_invoiceability/README.rst
  sale_force_whole_invoiceability/__init__.py
  sale_force_whole_invoiceability/__manifest__.py
  sale_force_whole_invoiceability/i18n/es.po
  sale_force_whole_invoiceability/i18n/sale_force_whole_invoiceability.pot
  sale_force_whole_invoiceability/models/__init__.py
  sale_force_whole_invoiceability/models/sale_order.py
  sale_force_whole_invoiceability/readme/CONTRIBUTORS.rst
  sale_force_whole_invoiceability/readme/DESCRIPTION.rst
  sale_force_whole_invoiceability/readme/ROADMAP.rst
  sale_force_whole_invoiceability/readme/USAGE.rst
  sale_force_whole_invoiceability/static/description/icon.png
  sale_force_whole_invoiceability/static/description/index.html
  sale_force_whole_invoiceability/tests/__init__.py
  sale_force_whole_invoiceability/tests/test_sale_force_whole.py
  sale_force_whole_invoiceability/views/sale_order_views.xml
  setup/sale_force_whole_invoiceability/odoo/addons/sale_force_whole_invoiceability
  setup/sale_force_whole_invoiceability/setup.py
Labels: approved, bot is merging ⏳

#2094 [15.0][MIG] sale_order_priority
  sale_order_priority/README.rst
  sale_order_priority/__init__.py
  sale_order_priority/__manifest__.py
  sale_order_priority/i18n/it.po
  sale_order_priority/i18n/sale_order_priority.pot
  sale_order_priority/models/__init__.py
  sale_order_priority/models/sale.py
  sale_order_priority/models/stock_picking.py
  sale_order_priority/readme/CONTRIBUTORS.rst
  sale_order_priority/readme/DESCRIPTION.rst
  sale_order_priority/static/description/icon.png
  sale_order_priority/static/description/index.html
  sale_order_priority/tests/__init__.py
  sale_order_priority/tests/test_sale_stock.py
  sale_order_priority/views/sale.xml
  setup/sale_order_priority/odoo/addons/sale_order_priority
  setup/sale_order_priority/setup.py
Labels: bot is merging ⏳

#2258 [16.0][MIG] partner_sale_pivot: Migration to 16.0
  partner_sale_pivot/README.rst
  partner_sale_pivot/__init__.py
  partner_sale_pivot/__manifest__.py
  partner_sale_pivot/i18n/ca.po
  partner_sale_pivot/i18n/ca_ES.po
  partner_sale_pivot/i18n/es.po
  partner_sale_pivot/i18n/partner_sale_pivot.pot
  partner_sale_pivot/readme/CONTRIBUTORS.rst
  partner_sale_pivot/readme/DESCRIPTION.rst
  partner_sale_pivot/readme/USAGE.rst
  partner_sale_pivot/static/description/icon.png
  partner_sale_pivot/static/description/index.html
  partner_sale_pivot/views/res_partner_views.xml
  partner_sale_pivot/views/sale_report_views.xml
  setup/partner_sale_pivot/odoo/addons/partner_sale_pivot
  setup/partner_sale_pivot/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2206 [15.0] [MIG] product_supplierinfo_for_customer_elaboration: Migration to 15.0
  product_supplierinfo_for_customer_elaboration/README.rst
  product_supplierinfo_for_customer_elaboration/__init__.py
  product_supplierinfo_for_customer_elaboration/__manifest__.py
  product_supplierinfo_for_customer_elaboration/i18n/es.po
  product_supplierinfo_for_customer_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_supplierinfo_for_customer_elaboration/models/__init__.py
  product_supplierinfo_for_customer_elaboration/models/product_customerinfo.py
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  product_supplierinfo_for_customer_elaboration/readme/CONFIGURE.rst
  product_supplierinfo_for_customer_elaboration/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_elaboration/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_elaboration/readme/USAGE.rst
  product_supplierinfo_for_customer_elaboration/security/ir.model.access.csv
  product_supplierinfo_for_customer_elaboration/static/description/icon.png
  product_supplierinfo_for_customer_elaboration/static/description/index.html
  product_supplierinfo_for_customer_elaboration/tests/__init__.py
  product_supplierinfo_for_customer_elaboration/tests/test_customerinfo_elaboration.py
  product_supplierinfo_for_customer_elaboration/views/product_views.xml
  setup/product_supplierinfo_for_customer_elaboration/odoo/addons/product_supplierinfo_for_customer_elaboration
  setup/product_supplierinfo_for_customer_elaboration/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2270 [15.0][MIG] sale_stock_last_date: Migration to version 15.0
  sale_stock_last_date/README.rst
  sale_stock_last_date/__init__.py
  sale_stock_last_date/__manifest__.py
  sale_stock_last_date/hooks.py
  sale_stock_last_date/i18n/es.po
  sale_stock_last_date/i18n/sale_stock_last_date.pot
  sale_stock_last_date/models/__init__.py
  sale_stock_last_date/models/sale.py
  sale_stock_last_date/readme/CONTRIBUTORS.rst
  sale_stock_last_date/readme/DESCRIPTION.rst
  sale_stock_last_date/readme/USAGE.rst
  sale_stock_last_date/reports/__init__.py
  sale_stock_last_date/reports/sale_report.py
  sale_stock_last_date/reports/sale_report_view.xml
  sale_stock_last_date/static/description/icon.png
  sale_stock_last_date/static/description/index.html
  sale_stock_last_date/tests/__init__.py
  sale_stock_last_date/tests/test_sale_stock_last_date.py
  sale_stock_last_date/views/sale_order_view.xml
  setup/sale_stock_last_date/odoo/addons/sale_stock_last_date
  setup/sale_stock_last_date/setup.py
Labels: approved, bot is merging ⏳

#2137 [ADD][10.0] sale_manual_delivery
  .github/workflows/test.yml
  portal_sale_personal_data_only/__manifest__.py
  product_margin_classification/readme/CONTRIBUTORS.rst
  product_margin_classification/readme/DESCRIPTION.rst
  sale_invoice_policy/__manifest__.py
  sale_manual_delivery/README.rst
  sale_manual_delivery/__init__.py
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/i18n/sale_manual_delivery.pot
  sale_manual_delivery/models/__init__.py
  sale_manual_delivery/models/crm_team.py
  sale_manual_delivery/models/procurement.py
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/models/sale_order_line.py
  sale_manual_delivery/models/stock_move.py
  sale_manual_delivery/static/description/icon.png
  sale_manual_delivery/static/description/icon.svg
  sale_manual_delivery/tests/__init__.py
  sale_manual_delivery/tests/test_manual_delivery.py
  sale_manual_delivery/views/crm_team_view.xml
  sale_manual_delivery/views/procurement_view.xml
  sale_manual_delivery/views/sale_order_view.xml
  sale_manual_delivery/wizard/__init__.py
  sale_manual_delivery/wizard/line.py
  sale_manual_delivery/wizard/manual_proc.py
  sale_manual_delivery/wizard/manual_proc_view.xml
  sale_mrp_link/readme/ROADMAP.rst
  sale_promotion_rule_assortment/demo/sale_order.xml
  sale_stock_picking_blocking_sale_manual_delivery/README.rst
  sale_stock_picking_blocking_sale_manual_delivery/__init__.py
  sale_stock_picking_blocking_sale_manual_delivery/__manifest__.py
  sale_stock_picking_blocking_sale_manual_delivery/models/__init__.py
  sale_stock_picking_blocking_sale_manual_delivery/models/sale_order_line.py
  sale_stock_picking_blocking_sale_manual_delivery/static/description/icon.png
  setup/sale_manual_delivery/odoo/__init__.py
  setup/sale_manual_delivery/odoo/addons/__init__.py
  setup/sale_manual_delivery/odoo/addons/sale_manual_delivery
  setup/sale_manual_delivery/setup.py
  setup/sale_stock_picking_blocking_sale_manual_delivery/odoo/__init__.py
  setup/sale_stock_picking_blocking_sale_manual_delivery/odoo/addons/__init__.py
  setup/sale_stock_picking_blocking_sale_manual_delivery/odoo/addons/sale_stock_picking_blocking_sale_manual_delivery
  setup/sale_stock_picking_blocking_sale_manual_delivery/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2287 [15.0][IMP] sale_payment_sheet: Remove redundant default on related field.
  sale_payment_sheet/models/sale_payment_sheet.py
Labels: bot is merging ⏳

#2032 [13.0][IMP] sale_order_product_assortment: Add blacklist product domain to exclude some products
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/readme/CONTRIBUTORS.rst
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
Labels: approved, bot is merging ⏳
