Repository OCA/sale-workflow, pull requests merged in 2022-01, with the labels that each got.

#1819 [14.0][IMP] sale_quotation_number, sale_isolated_quotation, sale_partner_version, sale_order_type: resolve conflicts
  .copier-answers.yml
  .travis.yml
  sale_isolated_quotation/README.rst
  sale_isolated_quotation/__manifest__.py
  sale_isolated_quotation/data/ir_sequence_data.xml
  sale_isolated_quotation/hooks.py
  sale_isolated_quotation/migrations/14.0.1.1.0/post-migration.py
  sale_isolated_quotation/models/sale.py
  sale_isolated_quotation/readme/INSTALL.rst
  sale_isolated_quotation/static/description/index.html
  sale_isolated_quotation/tests/test_sale_isolated_quotation.py
  sale_isolated_quotation/views/sale_views.xml
  sale_order_type/models/res_partner.py
  sale_partner_version/__manifest__.py
  sale_partner_version/models/sale.py
  sale_quotation_number/README.rst
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/ir_sequence_data.xml
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/INSTALL.rst
  sale_quotation_number/static/description/index.html
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1793 [14.0][FW] [13.0][Fix] sale_order_line_packaging_qty zero qty
  sale_order_line_packaging_qty/views/sale_order.xml
Labels: approved, bot is merging ⏳

#1827 [14.0][FW] sale_product_set_packaging_qty: extend set line tree
  sale_product_set_packaging_qty/__manifest__.py
  sale_product_set_packaging_qty/readme/CONTRIBUTORS.rst
  sale_product_set_packaging_qty/views/product_set_line.xml
Labels: bot is merging ⏳

#1789 [14.0][FW] sale_automatic_workflow: port from 12.0/13.0
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/data/automatic_workflow_data.xml
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/readme/DESCRIPTION.rst
  sale_automatic_workflow/static/description/index.html
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
  sale_automatic_workflow/views/sale_workflow_process_view.xml
Labels: approved, bot is merging ⏳

#1851 [15.0] [MIG] sale_delivery_state
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/i18n/sale_delivery_state.pot
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/static/description/icon.png
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
  setup/sale_delivery_state/odoo/addons/sale_delivery_state
  setup/sale_delivery_state/setup.py
Labels: approved, bot is merging ⏳

#1868 [14.0][MIG] sale_automatic_workflow_job: Migrate to version 14.0
  sale_automatic_workflow_job/README.rst
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_automatic_workflow_job/i18n/sale_automatic_workflow_job.pot
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/readme/CONTRIBUTORS.rst
  sale_automatic_workflow_job/readme/DESCRIPTION.rst
  sale_automatic_workflow_job/static/description/icon.png
  sale_automatic_workflow_job/static/description/index.html
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  setup/sale_automatic_workflow_job/odoo/addons/sale_automatic_workflow_job
  setup/sale_automatic_workflow_job/setup.py
Labels: approved, bot is merging ⏳

#1871 [13.0][IMP] sale_partner_selectable_option: Improve sale button in contact form to show only if "Selectable in orders" is checked.
  sale_partner_selectable_option/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1861 [MIG] sale_automatic_workflow: Migration to 15.0
  .pre-commit-config.yaml
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/i18n/sale_automatic_workflow.pot
  sale_automatic_workflow/migrations/13.0.1.2.0/noupdate_changes.xml
  sale_automatic_workflow/migrations/13.0.1.2.0/post.py
  sale_automatic_workflow/models/sale_order.py
  sale_automatic_workflow/models/stock_picking.py
  sale_automatic_workflow/static/description/index.html
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  setup/sale_automatic_workflow/odoo/addons/sale_automatic_workflow
  setup/sale_automatic_workflow/setup.py
Labels: approved, bot is merging ⏳

#736 [11.0][MIG] sale_stock_picking_blocking_proc_group_by_line
  .travis.yml
  sale_stock_picking_blocking_proc_group_by_line/README.rst
  sale_stock_picking_blocking_proc_group_by_line/__init__.py
  sale_stock_picking_blocking_proc_group_by_line/__manifest__.py
  sale_stock_picking_blocking_proc_group_by_line/i18n/ca.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/de.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/es.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/es_VE.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/fi.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/fr.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/it.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/nl.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/nl_NL.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/pt_BR.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/ro.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/sale_stock_picking_blocking_proc_group_by_line.pot
  sale_stock_picking_blocking_proc_group_by_line/i18n/sk.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/sl.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/tr.po
  sale_stock_picking_blocking_proc_group_by_line/i18n/tr_TR.po
  sale_stock_picking_blocking_proc_group_by_line/models/__init__.py
  sale_stock_picking_blocking_proc_group_by_line/models/sale_order.py
  sale_stock_picking_blocking_proc_group_by_line/readme/CONTRIBUTORS.rst
  sale_stock_picking_blocking_proc_group_by_line/readme/DESCRIPTION.rst
  sale_stock_picking_blocking_proc_group_by_line/readme/INSTALL.rst
Labels: needs review, bot is merging ⏳

#1872 [14.0][FIX] Fix sale_automatic_workflow_payment_mode migration
  sale_automatic_workflow/__manifest__.py
  sale_automatic_workflow/data/automatic_workflow_data.xml
  sale_automatic_workflow/migrations/14.0.1.3.0/pre-migration.py
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow_payment_mode/__manifest__.py
  sale_automatic_workflow_payment_mode/data/automatic_workflow_data.xml
  sale_automatic_workflow_payment_mode/models/__init__.py
  sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py
  sale_automatic_workflow_payment_mode/models/sale_workflow_process.py
  sale_automatic_workflow_payment_mode/views/sale_workflow_process_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1826 [13.0][ADD] sale_order_partner_restrict
  sale_order_partner_restrict/__init__.py
  sale_order_partner_restrict/__manifest__.py
  sale_order_partner_restrict/models/__init__.py
  sale_order_partner_restrict/models/res_company.py
  sale_order_partner_restrict/models/res_config_settings.py
  sale_order_partner_restrict/models/sale.py
  sale_order_partner_restrict/readme/CONTRIBUTORS.rst
  sale_order_partner_restrict/readme/DESCRIPTION.rst
  sale_order_partner_restrict/readme/USAGE.rst
  sale_order_partner_restrict/static/description/icon.png
  sale_order_partner_restrict/tests/__init__.py
  sale_order_partner_restrict/tests/test_sale_order_partner_restrict.py
  sale_order_partner_restrict/views/res_config_settings_views.xml
  sale_order_partner_restrict/views/sale_order_view.xml
  setup/sale_order_partner_restrict/odoo/addons/sale_order_partner_restrict
  setup/sale_order_partner_restrict/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1884 [13.0][FIX] sale_order_type: Inconsistent data in multi-company environments
  sale_order_type/data/default_type.xml
  sale_order_type/models/sale.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/views/sale_order_type_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1882 [13.0][FIX] sale_order_line_input: company_id field is empty and multi-company...
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1894 [FIX] sale_order_type: Default value check company
  sale_order_type/models/sale.py
Labels: bot is merging ⏳
