Repository OCA/sale-workflow, pull requests merged in 2022-07, with the labels that each got.

#1945 [MIG][15.0]sale_quotation_number: Migration v15
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/ir_sequence_data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2076 [13.0][IMP] product_supplierinfo_for_customer_sale: Add menu entry to access all product.customerinfo
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
Labels: approved, bot is merging ⏳

#2112 [15.0][MIG] partner_contact_sale_info_propagation: Migration to 15.0
  partner_contact_sale_info_propagation/README.rst
  partner_contact_sale_info_propagation/__init__.py
  partner_contact_sale_info_propagation/__manifest__.py
  partner_contact_sale_info_propagation/i18n/ca.po
  partner_contact_sale_info_propagation/i18n/de.po
  partner_contact_sale_info_propagation/i18n/es.po
  partner_contact_sale_info_propagation/i18n/fr.po
  partner_contact_sale_info_propagation/i18n/partner_contact_sale_info_propagation.pot
  partner_contact_sale_info_propagation/models/__init__.py
  partner_contact_sale_info_propagation/models/res_partner.py
  partner_contact_sale_info_propagation/readme/CONTRIBUTORS.rst
  partner_contact_sale_info_propagation/readme/DESCRIPTION.rst
  partner_contact_sale_info_propagation/readme/USAGE.rst
  partner_contact_sale_info_propagation/static/description/icon.png
  partner_contact_sale_info_propagation/static/description/index.html
  partner_contact_sale_info_propagation/tests/__init__.py
  partner_contact_sale_info_propagation/tests/test_partner_contact_sale_info_propagation.py
  partner_contact_sale_info_propagation/views/res_partner_view.xml
  setup/partner_contact_sale_info_propagation/odoo/addons/partner_contact_sale_info_propagation
  setup/partner_contact_sale_info_propagation/setup.py
Labels: approved, bot is merging ⏳

#2097 [15.0][MIG] sales_team_security_crm: Migration to 15.0
  sales_team_security_crm/README.rst
  sales_team_security_crm/__init__.py
  sales_team_security_crm/__manifest__.py
  sales_team_security_crm/i18n/sales_team_security_crm.pot
  sales_team_security_crm/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_crm/readme/CONTRIBUTORS.rst
  sales_team_security_crm/readme/DESCRIPTION.rst
  sales_team_security_crm/security/security.xml
  sales_team_security_crm/static/description/icon.png
  sales_team_security_crm/static/description/index.html
  sales_team_security_crm/tests/__init__.py
  sales_team_security_crm/tests/test_sales_team_security_crm.py
  setup/sales_team_security_crm/odoo/addons/sales_team_security_crm
  setup/sales_team_security_crm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2061 [15.0][mig] sale_invoice_blocking
  sale_invoice_blocking/README.rst
  sale_invoice_blocking/__init__.py
  sale_invoice_blocking/__manifest__.py
  sale_invoice_blocking/i18n/ca.po
  sale_invoice_blocking/i18n/es.po
  sale_invoice_blocking/i18n/es_PA.po
  sale_invoice_blocking/i18n/fr.po
  sale_invoice_blocking/i18n/sale_invoice_blocking.pot
  sale_invoice_blocking/models/__init__.py
  sale_invoice_blocking/models/invoice_blocking_reason.py
  sale_invoice_blocking/models/sale_order.py
  sale_invoice_blocking/readme/CONFIGURE.rst
  sale_invoice_blocking/readme/CONTRIBUTORS.rst
  sale_invoice_blocking/readme/DESCRIPTION.rst
  sale_invoice_blocking/readme/USAGE.rst
  sale_invoice_blocking/security/ir.model.access.csv
  sale_invoice_blocking/static/description/icon.png
  sale_invoice_blocking/static/description/index.html
  sale_invoice_blocking/views/menus.xml
  sale_invoice_blocking/views/sale_invoice_blocking_reason_view.xml
  sale_invoice_blocking/views/sale_order.xml
  setup/sale_invoice_blocking/odoo/addons/sale_invoice_blocking
  setup/sale_invoice_blocking/setup.py
Labels: approved, bot is merging ⏳

#2053 [15.0][MIG] sale_order_product_availability_inline: Migration to 15.0
  sale_order_product_availability_inline/README.rst
  sale_order_product_availability_inline/__init__.py
  sale_order_product_availability_inline/__manifest__.py
  sale_order_product_availability_inline/i18n/ca.po
  sale_order_product_availability_inline/i18n/es.po
  sale_order_product_availability_inline/i18n/sale_order_product_availability_inline.pot
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_product.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/readme/CONTRIBUTORS.rst
  sale_order_product_availability_inline/readme/DESCRIPTION.rst
  sale_order_product_availability_inline/readme/USAGE.rst
  sale_order_product_availability_inline/static/description/icon.png
  sale_order_product_availability_inline/static/description/index.html
  sale_order_product_availability_inline/tests/__init__.py
  sale_order_product_availability_inline/tests/test_sale_order_product_availability_inline.py
  sale_order_product_availability_inline/views/sale_views.xml
  setup/sale_order_product_availability_inline/odoo/addons/sale_order_product_availability_inline
  setup/sale_order_product_availability_inline/setup.py
Labels: needs fixing, migration, bot is merging ⏳

#2115 [IMP] sale_tier_validation: Add subtypes to allow subscriptions by crm.team
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/models/sale_order.py
Labels: approved, bot is merging ⏳

#2128 [15.0][MIG] sale_order_line_price_history: Migration to 15.0
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/DESCRIPTION.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
  setup/sale_order_line_price_history/odoo/addons/sale_order_line_price_history
  setup/sale_order_line_price_history/setup.py
Labels: approved, bot is merging ⏳

#2143 [14.0][UPD] Eficent -> ForgeFlow
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  sale_blanket_order/README.rst
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_stock_picking_blocking/README.rst
  sale_stock_picking_blocking/__manifest__.py
  sale_stock_picking_blocking/data/sale_stock_picking_blocking_data.xml
  sale_stock_picking_blocking/models/res_partner.py
  sale_stock_picking_blocking/models/sale_order.py
  sale_stock_picking_blocking/models/sale_stock_picking_blocking_reason.py
  sale_stock_picking_blocking/readme/CONTRIBUTORS.rst
  sale_stock_picking_blocking/security/sale_stock_picking_blocking_security.xml
  sale_stock_picking_blocking/static/description/index.html
  sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py
  sale_stock_picking_blocking/views/res_partner_view.xml
  sale_stock_picking_blocking/views/sale_order_view.xml
  sale_stock_picking_blocking/views/sale_stock_picking_blocking_reason_view.xml
Labels: bot is merging ⏳

#2104 [14.0][MIG] sale_order_line_sequence
  .copier-answers.yml
  .github/workflows/test.yml
  sale_order_line_sequence/README.rst
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/i18n/ca.po
  sale_order_line_sequence/i18n/de.po
  sale_order_line_sequence/i18n/el_GR.po
  sale_order_line_sequence/i18n/es.po
  sale_order_line_sequence/i18n/es_ES.po
  sale_order_line_sequence/i18n/es_VE.po
  sale_order_line_sequence/i18n/fi.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_line_sequence/i18n/hr.po
  sale_order_line_sequence/i18n/hr_HR.po
  sale_order_line_sequence/i18n/hu.po
  sale_order_line_sequence/i18n/it.po
  sale_order_line_sequence/i18n/nl.po
  sale_order_line_sequence/i18n/nl_NL.po
  sale_order_line_sequence/i18n/pt.po
  sale_order_line_sequence/i18n/pt_BR.po
  sale_order_line_sequence/i18n/ro.po
  sale_order_line_sequence/i18n/sale_order_line_sequence.pot
  sale_order_line_sequence/i18n/sk.po
  sale_order_line_sequence/i18n/sl.po
  sale_order_line_sequence/i18n/tr.po
  sale_order_line_sequence/i18n/tr_TR.po
  sale_order_line_sequence/i18n/vi_VN.po
  sale_order_line_sequence/i18n/zh_CN.po
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/__init__.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/readme/CONTRIBUTORS.rst
  sale_order_line_sequence/readme/CREDITS.rst
  sale_order_line_sequence/readme/DESCRIPTION.rst
  sale_order_line_sequence/static/description/icon.png
  sale_order_line_sequence/static/description/index.html
  sale_order_line_sequence/tests/__init__.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
  setup/sale_order_line_sequence/odoo/addons/sale_order_line_sequence
  setup/sale_order_line_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2133 [15.0][MIG] sale_order_product_assortment: Migration to version 15.0
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/__init__.py
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/i18n/ca.po
  sale_order_product_assortment/i18n/es.po
  sale_order_product_assortment/i18n/it.po
  sale_order_product_assortment/i18n/sale_order_product_assortment.pot
  sale_order_product_assortment/models/__init__.py
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/models/sale_order_line.py
  sale_order_product_assortment/readme/CONFIGURE.rst
  sale_order_product_assortment/readme/CONTRIBUTORS.rst
  sale_order_product_assortment/readme/DESCRIPTION.rst
  sale_order_product_assortment/readme/ROADMAP.rst
  sale_order_product_assortment/readme/USAGE.rst
  sale_order_product_assortment/static/description/icon.png
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/__init__.py
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
  sale_order_product_assortment/views/sale_order_view.xml
  setup/sale_order_product_assortment/odoo/addons/sale_order_product_assortment
  setup/sale_order_product_assortment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2098 [15.0][MIG] sales_team_security_sale: Migration to 15.0
  sales_team_security_sale/README.rst
  sales_team_security_sale/__init__.py
  sales_team_security_sale/__manifest__.py
  sales_team_security_sale/i18n/sales_team_security_sale.pot
  sales_team_security_sale/migrations/14.0.2.0.0/pre-migration.py
  sales_team_security_sale/readme/CONFIGURE.rst
  sales_team_security_sale/readme/CONTRIBUTORS.rst
  sales_team_security_sale/readme/DESCRIPTION.rst
  sales_team_security_sale/security/security.xml
  sales_team_security_sale/static/description/icon.png
  sales_team_security_sale/static/description/index.html
  sales_team_security_sale/tests/__init__.py
  sales_team_security_sale/tests/test_sales_team_security_sale.py
  setup/sales_team_security_sale/odoo/addons/sales_team_security_sale
  setup/sales_team_security_sale/setup.py
Labels: bot is merging ⏳

#2136 [14.0] [MIG] sale_order_price_recalculation
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/en.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2052 [15.0][MIG] sale_order_product_recommendation: Migration to 15.0
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/pt_BR.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/models/sale_order.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/readme/DESCRIPTION.rst
  sale_order_product_recommendation/readme/USAGE.rst
  sale_order_product_recommendation/security/ir.model.access.csv
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  setup/sale_order_product_recommendation/odoo/addons/sale_order_product_recommendation
  setup/sale_order_product_recommendation/setup.py
Labels: bot is merging ⏳

#2148 [14.0][FIX] sale_order_invoicing_finished_task: Incorrect inheritance chain
  sale_order_invoicing_finished_task/views/product_view.xml
Labels: approved, bot is merging ⏳
