Repository OCA/sale-workflow, pull requests merged in 2022-02, with the labels that each got.

#1763 [MIG] sale_resource_booking: Migration to 13.0
  oca_dependencies.txt
  requirements.txt
  sale_resource_booking/README.rst
  sale_resource_booking/__init__.py
  sale_resource_booking/__manifest__.py
  sale_resource_booking/i18n/es.po
  sale_resource_booking/i18n/fr.po
  sale_resource_booking/i18n/fr_CH.po
  sale_resource_booking/i18n/sale_resource_booking.pot
  sale_resource_booking/models/__init__.py
  sale_resource_booking/models/product_template.py
  sale_resource_booking/models/resource_booking.py
  sale_resource_booking/models/resource_booking_type.py
  sale_resource_booking/models/sale_order.py
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/readme/CONFIGURE.rst
  sale_resource_booking/readme/CONTRIBUTORS.rst
  sale_resource_booking/readme/DESCRIPTION.rst
  sale_resource_booking/readme/INSTALL.rst
  sale_resource_booking/readme/USAGE.rst
  sale_resource_booking/static/description/icon.png
  sale_resource_booking/static/description/index.html
  sale_resource_booking/tests/__init__.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/views/product_template_views.xml
  sale_resource_booking/views/resource_booking_type_views.xml
  sale_resource_booking/views/resource_booking_views.xml
  sale_resource_booking/views/sale_order_views.xml
  sale_resource_booking/wizards/__init__.py
  sale_resource_booking/wizards/resource_booking_sale.py
  sale_resource_booking/wizards/resource_booking_sale_views.xml
  sale_resource_booking/wizards/sale_order_booking_confirm.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
  setup/sale_resource_booking/odoo/addons/sale_resource_booking
  setup/sale_resource_booking/setup.py
Labels: needs review, migration, bot is merging ⏳

#1865 [14.0][MIG] sale_blanket_order
  sale_blanket_order/README.rst
  sale_blanket_order/__init__.py
  sale_blanket_order/__manifest__.py
  sale_blanket_order/data/ir_cron.xml
  sale_blanket_order/data/sequence.xml
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/pt.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/DESCRIPTION.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/report/report.xml
  sale_blanket_order/report/templates.xml
  sale_blanket_order/security/ir.model.access.csv
  sale_blanket_order/security/security.xml
  sale_blanket_order/static/description/BO_actions.png
  sale_blanket_order/static/description/BO_form.png
  sale_blanket_order/static/description/BO_lines.png
  sale_blanket_order/static/description/BO_menu.png
  sale_blanket_order/static/description/PO_BOLine.png
  sale_blanket_order/static/description/PO_from_BO.png
  sale_blanket_order/static/description/icon.png
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/__init__.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/views/sale_order_views.xml
  sale_blanket_order/wizard/__init__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order/wizard/create_sale_orders.xml
  setup/sale_blanket_order/odoo/addons/sale_blanket_order
  setup/sale_blanket_order/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#849 [9.0] backport sale_discount_display_amount from 10.0
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__init__.py
  sale_discount_display_amount/__openerp__.py
  sale_discount_display_amount/hooks.py
  sale_discount_display_amount/i18n/es.po
  sale_discount_display_amount/i18n/es_ES.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/sale_discount_display_amount.pot
  sale_discount_display_amount/models/__init__.py
  sale_discount_display_amount/models/sale_order.py
  sale_discount_display_amount/models/sale_order_line.py
  sale_discount_display_amount/readme/CONFIGURE.rst
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/readme/DESCRIPTION.rst
  sale_discount_display_amount/readme/USAGE.rst
  sale_discount_display_amount/static/description/icon.png
  sale_discount_display_amount/static/description/index.html
  sale_discount_display_amount/tests/__init__.py
  sale_discount_display_amount/tests/test_discount_display_amount.py
  sale_discount_display_amount/views/sale_view.xml
  setup/sale_discount_display_amount/.eggs/README.txt
  setup/sale_discount_display_amount/odoo_addons/__init__.py
  setup/sale_discount_display_amount/odoo_addons/sale_discount_display_amount
  setup/sale_discount_display_amount/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#850 [9.0] backport sale_shipping_info_helper from 10.0
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__openerp__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
  setup/sale_shipping_info_helper/.eggs/README.txt
  setup/sale_shipping_info_helper/odoo_addons/__init__.py
  setup/sale_shipping_info_helper/odoo_addons/sale_shipping_info_helper
  setup/sale_shipping_info_helper/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1837 [14.0][MIG] sale_order_line_input: Migration to 14.0
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/readme/CONTRIBUTORS.rst
  sale_order_line_input/readme/DESCRIPTION.rst
  sale_order_line_input/readme/USAGE.rst
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
  setup/sale_order_line_input/odoo/addons/sale_order_line_input
  setup/sale_order_line_input/setup.py
Labels: bot is merging ⏳

#1781 [14.0][MIG] sale_order_line_delivery_state: migration from v13 to v14
  sale_order_line_delivery_state/README.rst
  sale_order_line_delivery_state/__init__.py
  sale_order_line_delivery_state/__manifest__.py
  sale_order_line_delivery_state/i18n/sale_order_line_delivery_state.pot
  sale_order_line_delivery_state/models/__init__.py
  sale_order_line_delivery_state/models/sale_order_line.py
  sale_order_line_delivery_state/readme/CONTRIBUTORS.rst
  sale_order_line_delivery_state/readme/DESCRIPTION.rst
  sale_order_line_delivery_state/static/description/icon.png
  sale_order_line_delivery_state/static/description/index.html
  sale_order_line_delivery_state/tests/__init__.py
  sale_order_line_delivery_state/tests/test_sale_line_delivery_state.py
  sale_order_line_delivery_state/views/sale_order_views.xml
  setup/sale_order_line_delivery_state/odoo/addons/sale_order_line_delivery_state
  setup/sale_order_line_delivery_state/setup.py
Labels: approved, bot is merging ⏳

#1856 [13.0][FIX] sale_order_invoicing_finished_task: Wrong value task_new_project...
  sale_order_invoicing_finished_task/models/sale_order.py
  sale_order_invoicing_finished_task/views/product_view.xml
Labels: approved, bot is merging ⏳

#1689 [14.0] [mig] sale_procurement_group_by_line
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_line/readme/DESCRIPTION.rst
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/static/description/index.html
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
  setup/sale_procurement_group_by_line/odoo/addons/sale_procurement_group_by_line
  setup/sale_procurement_group_by_line/setup.py
Labels: migration, bot is merging ⏳

#1898 [14.0][IMP] sale_order_revision: Add tests
  sale_order_revision/tests/__init__.py
  sale_order_revision/tests/test_sale_order_revision.py
  test-requirements.txt
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1832 [15.0][MIG] sale_order_invoice_amount
  sale_order_invoice_amount/README.rst
  sale_order_invoice_amount/__init__.py
  sale_order_invoice_amount/__manifest__.py
  sale_order_invoice_amount/i18n/sale_order_invoice_amount.pot
  sale_order_invoice_amount/models/__init__.py
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/readme/CONTRIBUTORS.rst
  sale_order_invoice_amount/readme/DESCRIPTION.rst
  sale_order_invoice_amount/static/description/icon.png
  sale_order_invoice_amount/static/description/index.html
  sale_order_invoice_amount/static/src/xml/tax_totals.xml
  sale_order_invoice_amount/tests/__init__.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
  sale_order_invoice_amount/views/sale_order_view.xml
  setup/sale_order_invoice_amount/odoo/addons/sale_order_invoice_amount
  setup/sale_order_invoice_amount/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1687 14.0 mig sale_delivery_split_date
  sale_delivery_split_date/README.rst
  sale_delivery_split_date/__init__.py
  sale_delivery_split_date/__manifest__.py
  sale_delivery_split_date/i18n/ca.po
  sale_delivery_split_date/i18n/es.po
  sale_delivery_split_date/i18n/it.po
  sale_delivery_split_date/i18n/pt_PT.po
  sale_delivery_split_date/i18n/sale_delivery_split_date.pot
  sale_delivery_split_date/models/__init__.py
  sale_delivery_split_date/models/sale_order.py
  sale_delivery_split_date/models/sale_order_line.py
  sale_delivery_split_date/readme/CONTRIBUTORS.rst
  sale_delivery_split_date/readme/DESCRIPTION.rst
  sale_delivery_split_date/readme/ROADMAP.rst
  sale_delivery_split_date/static/description/icon.png
  sale_delivery_split_date/static/description/index.html
  sale_delivery_split_date/tests/__init__.py
  sale_delivery_split_date/tests/test_sale_delivery.py
  sale_delivery_split_date/views/stock_picking.xml
  setup/sale_delivery_split_date/odoo/addons/sale_delivery_split_date
  setup/sale_delivery_split_date/setup.py
Labels: needs fixing, needs review, approved, migration, ready to merge, bot is merging ⏳

#1893 [15.0][FIX] sale_order_line_date: Refactor code
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/readme/CONTRIBUTORS.rst
  sale_order_line_date/readme/DESCRIPTION.rst
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1825 [ADD] sale_order_line_discount_validation
  .pre-commit-config.yaml
  sale_order_line_discount_validation/README.rst
  sale_order_line_discount_validation/__init__.py
  sale_order_line_discount_validation/__manifest__.py
  sale_order_line_discount_validation/data/mail_template.xml
  sale_order_line_discount_validation/i18n/es.po
  sale_order_line_discount_validation/i18n/sale_order_line_discount_validation.pot
  sale_order_line_discount_validation/models/__init__.py
  sale_order_line_discount_validation/models/res_company.py
  sale_order_line_discount_validation/models/res_config_settings.py
  sale_order_line_discount_validation/models/sale_order.py
  sale_order_line_discount_validation/readme/CONFIGURE.rst
  sale_order_line_discount_validation/readme/CONTRIBUTORS.rst
  sale_order_line_discount_validation/readme/DESCRIPTION.rst
  sale_order_line_discount_validation/readme/USAGE.rst
  sale_order_line_discount_validation/report/__init__.py
  sale_order_line_discount_validation/report/sale_report.py
  sale_order_line_discount_validation/static/description/icon.png
  sale_order_line_discount_validation/static/description/index.html
  sale_order_line_discount_validation/views/res_config_settings_views.xml
  sale_order_line_discount_validation/views/sale_order.xml
  setup/sale_order_line_discount_validation/odoo/addons/sale_order_line_discount_validation
  setup/sale_order_line_discount_validation/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#864 [9.0] [MIG] Backport of Sale Order General Discount (from 12.0)
  .gitignore
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__openerp__.py
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/sale_order_general_discount/odoo_addons/__init__.py
  setup/sale_order_general_discount/odoo_addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: bot is merging ⏳

#1915 [13.0][IMP] sale_order_type: Add quotation validity date field
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_order_type/models/sale.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/views/sale_order_type_view.xml
Labels: approved, bot is merging ⏳

#1920 [14.0][IMP] sale_order_type: Commits from v13
  sale_order_line_discount_validation/models/sale_order.py
  sale_order_type/README.rst
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/models/sale.py
  sale_order_type/models/sale_order_type.py
  sale_order_type/readme/CONTRIBUTORS.rst
  sale_order_type/static/description/index.html
  sale_order_type/tests/test_sale_order_type.py
  sale_order_type/views/sale_order_type_view.xml
Labels: approved, bot is merging ⏳

#1878 [14.0][FIX] sale_advance_payment: Fix residual amount not being zero on fully invoice
  sale_advance_payment/models/sale.py
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1824 [14.0] [MIG] sale_order_invoice_amount
  sale_order_invoice_amount/README.rst
  sale_order_invoice_amount/__init__.py
  sale_order_invoice_amount/__manifest__.py
  sale_order_invoice_amount/i18n/sale_order_invoice_amount.pot
  sale_order_invoice_amount/models/__init__.py
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/readme/CONTRIBUTORS.rst
  sale_order_invoice_amount/readme/DESCRIPTION.rst
  sale_order_invoice_amount/static/description/icon.png
  sale_order_invoice_amount/static/description/index.html
  sale_order_invoice_amount/tests/__init__.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
  sale_order_invoice_amount/views/sale_order_view.xml
  setup/sale_order_invoice_amount/odoo/addons/sale_order_invoice_amount
  setup/sale_order_invoice_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1879 [15.0] [MIG] sale_advance_payment
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1835 [15.0][MIG] sale_tier_validation
  sale_tier_validation/README.rst
  sale_tier_validation/__init__.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/__init__.py
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/models/tier_definition.py
  sale_tier_validation/readme/CONFIGURE.rst
  sale_tier_validation/readme/CONTRIBUTORS.rst
  sale_tier_validation/readme/DESCRIPTION.rst
  sale_tier_validation/readme/INSTALL.rst
  sale_tier_validation/readme/USAGE.rst
  sale_tier_validation/static/description/icon.png
  sale_tier_validation/static/description/index.html
  sale_tier_validation/tests/__init__.py
  sale_tier_validation/tests/test_tier_validation.py
  sale_tier_validation/views/sale_order_view.xml
  setup/sale_tier_validation/odoo/addons/sale_tier_validation
  setup/sale_tier_validation/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1896 [IMP][PERF] sale_coupon_multi_currency
  sale_coupon_multi_currency/models/sale_coupon_program.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1783 [14.0][MIG] sale_order_priority: Migration to v14.0
  sale_order_priority/README.rst
  sale_order_priority/__init__.py
  sale_order_priority/__manifest__.py
  sale_order_priority/i18n/it.po
  sale_order_priority/i18n/sale_order_priority.pot
  sale_order_priority/migrations/14.0.1.0.0/post-migration.py
  sale_order_priority/migrations/14.0.1.0.0/pre-migration.py
  sale_order_priority/models/__init__.py
  sale_order_priority/models/sale.py
  sale_order_priority/models/stock_picking.py
  sale_order_priority/readme/CONTRIBUTORS.rst
  sale_order_priority/readme/DESCRIPTION.rst
  sale_order_priority/static/description/icon.png
  sale_order_priority/static/description/index.html
  sale_order_priority/tests/__init__.py
  sale_order_priority/tests/test_sale_stock.py
  sale_order_priority/views/sale.xml
  setup/sale_order_priority/odoo/addons/sale_order_priority
  setup/sale_order_priority/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1904 [13.0][IMP] change development_status
  sale_by_packaging/__manifest__.py
  sale_order_line_packaging_qty/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#1881 [15.0][MIG] sale_invoice_plan: Migrate to version 15.0
  sale_invoice_plan/README.rst
  sale_invoice_plan/__init__.py
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/i18n/es.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/__init__.py
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/readme/CONTRIBUTORS.rst
  sale_invoice_plan/readme/CREDITS.rst
  sale_invoice_plan/readme/DESCRIPTION.rst
  sale_invoice_plan/readme/HISTORY.rst
  sale_invoice_plan/readme/INSTALL.rst
  sale_invoice_plan/readme/USAGE.rst
  sale_invoice_plan/security/ir.model.access.csv
  sale_invoice_plan/static/description/icon.png
  sale_invoice_plan/static/description/index.html
  sale_invoice_plan/tests/__init__.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/__init__.py
  sale_invoice_plan/wizard/sale_create_invoice_plan.py
  sale_invoice_plan/wizard/sale_create_invoice_plan_view.xml
  sale_invoice_plan/wizard/sale_make_invoice_advance.py
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
  sale_invoice_plan/wizard/sale_make_planned_invoice_view.xml
  setup/sale_invoice_plan/odoo/addons/sale_invoice_plan
  setup/sale_invoice_plan/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1784 [14.0][IMP] sale_by_packaging: Add min_sellable_qty on product
  sale_by_packaging/__manifest__.py
  sale_by_packaging/models/product_product.py
  sale_by_packaging/models/product_template.py
  sale_by_packaging/tests/__init__.py
  sale_by_packaging/tests/test_minimum_sellable_qty.py
  sale_by_packaging/views/product_product.xml
  sale_by_packaging/views/product_template.xml
Labels: needs review, approved, bot is merging ⏳

#1895 [14.0] fix sale_stock_picking_blocking: partner_commercial_id field
  sale_stock_picking_blocking/models/sale_order.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1902 [14.0][FIX] sale_order_line_date: Fix for same behaviour as v13
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1900 [15.0][MIG] sale_product_multi_add
  sale_product_multi_add/README.rst
  sale_product_multi_add/__init__.py
  sale_product_multi_add/__manifest__.py
  sale_product_multi_add/i18n/ca.po
  sale_product_multi_add/i18n/de.po
  sale_product_multi_add/i18n/es.po
  sale_product_multi_add/i18n/fr_FR.po
  sale_product_multi_add/i18n/sale_product_multi_add.pot
  sale_product_multi_add/i18n/zh_CN.po
  sale_product_multi_add/readme/CONTRIBUTORS.rst
  sale_product_multi_add/readme/DESCRIPTION.rst
  sale_product_multi_add/readme/USAGE.rst
  sale_product_multi_add/security/ir.model.access.csv
  sale_product_multi_add/static/description/icon.png
  sale_product_multi_add/static/description/index.html
  sale_product_multi_add/static/description/sale_product_multi_add.png
  sale_product_multi_add/tests/__init__.py
  sale_product_multi_add/tests/test_sale.py
  sale_product_multi_add/views/sale_view.xml
  sale_product_multi_add/wizards/__init__.py
  sale_product_multi_add/wizards/sale_import_products.py
  sale_product_multi_add/wizards/sale_import_products_view.xml
  setup/sale_product_multi_add/odoo/addons/sale_product_multi_add
  setup/sale_product_multi_add/setup.py
Labels: needs review, approved, bot is merging ⏳

#1928 [FIX] sale_automatic_workflow: active model context
  sale_automatic_workflow/models/automatic_workflow_job.py
Labels: needs review, approved, bot is merging ⏳

#1926 [13.0][FIX] sale_order_invoicing_finished_task: Leaky display button because boolean_button widget was removed
  sale_order_invoicing_finished_task/views/project_view.xml
Labels: needs review, bot is merging ⏳

#1905 [14.0][PORT] sale_delivery_date: Fix report expected delivery date in the past
  sale_delivery_date/models/stock_picking.py
  sale_delivery_date/reports/stock_picking.xml
  sale_delivery_date/tests/__init__.py
  sale_delivery_date/tests/test_delivery_date_in_the_past.py
Labels: approved, ready to merge, bot is merging ⏳

#1929 [15.0] [MIG] sale_procurement_group_by_line
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_line/readme/DESCRIPTION.rst
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/static/description/index.html
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
  setup/sale_procurement_group_by_line/odoo/addons/sale_procurement_group_by_line
  setup/sale_procurement_group_by_line/setup.py
Labels: approved, bot is merging ⏳

#1897 [14.0][MIG] sale_order_mass_action
  sale_order_mass_action/README.rst
  sale_order_mass_action/__init__.py
  sale_order_mass_action/__manifest__.py
  sale_order_mass_action/i18n/fr.po
  sale_order_mass_action/i18n/sale_order_mass_action.pot
  sale_order_mass_action/readme/CONTRIBUTORS.rst
  sale_order_mass_action/readme/DESCRIPTION.rst
  sale_order_mass_action/readme/ROADMAP.rst
  sale_order_mass_action/readme/USAGE.rst
  sale_order_mass_action/security/security.xml
  sale_order_mass_action/static/description/index.html
  sale_order_mass_action/tests/__init__.py
  sale_order_mass_action/tests/test_sale_order_mass_action.py
  sale_order_mass_action/wizards/__init__.py
  sale_order_mass_action/wizards/sale_order_mass_action_view.xml
  sale_order_mass_action/wizards/sale_order_mass_action_wizard.py
  setup/sale_order_mass_action/odoo/addons/sale_order_mass_action
  setup/sale_order_mass_action/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1911 [14.0][IMP] sale_order_revision: Set state=cancel in _prepare_revision_data() function.
  sale_order_revision/models/sale_order.py
  sale_order_revision/view/sale_order.xml
Labels: approved, bot is merging ⏳

#1833 [14.0][MIG] sale_stock_delivery_address
  sale_stock_delivery_address/README.rst
  sale_stock_delivery_address/__init__.py
  sale_stock_delivery_address/__manifest__.py
  sale_stock_delivery_address/i18n/ca.po
  sale_stock_delivery_address/i18n/es.po
  sale_stock_delivery_address/i18n/sale_stock_delivery_address.pot
  sale_stock_delivery_address/models/__init__.py
  sale_stock_delivery_address/models/procurement_group.py
  sale_stock_delivery_address/models/sale_order.py
  sale_stock_delivery_address/models/sale_order_line.py
  sale_stock_delivery_address/readme/CONTRIBUTORS.rst
  sale_stock_delivery_address/readme/DESCRIPTION.rst
  sale_stock_delivery_address/readme/USAGE.rst
  sale_stock_delivery_address/static/description/icon.png
  sale_stock_delivery_address/static/description/index.html
  sale_stock_delivery_address/tests/__init__.py
  sale_stock_delivery_address/tests/test_sale_stock_delivery_address.py
  sale_stock_delivery_address/views/res_partner_view.xml
  sale_stock_delivery_address/views/sale_order_view.xml
  setup/sale_stock_delivery_address/odoo/addons/sale_stock_delivery_address
  setup/sale_stock_delivery_address/setup.py
Labels: needs fixing, approved, migration, bot is merging ⏳
