Repository OCA/sale-workflow, pull requests merged in 2023-09, with the labels that each got.

#2681 [16.0][FIX] sale_invoice_frequency: name translatable
  sale_invoice_frequency/i18n/es.po
  sale_invoice_frequency/i18n/sale_invoice_frequency.pot
  sale_invoice_frequency/models/sale_invoice_frequency.py
  sale_invoice_frequency/views/sale_invoice_frequency_view.xml
Labels: bot is merging ⏳

#2644 [14.0] sale_exception_product_sale_manufactured_for: adapt to variant
  sale_exception_product_sale_manufactured_for/models/sale_order.py
  sale_exception_product_sale_manufactured_for/tests/test_sale_exception.py
Labels: bot is merging ⏳

#2686 [16.0] Convert `sale_tier_validation` and `sale_order_line_menu` readme fragments to markdown
  sale_order_line_menu/README.rst
  sale_order_line_menu/readme/CONTRIBUTORS.md
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.md
  sale_order_line_menu/readme/USAGE.md
  sale_order_line_menu/readme/USAGE.rst
  sale_order_line_menu/static/description/index.html
  sale_tier_validation/README.rst
  sale_tier_validation/readme/CONFIGURE.md
  sale_tier_validation/readme/CONFIGURE.rst
  sale_tier_validation/readme/CONTRIBUTORS.md
  sale_tier_validation/readme/CONTRIBUTORS.rst
  sale_tier_validation/readme/DESCRIPTION.md
  sale_tier_validation/readme/INSTALL.md
  sale_tier_validation/readme/INSTALL.rst
  sale_tier_validation/readme/ROADMAP.md
  sale_tier_validation/readme/ROADMAP.rst
  sale_tier_validation/readme/USAGE.md
  sale_tier_validation/readme/USAGE.rst
  sale_tier_validation/static/description/index.html
Labels: bot is merging ⏳

#2673 [14.0] [IMP] sale_discount_display_amount: add total without discount in report
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/models/__init__.py
  sale_discount_display_amount/models/res_company.py
  sale_discount_display_amount/models/res_config_settings.py
  sale_discount_display_amount/readme/CONFIGURE.rst
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/report/sale_report_template.xml
  sale_discount_display_amount/static/description/index.html
  sale_discount_display_amount/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2660 [14.0][ADD]sale_order_general_discount_payment_term: Add sale order general discount on payment term
  sale_order_general_discount_payment_term/README.rst
  sale_order_general_discount_payment_term/__init__.py
  sale_order_general_discount_payment_term/__manifest__.py
  sale_order_general_discount_payment_term/models/__init__.py
  sale_order_general_discount_payment_term/models/account_payment_term.py
  sale_order_general_discount_payment_term/models/sale_order.py
  sale_order_general_discount_payment_term/readme/CONTRIBUTORS.rst
  sale_order_general_discount_payment_term/readme/DESCRIPTION.rst
  sale_order_general_discount_payment_term/readme/USAGE.rst
  sale_order_general_discount_payment_term/static/description/icon.png
  sale_order_general_discount_payment_term/static/description/index.html
  sale_order_general_discount_payment_term/tests/__init__.py
  sale_order_general_discount_payment_term/tests/test_payment_term_discount.py
  sale_order_general_discount_payment_term/views/account_payment_term_view.xml
  setup/sale_order_general_discount_payment_term/odoo/addons/sale_order_general_discount_payment_term
  setup/sale_order_general_discount_payment_term/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2392 [16.0][IMP] sale_order_general_discount_triple
  .pre-commit-config.yaml
  sale_order_general_discount_triple/README.rst
  sale_order_general_discount_triple/__manifest__.py
  sale_order_general_discount_triple/models/res_config_settings.py
  sale_order_general_discount_triple/models/sale_order.py
  sale_order_general_discount_triple/models/sale_order_line.py
  sale_order_general_discount_triple/readme/USAGE.rst
  sale_order_general_discount_triple/static/description/index.html
  sale_order_general_discount_triple/tests/test_module.py
  sale_order_general_discount_triple/views/res_config_settings.xml
  setup/sale_order_general_discount_triple/odoo/addons/sale_order_general_discount_triple
  setup/sale_order_general_discount_triple/setup.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2684 [16.0][MIG] sale_order_line_delivery_state: Migration to 16.0
  sale_order_line_delivery_state/README.rst
  sale_order_line_delivery_state/__init__.py
  sale_order_line_delivery_state/__manifest__.py
  sale_order_line_delivery_state/i18n/sale_order_line_delivery_state.pot
  sale_order_line_delivery_state/models/__init__.py
  sale_order_line_delivery_state/models/sale_order_line.py
  sale_order_line_delivery_state/readme/CONTRIBUTORS.rst
  sale_order_line_delivery_state/readme/DESCRIPTION.rst
  sale_order_line_delivery_state/static/description/icon.png
  sale_order_line_delivery_state/static/description/index.html
  sale_order_line_delivery_state/tests/__init__.py
  sale_order_line_delivery_state/tests/test_sale_line_delivery_state.py
  sale_order_line_delivery_state/views/sale_order_views.xml
  setup/sale_order_line_delivery_state/odoo/addons/sale_order_line_delivery_state
  setup/sale_order_line_delivery_state/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2513 [16.0][MIG] sale_order_invoicing_finished_task: Migration to version 16.0
  sale_order_invoicing_finished_task/README.rst
  sale_order_invoicing_finished_task/__init__.py
  sale_order_invoicing_finished_task/__manifest__.py
  sale_order_invoicing_finished_task/i18n/ca.po
  sale_order_invoicing_finished_task/i18n/de.po
  sale_order_invoicing_finished_task/i18n/el_GR.po
  sale_order_invoicing_finished_task/i18n/es.po
  sale_order_invoicing_finished_task/i18n/es_ES.po
  sale_order_invoicing_finished_task/i18n/es_VE.po
  sale_order_invoicing_finished_task/i18n/fi.po
  sale_order_invoicing_finished_task/i18n/fr.po
  sale_order_invoicing_finished_task/i18n/hr.po
  sale_order_invoicing_finished_task/i18n/hr_HR.po
  sale_order_invoicing_finished_task/i18n/hu.po
  sale_order_invoicing_finished_task/i18n/it.po
  sale_order_invoicing_finished_task/i18n/nl.po
  sale_order_invoicing_finished_task/i18n/nl_NL.po
  sale_order_invoicing_finished_task/i18n/pt.po
  sale_order_invoicing_finished_task/i18n/pt_BR.po
  sale_order_invoicing_finished_task/i18n/ro.po
  sale_order_invoicing_finished_task/i18n/sale_order_invoicing_finished_task.pot
  sale_order_invoicing_finished_task/i18n/sk.po
  sale_order_invoicing_finished_task/i18n/sl.po
  sale_order_invoicing_finished_task/i18n/tr.po
  sale_order_invoicing_finished_task/i18n/tr_TR.po
  sale_order_invoicing_finished_task/i18n/vi_VN.po
  sale_order_invoicing_finished_task/i18n/zh_CN.po
  sale_order_invoicing_finished_task/models/__init__.py
  sale_order_invoicing_finished_task/models/product.py
  sale_order_invoicing_finished_task/models/project.py
  sale_order_invoicing_finished_task/models/sale_order.py
  sale_order_invoicing_finished_task/readme/CONTRIBUTORS.rst
  sale_order_invoicing_finished_task/readme/DESCRIPTION.rst
  sale_order_invoicing_finished_task/readme/USAGE.rst
  sale_order_invoicing_finished_task/static/description/icon.png
  sale_order_invoicing_finished_task/static/description/index.html
  sale_order_invoicing_finished_task/static/description/product_view_invoicefinishedtask2.png
  sale_order_invoicing_finished_task/static/description/task_view_invoicefinishedtask2.png
  sale_order_invoicing_finished_task/tests/__init__.py
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
  sale_order_invoicing_finished_task/views/product_view.xml
  sale_order_invoicing_finished_task/views/project_view.xml
  setup/sale_order_invoicing_finished_task/odoo/addons/sale_order_invoicing_finished_task
  setup/sale_order_invoicing_finished_task/setup.py
Labels: bot is merging ⏳

#2625 [14.0] sale_quotation_number: fix company sequence lookup
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/tests/test_sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2701 [15.0][IMP] sale_planner_calendar: Use same method as kanban button to open sale orders
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/static/src/js/sale_planner_calendar_event_sales.js
Labels: approved, bot is merging ⏳
