Repository OCA/sale-workflow, pull requests merged in 2023-10, with the labels that each got.

#2614 [16.0][MIG] sale_fixed_discount: Migration to 16.0
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/es.po
  sale_fixed_discount/i18n/fr.po
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/security/res_groups.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  sale_fixed_discount/views/sale_portal_templates.xml
  setup/sale_fixed_discount/odoo/addons/sale_fixed_discount
  setup/sale_fixed_discount/setup.py
Labels: needs review, migration, bot is merging ⏳

#2704 [16.0] sale_quotation_number: fix company sequence lookup
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/tests/test_sale_order.py
Labels: approved, bot is merging ⏳

#2710 [15.0][FIX] sale_planner_calendar: Remove search method overwrite and set key on domains
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/views/calendar_view.xml
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
Labels: approved, bot is merging ⏳

#2711 [16.0][FIX] sale_commercial_partner: add development_status
  sale_commercial_partner/README.rst
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/static/description/index.html
Labels: approved, bot is merging ⏳

#2716 [15.0]][FIX] sale_stock_return_request: `_for_xml_id()` retrieving action
  sale_stock_return_request/models/stock_return_request.py
Labels: approved, bot is merging ⏳

#2713 [14.0][MIG] sale_stock_return_request
  sale_stock_return_request/README.rst
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/ca.po
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/i18n/fr.po
  sale_stock_return_request/i18n/sale_stock_return_request.pot
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/readme/DESCRIPTION.rst
  sale_stock_return_request/readme/USAGE.rst
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_return_request_views.xml
  setup/sale_stock_return_request/odoo/addons/sale_stock_return_request
  setup/sale_stock_return_request/setup.py
Labels: approved, bot is merging ⏳

#2697 [14.0][ADD] sale_invoice_delivery_state
  sale_invoice_delivery_state/README.rst
  sale_invoice_delivery_state/__init__.py
  sale_invoice_delivery_state/__manifest__.py
  sale_invoice_delivery_state/i18n/fr.po
  sale_invoice_delivery_state/models/__init__.py
  sale_invoice_delivery_state/models/partner.py
  sale_invoice_delivery_state/models/sale.py
  sale_invoice_delivery_state/readme/CONTRIBUTORS.rst
  sale_invoice_delivery_state/readme/DESCRIPTION.rst
  sale_invoice_delivery_state/static/description/icon.png
  sale_invoice_delivery_state/static/description/index.html
  sale_invoice_delivery_state/tests/__init__.py
  sale_invoice_delivery_state/tests/test_sale_invoice_delivery_state.py
  sale_invoice_delivery_state/views/partner.xml
  setup/sale_invoice_delivery_state/odoo/addons/sale_invoice_delivery_state
  setup/sale_invoice_delivery_state/setup.py
Labels: bot is merging ⏳

#2723 [ADD] sale_order_product_recommendation_packaging_default: glue module
  sale_order_product_recommendation_packaging_default/README.rst
  sale_order_product_recommendation_packaging_default/__init__.py
  sale_order_product_recommendation_packaging_default/__manifest__.py
  sale_order_product_recommendation_packaging_default/i18n/es.po
  sale_order_product_recommendation_packaging_default/i18n/sale_order_product_recommendation_packaging_default.pot
  sale_order_product_recommendation_packaging_default/readme/CONFIGURE.md
  sale_order_product_recommendation_packaging_default/readme/CONTRIBUTORS.md
  sale_order_product_recommendation_packaging_default/readme/DESCRIPTION.md
  sale_order_product_recommendation_packaging_default/readme/INSTALL.md
  sale_order_product_recommendation_packaging_default/readme/USAGE.md
  sale_order_product_recommendation_packaging_default/static/description/icon.png
  sale_order_product_recommendation_packaging_default/static/description/index.html
  sale_order_product_recommendation_packaging_default/tests/__init__.py
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/__init__.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation_view.xml
  setup/sale_order_product_recommendation_packaging_default/odoo/addons/sale_order_product_recommendation_packaging_default
  setup/sale_order_product_recommendation_packaging_default/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2718 [14.0] [ADD] sale_order_product_assortment_quick
  sale_order_product_assortment_quick/README.rst
  sale_order_product_assortment_quick/__init__.py
  sale_order_product_assortment_quick/__manifest__.py
  sale_order_product_assortment_quick/models/__init__.py
  sale_order_product_assortment_quick/models/sale_order.py
  sale_order_product_assortment_quick/readme/CONFIGURE.rst
  sale_order_product_assortment_quick/readme/CONTRIBUTORS.rst
  sale_order_product_assortment_quick/readme/DESCRIPTION.rst
  sale_order_product_assortment_quick/readme/USAGE.rst
  sale_order_product_assortment_quick/static/description/index.html
  sale_order_product_assortment_quick/tests/__init__.py
  sale_order_product_assortment_quick/tests/test_sale_order_product_assortment_quick.py
  setup/sale_order_product_assortment_quick/odoo/addons/sale_order_product_assortment_quick
  setup/sale_order_product_assortment_quick/setup.py
Labels: bot is merging ⏳

#2720 [14.0] [IMP] sale_order_product_assortment: Check products on write and create
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/readme/CONTRIBUTORS.rst
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
Labels: approved, ready to merge, bot is merging ⏳

#2726 [14.0] [FIX] sale_discount_display_amount: switch field positions
  sale_discount_display_amount/report/sale_report_template.xml
Labels: approved, bot is merging ⏳

#2699 [16.0][MIG] sale_payment_sheet: Migration to version 16.0
  sale_payment_sheet/README.rst
  sale_payment_sheet/__init__.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/models/__init__.py
  sale_payment_sheet/models/res_users.py
  sale_payment_sheet/models/sale_payment_sheet.py
  sale_payment_sheet/readme/CONFIGURE.rst
  sale_payment_sheet/readme/CONTRIBUTORS.rst
  sale_payment_sheet/readme/DESCRIPTION.rst
  sale_payment_sheet/readme/USAGE.rst
  sale_payment_sheet/report/report_sale_payment_sheet_summary.xml
  sale_payment_sheet/report/sale_payment_sheet_report.xml
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/security/security.xml
  sale_payment_sheet/static/description/icon.png
  sale_payment_sheet/static/description/index.html
  sale_payment_sheet/tests/__init__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_payment_sheet/views/res_users_views.xml
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
  sale_payment_sheet/views/sale_payment_sheet_views.xml
  sale_payment_sheet/wizards/__init__.py
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
  setup/sale_payment_sheet/odoo/addons/sale_payment_sheet
  setup/sale_payment_sheet/setup.py
Labels: needs review, approved, bot is merging ⏳

#2719 [15.0][IMP]sale_quotation_number: Boolean to determine whether quotation sequence has been used
  sale_quotation_number/__manifest__.py
  sale_quotation_number/migrations/15.0.1.0.2/post-migration.py
  sale_quotation_number/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2729 [15.0][IMP] sale_order_type: Add type field in search view
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#2731 [16.0][IMP] sale_order_type: Add type field in search view
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#2734 [14.0][IMP] sale_order_type: Add type field in search view
  sale_order_type/i18n/es.po
  sale_order_type/i18n/sale_order_type.pot
  sale_order_type/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#2740 [15.0][FIX] sale_order_type: Route is missed when partner/sale_type is changed
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#2727 [13.0][ADD] sale_order_line_remove: allows the removal of sale order lines
  sale_order_line_remove/__init__.py
  sale_order_line_remove/__manifest__.py
  sale_order_line_remove/models/__init__.py
  sale_order_line_remove/models/sale_order.py
  sale_order_line_remove/readme/CONTRIBUTORS.rst
  sale_order_line_remove/readme/DESCRIPTION.rst
  sale_order_line_remove/readme/USAGE.rst
  sale_order_line_remove/tests/__init__.py
  sale_order_line_remove/tests/test_sale_order_line.py
  setup/sale_order_line_remove/odoo/addons/sale_order_line_remove
  setup/sale_order_line_remove/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2751 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_missing_tracking/i18n/sale_missing_tracking.pot
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_rental/i18n/es.po
  sale_rental/i18n/sale_rental.pot
  sale_rental/models/sale_order.py
Labels: help wanted, needs review, bot is merging ⏳

#2746 [16.0][MIG] portal_sale_personal_data_only: Migration to version 16.0
  portal_sale_personal_data_only/README.rst
  portal_sale_personal_data_only/__init__.py
  portal_sale_personal_data_only/__manifest__.py
  portal_sale_personal_data_only/hooks.py
  portal_sale_personal_data_only/i18n/de.po
  portal_sale_personal_data_only/i18n/es.po
  portal_sale_personal_data_only/i18n/portal_sale_personal_data_only.pot
  portal_sale_personal_data_only/i18n/zh_CN.po
  portal_sale_personal_data_only/readme/CONTRIBUTORS.rst
  portal_sale_personal_data_only/readme/DESCRIPTION.rst
  portal_sale_personal_data_only/readme/USAGE.rst
  portal_sale_personal_data_only/security/security.xml
  portal_sale_personal_data_only/static/description/icon.png
  portal_sale_personal_data_only/static/description/index.html
  portal_sale_personal_data_only/tests/__init__.py
  portal_sale_personal_data_only/tests/test_partner_access.py
  setup/portal_sale_personal_data_only/odoo/addons/portal_sale_personal_data_only
  setup/portal_sale_personal_data_only/setup.py
Labels: approved, bot is merging ⏳

#2747 [FIX] sale_order_product_recommendation: freezegun hack
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
Labels: needs review, approved, bot is merging ⏳

#2752 [FIX]sale_quotation_number: get_quotation_seq method
  sale_quotation_number/models/sale_order.py
Labels: approved, bot is merging ⏳

#2753 [15.0][MIG]sale_order_warn_message
  sale_order_warn_message/README.rst
  sale_order_warn_message/__init__.py
  sale_order_warn_message/__manifest__.py
  sale_order_warn_message/i18n/it.po
  sale_order_warn_message/i18n/sale_order_warn_message.pot
  sale_order_warn_message/models/__init__.py
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/readme/CONTRIBUTORS.rst
  sale_order_warn_message/readme/DESCRIPTION.rst
  sale_order_warn_message/static/description/icon.png
  sale_order_warn_message/static/description/index.html
  sale_order_warn_message/tests/__init__.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
  sale_order_warn_message/views/sale_order.xml
  setup/sale_order_warn_message/odoo/addons/sale_order_warn_message
  setup/sale_order_warn_message/setup.py
Labels: approved, bot is merging ⏳

#2754 [14.0][IMP] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pricelist_cache/views/product_pricelist_cache.xml
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_cancel_reason/view/sale_view.xml
  sale_default_uom/views/product_template_view.xml
  sale_delivery_state/demo/sale_demo.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_exception/wizard/sale_exception_confirm_view.xml
  sale_fixed_discount/views/sale_portal_templates.xml
  sale_order_general_discount/views/res_config_settings_view.xml
  sale_order_general_discount_triple/views/res_config_settings.xml
  sale_order_report_without_price/report/sale_report.xml
  sale_order_report_without_price/report/sale_report_templates.xml
  sale_product_set/views/product_set.xml
  sale_product_set/views/product_set_line.xml
  sale_product_set/wizard/product_set_add.xml
  sale_product_set_sale_by_packaging/views/product_set_line.xml
  sale_quick/views/product_view.xml
  sale_rental/views/sale_rental.xml
  sale_start_end_dates/i18n/de.po
  sale_start_end_dates/i18n/fr.po
  sale_start_end_dates/i18n/nl_NL.po
  sale_start_end_dates/i18n/sl.po
  sale_stock_picking_blocking/views/sale_stock_picking_blocking_reason_view.xml
  sales_team_security_crm/security/security.xml
  sales_team_security_sale/security/security.xml
Labels: bot is merging ⏳

#2743 [IMP] sale_order_secondary_unit: promote to Stable
  sale_order_secondary_unit/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#2732 [15.0][MIG] sale_order_secondary_unit: Add migration script to adapt secod uom to variants
  sale_order_secondary_unit/migrations/15.0.2.0.0/post-migration.py
Labels: approved, bot is merging ⏳
