Repository OCA/sale-workflow, pull requests merged in 2023-08, with the labels that each got.

#2627 [15.0][IMP] sale_order_line_menu: Added invoice lines in tree view
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: needs review, bot is merging ⏳

#2592 [14.0] [IMP] sale_discount_display_amount: Add untaxed no discount
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/hooks.py
  sale_discount_display_amount/i18n/ca.po
  sale_discount_display_amount/i18n/de.po
  sale_discount_display_amount/i18n/es.po
  sale_discount_display_amount/i18n/es_ES.po
  sale_discount_display_amount/i18n/fr.po
  sale_discount_display_amount/i18n/it.po
  sale_discount_display_amount/i18n/nl.po
  sale_discount_display_amount/i18n/sale_discount_display_amount.pot
  sale_discount_display_amount/i18n/zh_CN.po
  sale_discount_display_amount/migrations/14.0.1.2.0/post-compute-subtotal-columns.py
  sale_discount_display_amount/migrations/14.0.1.2.0/pre-add-subtotal-columns.py
  sale_discount_display_amount/models/sale_order.py
  sale_discount_display_amount/models/sale_order_line.py
  sale_discount_display_amount/tests/test_discount_display_amount.py
  sale_discount_display_amount/views/sale_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2632 [16.0][IMP] sale_order_line_menu: New views and stored fields
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/models/__init__.py
  sale_order_line_menu/models/sale_order_line.py
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.rst
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: needs review, approved, bot is merging ⏳

#2602 [16.0][MIG] sales_team_security: Migration to version 16.0
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/it.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/readme/CONFIGURE.rst
  sales_team_security/readme/CONTRIBUTORS.rst
  sales_team_security/readme/DESCRIPTION.rst
  sales_team_security/readme/INSTALL.rst
  sales_team_security/readme/ROADMAP.rst
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/common.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
  setup/sales_team_security/odoo/addons/sales_team_security
  setup/sales_team_security/setup.py
Labels: needs review, bot is merging ⏳

#2634 [15.0][MIG] sale_global_discount: Migration to 15.0
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/it.po
  sale_global_discount/i18n/pt.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/readme/CONFIGURE.rst
  sale_global_discount/readme/CONTRIBUTORS.rst
  sale_global_discount/readme/DESCRIPTION.rst
  sale_global_discount/readme/ROADMAP.rst
  sale_global_discount/readme/USAGE.rst
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
  setup/sale_global_discount/odoo/addons/sale_global_discount
  setup/sale_global_discount/setup.py
Labels: bot is merging ⏳

#2628 [16.0] [MIG] sale_order_line_sequence: Migration to 16.0
  sale_order_line_sequence/README.rst
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/i18n/ca.po
  sale_order_line_sequence/i18n/de.po
  sale_order_line_sequence/i18n/el_GR.po
  sale_order_line_sequence/i18n/es.po
  sale_order_line_sequence/i18n/es_ES.po
  sale_order_line_sequence/i18n/es_VE.po
  sale_order_line_sequence/i18n/fi.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_line_sequence/i18n/hr.po
  sale_order_line_sequence/i18n/hr_HR.po
  sale_order_line_sequence/i18n/hu.po
  sale_order_line_sequence/i18n/it.po
  sale_order_line_sequence/i18n/nl.po
  sale_order_line_sequence/i18n/nl_NL.po
  sale_order_line_sequence/i18n/pt.po
  sale_order_line_sequence/i18n/pt_BR.po
  sale_order_line_sequence/i18n/ro.po
  sale_order_line_sequence/i18n/sale_order_line_sequence.pot
  sale_order_line_sequence/i18n/sk.po
  sale_order_line_sequence/i18n/sl.po
  sale_order_line_sequence/i18n/tr.po
  sale_order_line_sequence/i18n/tr_TR.po
  sale_order_line_sequence/i18n/vi_VN.po
  sale_order_line_sequence/i18n/zh_CN.po
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/__init__.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/readme/CONTRIBUTORS.rst
  sale_order_line_sequence/readme/CREDITS.rst
  sale_order_line_sequence/readme/DESCRIPTION.rst
  sale_order_line_sequence/static/description/icon.png
  sale_order_line_sequence/static/description/index.html
  sale_order_line_sequence/tests/__init__.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
  setup/sale_order_line_sequence/odoo/addons/sale_order_line_sequence
  setup/sale_order_line_sequence/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2603 [14.0][IMP] sale_order_line_sequence: module refactor, new sequence fields for orders and invoices
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/models/__init__.py
  sale_order_line_sequence/models/account_move_line.py
  sale_order_line_sequence/models/sale_order.py
  sale_order_line_sequence/models/sale_order_line.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/account_move_view.xml
  sale_order_line_sequence/views/report_invoice.xml
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2630 [16.0][MIG] sale_stock_picking_note: Migration to 16.0
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/DESCRIPTION.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/report_deliveryslip.xml
  sale_stock_picking_note/views/sale_order_view.xml
  sale_stock_picking_note/views/stock_picking_view.xml
  setup/sale_stock_picking_note/odoo/addons/sale_stock_picking_note
  setup/sale_stock_picking_note/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2626 [14.0][IMP] sale_blanket_order: add blanket order line form
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#2639 [16.0][IMP-FIX] sale_order_type: Remove onchange_type_id method
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: approved, bot is merging ⏳

#2498 [16.0][FIX]sale_order_type: company_id singleton error
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#2607 [14.0][MIG] sale_stock_line_sequence
  sale_stock_line_sequence/README.rst
  sale_stock_line_sequence/__init__.py
  sale_stock_line_sequence/__manifest__.py
  sale_stock_line_sequence/i18n/sale_stock_line_sequence.pot
  sale_stock_line_sequence/models/__init__.py
  sale_stock_line_sequence/models/sale_order.py
  sale_stock_line_sequence/models/stock_move.py
  sale_stock_line_sequence/readme/CONTRIBUTORS.rst
  sale_stock_line_sequence/readme/DESCRIPTION.rst
  sale_stock_line_sequence/static/description/icon.png
  sale_stock_line_sequence/static/description/index.html
  sale_stock_line_sequence/tests/__init__.py
  sale_stock_line_sequence/tests/test_line_sequence.py
  setup/sale_stock_line_sequence/odoo/addons/sale_stock_line_sequence
  setup/sale_stock_line_sequence/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2659 [15.0][FIX] sale_planner_calendar: Recurrent events not removed when changing the recurrence from the planner
  sale_planner_calendar/models/calendar.py
Labels: approved, bot is merging ⏳

#2657 [ADD] sale_packaging_default: default packaging for sales
  sale_packaging_default/README.rst
  sale_packaging_default/__init__.py
  sale_packaging_default/__manifest__.py
  sale_packaging_default/models/__init__.py
  sale_packaging_default/models/product_packaging.py
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/readme/CONFIGURE.rst
  sale_packaging_default/readme/CONTRIBUTORS.rst
  sale_packaging_default/readme/DESCRIPTION.rst
  sale_packaging_default/readme/USAGE.rst
  sale_packaging_default/static/description/icon.png
  sale_packaging_default/static/description/index.html
  sale_packaging_default/tests/__init__.py
  sale_packaging_default/tests/test_sale_packaging_default.py
  sale_packaging_default/views/product_packaging_view.xml
  sale_packaging_default/views/sale_order_view.xml
  setup/sale_packaging_default/odoo/addons/sale_packaging_default
  setup/sale_packaging_default/setup.py
Labels: needs review, approved, bot is merging ⏳
