Repository OCA/sale-workflow, pull requests merged in 2023-11, with the labels that each got.

#2694 [14.0][IMP] sale_order_line_chained_move: do not merge propagated moves
  sale_order_line_chained_move/README.rst
  sale_order_line_chained_move/__manifest__.py
  sale_order_line_chained_move/models/stock_move.py
  sale_order_line_chained_move/models/stock_rule.py
  sale_order_line_chained_move/readme/CONTRIBUTORS.rst
  sale_order_line_chained_move/readme/DESCRIPTION.rst
  sale_order_line_chained_move/readme/USAGE.rst
  sale_order_line_chained_move/static/description/index.html
  sale_order_line_chained_move/tests/test_chained_move.py
  sale_order_line_chained_move/views/stock_rule_views.xml
Labels: approved, bot is merging ⏳

#2764 [16.0][IMP] sale_invoice_policy: Make it uninstallable
  .pre-commit-config.yaml
  sale_invoice_policy/__manifest__.py
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: bot is merging ⏳

#2730 Hide(optional) discount_fixed
  sale_fixed_discount/views/sale_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2738 [FIX] sale_advance_payment: residual amount
  sale_advance_payment/models/sale.py
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2761 [14.0][MIG] sale_stock_secondary_unit: Migration to 14.0
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/i18n/de.po
  sale_stock_secondary_unit/i18n/es.po
  sale_stock_secondary_unit/i18n/it.po
  sale_stock_secondary_unit/i18n/sale_stock_secondary_unit.pot
  sale_stock_secondary_unit/i18n/zh_CN.po
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/stock_rule.py
  sale_stock_secondary_unit/readme/CONTRIBUTORS.rst
  sale_stock_secondary_unit/readme/DESCRIPTION.rst
  sale_stock_secondary_unit/readme/USAGE.rst
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
  setup/sale_stock_secondary_unit/odoo/addons/sale_stock_secondary_unit
  setup/sale_stock_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#2769 [15.0][FIX] sale_planner_calendar: Add security group to root menu
  sale_planner_calendar/views/sale_planner_calendar_menu.xml
Labels: approved, bot is merging ⏳

#2240 [MIG][15.0] sale_order_product_recommendation_secondary_unit: Migration to v15
  sale_order_product_recommendation_secondary_unit/README.rst
  sale_order_product_recommendation_secondary_unit/__init__.py
  sale_order_product_recommendation_secondary_unit/__manifest__.py
  sale_order_product_recommendation_secondary_unit/i18n/es.po
  sale_order_product_recommendation_secondary_unit/i18n/sale_order_product_recommendation_secondary_unit.pot
  sale_order_product_recommendation_secondary_unit/readme/CONFIGURE.rst
  sale_order_product_recommendation_secondary_unit/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation_secondary_unit/readme/DESCRIPTION.rst
  sale_order_product_recommendation_secondary_unit/readme/USAGE.rst
  sale_order_product_recommendation_secondary_unit/static/description/icon.png
  sale_order_product_recommendation_secondary_unit/static/description/index.html
  sale_order_product_recommendation_secondary_unit/tests/__init__.py
  sale_order_product_recommendation_secondary_unit/tests/test_recommendations.py
  sale_order_product_recommendation_secondary_unit/wizards/__init__.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
  setup/sale_order_product_recommendation_secondary_unit/odoo/addons/sale_order_product_recommendation_secondary_unit
  setup/sale_order_product_recommendation_secondary_unit/setup.py
Labels: needs review, approved, bot is merging ⏳

#2517 [16.0][MIG] - sale_wishlist
  sale_wishlist/README.rst
  sale_wishlist/__init__.py
  sale_wishlist/__manifest__.py
  sale_wishlist/i18n/es.po
  sale_wishlist/i18n/fr_FR.po
  sale_wishlist/i18n/sale_wishlist.pot
  sale_wishlist/models/__init__.py
  sale_wishlist/models/product_set.py
  sale_wishlist/models/res_partner.py
  sale_wishlist/readme/CONTRIBUTORS.rst
  sale_wishlist/readme/CREDITS.rst
  sale_wishlist/readme/DESCRIPTION.rst
  sale_wishlist/readme/USAGE.rst
  sale_wishlist/static/description/icon.png
  sale_wishlist/static/description/index.html
  sale_wishlist/tests/__init__.py
  sale_wishlist/tests/test_wishlist.py
  sale_wishlist/views/partner.xml
  sale_wishlist/views/product_set.xml
  setup/sale_wishlist/odoo/addons/sale_wishlist
  setup/sale_wishlist/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2765 [15.0][IMP] product_supplierinfo_for_customer_sale: Change acls to noupdate
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2745 [ADD]sale_order_type_quotation_number: Set quotation sequences in sale order types
  sale_order_type_quotation_number/README.rst
  sale_order_type_quotation_number/__init__.py
  sale_order_type_quotation_number/__manifest__.py
  sale_order_type_quotation_number/i18n/es.po
  sale_order_type_quotation_number/models/__init__.py
  sale_order_type_quotation_number/models/sale_order.py
  sale_order_type_quotation_number/models/sale_order_type.py
  sale_order_type_quotation_number/readme/CONFIGURE.rst
  sale_order_type_quotation_number/readme/CONTRIBUTORS.rst
  sale_order_type_quotation_number/readme/DESCRIPTION.rst
  sale_order_type_quotation_number/readme/ROADMAP.rst
  sale_order_type_quotation_number/readme/USAGE.rst
  sale_order_type_quotation_number/static/description/icon.png
  sale_order_type_quotation_number/static/description/index.html
  sale_order_type_quotation_number/tests/__init__.py
  sale_order_type_quotation_number/tests/test_sale_order_type_quotation_number.py
  sale_order_type_quotation_number/views/sale_order_type_view.xml
  sale_order_type_quotation_number/views/sale_views.xml
  setup/sale_order_type_quotation_number/odoo/addons/sale_order_type_quotation_number
  setup/sale_order_type_quotation_number/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2636 [15.0][IMP] sale_order_line_sequence: module refactor, new sequence fields for orders and invoices
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/models/__init__.py
  sale_order_line_sequence/models/account_move_line.py
  sale_order_line_sequence/models/sale_order.py
  sale_order_line_sequence/models/sale_order_line.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/account_move_view.xml
  sale_order_line_sequence/views/report_invoice.xml
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
Labels: enhancement, approved, bot is merging ⏳

#2767 [15.0][MIG] sale_order_line_remove
  sale_order_line_remove/README.rst
  sale_order_line_remove/__init__.py
  sale_order_line_remove/__manifest__.py
  sale_order_line_remove/i18n/sale_order_line_remove.pot
  sale_order_line_remove/models/__init__.py
  sale_order_line_remove/models/sale_order.py
  sale_order_line_remove/readme/CONTRIBUTORS.rst
  sale_order_line_remove/readme/DESCRIPTION.rst
  sale_order_line_remove/readme/USAGE.rst
  sale_order_line_remove/static/description/icon.png
  sale_order_line_remove/static/description/index.html
  sale_order_line_remove/tests/__init__.py
  sale_order_line_remove/tests/test_sale_order_line.py
  setup/sale_order_line_remove/odoo/addons/sale_order_line_remove
  setup/sale_order_line_remove/setup.py
Labels: bot is merging ⏳

#2646 [15.0][MIG] sale_stock_line_sequence
  sale_stock_line_sequence/README.rst
  sale_stock_line_sequence/__init__.py
  sale_stock_line_sequence/__manifest__.py
  sale_stock_line_sequence/i18n/sale_stock_line_sequence.pot
  sale_stock_line_sequence/models/__init__.py
  sale_stock_line_sequence/models/sale_order.py
  sale_stock_line_sequence/models/stock_move.py
  sale_stock_line_sequence/readme/CONTRIBUTORS.rst
  sale_stock_line_sequence/readme/DESCRIPTION.rst
  sale_stock_line_sequence/static/description/icon.png
  sale_stock_line_sequence/static/description/index.html
  sale_stock_line_sequence/tests/__init__.py
  sale_stock_line_sequence/tests/test_line_sequence.py
  setup/sale_stock_line_sequence/odoo/addons/sale_stock_line_sequence
  setup/sale_stock_line_sequence/setup.py
Labels: needs review, migration, bot is merging ⏳

#2623 [16.0][MOV] sale_by_packaging becomes sell_only_by_packaging
  sell_only_by_packaging/README.rst
  sell_only_by_packaging/__init__.py
  sell_only_by_packaging/__manifest__.py
  sell_only_by_packaging/i18n/es.po
  sell_only_by_packaging/i18n/sell_only_by_packaging.pot
  sell_only_by_packaging/models/__init__.py
  sell_only_by_packaging/models/product_packaging.py
  sell_only_by_packaging/models/product_packaging_level.py
  sell_only_by_packaging/models/product_product.py
  sell_only_by_packaging/models/product_template.py
  sell_only_by_packaging/models/sale_order_line.py
  sell_only_by_packaging/readme/CONFIGURE.rst
  sell_only_by_packaging/readme/CONTRIBUTORS.rst
  sell_only_by_packaging/readme/CREDITS.rst
  sell_only_by_packaging/readme/DESCRIPTION.rst
  sell_only_by_packaging/static/description/icon.png
  sell_only_by_packaging/static/description/index.html
  sell_only_by_packaging/tests/__init__.py
  sell_only_by_packaging/tests/common.py
  sell_only_by_packaging/tests/test_minimum_sellable_qty.py
  sell_only_by_packaging/tests/test_sale_line_onchanges.py
  sell_only_by_packaging/tests/test_sale_only_by_packaging.py
  sell_only_by_packaging/views/product_packaging.xml
  sell_only_by_packaging/views/product_product.xml
  sell_only_by_packaging/views/product_template.xml
  setup/sell_only_by_packaging/odoo/addons/sell_only_by_packaging
  setup/sell_only_by_packaging/setup.py
Labels: approved, bot is merging ⏳

#2672 [16.0][ADD] sale_exception_holidays_public: new module
  sale_exception_holidays_public/README.rst
  sale_exception_holidays_public/__init__.py
  sale_exception_holidays_public/__manifest__.py
  sale_exception_holidays_public/data/sale_exception_data.xml
  sale_exception_holidays_public/i18n/sale_exception_holidays_public.pot
  sale_exception_holidays_public/models/__init__.py
  sale_exception_holidays_public/models/sale_order.py
  sale_exception_holidays_public/readme/CONFIGURE.rst
  sale_exception_holidays_public/readme/CONTRIBUTORS.rst
  sale_exception_holidays_public/readme/CREDITS.rst
  sale_exception_holidays_public/readme/DESCRIPTION.rst
  sale_exception_holidays_public/readme/USAGE.rst
  sale_exception_holidays_public/static/description/icon.png
  sale_exception_holidays_public/static/description/index.html
  sale_exception_holidays_public/tests/__init__.py
  sale_exception_holidays_public/tests/test_sale_exception.py
  setup/sale_exception_holidays_public/odoo/addons/sale_exception_holidays_public
  setup/sale_exception_holidays_public/setup.py
Labels: approved, bot is merging ⏳

#2692 [ADD] sale_product_packaging_container_deposit
  sale_product_packaging_container_deposit/README.rst
  sale_product_packaging_container_deposit/__init__.py
  sale_product_packaging_container_deposit/__manifest__.py
  sale_product_packaging_container_deposit/models/__init__.py
  sale_product_packaging_container_deposit/models/sale_order.py
  sale_product_packaging_container_deposit/models/sale_order_line.py
  sale_product_packaging_container_deposit/readme/CONTRIBUTORS.rst
  sale_product_packaging_container_deposit/readme/DESCRIPTION.rst
  sale_product_packaging_container_deposit/static/description/index.html
  sale_product_packaging_container_deposit/tests/__init__.py
  sale_product_packaging_container_deposit/tests/test_sale_product_packaging_container_deposit.py
  setup/sale_product_packaging_container_deposit/odoo/addons/sale_product_packaging_container_deposit
  setup/sale_product_packaging_container_deposit/setup.py
Labels: bot is merging ⏳

#2404 [16.0][MIG] sale_delivery_split_date: Migration to 16.0
  sale_delivery_split_date/README.rst
  sale_delivery_split_date/__init__.py
  sale_delivery_split_date/__manifest__.py
  sale_delivery_split_date/i18n/ca.po
  sale_delivery_split_date/i18n/es.po
  sale_delivery_split_date/i18n/it.po
  sale_delivery_split_date/i18n/pt_PT.po
  sale_delivery_split_date/i18n/sale_delivery_split_date.pot
  sale_delivery_split_date/models/__init__.py
  sale_delivery_split_date/models/sale_order_line.py
  sale_delivery_split_date/readme/CONTRIBUTORS.rst
  sale_delivery_split_date/readme/DESCRIPTION.rst
  sale_delivery_split_date/readme/ROADMAP.rst
  sale_delivery_split_date/static/description/icon.png
  sale_delivery_split_date/static/description/index.html
  sale_delivery_split_date/tests/__init__.py
  sale_delivery_split_date/tests/test_sale_delivery.py
  sale_delivery_split_date/views/stock_picking.xml
  setup/sale_delivery_split_date/odoo/addons/sale_delivery_split_date
  setup/sale_delivery_split_date/setup.py
Labels: approved, bot is merging ⏳

#2762 [16.0][ADD] sale_order_product_picker: New module to easy manage sale orders for salesmen
  sale_order_product_picker/README.rst
  sale_order_product_picker/__init__.py
  sale_order_product_picker/__manifest__.py
  sale_order_product_picker/hooks.py
  sale_order_product_picker/i18n/es.po
  sale_order_product_picker/i18n/sale_order_product_picker.pot
  sale_order_product_picker/models/__init__.py
  sale_order_product_picker/models/sale_order.py
  sale_order_product_picker/models/sale_order_picker.py
  sale_order_product_picker/readme/CONFIGURE.rst
  sale_order_product_picker/readme/CONTRIBUTORS.rst
  sale_order_product_picker/readme/DESCRIPTION.rst
  sale_order_product_picker/readme/USAGE.rst
  sale_order_product_picker/security/ir.model.access.csv
  sale_order_product_picker/static/description/icon.png
  sale_order_product_picker/static/description/index.html
  sale_order_product_picker/static/image/picker.gif
  sale_order_product_picker/static/src/kanban/kanban_record.esm.js
  sale_order_product_picker/static/src/scss/picker.scss
  sale_order_product_picker/static/src/x2many/x2many_field.esm.js
  sale_order_product_picker/views/product_views.xml
  sale_order_product_picker/views/sale_order_views.xml
  setup/sale_order_product_picker/odoo/addons/sale_order_product_picker
  setup/sale_order_product_picker/setup.py
Labels: needs review, approved, bot is merging ⏳

#2791 [15.0][IMP] sale_order_line_price_history: Manage price history from wizard
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/views/sale_views.xml
Labels: approved, bot is merging ⏳

#2790 [FIX] sale_packaging_default: reorder SO sub-form view too
  sale_packaging_default/views/sale_order_view.xml
Labels: enhancement, bot is merging ⏳

#2793 [FIX] sale_order_product_picker: store packaging information
  sale_order_product_picker/views/sale_order_views.xml
Labels: bug, approved, bot is merging ⏳

#2792 [FIX] sale_packaging_default: setting product_uom_qty to 0 empties packaging
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/tests/test_sale_packaging_default.py
  sell_only_by_packaging/tests/test_sale_only_by_packaging.py
Labels: bug, bot is merging ⏳

#2798 Revert "[IMP] sale_order_line_price_history: Manage price history from wizard
  README.md
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/views/sale_views.xml
Labels: bot is merging ⏳

#2799 [FIX] sale_order_product_recommendation_packaging_default: can add product without packaging
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation_view.xml
Labels: bug, bot is merging ⏳

#2781 [16.0][IMP] sale_order_line_sequence: module refactor, new sequence fields for orders and invoices
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/models/__init__.py
  sale_order_line_sequence/models/account_move_line.py
  sale_order_line_sequence/models/sale_order.py
  sale_order_line_sequence/models/sale_order_line.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/account_move_view.xml
  sale_order_line_sequence/views/report_invoice.xml
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
Labels: bot is merging ⏳

#2782 [16.0][MIG] sale_stock_line_sequence
  sale_stock_line_sequence/README.rst
  sale_stock_line_sequence/__init__.py
  sale_stock_line_sequence/__manifest__.py
  sale_stock_line_sequence/i18n/sale_stock_line_sequence.pot
  sale_stock_line_sequence/models/__init__.py
  sale_stock_line_sequence/models/sale_order.py
  sale_stock_line_sequence/models/stock_move.py
  sale_stock_line_sequence/readme/CONTRIBUTORS.rst
  sale_stock_line_sequence/readme/DESCRIPTION.rst
  sale_stock_line_sequence/static/description/icon.png
  sale_stock_line_sequence/static/description/index.html
  sale_stock_line_sequence/tests/__init__.py
  sale_stock_line_sequence/tests/test_line_sequence.py
  setup/sale_stock_line_sequence/odoo/addons/sale_stock_line_sequence
  setup/sale_stock_line_sequence/setup.py
Labels: bot is merging ⏳

#2772 [16.0][IMP] sale order product recommendation - add zero unit included + extended product recommendation domain
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_company.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: approved, ready to merge, bot is merging ⏳

#2770 16.0 mig sale delivery state
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/i18n/sale_delivery_state.pot
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/static/description/icon.png
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
  sale_stock_delivery_state/README.rst
  sale_stock_delivery_state/__init__.py
  sale_stock_delivery_state/__manifest__.py
  sale_stock_delivery_state/hooks.py
  sale_stock_delivery_state/models/__init__.py
  sale_stock_delivery_state/models/sale_order.py
  sale_stock_delivery_state/readme/CONTRIBUTORS.rst
  sale_stock_delivery_state/readme/DESCRIPTION.rst
  sale_stock_delivery_state/static/description/index.html
  sale_stock_delivery_state/views/sale_order_views.xml
  setup/sale_delivery_state/odoo/addons/sale_delivery_state
  setup/sale_delivery_state/setup.py
  setup/sale_stock_delivery_state/odoo/addons/sale_stock_delivery_state
  setup/sale_stock_delivery_state/setup.py
Labels: approved, bot is merging ⏳

#2674 [ADD] sale_order_line_tag
  sale_order_line_tag/README.rst
  sale_order_line_tag/__init__.py
  sale_order_line_tag/__manifest__.py
  sale_order_line_tag/models/__init__.py
  sale_order_line_tag/models/sale_order_line.py
  sale_order_line_tag/models/sale_order_line_tag.py
  sale_order_line_tag/readme/CONTRIBUTORS.rst
  sale_order_line_tag/readme/DESCRIPTION.rst
  sale_order_line_tag/security/ir.model.access.csv
  sale_order_line_tag/views/sale_order_views.xml
  setup/sale_order_line_tag/odoo/addons/sale_order_line_tag
  setup/sale_order_line_tag/setup.py
Labels: bot is merging ⏳

#2800 [15.0][IMP] sale_order_line_price_history: Use just widget to display wizard and update values without saving
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/js/set_price_to_line_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/static/src/xml/set_price_to_line_widget.xml
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: approved, bot is merging ⏳

#2340 [ADD] sale_order_discount_fast_change_ui
  sale_coupon_order_discount_fast_change_ui/__init__.py
  sale_coupon_order_discount_fast_change_ui/__manifest__.py
  sale_coupon_order_discount_fast_change_ui/tests/__init__.py
  sale_coupon_order_discount_fast_change_ui/tests/test_sale_coupon_order_discount_fast_change.py
  sale_coupon_order_discount_fast_change_ui/wizard/__init__.py
  sale_coupon_order_discount_fast_change_ui/wizard/sale_order_discount_fast_change.py
  sale_coupon_order_discount_fast_change_ui/wizard/sale_order_discount_fast_change.xml
  sale_order_discount_fast_change_ui/README.rst
  sale_order_discount_fast_change_ui/__init__.py
  sale_order_discount_fast_change_ui/__manifest__.py
  sale_order_discount_fast_change_ui/readme/CONTRIBUTORS.rst
  sale_order_discount_fast_change_ui/readme/DESCRIPTION.rst
  sale_order_discount_fast_change_ui/readme/USAGE.rst
  sale_order_discount_fast_change_ui/security/ir.model.access.csv
  sale_order_discount_fast_change_ui/static/description/index.html
  sale_order_discount_fast_change_ui/static/src/js/sale_order_view.js
  sale_order_discount_fast_change_ui/tests/__init__.py
  sale_order_discount_fast_change_ui/tests/test_sale_order_discount_fast_change.py
  sale_order_discount_fast_change_ui/views/assets.xml
  sale_order_discount_fast_change_ui/views/sale_order_view.xml
  sale_order_discount_fast_change_ui/wizard/__init__.py
  sale_order_discount_fast_change_ui/wizard/sale_order_discount_fast_change.py
  sale_order_discount_fast_change_ui/wizard/sale_order_discount_fast_change.xml
  setup/sale_coupon_order_discount_fast_change_ui/odoo/addons/sale_coupon_order_discount_fast_change_ui
  setup/sale_coupon_order_discount_fast_change_ui/setup.py
  setup/sale_order_discount_fast_change_ui/odoo/addons/sale_order_discount_fast_change_ui
  setup/sale_order_discount_fast_change_ui/setup.py
Labels: needs review, approved, ready to merge, merged 🎉

#1585 [14.0][MIG] sale_promotion_rule_delivery
  sale_promotion_rule_delivery/README.rst
  sale_promotion_rule_delivery/__init__.py
  sale_promotion_rule_delivery/__manifest__.py
  sale_promotion_rule_delivery/i18n/ca.po
  sale_promotion_rule_delivery/i18n/es.po
  sale_promotion_rule_delivery/i18n/sale_promotion_rule_delivery.pot
  sale_promotion_rule_delivery/models/__init__.py
  sale_promotion_rule_delivery/models/sale_promotion_rule.py
  sale_promotion_rule_delivery/readme/CONTRIBUTORS.rst
  sale_promotion_rule_delivery/readme/DESCRIPTION.rst
  sale_promotion_rule_delivery/readme/ROADMAP.rst
  sale_promotion_rule_delivery/static/description/icon.png
  sale_promotion_rule_delivery/static/description/index.html
  sale_promotion_rule_delivery/tests/__init__.py
  sale_promotion_rule_delivery/tests/test_promotion.py
  setup/sale_promotion_rule_delivery/odoo/addons/sale_promotion_rule_delivery
  setup/sale_promotion_rule_delivery/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2806 [14.0][IMP] sale_order_product_assortment_quick: maintainers
  sale_order_product_assortment_quick/README.rst
  sale_order_product_assortment_quick/__manifest__.py
  sale_order_product_assortment_quick/static/description/index.html
Labels: bot is merging ⏳

#1584 [14.0][MIG] sale_promotion_rule_assortment
  sale_promotion_rule_assortment/README.rst
  sale_promotion_rule_assortment/__init__.py
  sale_promotion_rule_assortment/__manifest__.py
  sale_promotion_rule_assortment/demo/sale_order.xml
  sale_promotion_rule_assortment/demo/sale_promotion_rule.xml
  sale_promotion_rule_assortment/i18n/sale_promotion_rule_assortment.pot
  sale_promotion_rule_assortment/models/__init__.py
  sale_promotion_rule_assortment/models/sale_promotion_rule.py
  sale_promotion_rule_assortment/readme/CONTRIBUTORS.rst
  sale_promotion_rule_assortment/readme/DESCRIPTION.rst
  sale_promotion_rule_assortment/readme/USAGE.rst
  sale_promotion_rule_assortment/static/description/icon.png
  sale_promotion_rule_assortment/static/description/index.html
  sale_promotion_rule_assortment/tests/__init__.py
  sale_promotion_rule_assortment/tests/test_promotion_rule_assortment.py
  sale_promotion_rule_assortment/views/sale_promotion_rule.xml
  setup/sale_promotion_rule_assortment/odoo/addons/sale_promotion_rule_assortment
  setup/sale_promotion_rule_assortment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2722 [14.0][IMP] sale_stock_return_request: optional sales order filter / shortcut from sales order
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/sale_order.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_order_views.xml
  sale_stock_return_request/views/sale_return_request_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2811 [FIX] sale_packaging_default: compatible with `sale_order_product_picker`
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/tests/test_sale_packaging_default.py
Labels: enhancement, bot is merging ⏳

#2721 [14.0] [FIX] sale_quick: multi company
  sale_quick/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2771 [14.0][FIX] sale_partner_shipping_invoice_domain: generate README
  sale_partner_shipping_invoice_domain/README.rst
  sale_partner_shipping_invoice_domain/readme/DESCRIPTION.rst
  sale_partner_shipping_invoice_domain/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2776 [14.0][FIX] sale_order_lot_selection_by_quant: fix widget resize error
  sale_order_lot_selection_by_quant/README.rst
  sale_order_lot_selection_by_quant/__manifest__.py
  sale_order_lot_selection_by_quant/static/description/index.html
  sale_order_lot_selection_by_quant/static/src/js/select_lot_by_quant_widget.js
Labels: approved, bot is merging ⏳

#2789 [16.0][MIG] sale_advance_payment
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/es.po
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/account_move.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/readme/CONTRIBUTORS.rst
  sale_advance_payment/readme/DESCRIPTION.rst
  sale_advance_payment/readme/ROADMAP.rst
  sale_advance_payment/readme/USAGE.rst
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
  setup/sale_advance_payment/odoo/addons/sale_advance_payment
  setup/sale_advance_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳
