Repository OCA/sale-workflow, pull requests merged in 2023-12, with the labels that each got.

#2824 [FIX][16.0] sale_invoice_frequency: Add Monthly
  sale_invoice_frequency/data/sale_invoice_frequency_data.xml
  sale_invoice_frequency/i18n/es.po
  sale_invoice_frequency/i18n/sale_invoice_frequency.pot
Labels: bot is merging ⏳

#2820 [15.0][IMP] sale_elaboration: Add field to filter elaborated lines
  sale_elaboration/README.rst
  sale_elaboration/__manifest__.py
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/sale_order.py
  sale_elaboration/static/description/index.html
  sale_elaboration/views/sale_elaboration_report_views.xml
Labels: approved, bot is merging ⏳

#2828 [15.0][IMP] sale_stock_return_request: optional sales order filter / shortcut from sales order
  sale_stock_return_request/README.rst
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/sale_order.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/readme/CONTRIBUTORS.rst
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_order_views.xml
  sale_stock_return_request/views/sale_return_request_views.xml
Labels: approved, bot is merging ⏳

#2696 [ADD] sale_probability_amount: New module
  sale_probability_amount/__init__.py
  sale_probability_amount/__manifest__.py
  sale_probability_amount/data/ir_config_parameter.xml
  sale_probability_amount/i18n/fr.po
  sale_probability_amount/models/__init__.py
  sale_probability_amount/models/sale_order.py
  sale_probability_amount/readme/CONTRIBUTORS.rst
  sale_probability_amount/readme/DESCRIPTION.rst
  sale_probability_amount/tests/__init__.py
  sale_probability_amount/tests/test_sale_probability_amount.py
  sale_probability_amount/views/sale_views.xml
  setup/sale_probability_amount/odoo/addons/sale_probability_amount
  setup/sale_probability_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2840 [FIX] [16.0] sale_invoice_frequency: Add `invoice_frequency_id` to commercial fields
  sale_invoice_frequency/README.rst
  sale_invoice_frequency/models/res_partner.py
  sale_invoice_frequency/readme/DESCRIPTION.rst
  sale_invoice_frequency/static/description/index.html
Labels: needs review, approved, bot is merging ⏳

#2827 [REF] sale_packaging_default: remove sale_default field
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_order_product_recommendation_packaging_default/__manifest__.py
  sale_order_product_recommendation_packaging_default/static/description/index.html
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation_view.xml
  sale_packaging_default/README.rst
  sale_packaging_default/__manifest__.py
  sale_packaging_default/models/product_packaging.py
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/readme/CONFIGURE.md
  sale_packaging_default/readme/CONFIGURE.rst
  sale_packaging_default/readme/CONTEXT.md
  sale_packaging_default/readme/CONTRIBUTORS.md
  sale_packaging_default/readme/CONTRIBUTORS.rst
  sale_packaging_default/readme/DESCRIPTION.md
  sale_packaging_default/readme/DESCRIPTION.rst
  sale_packaging_default/readme/USAGE.md
  sale_packaging_default/readme/USAGE.rst
  sale_packaging_default/static/description/index.html
  sale_packaging_default/tests/test_sale_packaging_default.py
  sale_packaging_default/views/product_packaging_view.xml
Labels: enhancement, approved, bot is merging ⏳

#2846 [15.0][FIX] sale_stock_return_request: Exclude section and notes from _get_returnable_lines
  sale_stock_return_request/models/sale_order.py
Labels: approved, bot is merging ⏳

#2821 [15.0][IMP] sale_resource_booking: add multiples attendees in booking
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
Labels: approved, bot is merging ⏳

#2810 [IMP] sale_order_type_quotation_number: store recompute_quotation_seq field
  sale_order_type_quotation_number/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2848 [14.0][FIX] sale_stock_return_request: Exclude section and notes from _get_returnable_lines
  sale_stock_return_request/models/sale_order.py
Labels: approved, bot is merging ⏳

#2847 [IMP] sale_elaboration: optional subtree fields
  sale_elaboration/views/sale_order_views.xml
  sale_elaboration/views/stock_picking_views.xml
Labels: enhancement, approved, bot is merging ⏳

#2807 [15.0][FIX] sale_stock_secondary_unit: Fix test, second qty manage qty done
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
Labels: approved, bot is merging ⏳

#2819 [FIX] sale_order_product_recommendation: remove flaky create & new button from mobile view
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: bug, approved, bot is merging ⏳

#2779 [16.0][FIX] sale_order_general_discount_triple: remove attribute required f…
  sale_order_general_discount_triple/models/res_config_settings.py
Labels: bot is merging ⏳

#2540 [16.0][MIG]sale_sourced_by_line: Migration to 16.0
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale.py
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
  setup/sale_sourced_by_line/odoo/addons/sale_sourced_by_line
  setup/sale_sourced_by_line/setup.py
Labels: approved, bot is merging ⏳

#2833 [16.0] sale_product_packaging_container_deposit: fix qty delivered update
  sale_product_packaging_container_deposit/models/__init__.py
  sale_product_packaging_container_deposit/models/sale_order_line.py
  sale_product_packaging_container_deposit/models/stock_move.py
  sale_product_packaging_container_deposit/readme/CONTRIBUTORS.rst
  sale_product_packaging_container_deposit/tests/test_sale_product_packaging_container_deposit.py
Labels: approved, ready to merge, bot is merging ⏳

#2778 [16.0][MIG] sale_order_price_recalculation
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/INSTALL.rst
  sale_order_price_recalculation/readme/ROADMAP.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
  setup/sale_order_price_recalculation/odoo/addons/sale_order_price_recalculation
  setup/sale_order_price_recalculation/setup.py
Labels: approved, bot is merging ⏳

#2786 [16.0][MIG] sale_product_set_layout: merge into product_set
  sale_product_set/tests/test_product_set.py
  sale_product_set/views/product_set_line.xml
  sale_product_set/wizard/product_set_add.py
  sale_product_set/wizard/product_set_add.xml
Labels: approved, bot is merging ⏳

#2853 [ADD] sale_numeric_step: new module for better selling on touch screens
  sale_numeric_step/README.rst
  sale_numeric_step/__init__.py
  sale_numeric_step/__manifest__.py
  sale_numeric_step/readme/CONTEXT.md
  sale_numeric_step/readme/CONTRIBUTORS.md
  sale_numeric_step/readme/CREDITS.md
  sale_numeric_step/readme/DESCRIPTION.md
  sale_numeric_step/readme/USAGE.md
  sale_numeric_step/static/description/icon.png
  sale_numeric_step/static/description/index.html
  sale_numeric_step/views/sale_order_view.xml
  setup/sale_numeric_step/odoo/addons/sale_numeric_step
  setup/sale_numeric_step/setup.py
Labels: needs review, approved, bot is merging ⏳

#2858 [FIX] sale_order_product_recommendation_packaging_default: quick crea…
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation_view.xml
Labels: enhancement, bot is merging ⏳

#2841 [IMP] picking notes in partner
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/res_partner.py
  sale_stock_picking_note/models/sale_order.py
  sale_stock_picking_note/models/sale_stock.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/readme/CONTRIBUTORS.rst
  sale_stock_picking_note/readme/USAGE.rst
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/res_partner_view.xml
Labels: needs review, approved, bot is merging ⏳

#2856 [ADD] sale_order_product_recommendation_elaboration
  .copier-answers.yml
  .github/workflows/test.yml
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation_elaboration/README.rst
  sale_order_product_recommendation_elaboration/__init__.py
  sale_order_product_recommendation_elaboration/__manifest__.py
  sale_order_product_recommendation_elaboration/readme/CONTEXT.md
  sale_order_product_recommendation_elaboration/readme/CONTRIBUTORS.md
  sale_order_product_recommendation_elaboration/readme/CREDITS.md
  sale_order_product_recommendation_elaboration/readme/DESCRIPTION.md
  sale_order_product_recommendation_elaboration/readme/USAGE.md
  sale_order_product_recommendation_elaboration/static/description/icon.png
  sale_order_product_recommendation_elaboration/static/description/index.html
  sale_order_product_recommendation_elaboration/tests/__init__.py
  sale_order_product_recommendation_elaboration/tests/test_sale_order_recommendation.py
  sale_order_product_recommendation_elaboration/wizards/__init__.py
  sale_order_product_recommendation_elaboration/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_elaboration/wizards/sale_order_recommendation_view.xml
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
  setup/sale_order_product_recommendation_elaboration/odoo/addons/sale_order_product_recommendation_elaboration
  setup/sale_order_product_recommendation_elaboration/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2648 [ADD] sale_order_line_field_from_product_attribute: new module (was sale_attribute_to_field)
  sale_order_line_field_from_product_attribute/README.md
  sale_order_line_field_from_product_attribute/README.rst
  sale_order_line_field_from_product_attribute/__init__.py
  sale_order_line_field_from_product_attribute/__manifest__.py
  sale_order_line_field_from_product_attribute/models/__init__.py
  sale_order_line_field_from_product_attribute/models/product_attribute.py
  sale_order_line_field_from_product_attribute/models/sale_order_line.py
  sale_order_line_field_from_product_attribute/readme/CONFIGURE.rst
  sale_order_line_field_from_product_attribute/readme/CONTRIBUTORS.rst
  sale_order_line_field_from_product_attribute/readme/DESCRIPTION.rst
  sale_order_line_field_from_product_attribute/readme/USAGE.rst
  sale_order_line_field_from_product_attribute/static/description/index.html
  sale_order_line_field_from_product_attribute/tests/__init__.py
  sale_order_line_field_from_product_attribute/tests/test_sale_attribute.py
  sale_order_line_field_from_product_attribute/views/product_attribute_view.xml
  setup/sale_order_line_field_from_product_attribute/odoo/addons/sale_order_line_field_from_product_attribute
  setup/sale_order_line_field_from_product_attribute/setup.py
Labels: needs review, bot is merging ⏳

#2845 [IMP]sale_delivery_state: Skip sale order lines for delivery state
  sale_delivery_state/README.rst
  sale_delivery_state/__manifest__.py
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/res_company.py
  sale_delivery_state/models/res_config_settings.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/models/sale_order_line.py
  sale_delivery_state/readme/CONFIGURE.rst
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/res_config_settings_views.xml
  sale_delivery_state/views/sale_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2864 [IMP]sale_delivery_state: Skip sale order lines for delivery state
  sale_delivery_state/README.rst
  sale_delivery_state/__manifest__.py
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/res_company.py
  sale_delivery_state/models/res_config_settings.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/models/sale_order_line.py
  sale_delivery_state/readme/CONFIGURE.rst
  sale_delivery_state/readme/CONTRIBUTORS.rst
  sale_delivery_state/readme/DESCRIPTION.rst
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/res_config_settings_views.xml
  sale_delivery_state/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#2863 [15.0][FIX] sale_payment_sheet: Don't set name on stamement lines
  sale_payment_sheet/models/sale_payment_sheet.py
Labels: approved, bot is merging ⏳

#2865 [16.0][FIX] sale_payment_sheet: Don't set name on stamement lines
  sale_payment_sheet/models/sale_payment_sheet.py
Labels: bot is merging ⏳

#2543 [15.0][FIX] sale_invoice_plan: recompute invoice plan table
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2857 [IMP] sale_order_product_recommendation: favorites, categories
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2868 [16.0][FIX] sale_exception_holidays_public: tests don't pass
  sale_exception_holidays_public/tests/test_sale_exception.py
Labels: needs review, approved, bot is merging ⏳

#2869 [FIX] sale_order_product_recommendation_elaboration: don't assume the current product is the same than the one in the elaboration
  sale_order_product_recommendation_elaboration/tests/test_sale_order_recommendation.py
  sale_order_product_recommendation_elaboration/wizards/sale_order_recommendation_view.xml
Labels: bug, approved, bot is merging ⏳

#2862 [16.0][IMP] sale_stock_picking_note: Notes from partner shipping
  sale_stock_picking_note/models/sale_order.py
Labels: approved, bot is merging ⏳

#2471 [16.0][mig] sale_last_price_info
  sale_last_price_info/README.rst
  sale_last_price_info/__init__.py
  sale_last_price_info/__manifest__.py
  sale_last_price_info/i18n/ca.po
  sale_last_price_info/i18n/de.po
  sale_last_price_info/i18n/es.po
  sale_last_price_info/i18n/fr.po
  sale_last_price_info/i18n/fr_FR.po
  sale_last_price_info/i18n/it.po
  sale_last_price_info/i18n/nl.po
  sale_last_price_info/i18n/sale_last_price_info.pot
  sale_last_price_info/i18n/sl_SI.po
  sale_last_price_info/i18n/zh_CN.po
  sale_last_price_info/models/__init__.py
  sale_last_price_info/models/product.py
  sale_last_price_info/models/sale.py
  sale_last_price_info/readme/CONTRIBUTORS.rst
  sale_last_price_info/readme/DESCRIPTION.rst
  sale_last_price_info/static/description/icon.png
  sale_last_price_info/static/description/index.html
  sale_last_price_info/tests/__init__.py
  sale_last_price_info/tests/test_sale_last_price_info.py
  sale_last_price_info/views/product_view.xml
  setup/sale_last_price_info/odoo/addons/sale_last_price_info
  setup/sale_last_price_info/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
