Repository OCA/sale-workflow, pull requests merged in 2023-01, with the labels that each got.

#2311 [15.0][MIG] sale_order_line_sequence
  sale_order_line_sequence/README.rst
  sale_order_line_sequence/__init__.py
  sale_order_line_sequence/__manifest__.py
  sale_order_line_sequence/i18n/ca.po
  sale_order_line_sequence/i18n/de.po
  sale_order_line_sequence/i18n/el_GR.po
  sale_order_line_sequence/i18n/es.po
  sale_order_line_sequence/i18n/es_ES.po
  sale_order_line_sequence/i18n/es_VE.po
  sale_order_line_sequence/i18n/fi.po
  sale_order_line_sequence/i18n/fr.po
  sale_order_line_sequence/i18n/hr.po
  sale_order_line_sequence/i18n/hr_HR.po
  sale_order_line_sequence/i18n/hu.po
  sale_order_line_sequence/i18n/it.po
  sale_order_line_sequence/i18n/nl.po
  sale_order_line_sequence/i18n/nl_NL.po
  sale_order_line_sequence/i18n/pt.po
  sale_order_line_sequence/i18n/pt_BR.po
  sale_order_line_sequence/i18n/ro.po
  sale_order_line_sequence/i18n/sale_order_line_sequence.pot
  sale_order_line_sequence/i18n/sk.po
  sale_order_line_sequence/i18n/sl.po
  sale_order_line_sequence/i18n/tr.po
  sale_order_line_sequence/i18n/tr_TR.po
  sale_order_line_sequence/i18n/vi_VN.po
  sale_order_line_sequence/i18n/zh_CN.po
  sale_order_line_sequence/init_hooks.py
  sale_order_line_sequence/model/__init__.py
  sale_order_line_sequence/model/sale_order.py
  sale_order_line_sequence/readme/CONTRIBUTORS.rst
  sale_order_line_sequence/readme/CREDITS.rst
  sale_order_line_sequence/readme/DESCRIPTION.rst
  sale_order_line_sequence/static/description/icon.png
  sale_order_line_sequence/static/description/index.html
  sale_order_line_sequence/tests/__init__.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_line_sequence/views/report_saleorder.xml
  sale_order_line_sequence/views/sale_view.xml
  setup/sale_order_line_sequence/odoo/addons/sale_order_line_sequence
  setup/sale_order_line_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1936 sale_delivery_date: deliveryslip report - Add div name
  sale_delivery_date/reports/stock_picking.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2241 [15.0][MIG] sale_stock_secondary_unit: Migration to version 15.0
  sale_order_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/i18n/de.po
  sale_stock_secondary_unit/i18n/es.po
  sale_stock_secondary_unit/i18n/sale_stock_secondary_unit.pot
  sale_stock_secondary_unit/i18n/zh_CN.po
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/stock_rule.py
  sale_stock_secondary_unit/readme/CONTRIBUTORS.rst
  sale_stock_secondary_unit/readme/DESCRIPTION.rst
  sale_stock_secondary_unit/readme/USAGE.rst
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
  setup/sale_stock_secondary_unit/odoo/addons/sale_stock_secondary_unit
  setup/sale_stock_secondary_unit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2328 [ADD] sale_stock_reconcile_valuation_kit
  sale_stock_reconcile_valuation_kit/README.rst
  sale_stock_reconcile_valuation_kit/__init__.py
  sale_stock_reconcile_valuation_kit/__manifest__.py
  sale_stock_reconcile_valuation_kit/models/__init__.py
  sale_stock_reconcile_valuation_kit/models/account_move.py
  sale_stock_reconcile_valuation_kit/readme/CONTRIBUTORS.rst
  sale_stock_reconcile_valuation_kit/readme/DESCRIPTION.rst
  sale_stock_reconcile_valuation_kit/static/description/icon.png
  sale_stock_reconcile_valuation_kit/static/description/index.html
  sale_stock_reconcile_valuation_kit/test/__init__.py
  sale_stock_reconcile_valuation_kit/test/test_sale_stock_reconcile_valuation_kit.py
  setup/sale_stock_reconcile_valuation_kit/odoo/addons/sale_stock_reconcile_valuation_kit
  setup/sale_stock_reconcile_valuation_kit/setup.py
Labels: bot is merging ⏳

#2342 [15.0][IMP] sale_commercial_partner: promote to stable
  sale_commercial_partner/__manifest__.py
Labels: bot is merging ⏳

#2326 [13.0][ADD] sale_validity_auto_cancel
  sale_validity_auto_cancel/README.rst
  sale_validity_auto_cancel/__init__.py
  sale_validity_auto_cancel/__manifest__.py
  sale_validity_auto_cancel/data/ir_cron.xml
  sale_validity_auto_cancel/models/__init__.py
  sale_validity_auto_cancel/models/res_company.py
  sale_validity_auto_cancel/models/res_config_settings.py
  sale_validity_auto_cancel/models/sale_order.py
  sale_validity_auto_cancel/readme/CONFIGURE.rst
  sale_validity_auto_cancel/readme/CONTRIBUTORS.rst
  sale_validity_auto_cancel/readme/DESCRIPTION.rst
  sale_validity_auto_cancel/readme/USAGE.rst
  sale_validity_auto_cancel/static/description/icon.png
  sale_validity_auto_cancel/static/description/index.html
  sale_validity_auto_cancel/tests/__init__.py
  sale_validity_auto_cancel/tests/test_sale_validity_auto_cancel.py
  sale_validity_auto_cancel/views/res_config_settings.xml
  setup/sale_validity_auto_cancel/odoo/addons/sale_validity_auto_cancel
  setup/sale_validity_auto_cancel/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2317 [16.0][MIG] - sale_triple_discount
  sale_triple_discount/README.rst
  sale_triple_discount/__init__.py
  sale_triple_discount/__manifest__.py
  sale_triple_discount/i18n/ca.po
  sale_triple_discount/i18n/de.po
  sale_triple_discount/i18n/es.po
  sale_triple_discount/i18n/es_VE.po
  sale_triple_discount/i18n/fr.po
  sale_triple_discount/i18n/hr.po
  sale_triple_discount/i18n/it.po
  sale_triple_discount/i18n/nl_NL.po
  sale_triple_discount/i18n/pt_BR.po
  sale_triple_discount/i18n/ro.po
  sale_triple_discount/i18n/sale_triple_discount.pot
  sale_triple_discount/i18n/sl.po
  sale_triple_discount/i18n/tr.po
  sale_triple_discount/i18n/tr_TR.po
  sale_triple_discount/models/__init__.py
  sale_triple_discount/models/sale_order_line.py
  sale_triple_discount/readme/CONFIGURE.rst
  sale_triple_discount/readme/CONTRIBUTORS.rst
  sale_triple_discount/readme/DESCRIPTION.rst
  sale_triple_discount/readme/USAGE.rst
  sale_triple_discount/static/description/icon.png
  sale_triple_discount/static/description/index.html
  sale_triple_discount/tests/__init__.py
  sale_triple_discount/tests/test_sale_triple_discount.py
  sale_triple_discount/views/sale_order_report.xml
  sale_triple_discount/views/sale_order_view.xml
  setup/sale_triple_discount/odoo/addons/sale_triple_discount
  setup/sale_triple_discount/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2349 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳
