Repository OCA/sale-workflow, pull requests merged in 2023-06, with the labels that each got.

#2138 [15.0] [MIG] product_form_sale_link
  product_form_sale_link/README.rst
  product_form_sale_link/__init__.py
  product_form_sale_link/__manifest__.py
  product_form_sale_link/i18n/ca.po
  product_form_sale_link/i18n/es.po
  product_form_sale_link/i18n/fr.po
  product_form_sale_link/i18n/product_form_sale_link.pot
  product_form_sale_link/models/__init__.py
  product_form_sale_link/models/product_product.py
  product_form_sale_link/models/product_template.py
  product_form_sale_link/readme/CONTRIBUTORS.rst
  product_form_sale_link/readme/DESCRIPTION.rst
  product_form_sale_link/readme/USAGE.rst
  product_form_sale_link/static/description/icon.png
  product_form_sale_link/static/description/index.html
  product_form_sale_link/static/description/product_sale.png
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
  setup/product_form_sale_link/odoo/addons/product_form_sale_link
  setup/product_form_sale_link/setup.py
Labels: question, approved, bot is merging ⏳

#2430 [14.0][ADD]sale_purchase_requisition
  sale_purchase_requisition/README.rst
  sale_purchase_requisition/__init__.py
  sale_purchase_requisition/__manifest__.py
  sale_purchase_requisition/i18n/es.po
  sale_purchase_requisition/i18n/sale_purchase_requisition.pot
  sale_purchase_requisition/models/__init__.py
  sale_purchase_requisition/models/purchase_requisition.py
  sale_purchase_requisition/models/sale_order.py
  sale_purchase_requisition/readme/CONTRIBUTORS.rst
  sale_purchase_requisition/readme/CREDITS.rst
  sale_purchase_requisition/readme/DESCRIPTION.rst
  sale_purchase_requisition/readme/INSTALL.rst
  sale_purchase_requisition/readme/ROADMAP.rst
  sale_purchase_requisition/readme/USAGE.rst
  sale_purchase_requisition/security/ir.model.access.csv
  sale_purchase_requisition/security/sale_purchase_requisition_security.xml
  sale_purchase_requisition/static/description/icon.png
  sale_purchase_requisition/static/description/index.html
  sale_purchase_requisition/tests/__init__.py
  sale_purchase_requisition/tests/test_sale_purchase_requisition.py
  sale_purchase_requisition/views/purchase_requisition.xml
  sale_purchase_requisition/views/sale_order.xml
  setup/sale_purchase_requisition/odoo/addons/sale_purchase_requisition
  setup/sale_purchase_requisition/setup.py
Labels: needs review, approved, bot is merging ⏳

#2537 [16.0][MIG] sale_elaboration: Migration to version 16.0
  sale_elaboration/README.rst
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/hooks.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/models/product_elaboration_mixin.py
  sale_elaboration/models/product_elaboration_profile.py
  sale_elaboration/models/product_template.py
  sale_elaboration/models/res_config_settings.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_move.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/models/stock_rule.py
  sale_elaboration/readme/CONFIGURE.rst
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/readme/DESCRIPTION.rst
  sale_elaboration/readme/USAGE.rst
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/security/ir.model.access.csv
  sale_elaboration/security/security.xml
  sale_elaboration/static/description/icon.png
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/__init__.py
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_views.xml
  sale_elaboration/views/res_config_settings_views.xml
  sale_elaboration/views/sale_elaboration_profile_views.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_elaboration/views/sale_order_views.xml
  sale_elaboration/views/stock_move_views.xml
  sale_elaboration/views/stock_picking_views.xml
  setup/sale_elaboration/odoo/addons/sale_elaboration
  setup/sale_elaboration/setup.py
Labels: approved, bot is merging ⏳

#2426 [16.0][MIG] sale_order_invoice_amount: Migration to 16.0
  sale_order_invoice_amount/README.rst
  sale_order_invoice_amount/__init__.py
  sale_order_invoice_amount/__manifest__.py
  sale_order_invoice_amount/hooks.py
  sale_order_invoice_amount/i18n/es.po
  sale_order_invoice_amount/i18n/sale_order_invoice_amount.pot
  sale_order_invoice_amount/models/__init__.py
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/readme/CONTRIBUTORS.rst
  sale_order_invoice_amount/readme/DESCRIPTION.rst
  sale_order_invoice_amount/static/description/icon.png
  sale_order_invoice_amount/static/description/index.html
  sale_order_invoice_amount/static/src/xml/tax_totals.xml
  sale_order_invoice_amount/tests/__init__.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
  sale_order_invoice_amount/views/sale_order_view.xml
  setup/sale_order_invoice_amount/odoo/addons/sale_order_invoice_amount
  setup/sale_order_invoice_amount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2491 [16.0][MIG] sale_order_product_recommendation: Migration to version 16.0
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/pt_BR.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/models/sale_order.py
  sale_order_product_recommendation/readme/CONFIGURE.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/readme/DESCRIPTION.rst
  sale_order_product_recommendation/readme/USAGE.rst
  sale_order_product_recommendation/security/ir.model.access.csv
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
  setup/sale_order_product_recommendation/odoo/addons/sale_order_product_recommendation
  setup/sale_order_product_recommendation/setup.py
Labels: needs review, migration, bot is merging ⏳

#2305 [MIG][16.0] sale_force_invoiced
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/readme/DESCRIPTION.rst
  sale_force_invoiced/readme/USAGE.rst
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_order.xml
  setup/sale_force_invoiced/odoo/addons/sale_force_invoiced
  setup/sale_force_invoiced/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2060 [15.0] [MIG] sale_order_report_without_price: Migrated the module in v15.
  sale_order_report_without_price/README.rst
  sale_order_report_without_price/__init__.py
  sale_order_report_without_price/__manifest__.py
  sale_order_report_without_price/i18n/sale_order_report_without_price.pot
  sale_order_report_without_price/readme/CONTRIBUTORS.rst
  sale_order_report_without_price/readme/DESCRIPTION.rst
  sale_order_report_without_price/readme/USAGE.rst
  sale_order_report_without_price/report/sale_report.xml
  sale_order_report_without_price/report/sale_report_templates.xml
  sale_order_report_without_price/static/description/icon.png
  sale_order_report_without_price/static/description/index.html
  setup/sale_order_report_without_price/odoo/addons/sale_order_report_without_price
  setup/sale_order_report_without_price/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2507 [14.0][MIG] sale_fixed_discount
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/es.po
  sale_fixed_discount/i18n/fr.po
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  sale_fixed_discount/views/sale_portal_templates.xml
  setup/sale_fixed_discount/odoo/addons/sale_fixed_discount
  setup/sale_fixed_discount/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2529 [16.0][MIG] sale_mrp_bom
  sale_mrp_bom/README.rst
  sale_mrp_bom/__init__.py
  sale_mrp_bom/__manifest__.py
  sale_mrp_bom/i18n/sale_mrp_bom.pot
  sale_mrp_bom/models/__init__.py
  sale_mrp_bom/models/sale_order_line.py
  sale_mrp_bom/models/stock_move.py
  sale_mrp_bom/readme/CONFIGURE.rst
  sale_mrp_bom/readme/CONTRIBUTORS.rst
  sale_mrp_bom/readme/CREDITS.rst
  sale_mrp_bom/readme/DESCRIPTION.rst
  sale_mrp_bom/readme/INSTALL.rst
  sale_mrp_bom/readme/ROADMAP.rst
  sale_mrp_bom/readme/USAGE.rst
  sale_mrp_bom/security/security.xml
  sale_mrp_bom/static/description/icon.png
  sale_mrp_bom/static/description/index.html
  sale_mrp_bom/static/description/manufacturing_order_1.png
  sale_mrp_bom/static/description/sale_order_1.png
  sale_mrp_bom/tests/__init__.py
  sale_mrp_bom/tests/test_sale_mrp_bom.py
  sale_mrp_bom/views/sale_order.xml
  sale_mrp_bom/views/sale_order_line.xml
  setup/sale_mrp_bom/odoo/addons/sale_mrp_bom
  setup/sale_mrp_bom/setup.py
Labels: approved, bot is merging ⏳

#2289 [IMP] sale_order_line_date: update existing moves date_deadline
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2301 [13.0][IMP] product_form_sale_link: fix compatibility with sale_stock and not filter out quotations
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2566 Port PR 2301 from 13.0 to 14.0
  product_form_sale_link/views/sale_order_line.xml
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2526 [14.0][FIX] sale_order_type: Default value not set for compute fields
  sale_order_type/models/sale.py
Labels: approved, bot is merging ⏳

#1583 [14.0][MIG] sale promotion rule
  sale_promotion_rule/README.rst
  sale_promotion_rule/__init__.py
  sale_promotion_rule/__manifest__.py
  sale_promotion_rule/demo/product.xml
  sale_promotion_rule/demo/sale_demo.xml
  sale_promotion_rule/i18n/ca.po
  sale_promotion_rule/i18n/fr.po
  sale_promotion_rule/i18n/sale_promotion_rule.pot
  sale_promotion_rule/models/__init__.py
  sale_promotion_rule/models/sale_order.py
  sale_promotion_rule/models/sale_order_line.py
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/readme/CONTRIBUTORS.rst
  sale_promotion_rule/readme/DESCRIPTION.rst
  sale_promotion_rule/readme/ROADMAP.rst
  sale_promotion_rule/security/ir.model.access.csv
  sale_promotion_rule/security/sale_promotion_rule.xml
  sale_promotion_rule/static/description/icon.png
  sale_promotion_rule/static/description/index.html
  sale_promotion_rule/static/description/promotion_rule.png
  sale_promotion_rule/tests/__init__.py
  sale_promotion_rule/tests/test_promotion.py
  sale_promotion_rule/views/sale_order.xml
  sale_promotion_rule/views/sale_promotion_rule.xml
  sale_promotion_rule/wizards/__init__.py
  sale_promotion_rule/wizards/sale_order_add_coupon.py
  sale_promotion_rule/wizards/sale_order_add_coupon.xml
  setup/sale_promotion_rule/odoo/addons/sale_promotion_rule
  setup/sale_promotion_rule/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, stale

#1586 [14.0][MIG] sale_promotion_rule_display_discount_amount
  sale_promotion_rule_display_discount_amount/README.rst
  sale_promotion_rule_display_discount_amount/__init__.py
  sale_promotion_rule_display_discount_amount/__manifest__.py
  sale_promotion_rule_display_discount_amount/models/__init__.py
  sale_promotion_rule_display_discount_amount/models/sale_order.py
  sale_promotion_rule_display_discount_amount/readme/CONTRIBUTORS.rst
  sale_promotion_rule_display_discount_amount/readme/DESCRIPTION.rst
  sale_promotion_rule_display_discount_amount/readme/USAGE.rst
  sale_promotion_rule_display_discount_amount/static/description/icon.png
  sale_promotion_rule_display_discount_amount/static/description/index.html
  sale_promotion_rule_display_discount_amount/tests/__init__.py
  sale_promotion_rule_display_discount_amount/tests/test_sale_order.py
  setup/sale_promotion_rule_display_discount_amount/odoo/addons/sale_promotion_rule_display_discount_amount
  setup/sale_promotion_rule_display_discount_amount/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2403 [16.0][MIG] sale_procurement_group_by_line: Migration to 16.0
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/model/stock_move.py
  sale_procurement_group_by_line/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_line/readme/DESCRIPTION.rst
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/static/description/index.html
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
  setup/sale_procurement_group_by_line/odoo/addons/sale_procurement_group_by_line
  setup/sale_procurement_group_by_line/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#2531 [16.0][IMP]sale_order_line_menu: set no visible sections and notes in sale order lines menu
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1433 [14.0][ADD] sale_partner_shipping_invoice_domain: add to 14.0
  sale_partner_shipping_invoice_domain/README.rst
  sale_partner_shipping_invoice_domain/__init__.py
  sale_partner_shipping_invoice_domain/__manifest__.py
  sale_partner_shipping_invoice_domain/models/__init__.py
  sale_partner_shipping_invoice_domain/models/sale_order.py
  sale_partner_shipping_invoice_domain/readme/CONFIGURATION.rst
  sale_partner_shipping_invoice_domain/readme/CONTRIBUTORS.rst
  sale_partner_shipping_invoice_domain/readme/USAGE.rst
  sale_partner_shipping_invoice_domain/static/description/icon.png
  sale_partner_shipping_invoice_domain/views/sale_order.xml
  setup/sale_partner_shipping_invoice_domain/odoo/addons/sale_partner_shipping_invoice_domain
  setup/sale_partner_shipping_invoice_domain/setup.py
Labels: needs review, approved, bot is merging ⏳, stale

#2323 [16.0][MIG] sale_substate
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/readme/CONTRIBUTORS.rst
  sale_substate/readme/DESCRIPTION.rst
  sale_substate/readme/USAGE.rst
  sale_substate/static/description/icon.png
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
  setup/sale_substate/odoo/addons/sale_substate
  setup/sale_substate/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2568 Port PR 2301 from 13.0 to 15.0
  product_form_sale_link/views/sale_order_line.xml
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: approved, bot is merging ⏳

#2573 [16.0][IMP] product_form_sale_link: do not filter out quotations (forward port)
  product_form_sale_link/views/sale_order_line.xml
Labels: bot is merging ⏳

#2549 [15.0][FIX] Sales order states in tier validation
  sale_tier_validation/models/sale_order.py
Labels: approved, bot is merging ⏳

#2569 [15.0][FIX] sale_elaboration: Header of table messy
  sale_elaboration/reports/report_deliveryslip.xml
Labels: approved, ready to merge, bot is merging ⏳

#2501 [14.0][FIX] sale workflow job email send before validation
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow_ignore_exception/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
Labels: approved, ready to merge, bot is merging ⏳

#1761 [14.0] [ADD] sale_exception_product_sale_manufactured_for
  sale_exception_product_sale_manufactured_for/README.rst
  sale_exception_product_sale_manufactured_for/__init__.py
  sale_exception_product_sale_manufactured_for/__manifest__.py
  sale_exception_product_sale_manufactured_for/data/exception_rule.xml
  sale_exception_product_sale_manufactured_for/demo/exception_rule.xml
  sale_exception_product_sale_manufactured_for/models/__init__.py
  sale_exception_product_sale_manufactured_for/models/sale_order.py
  sale_exception_product_sale_manufactured_for/readme/CONTRIBUTORS.rst
  sale_exception_product_sale_manufactured_for/readme/CREDITS.rst
  sale_exception_product_sale_manufactured_for/readme/DESCRIPTION.rst
  sale_exception_product_sale_manufactured_for/static/description/index.html
  sale_exception_product_sale_manufactured_for/tests/__init__.py
  sale_exception_product_sale_manufactured_for/tests/test_sale_exception.py
  setup/sale_exception_product_sale_manufactured_for/odoo/addons/sale_exception_product_sale_manufactured_for
  setup/sale_exception_product_sale_manufactured_for/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2561 [16.0][MIG] sale_stock_cancel_restriction
  sale_stock_cancel_restriction/README.rst
  sale_stock_cancel_restriction/__init__.py
  sale_stock_cancel_restriction/__manifest__.py
  sale_stock_cancel_restriction/i18n/es.po
  sale_stock_cancel_restriction/i18n/sale_stock_cancel_restriction.pot
  sale_stock_cancel_restriction/models/__init__.py
  sale_stock_cancel_restriction/models/sale_order.py
  sale_stock_cancel_restriction/readme/CONTRIBUTORS.rst
  sale_stock_cancel_restriction/readme/DESCRIPTION.rst
  sale_stock_cancel_restriction/readme/USAGE.rst
  sale_stock_cancel_restriction/static/description/icon.png
  sale_stock_cancel_restriction/static/description/index.html
  sale_stock_cancel_restriction/tests/__init__.py
  sale_stock_cancel_restriction/tests/test_sale_stock_cancel_restriction.py
  setup/sale_stock_cancel_restriction/odoo/addons/sale_stock_cancel_restriction
  setup/sale_stock_cancel_restriction/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2579 [13.0][IMP] sale_payment_sheet: Allow select invoices instead of remove them
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2358 [16.0][MIG] sale_order_general_discount_triple
  sale_order_general_discount_triple/README.rst
  sale_order_general_discount_triple/__init__.py
  sale_order_general_discount_triple/__manifest__.py
  sale_order_general_discount_triple/i18n/it.po
  sale_order_general_discount_triple/i18n/sale_order_general_discount_triple.pot
  sale_order_general_discount_triple/models/__init__.py
  sale_order_general_discount_triple/models/res_config_settings.py
  sale_order_general_discount_triple/models/sale_order.py
  sale_order_general_discount_triple/models/sale_order_line.py
  sale_order_general_discount_triple/readme/CONTRIBUTORS.rst
  sale_order_general_discount_triple/readme/DESCRIPTION.rst
  sale_order_general_discount_triple/readme/HISTORY.rst
  sale_order_general_discount_triple/readme/USAGE.rst
  sale_order_general_discount_triple/static/description/icon.png
  sale_order_general_discount_triple/static/description/index.html
  sale_order_general_discount_triple/tests/__init__.py
  sale_order_general_discount_triple/tests/test_module.py
  sale_order_general_discount_triple/views/res_config_settings.xml
  setup/sale_order_general_discount_triple/odoo/addons/sale_order_general_discount_triple
  setup/sale_order_general_discount_triple/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2538 [15.0][IMP] sale_order_product_assortment: Use original product_id field keeping domain. Use cache to performance
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/models/__init__.py
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/models/sale_order_line.py
  sale_order_product_assortment/views/sale_order_view.xml
Labels: bot is merging ⏳

#1972 [13.0][FIX] sale_order_invoicing_finished_task: invoiceable field is not updated
  sale_order_invoicing_finished_task/views/project_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2585 [13.0][IMP] sale_payment_sheet: Allow select lines without clicking 2 times
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: approved, bot is merging ⏳

#2341 [16.0] [MIG] sale_order_line_date
  sale_order_line_date/README.rst
  sale_order_line_date/__init__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_date/i18n/ca.po
  sale_order_line_date/i18n/de.po
  sale_order_line_date/i18n/el_GR.po
  sale_order_line_date/i18n/es.po
  sale_order_line_date/i18n/es_ES.po
  sale_order_line_date/i18n/es_VE.po
  sale_order_line_date/i18n/fi.po
  sale_order_line_date/i18n/fr.po
  sale_order_line_date/i18n/hr.po
  sale_order_line_date/i18n/hr_HR.po
  sale_order_line_date/i18n/hu.po
  sale_order_line_date/i18n/it.po
  sale_order_line_date/i18n/nl.po
  sale_order_line_date/i18n/nl_NL.po
  sale_order_line_date/i18n/pt.po
  sale_order_line_date/i18n/pt_BR.po
  sale_order_line_date/i18n/ro.po
  sale_order_line_date/i18n/sale_order_line_date.pot
  sale_order_line_date/i18n/sk.po
  sale_order_line_date/i18n/sl.po
  sale_order_line_date/i18n/tr.po
  sale_order_line_date/i18n/tr_TR.po
  sale_order_line_date/i18n/vi_VN.po
  sale_order_line_date/i18n/zh_CN.po
  sale_order_line_date/models/__init__.py
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/readme/CONTRIBUTORS.rst
  sale_order_line_date/readme/DESCRIPTION.rst
  sale_order_line_date/readme/USAGE.rst
  sale_order_line_date/reports/sale_order_report.xml
  sale_order_line_date/static/description/icon.png
  sale_order_line_date/static/description/index.html
  sale_order_line_date/tests/__init__.py
  sale_order_line_date/tests/test_sale_order_line_date.py
  sale_order_line_date/views/sale_order_view.xml
  setup/sale_order_line_date/odoo/addons/sale_order_line_date
  setup/sale_order_line_date/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2425 [16.0][MIG] sale_product_category_menu
  sale_product_category_menu/README.rst
  sale_product_category_menu/__init__.py
  sale_product_category_menu/__manifest__.py
  sale_product_category_menu/i18n/ca.po
  sale_product_category_menu/i18n/es.po
  sale_product_category_menu/i18n/fr.po
  sale_product_category_menu/i18n/fr_FR.po
  sale_product_category_menu/i18n/nl.po
  sale_product_category_menu/i18n/sale_product_category_menu.pot
  sale_product_category_menu/readme/CONTRIBUTORS.rst
  sale_product_category_menu/readme/DESCRIPTION.rst
  sale_product_category_menu/static/description/icon.png
  sale_product_category_menu/static/description/index.html
  sale_product_category_menu/views/sale_views.xml
  setup/sale_product_category_menu/odoo/addons/sale_product_category_menu
  setup/sale_product_category_menu/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2589 [16.0][FIX] sale_tier_validation: Sales order states in tier validation: Port PR 2549 from 15.0 to 16.0
  sale_tier_validation/models/sale_order.py
Labels: bot is merging ⏳

#1597 [14.0][ADD] - New module sale_order_change_analytic_account
  sale_order_change_analytic_account/__init__.py
  sale_order_change_analytic_account/__manifest__.py
  sale_order_change_analytic_account/models/__init__.py
  sale_order_change_analytic_account/models/sale_order.py
  sale_order_change_analytic_account/readme/CONTRIBUTORS.rst
  sale_order_change_analytic_account/readme/DESCRIPTION.rst
  sale_order_change_analytic_account/security/sale_order_change_analytic.xml
  sale_order_change_analytic_account/tests/__init__.py
  sale_order_change_analytic_account/tests/test_sale_order_change_analytic.py
  sale_order_change_analytic_account/views/sale_order.xml
  sale_order_change_analytic_account/wizards/__init__.py
  sale_order_change_analytic_account/wizards/sale_order_change_analytic.py
  sale_order_change_analytic_account/wizards/sale_order_change_analytic.xml
  setup/sale_order_change_analytic_account/odoo/addons/sale_order_change_analytic_account
  setup/sale_order_change_analytic_account/setup.py
Labels: needs review, bot is merging ⏳, stale
