Repository OCA/sale-workflow, pull requests merged in 2023-07, with the labels that each got.

#2593 [16.0][IMP] sale_tier_validation: Add in ROADMAP sent validation problem
  sale_tier_validation/readme/ROADMAP.rst
Labels: bot is merging ⏳

#2575 [15.0][IMP] sale_order_product_recommendation: add widget units_included_widget
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/static/src/css/units_included_widget.scss
  sale_order_product_recommendation/static/src/js/units_included_widget.js
  sale_order_product_recommendation/static/src/xml/units_included_widget.xml
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#2408 [15.0][FIX] sale_invoice_plan: hide create invoice button
  sale_invoice_plan/views/sale_view.xml
Labels: approved, bot is merging ⏳

#2418 [16.0][MIG] sale_manual_delivery: Migration to 16.0
  sale_manual_delivery/README.rst
  sale_manual_delivery/__init__.py
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/hook.py
  sale_manual_delivery/i18n/es.po
  sale_manual_delivery/i18n/sale_manual_delivery.pot
  sale_manual_delivery/models/__init__.py
  sale_manual_delivery/models/crm_team.py
  sale_manual_delivery/models/procurement_group.py
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/models/sale_order_line.py
  sale_manual_delivery/models/stock_move.py
  sale_manual_delivery/readme/CONTRIBUTORS.rst
  sale_manual_delivery/readme/CREDITS.rst
  sale_manual_delivery/readme/DESCRIPTION.rst
  sale_manual_delivery/security/ir.model.access.csv
  sale_manual_delivery/static/description/field.png
  sale_manual_delivery/static/description/icon.png
  sale_manual_delivery/static/description/icon.svg
  sale_manual_delivery/static/description/index.html
  sale_manual_delivery/static/description/wizard.png
  sale_manual_delivery/tests/__init__.py
  sale_manual_delivery/tests/test_manual_delivery.py
  sale_manual_delivery/views/crm_team.xml
  sale_manual_delivery/views/sale_order.xml
  sale_manual_delivery/wizard/__init__.py
  sale_manual_delivery/wizard/manual_delivery.py
  sale_manual_delivery/wizard/manual_delivery.xml
  sale_manual_delivery/wizard/manual_delivery_line.py
  setup/sale_manual_delivery/odoo/addons/sale_manual_delivery
  setup/sale_manual_delivery/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2478 [14.0][FIX] sale_order_invoicing_finished_task: SOL with qty =< 0
  sale_order_invoicing_finished_task/models/project.py
Labels: approved, ready to merge, bot is merging ⏳

#2586 [13.0][ADD] sale_stock_line_sequence
  .copier-answers.yml
  .github/workflows/test.yml
  sale_stock_line_sequence/__init__.py
  sale_stock_line_sequence/__manifest__.py
  sale_stock_line_sequence/models/__init__.py
  sale_stock_line_sequence/models/sale_order.py
  sale_stock_line_sequence/readme/CONTRIBUTORS.rst
  sale_stock_line_sequence/readme/DESCRIPTION.rst
  sale_stock_line_sequence/tests/__init__.py
  sale_stock_line_sequence/tests/test_line_sequence.py
  setup/sale_stock_line_sequence/odoo/addons/sale_stock_line_sequence
  setup/sale_stock_line_sequence/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2460 [14.0][FIX] Stop deleting lot on sale order cancelation
  sale_order_lot_generator/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2557 [FIX] sale_order_type: Error when hr-expense is installed
  sale_order_type/models/__init__.py
  sale_order_type/models/account_move.py
  sale_order_type/models/res_currency.py
  sale_order_type/readme/CONTRIBUTORS.rst
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2591 [15.0][ADD] sale_order_line_menu: New views and stored fields
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/models/__init__.py
  sale_order_line_menu/models/sale_order_line.py
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.rst
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2599 [14.0][MIG] sale_substate
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/readme/CONTRIBUTORS.rst
  sale_substate/readme/DESCRIPTION.rst
  sale_substate/readme/USAGE.rst
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
  setup/sale_substate/odoo/addons/sale_substate
  setup/sale_substate/setup.py
Labels: approved, bot is merging ⏳

#1983 [14.0][MIG] sale_manual_delivery
  sale_manual_delivery/README.rst
  sale_manual_delivery/__init__.py
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/hook.py
  sale_manual_delivery/i18n/es.po
  sale_manual_delivery/i18n/sale_manual_delivery.pot
  sale_manual_delivery/models/__init__.py
  sale_manual_delivery/models/crm_team.py
  sale_manual_delivery/models/procurement_group.py
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/models/sale_order_line.py
  sale_manual_delivery/models/stock_move.py
  sale_manual_delivery/readme/CONTRIBUTORS.rst
  sale_manual_delivery/readme/DESCRIPTION.rst
  sale_manual_delivery/readme/ROADMAP.rst
  sale_manual_delivery/security/ir.model.access.csv
  sale_manual_delivery/static/description/icon.png
  sale_manual_delivery/static/description/icon.svg
  sale_manual_delivery/static/description/index.html
  sale_manual_delivery/tests/__init__.py
  sale_manual_delivery/tests/test_manual_delivery.py
  sale_manual_delivery/views/crm_team.xml
  sale_manual_delivery/views/sale_order.xml
  sale_manual_delivery/wizard/__init__.py
  sale_manual_delivery/wizard/manual_delivery.py
  sale_manual_delivery/wizard/manual_delivery.xml
  sale_manual_delivery/wizard/manual_delivery_line.py
  setup/sale_manual_delivery/odoo/addons/sale_manual_delivery
  setup/sale_manual_delivery/setup.py
Labels: bot is merging ⏳

#2563 [15.0][IMP] sale_payment_sheet: Allow select invoices instead of remove them
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2560 [15.0][IMP] sale_planner_calendar: Add button to create sale.order from event tree and kanban view
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/models/sale_order.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/models/sale_planner_calendar_issue_type.py
  sale_planner_calendar/static/src/js/sale_planner_calendar_event_sales.js
  sale_planner_calendar/static/src/xml/sale_planner_calendar_event_sales.xml
  sale_planner_calendar/views/sale_planner_calendar_event_view.xml
  sale_planner_calendar/views/sale_planner_calendar_issue_type_view.xml
  sale_planner_calendar/views/sale_planner_calendar_menu.xml
Labels: bot is merging ⏳

#2574 [15.0][MIG] sale_fixed_discount
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/es.po
  sale_fixed_discount/i18n/fr.po
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order.py
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/readme/CONFIGURE.rst
  sale_fixed_discount/readme/CONTRIBUTORS.rst
  sale_fixed_discount/readme/DESCRIPTION.rst
  sale_fixed_discount/readme/INSTALL.rst
  sale_fixed_discount/readme/USAGE.rst
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  sale_fixed_discount/views/sale_portal_templates.xml
  setup/sale_fixed_discount/odoo/addons/sale_fixed_discount
  setup/sale_fixed_discount/setup.py
Labels: bot is merging ⏳

#1427 [13.0][FIX] sale_order_type: Enable copying a sale order with different type_id
  sale_order_type/__manifest__.py
  sale_order_type/models/sale.py
  sale_order_type/readme/CONTRIBUTORS.rst
  sale_order_type/tests/test_sale_order_type.py
Labels: approved, ready to merge, bot is merging ⏳

#2611 [16.0][FIX] sale_order_revision unit tests adapted to base_revision
  sale_order_revision/tests/test_sale_order_revision.py
Labels: bot is merging ⏳

#2578 [16.0][mig] sale_quotation_number: Migration to 16.0
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/ir_sequence_data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/readme/CONFIGURE.rst
  sale_quotation_number/readme/CONTRIBUTORS.rst
  sale_quotation_number/readme/CREDITS.rst
  sale_quotation_number/readme/DESCRIPTION.rst
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
  setup/sale_quotation_number/odoo/addons/sale_quotation_number
  setup/sale_quotation_number/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2617 [FIX] sale_credit_point: Use correct expression for translation
  sale_credit_point/i18n/es.po
Labels: enhancement, bot is merging ⏳

#2615 [15.0][FIX] sale_order_revision: Users can access the smart button Prev. revision
  sale_order_revision/models/sale_order.py
Labels: approved, bot is merging ⏳

#2619 [16.0][IMP]sale_order_line_menu: set no visible sale order line menu …
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳
