Repository OCA/sale-workflow, pull requests merged in 2023-04, with the labels that each got.

#2463 [15.0][IMP] product_supplierinfo_for_customer_sale: Add menu entry to access all product.customerinfo
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
Labels: bot is merging ⏳

#2261 New OCA module: allow different account for discount
  sale_order_discount_invoicing/README.rst
  sale_order_discount_invoicing/__init__.py
  sale_order_discount_invoicing/__manifest__.py
  sale_order_discount_invoicing/i18n/fr.po
  sale_order_discount_invoicing/i18n/sale_order_discount_invoicing.pot
  sale_order_discount_invoicing/models/__init__.py
  sale_order_discount_invoicing/models/account_move.py
  sale_order_discount_invoicing/models/account_move_line.py
  sale_order_discount_invoicing/models/product_category.py
  sale_order_discount_invoicing/models/product_template.py
  sale_order_discount_invoicing/models/res_company.py
  sale_order_discount_invoicing/models/res_config_settings.py
  sale_order_discount_invoicing/models/sale_order_line.py
  sale_order_discount_invoicing/readme/CONFIGURE.rst
  sale_order_discount_invoicing/readme/DESCRIPTION.rst
  sale_order_discount_invoicing/readme/USAGE.rst
  sale_order_discount_invoicing/static/description/index.html
  sale_order_discount_invoicing/tests/__init__.py
  sale_order_discount_invoicing/tests/test_sale_discount.py
  sale_order_discount_invoicing/views/product_category.xml
  sale_order_discount_invoicing/views/product_template.xml
  sale_order_discount_invoicing/views/res_config_settings.xml
  sale_order_discount_invoicing/views/sale_order.xml
  setup/sale_order_discount_invoicing/odoo/addons/sale_order_discount_invoicing
  setup/sale_order_discount_invoicing/setup.py
Labels: approved, bot is merging ⏳

#2441 [15.0][MIG] sale_resource_booking: Migration to version 15.0
  sale_resource_booking/README.rst
  sale_resource_booking/__init__.py
  sale_resource_booking/__manifest__.py
  sale_resource_booking/i18n/es.po
  sale_resource_booking/i18n/fr.po
  sale_resource_booking/i18n/fr_CH.po
  sale_resource_booking/i18n/sale_resource_booking.pot
  sale_resource_booking/models/__init__.py
  sale_resource_booking/models/product_template.py
  sale_resource_booking/models/resource_booking.py
  sale_resource_booking/models/resource_booking_type.py
  sale_resource_booking/models/sale_order.py
  sale_resource_booking/models/sale_order_line.py
  sale_resource_booking/readme/CONFIGURE.rst
  sale_resource_booking/readme/CONTRIBUTORS.rst
  sale_resource_booking/readme/DESCRIPTION.rst
  sale_resource_booking/readme/INSTALL.rst
  sale_resource_booking/readme/USAGE.rst
  sale_resource_booking/security/ir.model.access.csv
  sale_resource_booking/static/description/icon.png
  sale_resource_booking/static/description/index.html
  sale_resource_booking/tests/__init__.py
  sale_resource_booking/tests/test_sale_resource_booking.py
  sale_resource_booking/views/product_template_views.xml
  sale_resource_booking/views/resource_booking_type_views.xml
  sale_resource_booking/views/resource_booking_views.xml
  sale_resource_booking/views/sale_order_views.xml
  sale_resource_booking/wizards/__init__.py
  sale_resource_booking/wizards/resource_booking_sale.py
  sale_resource_booking/wizards/resource_booking_sale_views.xml
  sale_resource_booking/wizards/sale_order_booking_confirm.py
  sale_resource_booking/wizards/sale_order_booking_confirm_views.xml
  setup/sale_resource_booking/odoo/addons/sale_resource_booking
  setup/sale_resource_booking/setup.py
Labels: approved, bot is merging ⏳

#2332 [MIG] product_supplierinfo_for_customer_sale: Migration to 16.0
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/__init__.py
  product_supplierinfo_for_customer_sale/__manifest__.py
  product_supplierinfo_for_customer_sale/i18n/ca.po
  product_supplierinfo_for_customer_sale/i18n/de.po
  product_supplierinfo_for_customer_sale/i18n/es.po
  product_supplierinfo_for_customer_sale/i18n/it.po
  product_supplierinfo_for_customer_sale/i18n/product_supplierinfo_for_customer_sale.pot
  product_supplierinfo_for_customer_sale/i18n/pt.po
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale/readme/ROADMAP.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/security/ir.model.access.csv
  product_supplierinfo_for_customer_sale/static/description/configuration_customer.png
  product_supplierinfo_for_customer_sale/static/description/description_code.png
  product_supplierinfo_for_customer_sale/static/description/description_code_2.png
  product_supplierinfo_for_customer_sale/static/description/icon.png
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/static/description/search_code.png
  product_supplierinfo_for_customer_sale/static/description/search_code_2.png
  product_supplierinfo_for_customer_sale/tests/__init__.py
  product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
  product_supplierinfo_for_customer_sale/views/product_customerinfo_views.xml
  product_supplierinfo_for_customer_sale/views/sale_view.xml
  setup/product_supplierinfo_for_customer_sale/odoo/addons/product_supplierinfo_for_customer_sale
  setup/product_supplierinfo_for_customer_sale/setup.py
Labels: bot is merging ⏳

#2354 [16.0][MIG] sale_company_currency: Migration to 16.0
  sale_company_currency/README.rst
  sale_company_currency/__init__.py
  sale_company_currency/__manifest__.py
  sale_company_currency/i18n/ca.po
  sale_company_currency/i18n/de.po
  sale_company_currency/i18n/el_GR.po
  sale_company_currency/i18n/es.po
  sale_company_currency/i18n/es_ES.po
  sale_company_currency/i18n/es_VE.po
  sale_company_currency/i18n/fi.po
  sale_company_currency/i18n/fr.po
  sale_company_currency/i18n/hr.po
  sale_company_currency/i18n/hr_HR.po
  sale_company_currency/i18n/hu.po
  sale_company_currency/i18n/it.po
  sale_company_currency/i18n/nl.po
  sale_company_currency/i18n/nl_NL.po
  sale_company_currency/i18n/pt.po
  sale_company_currency/i18n/pt_BR.po
  sale_company_currency/i18n/ro.po
  sale_company_currency/i18n/sale_company_currency.pot
  sale_company_currency/i18n/sk.po
  sale_company_currency/i18n/sl.po
  sale_company_currency/i18n/tr.po
  sale_company_currency/i18n/tr_TR.po
  sale_company_currency/i18n/vi_VN.po
  sale_company_currency/i18n/zh_CN.po
  sale_company_currency/models/__init__.py
  sale_company_currency/models/sale_order.py
  sale_company_currency/readme/CONTRIBUTORS.rst
  sale_company_currency/readme/DESCRIPTION.rst
  sale_company_currency/static/description/icon.png
  sale_company_currency/static/description/index.html
  sale_company_currency/views/sale_order_view.xml
  setup/sale_company_currency/odoo/addons/sale_company_currency
  setup/sale_company_currency/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2318 [MIG] sale_order_general_discount: migration to 16.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
  setup/sale_order_general_discount/odoo/addons/sale_order_general_discount
  setup/sale_order_general_discount/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2490 [16.0][IMP]sale_cancel_reason: set reason to false when status is != cancel
  sale_cancel_reason/model/sale.py
Labels: approved, bot is merging ⏳

#2410 [16.0][MIG] sale_invoice_policy: Migration to 16.0
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/ca.po
  sale_invoice_policy/i18n/es.po
  sale_invoice_policy/i18n/es_MX.po
  sale_invoice_policy/i18n/fr.po
  sale_invoice_policy/i18n/pt.po
  sale_invoice_policy/i18n/sale_invoice_policy.pot
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/models/res_config_settings.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/post_init_hook.py
  sale_invoice_policy/readme/CONTRIBUTORS.rst
  sale_invoice_policy/readme/DESCRIPTION.rst
  sale_invoice_policy/readme/USAGE.rst
  sale_invoice_policy/static/description/icon.png
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/__init__.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/product_template_view.xml
  sale_invoice_policy/views/res_config_settings_view.xml
  sale_invoice_policy/views/sale_view.xml
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2492 [14.0][IMP] sale_global_discount, added init hook to avoid memory issues on big database installation
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/hooks.py
Labels: enhancement, needs review, approved, bot is merging ⏳
