Repository OCA/sale-workflow, pull requests merged in 2024-07, with the labels that each got.

#3214 [FIX] sale_block_no_stock: Add notes to sale orders when adjusting or moving quantities
  sale_block_no_stock/README.rst
  sale_block_no_stock/__manifest__.py
  sale_block_no_stock/i18n/es.po
  sale_block_no_stock/i18n/sale_block_no_stock.pot
  sale_block_no_stock/readme/DESCRIPTION.md
  sale_block_no_stock/static/description/index.html
  sale_block_no_stock/tests/test_sale_block_no_stock.py
  sale_block_no_stock/wizard/sale_order_block_wizard.py
Labels: approved, bot is merging ⏳

#3215 [FIX] [16.0] sale_order_line_effective_date: Add commitment date
  sale_order_line_effective_date/README.rst
  sale_order_line_effective_date/i18n/es.po
  sale_order_line_effective_date/i18n/sale_order_line_effective_date.pot
  sale_order_line_effective_date/models/sale_order_line.py
  sale_order_line_effective_date/readme/DESCRIPTION.md
  sale_order_line_effective_date/readme/INSTALL.md
  sale_order_line_effective_date/readme/USAGE.md
  sale_order_line_effective_date/static/description/index.html
  sale_order_line_effective_date/views/sale_order_line.xml
Labels: approved, bot is merging ⏳

#3192 IMP sale_recalculation: allow to recompute several orders
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/action/action.xml
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/readme/CONTRIBUTORS.rst
  sale_order_price_recalculation/readme/DESCRIPTION.rst
  sale_order_price_recalculation/readme/USAGE.rst
  sale_order_price_recalculation/static/description/index.html
Labels: enhancement, needs review, approved, bot is merging ⏳

#3227 [15.0][IMP] sale_planner_calendar: Open links Whatsapp and Location in new window
  sale_planner_calendar/views/sale_planner_calendar_event_view.xml
Labels: approved, bot is merging ⏳

#3201 [17.0][IMP] sale_fixed_discount: prevent using replace in xml view extension
  sale_fixed_discount/views/sale_portal_templates.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3229 [16.0][MIG] sale_order_product_assortment: Migration to version 16.0
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/__init__.py
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/i18n/ca.po
  sale_order_product_assortment/i18n/es.po
  sale_order_product_assortment/i18n/it.po
  sale_order_product_assortment/i18n/sale_order_product_assortment.pot
  sale_order_product_assortment/models/__init__.py
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/readme/CONFIGURE.rst
  sale_order_product_assortment/readme/CONTRIBUTORS.rst
  sale_order_product_assortment/readme/DESCRIPTION.rst
  sale_order_product_assortment/readme/ROADMAP.rst
  sale_order_product_assortment/readme/USAGE.rst
  sale_order_product_assortment/static/description/icon.png
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/__init__.py
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
  sale_order_product_assortment/views/sale_order_view.xml
  setup/sale_order_product_assortment/odoo/addons/sale_order_product_assortment
  setup/sale_order_product_assortment/setup.py
Labels: approved, bot is merging ⏳

#3231 [15.0][IMP] sale_order_product_recommendation_secondary_unit: Change position of secondary uom qty field to maintain coherence with the lines of the order
  sale_order_product_recommendation_secondary_unit/wizards/sale_order_recommendation_view.xml
Labels: approved, bot is merging ⏳

#2127 [13.0][FIX] product_form_sale_link: replace sales_count by a coherent one
  product_form_sale_link/__init__.py
  product_form_sale_link/models/__init__.py
  product_form_sale_link/models/product_product.py
  product_form_sale_link/models/product_template.py
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
Labels: enhancement, approved, bot is merging ⏳

#3239 [16.0][IMP] sale_order_line_sequence: Improved xpath on invoice report
  sale_order_line_sequence/views/report_invoice.xml
Labels: approved, bot is merging ⏳

#3198 [16.0][MIG] sale_planner_calendar: Migration to version 16.0
  sale_planner_calendar/README.rst
  sale_planner_calendar/__init__.py
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/data/sale_planner_calendar_action_server.xml
  sale_planner_calendar/data/sale_planner_calendar_cron.xml
  sale_planner_calendar/data/sale_planner_calendar_data.xml
  sale_planner_calendar/data/sale_planner_calendar_event_profile.xml
  sale_planner_calendar/i18n/ca_ES.po
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/models/__init__.py
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/calendar_attendee.py
  sale_planner_calendar/models/calendar_event_type.py
  sale_planner_calendar/models/res_config_settings.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/models/sale_order.py
  sale_planner_calendar/models/sale_payment_sheet.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/models/sale_planner_calendar_event_profile.py
  sale_planner_calendar/models/sale_planner_calendar_issue_type.py
  sale_planner_calendar/models/sale_planner_calendar_summary.py
  sale_planner_calendar/readme/CONFIGURE.rst
  sale_planner_calendar/readme/CONTRIBUTORS.rst
  sale_planner_calendar/readme/DESCRIPTION.rst
  sale_planner_calendar/readme/USAGE.rst
  sale_planner_calendar/security/ir.model.access.csv
  sale_planner_calendar/security/sale_planner_calendar_security.xml
  sale_planner_calendar/static/description/icon.png
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/static/img/menu_entry.png
  sale_planner_calendar/static/img/smart_button.png
  sale_planner_calendar/static/src/js/form_controller.esm.js
  sale_planner_calendar/static/src/js/list_controller.esm.js
  sale_planner_calendar/static/src/js/sale_planner_calendar_event_sales_kanban_view.esm.js
  sale_planner_calendar/static/src/js/sale_planner_calendar_event_sales_list_view.esm.js
  sale_planner_calendar/static/src/scss/sale_planner_calendar.scss
  sale_planner_calendar/static/src/xml/sale_planner_calendar_event_sales.xml
  sale_planner_calendar/tests/__init__.py
  sale_planner_calendar/tests/test_sale_planner_calendar.py
  sale_planner_calendar/views/calendar_event_type_view.xml
  sale_planner_calendar/views/calendar_view.xml
  sale_planner_calendar/views/res_config_settings_views.xml
  sale_planner_calendar/views/res_partner_view.xml
  sale_planner_calendar/views/sale_planner_calendar_event_profile_view.xml
  sale_planner_calendar/views/sale_planner_calendar_event_view.xml
  sale_planner_calendar/views/sale_planner_calendar_issue_type_view.xml
  sale_planner_calendar/views/sale_planner_calendar_menu.xml
  sale_planner_calendar/views/sale_planner_calendar_summary_view.xml
  sale_planner_calendar/wizard/__init__.py
  sale_planner_calendar/wizard/sale_invoice_payment.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.xml
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.xml
  setup/sale_planner_calendar/odoo/addons/sale_planner_calendar
  setup/sale_planner_calendar/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2273 [13.0][ADD] sale_down_payment_wizard_taxes
  sale_down_payment_wizard_taxes/README.rst
  sale_down_payment_wizard_taxes/__init__.py
  sale_down_payment_wizard_taxes/__manifest__.py
  sale_down_payment_wizard_taxes/readme/CONTRIBUTORS.rst
  sale_down_payment_wizard_taxes/readme/DESCRIPTION.rst
  sale_down_payment_wizard_taxes/readme/USAGE.rst
  sale_down_payment_wizard_taxes/static/description/icon.png
  sale_down_payment_wizard_taxes/static/description/index.html
  sale_down_payment_wizard_taxes/tests/__init__.py
  sale_down_payment_wizard_taxes/tests/test_sale_down_payment_wizard_taxes.py
  sale_down_payment_wizard_taxes/views/sale_make_invoice_advance_views.xml
  sale_down_payment_wizard_taxes/wizards/__init__.py
  sale_down_payment_wizard_taxes/wizards/sale_advance_payment_inv.py
  setup/sale_down_payment_wizard_taxes/odoo/addons/sale_down_payment_wizard_taxes
  setup/sale_down_payment_wizard_taxes/setup.py
Labels: needs review, approved, bot is merging ⏳

#3183 [15.0] Replace 'Camptocamp SA' with 'Camptocamp'
  sale_invoice_no_mail/__manifest__.py
  sale_wishlist/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#3226 [17.0][MIG] sale_order_priority
  sale_order_priority/README.rst
  sale_order_priority/__init__.py
  sale_order_priority/__manifest__.py
  sale_order_priority/i18n/es.po
  sale_order_priority/i18n/it.po
  sale_order_priority/i18n/sale_order_priority.pot
  sale_order_priority/models/__init__.py
  sale_order_priority/models/sale.py
  sale_order_priority/models/stock_picking.py
  sale_order_priority/pyproject.toml
  sale_order_priority/readme/CONTRIBUTORS.md
  sale_order_priority/readme/DESCRIPTION.md
  sale_order_priority/static/description/icon.png
  sale_order_priority/static/description/index.html
  sale_order_priority/tests/__init__.py
  sale_order_priority/tests/test_sale_stock.py
  sale_order_priority/views/sale.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3186 [12.0] Replace 'Camptocamp SA' with 'Camptocamp'
  sale_manual_delivery/__manifest__.py
  sale_milestone_profile_invoicing/__manifest__.py
  sale_wishlist/__manifest__.py
Labels: bot is merging ⏳

#3244 [17.0][MIG] sale_advance_payment: Migration to 17.0
  sale_advance_payment/README.rst
  sale_advance_payment/__init__.py
  sale_advance_payment/__manifest__.py
  sale_advance_payment/i18n/es.po
  sale_advance_payment/i18n/fr.po
  sale_advance_payment/i18n/hr.po
  sale_advance_payment/i18n/it.po
  sale_advance_payment/i18n/sale_advance_payment.pot
  sale_advance_payment/models/__init__.py
  sale_advance_payment/models/account_move.py
  sale_advance_payment/models/payment.py
  sale_advance_payment/models/sale.py
  sale_advance_payment/pyproject.toml
  sale_advance_payment/readme/CONTRIBUTORS.md
  sale_advance_payment/readme/DESCRIPTION.md
  sale_advance_payment/readme/ROADMAP.md
  sale_advance_payment/readme/USAGE.md
  sale_advance_payment/security/ir.model.access.csv
  sale_advance_payment/static/description/icon.png
  sale_advance_payment/static/description/index.html
  sale_advance_payment/tests/__init__.py
  sale_advance_payment/tests/test_sale_advance_payment.py
  sale_advance_payment/views/sale_view.xml
  sale_advance_payment/wizard/__init__.py
  sale_advance_payment/wizard/sale_advance_payment_wzd.py
  sale_advance_payment/wizard/sale_advance_payment_wzd_view.xml
Labels: approved, bot is merging ⏳

#3240 [FIX] sale_company_currency: Changes on currency rate application
  sale_company_currency/models/sale_order.py
Labels: approved, bot is merging ⏳

#3251 [FIX]sale_order_type_quotation_number: wrong icon
  sale_order_type_quotation_number/static/description/icon.png
Labels: bot is merging ⏳

#2949 [ADD] sale_order_line_delivery_state: added filter goods not delivered on order line search
  sale_order_line_delivery_state/README.rst
  sale_order_line_delivery_state/__manifest__.py
  sale_order_line_delivery_state/static/description/index.html
  sale_order_line_delivery_state/views/sale_order_line_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3250 [17.0][MIG] sale_force_whole_invoiceability: Migration to 17.0
  sale_force_whole_invoiceability/README.rst
  sale_force_whole_invoiceability/__init__.py
  sale_force_whole_invoiceability/__manifest__.py
  sale_force_whole_invoiceability/i18n/es.po
  sale_force_whole_invoiceability/i18n/sale_force_whole_invoiceability.pot
  sale_force_whole_invoiceability/models/__init__.py
  sale_force_whole_invoiceability/models/sale_order.py
  sale_force_whole_invoiceability/pyproject.toml
  sale_force_whole_invoiceability/readme/CONTRIBUTORS.md
  sale_force_whole_invoiceability/readme/DESCRIPTION.md
  sale_force_whole_invoiceability/readme/ROADMAP.md
  sale_force_whole_invoiceability/readme/USAGE.md
  sale_force_whole_invoiceability/static/description/icon.png
  sale_force_whole_invoiceability/static/description/index.html
  sale_force_whole_invoiceability/tests/__init__.py
  sale_force_whole_invoiceability/tests/test_sale_force_whole.py
  sale_force_whole_invoiceability/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#3204 [17.0][MIG/IMP] sale_validity_auto_cancel: Migration to 17.0
  sale_validity_auto_cancel/README.rst
  sale_validity_auto_cancel/__init__.py
  sale_validity_auto_cancel/__manifest__.py
  sale_validity_auto_cancel/data/ir_cron.xml
  sale_validity_auto_cancel/i18n/sale_validity_auto_cancel.pot
  sale_validity_auto_cancel/models/__init__.py
  sale_validity_auto_cancel/models/res_company.py
  sale_validity_auto_cancel/models/res_config_settings.py
  sale_validity_auto_cancel/models/res_partner.py
  sale_validity_auto_cancel/models/sale_order.py
  sale_validity_auto_cancel/pyproject.toml
  sale_validity_auto_cancel/readme/CONFIGURE.md
  sale_validity_auto_cancel/readme/CONTRIBUTORS.md
  sale_validity_auto_cancel/readme/DESCRIPTION.md
  sale_validity_auto_cancel/readme/USAGE.md
  sale_validity_auto_cancel/static/description/icon.png
  sale_validity_auto_cancel/static/description/index.html
  sale_validity_auto_cancel/tests/__init__.py
  sale_validity_auto_cancel/tests/test_sale_validity_auto_cancel.py
  sale_validity_auto_cancel/views/res_config_settings.xml
  sale_validity_auto_cancel/views/res_partner_views.xml
Labels: needs review, approved, migration, bot is merging ⏳
