Repository OCA/sale-workflow, pull requests merged in 2024-03, with the labels that each got.

#2983 [15.0][FIX] sale_custom_rounding: Do not call super with empty recordset
  sale_custom_rounding/models/sale_order.py
  sale_custom_rounding/tests/test_sale_custom_rounding.py
Labels: approved, bot is merging ⏳

#2927 [14.0][IMP]sale_blanket_order: refactor module making it similar to sale_order
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/res_company.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/readme/CONFIGURE.rst
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/wizard/create_sale_orders.py
Labels: enhancement, needs review, bot is merging ⏳

#2952 [17.0][MIG]sale_fixed_discount: Migrated module to v17.0
  sale_fixed_discount/README.rst
  sale_fixed_discount/__init__.py
  sale_fixed_discount/__manifest__.py
  sale_fixed_discount/i18n/es.po
  sale_fixed_discount/i18n/fr.po
  sale_fixed_discount/i18n/it.po
  sale_fixed_discount/i18n/pt_BR.po
  sale_fixed_discount/i18n/sale_fixed_discount.pot
  sale_fixed_discount/models/__init__.py
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/pyproject.toml
  sale_fixed_discount/readme/CONFIGURE.md
  sale_fixed_discount/readme/CONTRIBUTORS.md
  sale_fixed_discount/readme/DESCRIPTION.md
  sale_fixed_discount/readme/INSTALL.md
  sale_fixed_discount/readme/USAGE.md
  sale_fixed_discount/reports/report_sale_order.xml
  sale_fixed_discount/security/res_groups.xml
  sale_fixed_discount/static/description/icon.png
  sale_fixed_discount/static/description/index.html
  sale_fixed_discount/tests/__init__.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
  sale_fixed_discount/views/account_invoice_views.xml
  sale_fixed_discount/views/sale_order_views.xml
  sale_fixed_discount/views/sale_portal_templates.xml
Labels: bot is merging ⏳

#3004 [FIX] sale_order_product_recommendation: product category field string
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: bug, bot is merging ⏳

#3003 [16.0] [FIX] sale_elaboration: Do not print Elaboration on incoming pickings
  sale_elaboration/README.rst
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/static/description/index.html
Labels: approved, bot is merging ⏳

#2991 [14.0][FIX] sale_restricted_qty: typos & duplicate fields
  sale_restricted_qty/README.rst
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/i18n/es.po
  sale_restricted_qty/i18n/fr.po
  sale_restricted_qty/i18n/it.po
  sale_restricted_qty/i18n/sale_restricted_qty.pot
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2977 [16.0][IMP] sale_auto_remove_zero_quantity_lines: implement conditions in a hook to make customization easier
  sale_auto_remove_zero_quantity_lines/models/sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3002 [14.0][FIX]sale_blanket_order_revision: enable module
  sale_blanket_order_revision/__manifest__.py
  setup/sale_blanket_order_revision/odoo/addons/sale_blanket_order_revision
  setup/sale_blanket_order_revision/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2976 [16.0][IMP] sale_order_carrier_auto_assign
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/models/__init__.py
  sale_order_carrier_auto_assign/models/res_company.py
  sale_order_carrier_auto_assign/models/res_config_settings.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/readme/CONFIGURE.rst
  sale_order_carrier_auto_assign/readme/CONTRIBUTORS.rst
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
  sale_order_carrier_auto_assign/views/res_config_settings_views.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2969 [16.0][IMP] sale_stock_picking_blocking: allow lock state on sale order
  sale_stock_picking_blocking/models/sale_order.py
  sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py
Labels: approved, ready to merge, bot is merging ⏳

#2970 [16.0][IMP] sale_auto_remove_zero_quantity_lines: exclude lines that don't have a product_id
  sale_auto_remove_zero_quantity_lines/models/sale_order.py
  sale_auto_remove_zero_quantity_lines/tests/test_sale_auto_remove_zero_quantity_lines.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3012 [15.0][IMP] sale_planner_calendar: Do not notify to attendees
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
  sale_planner_calendar/wizard/sale_planner_calendar_wizard.py
Labels: approved, bot is merging ⏳

#3009 [16.0][IMP] sale_product_set: Move the base logic of the transient model to product_set
  sale_product_set/README.rst
  sale_product_set/__manifest__.py
  sale_product_set/readme/CONTRIBUTORS.rst
  sale_product_set/security/ir.model.access.csv
  sale_product_set/static/description/index.html
  sale_product_set/tests/test_product_set.py
  sale_product_set/wizard/__init__.py
  sale_product_set/wizard/sale_product_set_wizard.py
  sale_product_set/wizard/sale_product_set_wizard_view.xml
Labels: bot is merging ⏳

#3017 [15.0][IMP] sale_planner_calendar: Do not create attendees is no mail option selected
  sale_planner_calendar/i18n/ca_ES.po
  sale_planner_calendar/i18n/es.po
  sale_planner_calendar/i18n/sale_planner_calendar.pot
  sale_planner_calendar/models/__init__.py
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/calendar_attendee.py
  sale_planner_calendar/models/sale_planner_calendar_summary.py
  sale_planner_calendar/views/calendar_view.xml
Labels: approved, bot is merging ⏳

#3015 [IMP] sale_packaging_default: keep packaging qty when changing product
  sale_packaging_default/README.rst
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/readme/USAGE.md
  sale_packaging_default/static/description/index.html
  sale_packaging_default/tests/test_sale_packaging_default.py
Labels: needs review, approved, bot is merging ⏳

#2993 [14.0][MIG] sale_order_amount_to_invoice: Migration to 14.0
  sale_order_amount_to_invoice/README.rst
  sale_order_amount_to_invoice/__init__.py
  sale_order_amount_to_invoice/__manifest__.py
  sale_order_amount_to_invoice/i18n/it.po
  sale_order_amount_to_invoice/i18n/sale_order_amount_to_invoice.pot
  sale_order_amount_to_invoice/models/__init__.py
  sale_order_amount_to_invoice/models/sale_order.py
  sale_order_amount_to_invoice/readme/CONFIGURE.md
  sale_order_amount_to_invoice/readme/CONTEXT.md
  sale_order_amount_to_invoice/readme/CONTRIBUTORS.md
  sale_order_amount_to_invoice/readme/DESCRIPTION.md
  sale_order_amount_to_invoice/readme/USAGE.md
  sale_order_amount_to_invoice/static/description/icon.png
  sale_order_amount_to_invoice/static/description/index.html
  sale_order_amount_to_invoice/tests/__init__.py
  sale_order_amount_to_invoice/tests/test_sale_order_invoice_amount.py
  sale_order_amount_to_invoice/views/sale_order_view.xml
  setup/sale_order_amount_to_invoice/odoo/addons/sale_order_amount_to_invoice
  setup/sale_order_amount_to_invoice/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3021 [16.0][FIX] sale_fixed_discount: Division by zero
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
Labels: approved, bot is merging ⏳

#3027 [15.0][IMP] sale_planner_calendar: Allow create so from event planned to commercial partner with a system parameter
  sale_planner_calendar/README.rst
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/readme/CONFIGURE.rst
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/tests/test_sale_planner_calendar.py
Labels: approved, ready to merge, bot is merging ⏳

#3029 [FIX] sale_elaboration: propagate note-only lines to stock moves
  sale_elaboration/README.rst
  sale_elaboration/__manifest__.py
  sale_elaboration/models/stock_rule.py
  sale_elaboration/readme/CONTRIBUTORS.rst
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/test_sale_elaboration.py
Labels: needs review, approved, bot is merging ⏳

#3040 [15.0][FIX] sale_order_line_price_history: Change partner do not populated in lines
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
Labels: approved, bot is merging ⏳

#3028 [16.0][IMP] sale_order_product_recommendation: improve performance of propagating recommendations to sale order
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/sale_order.py
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_elaboration/README.rst
  sale_order_product_recommendation_elaboration/readme/CONTRIBUTORS.md
  sale_order_product_recommendation_elaboration/static/description/index.html
  sale_order_product_recommendation_elaboration/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_packaging_default/README.rst
  sale_order_product_recommendation_packaging_default/readme/CONTRIBUTORS.md
  sale_order_product_recommendation_packaging_default/static/description/index.html
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
Labels: approved, ready to merge, bot is merging ⏳

#3011 [16.0][IMP] sale_product_packaging_container_deposit: Avoid forbidden modifying locked SO when updating order container deposit quantity
  sale_product_packaging_container_deposit/models/sale_order_line.py
  sale_product_packaging_container_deposit/tests/test_sale_product_packaging_container_deposit.py
Labels: approved, bot is merging ⏳

#3045 [FIX] sale_product_rating_verified: Don't set computed method to required
  sale_product_rating_verified/models/rating.py
Labels: needs review, bot is merging ⏳

#3010 [14.0][FIX] sale_restricted_qty: remove post-migration junk
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/tests/test_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2961 [17.0] [MIG] sale_force_invoiced: migration to 17.0
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/pyproject.toml
  sale_force_invoiced/readme/CONTRIBUTORS.md
  sale_force_invoiced/readme/DESCRIPTION.md
  sale_force_invoiced/readme/USAGE.md
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3042 [14.0] [IMP] sale_triple_discount: improve module extensibility
  sale_triple_discount/models/sale_order_line.py
Labels: approved, bot is merging ⏳
