Repository OCA/sale-workflow, pull requests merged in 2024-12, with the labels that each got.

#3398 [18.0][MIG] sale_force_invoiced
  sale_force_invoiced/README.rst
  sale_force_invoiced/__init__.py
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/i18n/ca.po
  sale_force_invoiced/i18n/de.po
  sale_force_invoiced/i18n/el_GR.po
  sale_force_invoiced/i18n/es.po
  sale_force_invoiced/i18n/es_ES.po
  sale_force_invoiced/i18n/es_VE.po
  sale_force_invoiced/i18n/fi.po
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/hr.po
  sale_force_invoiced/i18n/hr_HR.po
  sale_force_invoiced/i18n/hu.po
  sale_force_invoiced/i18n/it.po
  sale_force_invoiced/i18n/nl.po
  sale_force_invoiced/i18n/nl_NL.po
  sale_force_invoiced/i18n/pt.po
  sale_force_invoiced/i18n/pt_BR.po
  sale_force_invoiced/i18n/ro.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/i18n/sk.po
  sale_force_invoiced/i18n/sl.po
  sale_force_invoiced/i18n/tr.po
  sale_force_invoiced/i18n/tr_TR.po
  sale_force_invoiced/i18n/vi_VN.po
  sale_force_invoiced/i18n/zh_CN.po
  sale_force_invoiced/migrations/18.0.1.0.0/post-migration.py
  sale_force_invoiced/model/__init__.py
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/pyproject.toml
  sale_force_invoiced/readme/CONTRIBUTORS.md
  sale_force_invoiced/readme/DESCRIPTION.md
  sale_force_invoiced/readme/USAGE.md
  sale_force_invoiced/security/security.xml
  sale_force_invoiced/static/description/icon.png
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/__init__.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/view/sale_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3442 [FIX] [16.0] sale_order_product_recommendation_packaging_default: Do not update packaging if quantities has not changed
  sale_order_product_recommendation_packaging_default/tests/test_recommendation.py
  sale_order_product_recommendation_packaging_default/wizards/sale_order_recommendation.py
Labels: approved, bot is merging ⏳

#3037 [16.0][IMP] sale_order_product_picker: Support use of discounts
  sale_order_product_picker/README.rst
  sale_order_product_picker/__manifest__.py
  sale_order_product_picker/i18n/es.po
  sale_order_product_picker/i18n/sale_order_product_picker.pot
  sale_order_product_picker/models/__init__.py
  sale_order_product_picker/models/ir_config_parameter.py
  sale_order_product_picker/models/sale_order.py
  sale_order_product_picker/models/sale_order_picker.py
  sale_order_product_picker/readme/CONFIGURE.rst
  sale_order_product_picker/static/description/index.html
  sale_order_product_picker/static/src/form/form_controller.esm.js
  sale_order_product_picker/static/src/kanban/kanban_record.esm.js
  sale_order_product_picker/static/src/scss/picker.scss
  sale_order_product_picker/static/src/utils/picker_change_processor.esm.js
  sale_order_product_picker/static/src/x2many/x2many_field.esm.js
  sale_order_product_picker/views/sale_order_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3305 [17.0][FIX] sale_quotation_number: fix numbering to be compatible with sale_order_revision
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/tests/test_sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3126 [17.0][MIG] sale_partner_selectable_option
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__init__.py
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/data/ir_config_parameter.xml
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/it.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/__init__.py
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/models/sale_order.py
  sale_partner_selectable_option/pyproject.toml
  sale_partner_selectable_option/readme/CONFIGURE.md
  sale_partner_selectable_option/readme/CONTRIBUTORS.md
  sale_partner_selectable_option/readme/DESCRIPTION.md
  sale_partner_selectable_option/readme/USAGE.md
  sale_partner_selectable_option/static/description/icon.png
  sale_partner_selectable_option/static/description/index.html
  sale_partner_selectable_option/tests/__init__.py
  sale_partner_selectable_option/tests/test_sale_partner_selectable_option.py
  sale_partner_selectable_option/views/res_partner_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3179 [14.0] sale_order_lot_selection: fix perf issue
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2387 [13.0][IMP] new function for inheritance in sale_manual_delivery
  sale_manual_delivery/wizard/manual_delivery.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2364 [16.0][MIG] sale_order_tag
  sale_order_tag/README.rst
  sale_order_tag/__init__.py
  sale_order_tag/__manifest__.py
  sale_order_tag/data/sale_order_tag_data.xml
  sale_order_tag/i18n/ca.po
  sale_order_tag/i18n/es.po
  sale_order_tag/i18n/it.po
  sale_order_tag/i18n/sale_order_tag.pot
  sale_order_tag/i18n/tr.po
  sale_order_tag/models/__init__.py
  sale_order_tag/models/sale_order.py
  sale_order_tag/models/sale_order_tag.py
  sale_order_tag/readme/CONTRIBUTORS.rst
  sale_order_tag/readme/DESCRIPTION.rst
  sale_order_tag/readme/USAGE.rst
  sale_order_tag/security/ir.model.access.csv
  sale_order_tag/security/sale_order_tag_security.xml
  sale_order_tag/static/description/icon.png
  sale_order_tag/static/description/index.html
  sale_order_tag/views/sale_order.xml
  sale_order_tag/views/sale_order_tag.xml
  setup/sale_order_tag/odoo/addons/sale_order_tag
  setup/sale_order_tag/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2988 [16.0][MIG] sale_invoice_plan, standard migration to 16.0
  .pre-commit-config.yaml
  sale_invoice_plan/README.rst
  sale_invoice_plan/__init__.py
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/data/sale_data.xml
  sale_invoice_plan/i18n/es.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/__init__.py
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/readme/CONTRIBUTORS.rst
  sale_invoice_plan/readme/CREDITS.rst
  sale_invoice_plan/readme/DESCRIPTION.rst
  sale_invoice_plan/readme/HISTORY.rst
  sale_invoice_plan/readme/INSTALL.rst
  sale_invoice_plan/readme/USAGE.rst
  sale_invoice_plan/security/ir.model.access.csv
  sale_invoice_plan/static/description/icon.png
  sale_invoice_plan/static/description/index.html
  sale_invoice_plan/tests/__init__.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/__init__.py
  sale_invoice_plan/wizard/sale_create_invoice_plan.py
  sale_invoice_plan/wizard/sale_create_invoice_plan_view.xml
  sale_invoice_plan/wizard/sale_make_invoice_advance.py
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
  sale_invoice_plan/wizard/sale_make_planned_invoice_view.xml
  setup/sale_invoice_plan/odoo/addons/sale_invoice_plan
  setup/sale_invoice_plan/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3432 [ADD] [16.0] sale_order_line_product_attribute_values
  sale_order_line_product_attribute_values/README.rst
  sale_order_line_product_attribute_values/__init__.py
  sale_order_line_product_attribute_values/__manifest__.py
  sale_order_line_product_attribute_values/i18n/es.po
  sale_order_line_product_attribute_values/i18n/sale_order_line_product_attribute_values.pot
  sale_order_line_product_attribute_values/models/__init__.py
  sale_order_line_product_attribute_values/models/sale_order_line.py
  sale_order_line_product_attribute_values/readme/CONFIGURE.md
  sale_order_line_product_attribute_values/readme/CONTEXT.md
  sale_order_line_product_attribute_values/readme/CONTRIBUTORS.md
  sale_order_line_product_attribute_values/readme/DESCRIPTION.md
  sale_order_line_product_attribute_values/readme/USAGE.md
  sale_order_line_product_attribute_values/static/description/icon.png
  sale_order_line_product_attribute_values/static/description/index.html
  sale_order_line_product_attribute_values/tests/__init__.py
  sale_order_line_product_attribute_values/tests/test_sale_order_line.py
  sale_order_line_product_attribute_values/views/sale_order_line_view.xml
  setup/sale_order_line_product_attribute_values/odoo/addons/sale_order_line_product_attribute_values
  setup/sale_order_line_product_attribute_values/setup.py
Labels: needs review, approved, bot is merging ⏳

#3498 [FIX] [16.0] sale_elaboration: Apply groups to views correctly
  sale_elaboration/README.rst
  sale_elaboration/readme/CONFIGURE.rst
  sale_elaboration/readme/USAGE.rst
  sale_elaboration/reports/report_base.xml
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/reports/report_picking_operations.xml
  sale_elaboration/static/description/index.html
Labels: needs review, approved, bot is merging ⏳

#3502 [17.0][ADD] sale_multi_template_application: new module to allow applying multiple templates to a sale order
  sale_multi_template_application/README.rst
  sale_multi_template_application/__init__.py
  sale_multi_template_application/__manifest__.py
  sale_multi_template_application/models/__init__.py
  sale_multi_template_application/models/sale_order.py
  sale_multi_template_application/pyproject.toml
  sale_multi_template_application/readme/CONFIGURE.md
  sale_multi_template_application/readme/CONTRIBUTORS.md
  sale_multi_template_application/readme/DESCRIPTION.md
  sale_multi_template_application/readme/USAGE.md
  sale_multi_template_application/static/description/icon.png
  sale_multi_template_application/static/description/index.html
  sale_multi_template_application/tests/__init__.py
  sale_multi_template_application/tests/test_sale_multi_template_application.py
Labels: approved, bot is merging ⏳

#3484 [14.0][IMP]product_supplierinfo_for_customer_sale: Search SO by customerinfo
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳
