Repository OCA/sale-workflow, pull requests merged in 2024-08, with the labels that each got.

#2715 [15.0][MIG] sale_order_partner_no_autofollow
  sale_order_partner_no_autofollow/README.rst
  sale_order_partner_no_autofollow/__init__.py
  sale_order_partner_no_autofollow/__manifest__.py
  sale_order_partner_no_autofollow/i18n/sale_order_partner_no_autofollow.pot
  sale_order_partner_no_autofollow/models/__init__.py
  sale_order_partner_no_autofollow/models/res_config_settings.py
  sale_order_partner_no_autofollow/models/sale_order.py
  sale_order_partner_no_autofollow/readme/CONFIGURE.rst
  sale_order_partner_no_autofollow/readme/DESCRIPTION.rst
  sale_order_partner_no_autofollow/static/description/icon.png
  sale_order_partner_no_autofollow/static/description/index.html
  sale_order_partner_no_autofollow/tests/__init__.py
  sale_order_partner_no_autofollow/tests/common.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_disabled.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_enabled.py
  sale_order_partner_no_autofollow/views/res_config_settings.xml
  setup/sale_order_partner_no_autofollow/odoo/addons/sale_order_partner_no_autofollow
  setup/sale_order_partner_no_autofollow/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2962 [17.0] [MIG] sale_order_line_date: migration to 17.0
  sale_order_line_date/README.rst
  sale_order_line_date/__init__.py
  sale_order_line_date/__manifest__.py
  sale_order_line_date/i18n/ca.po
  sale_order_line_date/i18n/de.po
  sale_order_line_date/i18n/el_GR.po
  sale_order_line_date/i18n/es.po
  sale_order_line_date/i18n/es_ES.po
  sale_order_line_date/i18n/es_VE.po
  sale_order_line_date/i18n/fi.po
  sale_order_line_date/i18n/fr.po
  sale_order_line_date/i18n/hr.po
  sale_order_line_date/i18n/hr_HR.po
  sale_order_line_date/i18n/hu.po
  sale_order_line_date/i18n/it.po
  sale_order_line_date/i18n/nl.po
  sale_order_line_date/i18n/nl_NL.po
  sale_order_line_date/i18n/pt.po
  sale_order_line_date/i18n/pt_BR.po
  sale_order_line_date/i18n/ro.po
  sale_order_line_date/i18n/sale_order_line_date.pot
  sale_order_line_date/i18n/sk.po
  sale_order_line_date/i18n/sl.po
  sale_order_line_date/i18n/tr.po
  sale_order_line_date/i18n/tr_TR.po
  sale_order_line_date/i18n/vi_VN.po
  sale_order_line_date/i18n/zh_CN.po
  sale_order_line_date/models/__init__.py
  sale_order_line_date/models/sale_order.py
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/pyproject.toml
  sale_order_line_date/readme/CONTRIBUTORS.md
  sale_order_line_date/readme/DESCRIPTION.md
  sale_order_line_date/readme/USAGE.md
  sale_order_line_date/reports/sale_order_report.xml
  sale_order_line_date/static/description/icon.png
  sale_order_line_date/static/description/index.html
  sale_order_line_date/tests/__init__.py
  sale_order_line_date/tests/test_sale_order_line_date.py
  sale_order_line_date/views/sale_order_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3271 [16.0][MIG] sale_order_partner_no_autofollow
  sale_order_partner_no_autofollow/README.rst
  sale_order_partner_no_autofollow/__init__.py
  sale_order_partner_no_autofollow/__manifest__.py
  sale_order_partner_no_autofollow/i18n/sale_order_partner_no_autofollow.pot
  sale_order_partner_no_autofollow/models/__init__.py
  sale_order_partner_no_autofollow/models/res_config_settings.py
  sale_order_partner_no_autofollow/models/sale_order.py
  sale_order_partner_no_autofollow/readme/CONFIGURE.rst
  sale_order_partner_no_autofollow/readme/DESCRIPTION.rst
  sale_order_partner_no_autofollow/static/description/icon.png
  sale_order_partner_no_autofollow/static/description/index.html
  sale_order_partner_no_autofollow/tests/__init__.py
  sale_order_partner_no_autofollow/tests/common.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_disabled.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_enabled.py
  sale_order_partner_no_autofollow/views/res_config_settings.xml
  setup/sale_order_partner_no_autofollow/odoo/addons/sale_order_partner_no_autofollow
  setup/sale_order_partner_no_autofollow/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3270 [16.0][IMP] sale_delivery_split_date: use security lead time
  sale_delivery_split_date/models/sale_order_line.py
  sale_delivery_split_date/tests/test_sale_delivery.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3233 [16.0][ADD] sale_force_invoiced_qty: add module
  sale_force_invoiced_quantity/README.rst
  sale_force_invoiced_quantity/__init__.py
  sale_force_invoiced_quantity/__manifest__.py
  sale_force_invoiced_quantity/demo/demo_product.xml
  sale_force_invoiced_quantity/demo/demo_sale_order.xml
  sale_force_invoiced_quantity/models/__init__.py
  sale_force_invoiced_quantity/models/sale_order_line.py
  sale_force_invoiced_quantity/readme/CONFIGURE.rst
  sale_force_invoiced_quantity/readme/CONTEXT.rst
  sale_force_invoiced_quantity/readme/CONTRIBUTORS.rst
  sale_force_invoiced_quantity/readme/DESCRIPTION.rst
  sale_force_invoiced_quantity/readme/USAGE.rst
  sale_force_invoiced_quantity/static/description/index.html
  sale_force_invoiced_quantity/tests/__init__.py
  sale_force_invoiced_quantity/tests/test_sale_force_invoiced_qty.py
  sale_force_invoiced_quantity/views/sale_order.xml
  setup/sale_force_invoiced_quantity/odoo/addons/sale_force_invoiced_quantity
  setup/sale_force_invoiced_quantity/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3242 [17.0][MIG] sale_order_product_recommendation: Migration to 17.0
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/it.po
  sale_order_product_recommendation/i18n/pt_BR.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_company.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/pyproject.toml
  sale_order_product_recommendation/readme/CONFIGURE.md
  sale_order_product_recommendation/readme/CONTRIBUTORS.md
  sale_order_product_recommendation/readme/DESCRIPTION.md
  sale_order_product_recommendation/readme/USAGE.md
  sale_order_product_recommendation/security/ir.model.access.csv
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: approved, migration, bot is merging ⏳

#3259 [17.0][MIG] sale_order_lot_selection: Migration to 17.0
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/pyproject.toml
  sale_order_lot_selection/readme/CONTRIBUTORS.md
  sale_order_lot_selection/readme/DESCRIPTION.md
  sale_order_lot_selection/readme/ROADMAP.md
  sale_order_lot_selection/readme/USAGE.md
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/views/sale_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3241 [16.0][FIX] sale_blanket_order: fix form view
  sale_blanket_order/views/sale_blanket_order_line_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2968 [17.0][MIG] sale_partner_incoterm: Migration to 17.0
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/pyproject.toml
  sale_partner_incoterm/readme/CONTRIBUTORS.md
  sale_partner_incoterm/readme/DESCRIPTION.md
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3283 [FIX] sale_automatic_workflow: Use of freeze time to test sale/invoice dates
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3269 [16.0][IMP] sale_tier_validation: add the option for blocking sale order print
  sale_tier_validation/README.rst
  sale_tier_validation/__init__.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/models/__init__.py
  sale_tier_validation/models/res_company.py
  sale_tier_validation/models/res_config_settings.py
  sale_tier_validation/readme/CONFIGURE.md
  sale_tier_validation/readme/CONTRIBUTORS.md
  sale_tier_validation/reports/__init__.py
  sale_tier_validation/reports/sale_report.py
  sale_tier_validation/static/description/index.html
  sale_tier_validation/tests/test_tier_validation.py
  sale_tier_validation/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3172 [16.0][FIX] sale_blanket_order: not require taxes on blanket orders
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3281 [16.0][ADD] sale_order_search_line
  sale_order_search_line/README.rst
  sale_order_search_line/__init__.py
  sale_order_search_line/__manifest__.py
  sale_order_search_line/readme/DESCRIPTION.rst
  sale_order_search_line/static/description/index.html
  sale_order_search_line/views/sale_order_views.xml
  setup/sale_order_search_line/odoo/addons/sale_order_search_line
  setup/sale_order_search_line/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3292 [17.0][FIX]sale_order_priority: Fix tests
  sale_order_priority/tests/test_sale_stock.py
Labels: approved, bot is merging ⏳
