Repository OCA/sale-workflow, pull requests merged in 2024-05, with the labels that each got.

#3114 [IMP] sale_discount_display_amount: hide total discount on reports when it is equal to zero.
  sale_discount_display_amount/report/sale_report_template.xml
Labels: approved, bot is merging ⏳

#2596 [16.0] [MIG] sale_order_report_without_price
  sale_order_report_without_price/README.rst
  sale_order_report_without_price/__init__.py
  sale_order_report_without_price/__manifest__.py
  sale_order_report_without_price/i18n/sale_order_report_without_price.pot
  sale_order_report_without_price/readme/CONTRIBUTORS.rst
  sale_order_report_without_price/readme/DESCRIPTION.rst
  sale_order_report_without_price/readme/USAGE.rst
  sale_order_report_without_price/report/sale_report.xml
  sale_order_report_without_price/report/sale_report_templates.xml
  sale_order_report_without_price/static/description/icon.png
  sale_order_report_without_price/static/description/index.html
  setup/sale_order_report_without_price/odoo/addons/sale_order_report_without_price
  setup/sale_order_report_without_price/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#2553 [15.0][ADD] sale_fully_invoiced
  sale_fully_invoiced/README.rst
  sale_fully_invoiced/__init__.py
  sale_fully_invoiced/__manifest__.py
  sale_fully_invoiced/models/__init__.py
  sale_fully_invoiced/models/sale.py
  sale_fully_invoiced/readme/CONTRIBUTORS.rst
  sale_fully_invoiced/readme/DESCRIPTION.rst
  sale_fully_invoiced/readme/USAGE.rst
  sale_fully_invoiced/static/description/index.html
  sale_fully_invoiced/tests/__init__.py
  sale_fully_invoiced/tests/test_sale_fully_invoiced.py
  sale_fully_invoiced/views/sale_views.xml
  setup/sale_fully_invoiced/odoo/addons/sale_fully_invoiced
  setup/sale_fully_invoiced/setup.py
Labels: approved, bot is merging ⏳

#3102 [16.0][FIX] sale_invoice_policy: compute qty to invoice
  .pre-commit-config.yaml
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/product_template.py
  sale_invoice_policy/models/res_config_settings.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/post_init_hook.py
  sale_invoice_policy/readme/CONTRIBUTORS.rst
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/product_template_view.xml
  sale_invoice_policy/views/res_config_settings_view.xml
  setup/sale_invoice_policy/odoo/addons/sale_invoice_policy
  setup/sale_invoice_policy/setup.py
Labels: bot is merging ⏳

#2186 [14.0] [IMP] `sale_invoice_blocking`: Make field readonly for cancelled orders
  sale_invoice_blocking/models/sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2642 [16.0][IMP] sale_automatic_workflow: add send invoice option
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/data/automatic_workflow_data.xml
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/readme/CONTRIBUTORS.rst
  sale_automatic_workflow/readme/DESCRIPTION.rst
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/tests/test_multicompany.py
  sale_automatic_workflow/views/sale_workflow_process_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2973 [17.0][MIG] sale_manual_delivery: Migration to 17.0
  sale_manual_delivery/README.rst
  sale_manual_delivery/__init__.py
  sale_manual_delivery/__manifest__.py
  sale_manual_delivery/hook.py
  sale_manual_delivery/i18n/es.po
  sale_manual_delivery/i18n/it.po
  sale_manual_delivery/i18n/sale_manual_delivery.pot
  sale_manual_delivery/models/__init__.py
  sale_manual_delivery/models/crm_team.py
  sale_manual_delivery/models/procurement_group.py
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/models/sale_order_line.py
  sale_manual_delivery/models/stock_move.py
  sale_manual_delivery/pyproject.toml
  sale_manual_delivery/readme/CONTRIBUTORS.md
  sale_manual_delivery/readme/CREDITS.md
  sale_manual_delivery/readme/DESCRIPTION.md
  sale_manual_delivery/security/ir.model.access.csv
  sale_manual_delivery/static/description/field.png
  sale_manual_delivery/static/description/icon.png
  sale_manual_delivery/static/description/icon.svg
  sale_manual_delivery/static/description/index.html
  sale_manual_delivery/static/description/wizard.png
  sale_manual_delivery/tests/__init__.py
  sale_manual_delivery/tests/test_manual_delivery.py
  sale_manual_delivery/views/crm_team.xml
  sale_manual_delivery/views/sale_order.xml
  sale_manual_delivery/wizard/__init__.py
  sale_manual_delivery/wizard/manual_delivery.py
  sale_manual_delivery/wizard/manual_delivery.xml
  sale_manual_delivery/wizard/manual_delivery_line.py
Labels: needs review, migration, bot is merging ⏳

#3076 [ADD] [15.0] sale_warn_option
  sale_warn_option/README.rst
  sale_warn_option/__init__.py
  sale_warn_option/__manifest__.py
  sale_warn_option/i18n/es.po
  sale_warn_option/i18n/sale_warn_option.pot
  sale_warn_option/models/__init__.py
  sale_warn_option/models/product_template.py
  sale_warn_option/models/res_partner.py
  sale_warn_option/models/warn_option.py
  sale_warn_option/readme/CONTEXT.md
  sale_warn_option/readme/CONTRIBUTORS.md
  sale_warn_option/readme/DESCRIPTION.md
  sale_warn_option/readme/USAGE.md
  sale_warn_option/static/description/icon.png
  sale_warn_option/static/description/index.html
  sale_warn_option/tests/__init__.py
  sale_warn_option/tests/test_warn_options.py
  sale_warn_option/views/product_template_views.xml
  sale_warn_option/views/res_partner_views.xml
  setup/sale_warn_option/odoo/addons/sale_warn_option
  setup/sale_warn_option/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3121 [17.0][IMP] sale_force_invoiced: Create specific group to isolate the access to the force invoiced action on sale order"
  sale_force_invoiced/__manifest__.py
  sale_force_invoiced/migrations/17.0.1.1.0/post-migration.py
  sale_force_invoiced/security/security.xml
  sale_force_invoiced/view/sale_order.xml
Labels: approved, bot is merging ⏳

#3116 [16.0][IMP] sale_discount_display_amount: Show total discount on sale report.
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/report/sale_report_template.xml
  sale_discount_display_amount/static/description/index.html
Labels: approved, bot is merging ⏳

#3095 [17.0][MIG] sale_order_qty_change_no_recompute
  sale_order_qty_change_no_recompute/README.rst
  sale_order_qty_change_no_recompute/__init__.py
  sale_order_qty_change_no_recompute/__manifest__.py
  sale_order_qty_change_no_recompute/i18n/it.po
  sale_order_qty_change_no_recompute/i18n/sale_order_qty_change_no_recompute.pot
  sale_order_qty_change_no_recompute/monkeypatching.py
  sale_order_qty_change_no_recompute/pyproject.toml
  sale_order_qty_change_no_recompute/readme/CONTRIBUTORS.md
  sale_order_qty_change_no_recompute/readme/DESCRIPTION.md
  sale_order_qty_change_no_recompute/readme/ROADMAP.md
  sale_order_qty_change_no_recompute/readme/USAGE.md
  sale_order_qty_change_no_recompute/static/description/icon.png
  sale_order_qty_change_no_recompute/static/description/index.html
  sale_order_qty_change_no_recompute/tests/__init__.py
  sale_order_qty_change_no_recompute/tests/test_sale_order_qty_change.py
Labels: approved, ready to merge, bot is merging ⏳

#3123 [15.0][MIG] sale_order_lot_selection
  sale_order_lot_selection/README.rst
  sale_order_lot_selection/__init__.py
  sale_order_lot_selection/__manifest__.py
  sale_order_lot_selection/demo/sale_demo.xml
  sale_order_lot_selection/i18n/ca.po
  sale_order_lot_selection/i18n/de.po
  sale_order_lot_selection/i18n/el_GR.po
  sale_order_lot_selection/i18n/es.po
  sale_order_lot_selection/i18n/es_ES.po
  sale_order_lot_selection/i18n/es_MX.po
  sale_order_lot_selection/i18n/es_VE.po
  sale_order_lot_selection/i18n/fi.po
  sale_order_lot_selection/i18n/fr.po
  sale_order_lot_selection/i18n/gl.po
  sale_order_lot_selection/i18n/hr.po
  sale_order_lot_selection/i18n/hr_HR.po
  sale_order_lot_selection/i18n/hu.po
  sale_order_lot_selection/i18n/it.po
  sale_order_lot_selection/i18n/nl.po
  sale_order_lot_selection/i18n/nl_NL.po
  sale_order_lot_selection/i18n/pt.po
  sale_order_lot_selection/i18n/pt_BR.po
  sale_order_lot_selection/i18n/pt_PT.po
  sale_order_lot_selection/i18n/ro.po
  sale_order_lot_selection/i18n/sale_order_lot_selection.pot
  sale_order_lot_selection/i18n/sk.po
  sale_order_lot_selection/i18n/sl.po
  sale_order_lot_selection/i18n/tr.po
  sale_order_lot_selection/i18n/tr_TR.po
  sale_order_lot_selection/i18n/vi_VN.po
  sale_order_lot_selection/i18n/zh_CN.po
  sale_order_lot_selection/models/__init__.py
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/readme/CONTRIBUTORS.rst
  sale_order_lot_selection/readme/DESCRIPTION.rst
  sale_order_lot_selection/readme/ROADMAP.rst
  sale_order_lot_selection/readme/USAGE.rst
  sale_order_lot_selection/static/description/icon.png
  sale_order_lot_selection/static/description/index.html
  sale_order_lot_selection/tests/__init__.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
  setup/sale_order_lot_selection/odoo/addons/sale_order_lot_selection
  setup/sale_order_lot_selection/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1977 [12.0][FIX] sale_order_lot_selection: call super
  sale_order_lot_selection/models/sale.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3132 [FIX] sale_stock_product_recommendation: wizard compatibility with sale_order_product_recommendation_packaging_default
  sale_stock_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: needs review, approved, bot is merging ⏳

#2284 [IMP] sale_by_packaging: restrict packaging removing
  sale_by_packaging/models/product_packaging.py
  sale_by_packaging/models/sale_order_line.py
  sale_by_packaging/views/product_packaging.xml
Labels: approved, bot is merging ⏳

#3122 [15.0][MIG] pricelist_cache
  pricelist_cache/README.rst
  pricelist_cache/__init__.py
  pricelist_cache/__manifest__.py
  pricelist_cache/data/base_automation.xml
  pricelist_cache/data/demo.xml
  pricelist_cache/data/ir_cron.xml
  pricelist_cache/data/ir_filters_data.xml
  pricelist_cache/data/queue_job.xml
  pricelist_cache/hooks.py
  pricelist_cache/i18n/es.po
  pricelist_cache/i18n/pricelist_cache.pot
  pricelist_cache/models/__init__.py
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/models/product_pricelist_item.py
  pricelist_cache/models/product_product.py
  pricelist_cache/models/res_partner.py
  pricelist_cache/readme/CONTRIBUTORS.rst
  pricelist_cache/readme/CREDITS.rst
  pricelist_cache/readme/DESCRIPTION.rst
  pricelist_cache/readme/ROADMAP.rst
  pricelist_cache/security/ir.model.access.csv
  pricelist_cache/static/description/icon.png
  pricelist_cache/static/description/index.html
  pricelist_cache/tests/__init__.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_methods.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
  pricelist_cache/tests/test_pricelist_cache.py
  pricelist_cache/views/product_pricelist.xml
  pricelist_cache/views/product_pricelist_cache.xml
  pricelist_cache/views/res_partner.xml
  pricelist_cache/wizards/__init__.py
  pricelist_cache/wizards/pricelist_cache_wizard.py
  pricelist_cache/wizards/pricelist_cache_wizard.xml
  setup/pricelist_cache/odoo/addons/pricelist_cache
  setup/pricelist_cache/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3119 [15.0][MIG] sale_order_line_chained_move
  sale_order_line_chained_move/README.rst
  sale_order_line_chained_move/__init__.py
  sale_order_line_chained_move/__manifest__.py
  sale_order_line_chained_move/demo/sale_order.xml
  sale_order_line_chained_move/hooks.py
  sale_order_line_chained_move/i18n/it.po
  sale_order_line_chained_move/i18n/sale_order_line_chained_move.pot
  sale_order_line_chained_move/models/__init__.py
  sale_order_line_chained_move/models/sale_order_line.py
  sale_order_line_chained_move/models/stock_move.py
  sale_order_line_chained_move/models/stock_rule.py
  sale_order_line_chained_move/readme/CONTRIBUTORS.rst
  sale_order_line_chained_move/readme/DESCRIPTION.rst
  sale_order_line_chained_move/readme/USAGE.rst
  sale_order_line_chained_move/static/description/icon.png
  sale_order_line_chained_move/static/description/index.html
  sale_order_line_chained_move/tests/__init__.py
  sale_order_line_chained_move/tests/test_chained_move.py
  sale_order_line_chained_move/views/stock_rule_views.xml
  setup/sale_order_line_chained_move/odoo/addons/sale_order_line_chained_move
  setup/sale_order_line_chained_move/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3092 [14.0][IMP] product_supplierinfo_for_customer_sale: menu for customer info
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/product_customerinfo.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#3038 [14.0][IMP] sale_order_invoice_amount: make sure to respect currencies
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2333 [14.0][mig]-sale_validity_auto_cancel
  sale_validity_auto_cancel/README.rst
  sale_validity_auto_cancel/__init__.py
  sale_validity_auto_cancel/__manifest__.py
  sale_validity_auto_cancel/data/ir_cron.xml
  sale_validity_auto_cancel/models/__init__.py
  sale_validity_auto_cancel/models/res_company.py
  sale_validity_auto_cancel/models/res_config_settings.py
  sale_validity_auto_cancel/models/sale_order.py
  sale_validity_auto_cancel/readme/CONFIGURE.rst
  sale_validity_auto_cancel/readme/CONTRIBUTORS.rst
  sale_validity_auto_cancel/readme/DESCRIPTION.rst
  sale_validity_auto_cancel/readme/USAGE.rst
  sale_validity_auto_cancel/static/description/icon.png
  sale_validity_auto_cancel/static/description/index.html
  sale_validity_auto_cancel/tests/__init__.py
  sale_validity_auto_cancel/tests/test_sale_validity_auto_cancel.py
  sale_validity_auto_cancel/views/res_config_settings.xml
  setup/sale_validity_auto_cancel/odoo/addons/sale_validity_auto_cancel
  setup/sale_validity_auto_cancel/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3101 [16.0][IMP] sale_force_invoiced: update untaxed_amount_to_invoice
  sale_force_invoiced/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#3098 [17.0][MIG] sale_stock_cancel_restriction
  sale_stock_cancel_restriction/README.rst
  sale_stock_cancel_restriction/__init__.py
  sale_stock_cancel_restriction/__manifest__.py
  sale_stock_cancel_restriction/i18n/es.po
  sale_stock_cancel_restriction/i18n/it.po
  sale_stock_cancel_restriction/i18n/sale_stock_cancel_restriction.pot
  sale_stock_cancel_restriction/models/__init__.py
  sale_stock_cancel_restriction/models/sale_order.py
  sale_stock_cancel_restriction/pyproject.toml
  sale_stock_cancel_restriction/readme/CONTRIBUTORS.md
  sale_stock_cancel_restriction/readme/DESCRIPTION.md
  sale_stock_cancel_restriction/readme/USAGE.md
  sale_stock_cancel_restriction/static/description/icon.png
  sale_stock_cancel_restriction/static/description/index.html
  sale_stock_cancel_restriction/tests/__init__.py
  sale_stock_cancel_restriction/tests/test_sale_stock_cancel_restriction.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3056 [IMP] sale_triple_discount: improve module extensibility
  sale_triple_discount/models/sale_order_line.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3125 [17.0][FIX] sale_fixed_discount: Division by zero
  sale_fixed_discount/models/sale_order_line.py
  sale_fixed_discount/tests/test_sale_fixed_discount.py
Labels: approved, ready to merge, bot is merging ⏳

#3131 [17.0][MIG] sale_invoice_policy: Migration to 17.0
  sale_invoice_policy/README.rst
  sale_invoice_policy/__init__.py
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/i18n/ca.po
  sale_invoice_policy/i18n/es.po
  sale_invoice_policy/i18n/es_MX.po
  sale_invoice_policy/i18n/fr.po
  sale_invoice_policy/i18n/it.po
  sale_invoice_policy/i18n/pt.po
  sale_invoice_policy/i18n/sale_invoice_policy.pot
  sale_invoice_policy/models/__init__.py
  sale_invoice_policy/models/res_config_settings.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/models/sale_order_line.py
  sale_invoice_policy/pyproject.toml
  sale_invoice_policy/readme/CONTRIBUTORS.md
  sale_invoice_policy/readme/DESCRIPTION.md
  sale_invoice_policy/readme/USAGE.md
  sale_invoice_policy/static/description/icon.png
  sale_invoice_policy/static/description/index.html
  sale_invoice_policy/tests/__init__.py
  sale_invoice_policy/tests/test_sale_invoice_policy.py
  sale_invoice_policy/views/res_config_settings_view.xml
  sale_invoice_policy/views/sale_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#2708 [MIG] sale_restricted_qty
  requirements.txt
  sale_restricted_qty/README.rst
  sale_restricted_qty/__init__.py
  sale_restricted_qty/__manifest__.py
  sale_restricted_qty/i18n/fr.po
  sale_restricted_qty/i18n/it.po
  sale_restricted_qty/i18n/sale_order_min_qty.pot
  sale_restricted_qty/i18n/sale_restricted_qty.pot
  sale_restricted_qty/models/__init__.py
  sale_restricted_qty/models/product_category.py
  sale_restricted_qty/models/product_product.py
  sale_restricted_qty/models/product_restricted_qty_mixin.py
  sale_restricted_qty/models/product_template.py
  sale_restricted_qty/models/sale.py
  sale_restricted_qty/readme/CONTRIBUTORS.rst
  sale_restricted_qty/readme/DESCRIPTION.rst
  sale_restricted_qty/readme/USAGE.rst
  sale_restricted_qty/static/description/icon.png
  sale_restricted_qty/static/description/index.html
  sale_restricted_qty/tests/__init__.py
  sale_restricted_qty/tests/test_sale.py
  sale_restricted_qty/views/product_category_views.xml
  sale_restricted_qty/views/product_product_views.xml
  sale_restricted_qty/views/product_template_views.xml
  sale_restricted_qty/views/sale_views.xml
  setup/sale_restricted_qty/odoo/addons/sale_restricted_qty
  setup/sale_restricted_qty/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2618 [15.0][MIG] sale_procurement_group_by_commitment_date
  .copier-answers.yml
  .github/workflows/test.yml
  sale_procurement_group_by_commitment_date/README.rst
  sale_procurement_group_by_commitment_date/__init__.py
  sale_procurement_group_by_commitment_date/__manifest__.py
  sale_procurement_group_by_commitment_date/i18n/ca.po
  sale_procurement_group_by_commitment_date/i18n/de.po
  sale_procurement_group_by_commitment_date/i18n/el_GR.po
  sale_procurement_group_by_commitment_date/i18n/es.po
  sale_procurement_group_by_commitment_date/i18n/es_ES.po
  sale_procurement_group_by_commitment_date/i18n/es_VE.po
  sale_procurement_group_by_commitment_date/i18n/fi.po
  sale_procurement_group_by_commitment_date/i18n/fr.po
  sale_procurement_group_by_commitment_date/i18n/hr.po
  sale_procurement_group_by_commitment_date/i18n/hr_HR.po
  sale_procurement_group_by_commitment_date/i18n/hu.po
  sale_procurement_group_by_commitment_date/i18n/it.po
  sale_procurement_group_by_commitment_date/i18n/nl.po
  sale_procurement_group_by_commitment_date/i18n/nl_NL.po
  sale_procurement_group_by_commitment_date/i18n/pt.po
  sale_procurement_group_by_commitment_date/i18n/pt_BR.po
  sale_procurement_group_by_commitment_date/i18n/ro.po
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_commitment_date.pot
  sale_procurement_group_by_commitment_date/i18n/sale_procurement_group_by_requested_date.pot
  sale_procurement_group_by_commitment_date/i18n/sl.po
  sale_procurement_group_by_commitment_date/i18n/tr.po
  sale_procurement_group_by_commitment_date/i18n/tr_TR.po
  sale_procurement_group_by_commitment_date/i18n/vi_VN.po
  sale_procurement_group_by_commitment_date/i18n/zh_CN.po
  sale_procurement_group_by_commitment_date/models/__init__.py
  sale_procurement_group_by_commitment_date/models/sale_order.py
  sale_procurement_group_by_commitment_date/readme/CONTRIBUTORS.rst
  sale_procurement_group_by_commitment_date/readme/DESCRIPTION.rst
  sale_procurement_group_by_commitment_date/readme/INSTALL.rst
  sale_procurement_group_by_commitment_date/readme/ROADMAP.rst
  sale_procurement_group_by_commitment_date/readme/USAGE.rst
  sale_procurement_group_by_commitment_date/static/description/icon.png
  sale_procurement_group_by_commitment_date/static/description/index.html
  sale_procurement_group_by_commitment_date/tests/__init__.py
  sale_procurement_group_by_commitment_date/tests/test_sale_procurement_group_by_commitment_date.py
  setup/sale_procurement_group_by_commitment_date/odoo/addons/sale_procurement_group_by_commitment_date
  setup/sale_procurement_group_by_commitment_date/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2598 [15.0][MIG] sale_order_restrict_cancel_existing_invoice
  sale_order_restrict_cancel_existing_invoice/README.rst
  sale_order_restrict_cancel_existing_invoice/__init__.py
  sale_order_restrict_cancel_existing_invoice/__manifest__.py
  sale_order_restrict_cancel_existing_invoice/i18n/ca.po
  sale_order_restrict_cancel_existing_invoice/i18n/es.po
  sale_order_restrict_cancel_existing_invoice/i18n/sale_order_restrict_cancel_existing_invoice.pot
  sale_order_restrict_cancel_existing_invoice/models/__init__.py
  sale_order_restrict_cancel_existing_invoice/models/sale_order.py
  sale_order_restrict_cancel_existing_invoice/readme/CONTRIBUTORS.rst
  sale_order_restrict_cancel_existing_invoice/readme/DESCRIPTION.rst
  sale_order_restrict_cancel_existing_invoice/readme/USAGE.rst
  sale_order_restrict_cancel_existing_invoice/static/description/icon.png
  sale_order_restrict_cancel_existing_invoice/static/description/index.html
  sale_order_restrict_cancel_existing_invoice/tests/__init__.py
  sale_order_restrict_cancel_existing_invoice/tests/test_sale_cancel_existing_invoice.py
  setup/sale_order_restrict_cancel_existing_invoice/odoo/addons/sale_order_restrict_cancel_existing_invoice
  setup/sale_order_restrict_cancel_existing_invoice/setup.py
Labels: migration, bot is merging ⏳

#2126 [14.0][IMP] sale_quotation_number-customizable_quotation_sequence
  sale_quotation_number/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#3139 [15.0][FIX] sale_planner_calendar: Do not take into account the user time zone when the planner events are created
  sale_planner_calendar/models/sale_planner_calendar_summary.py
Labels: approved, bot is merging ⏳

#3073 [15.0][IMP] sale_planner_calendar: Design improves and new buttons in calendar planner event
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/data/sale_planner_calendar_event_profile.xml
  sale_planner_calendar/models/__init__.py
  sale_planner_calendar/models/calendar.py
  sale_planner_calendar/models/sale_planner_calendar_event.py
  sale_planner_calendar/models/sale_planner_calendar_event_profile.py
  sale_planner_calendar/readme/CONTRIBUTORS.rst
  sale_planner_calendar/security/ir.model.access.csv
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/views/calendar_view.xml
  sale_planner_calendar/views/sale_planner_calendar_event_profile_view.xml
  sale_planner_calendar/views/sale_planner_calendar_event_view.xml
  sale_planner_calendar/views/sale_planner_calendar_menu.xml
Labels: bot is merging ⏳

#3163 [16.0][IMP] product_supplierinfo_for_customer_sale: Add compatibility with Form() to change line name properly
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
Labels: bot is merging ⏳
