Repository OCA/sale-workflow, pull requests merged in 2024-04, with the labels that each got.

#3050 [17.0][MIG] sale_order_archive: Migration to 17.0
  sale_order_archive/README.rst
  sale_order_archive/__init__.py
  sale_order_archive/__manifest__.py
  sale_order_archive/i18n/ca.po
  sale_order_archive/i18n/de.po
  sale_order_archive/i18n/es.po
  sale_order_archive/i18n/it.po
  sale_order_archive/i18n/nl.po
  sale_order_archive/i18n/pt_BR.po
  sale_order_archive/i18n/sale_order_archive.pot
  sale_order_archive/i18n/zh_CN.po
  sale_order_archive/models/__init__.py
  sale_order_archive/models/sale_order.py
  sale_order_archive/pyproject.toml
  sale_order_archive/readme/CONTRIBUTORS.md
  sale_order_archive/readme/DESCRIPTION.md
  sale_order_archive/readme/INSTALL.md
  sale_order_archive/readme/USAGE.md
  sale_order_archive/static/description/icon.png
  sale_order_archive/static/description/index.html
  sale_order_archive/tests/__init__.py
  sale_order_archive/tests/test_sale_order_archive.py
  sale_order_archive/views/sale_order.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#3013 [17.0][MIG] sale_delivery_state
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/i18n/es.po
  sale_delivery_state/i18n/it.po
  sale_delivery_state/i18n/sale_delivery_state.pot
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/pyproject.toml
  sale_delivery_state/readme/CONTRIBUTORS.md
  sale_delivery_state/readme/DESCRIPTION.md
  sale_delivery_state/static/description/icon.png
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3049 [17.0][MIG] sale_order_line_menu: Migration to 17.0
  sale_order_line_menu/README.rst
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/i18n/de.po
  sale_order_line_menu/i18n/es.po
  sale_order_line_menu/i18n/fr.po
  sale_order_line_menu/i18n/fr_BE.po
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/hr.po
  sale_order_line_menu/i18n/it.po
  sale_order_line_menu/i18n/pt_BR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  sale_order_line_menu/models/__init__.py
  sale_order_line_menu/models/sale_order_line.py
  sale_order_line_menu/pyproject.toml
  sale_order_line_menu/readme/CONTRIBUTORS.md
  sale_order_line_menu/readme/DESCRIPTION.md
  sale_order_line_menu/readme/USAGE.md
  sale_order_line_menu/static/description/icon.png
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3067 [IMP] sale_elaboration: remove elaboration column from delivery slip
  sale_elaboration/reports/report_deliveryslip.xml
Labels: enhancement, needs review, bot is merging ⏳

#3068 [IMP] sale_elaboration: display elaboration notes in picking operations report
  sale_elaboration/__manifest__.py
  sale_elaboration/models/res_config_settings.py
  sale_elaboration/reports/report_picking_operations.xml
  sale_elaboration/security/security.xml
  sale_elaboration/static/description/index.html
  sale_elaboration/views/res_config_settings_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#2915 [17.0][MIG] sale_procurement_group_by_line
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/model/stock_move.py
  sale_procurement_group_by_line/pyproject.toml
  sale_procurement_group_by_line/readme/CONTRIBUTORS.md
  sale_procurement_group_by_line/readme/DESCRIPTION.md
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/static/description/index.html
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3052 [17.0][MIG] product_form_sale_link: Migration to 17.0
  product_form_sale_link/README.rst
  product_form_sale_link/__init__.py
  product_form_sale_link/__manifest__.py
  product_form_sale_link/i18n/ca.po
  product_form_sale_link/i18n/es.po
  product_form_sale_link/i18n/fr.po
  product_form_sale_link/i18n/it.po
  product_form_sale_link/i18n/product_form_sale_link.pot
  product_form_sale_link/models/__init__.py
  product_form_sale_link/models/product_product.py
  product_form_sale_link/models/product_template.py
  product_form_sale_link/pyproject.toml
  product_form_sale_link/readme/CONTRIBUTORS.md
  product_form_sale_link/readme/DESCRIPTION.md
  product_form_sale_link/readme/USAGE.md
  product_form_sale_link/static/description/icon.png
  product_form_sale_link/static/description/index.html
  product_form_sale_link/static/description/product_sale.png
  product_form_sale_link/views/product_product.xml
  product_form_sale_link/views/product_template.xml
  product_form_sale_link/views/sale_order_line.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3048 [17.0][MIG] sale_commercial_partner: Migration to 17.0
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca.po
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_MX.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/fr_FR.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale_order.py
  sale_commercial_partner/pyproject.toml
  sale_commercial_partner/readme/CONTRIBUTORS.md
  sale_commercial_partner/readme/DESCRIPTION.md
  sale_commercial_partner/readme/USAGE.md
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/views/sale_order.xml
  sale_commercial_partner/views/sale_report.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3006 [17.0][MIG] sale_shipping_info_helper
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__manifest__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/pyproject.toml
  sale_shipping_info_helper/readme/CONTRIBUTORS.md
  sale_shipping_info_helper/readme/DESCRIPTION.md
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/static/description/index.html
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
Labels: enhancement, approved, migration, ready to merge, bot is merging ⏳

#3069 [17.0][MIG] partner_sale_pivot
  partner_sale_pivot/README.rst
  partner_sale_pivot/__init__.py
  partner_sale_pivot/__manifest__.py
  partner_sale_pivot/i18n/ca.po
  partner_sale_pivot/i18n/ca_ES.po
  partner_sale_pivot/i18n/de.po
  partner_sale_pivot/i18n/es.po
  partner_sale_pivot/i18n/hr.po
  partner_sale_pivot/i18n/it.po
  partner_sale_pivot/i18n/partner_sale_pivot.pot
  partner_sale_pivot/pyproject.toml
  partner_sale_pivot/readme/CONTRIBUTORS.md
  partner_sale_pivot/readme/DESCRIPTION.md
  partner_sale_pivot/readme/USAGE.md
  partner_sale_pivot/static/description/icon.png
  partner_sale_pivot/static/description/index.html
  partner_sale_pivot/views/res_partner_views.xml
  partner_sale_pivot/views/sale_report_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2890 [16.0][FIX] sale_force_invoice: Prevent invoicing on fully invoiced sale order
  sale_force_invoiced/__init__.py
  sale_force_invoiced/i18n/fr.po
  sale_force_invoiced/i18n/sale_force_invoiced.pot
  sale_force_invoiced/models/__init__.py
  sale_force_invoiced/models/sale_order.py
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/tests/test_sale_force_invoiced.py
  sale_force_invoiced/wizards/__init__.py
  sale_force_invoiced/wizards/sale_make_invoice_advance.py
Labels: enhancement, approved, bot is merging ⏳

#3078 [15.0][IMP] sale_payment_sheet: add kanban mode to act_window
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
Labels: approved, bot is merging ⏳

#3082 [16.0][IMP] sale_payment_sheet: add kanban mode to act_window
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
Labels: approved, bot is merging ⏳

#3083 [16.0][IMP] sale_elaboration: Elaborations and elaboration note in move line tree detailed
  sale_elaboration/__manifest__.py
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/reports/report_picking_operations.xml
  sale_elaboration/views/stock_move_line_views.xml
Labels: approved, bot is merging ⏳

#3084 [16.0][PERF] sale_product_multi_add : SO lines creation in batch
  sale_product_multi_add/readme/CONTRIBUTORS.rst
  sale_product_multi_add/wizards/sale_import_products.py
Labels: approved, bot is merging ⏳

#3063 [FIX] sale_order_lot_selection: remove deprecated method for domain
  sale_order_lot_selection/models/sale_order_line.py
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_lot_selection/view/sale_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3094 [FIX] [16.0] sale_order_line_price_history: Increase view priority
  sale_order_line_price_history/views/sale_views.xml
Labels: approved, bot is merging ⏳

#3087 [17.0][MIG] sales_team_security
  sales_team_security/README.rst
  sales_team_security/__init__.py
  sales_team_security/__manifest__.py
  sales_team_security/hooks.py
  sales_team_security/i18n/es.po
  sales_team_security/i18n/it.po
  sales_team_security/i18n/sales_team_security.pot
  sales_team_security/models/__init__.py
  sales_team_security/models/ir_rule.py
  sales_team_security/models/res_partner.py
  sales_team_security/pyproject.toml
  sales_team_security/readme/CONFIGURE.md
  sales_team_security/readme/CONTRIBUTORS.md
  sales_team_security/readme/DESCRIPTION.md
  sales_team_security/readme/INSTALL.md
  sales_team_security/readme/ROADMAP.md
  sales_team_security/security/sales_team_security.xml
  sales_team_security/static/description/icon.png
  sales_team_security/static/description/index.html
  sales_team_security/tests/__init__.py
  sales_team_security/tests/common.py
  sales_team_security/tests/test_sales_team_security.py
  sales_team_security/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2882 [16.0][FIX] product_packaging_container_deposit: Deprecated method invalida…
  sale_product_packaging_container_deposit/tests/test_sale_product_packaging_container_deposit.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3066 [14.0][IMP] sale_order_tag: allowed to hide so_tag_ids in list views
  sale_order_tag/README.rst
  sale_order_tag/__manifest__.py
  sale_order_tag/readme/CONTRIBUTORS.rst
  sale_order_tag/static/description/index.html
  sale_order_tag/views/sale_order.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3085 [16.0][IMP] sale_auto_remove_zero_quantity_lines: Remove empty note in sale order
  sale_auto_remove_zero_quantity_lines/models/sale_order.py
  sale_auto_remove_zero_quantity_lines/tests/test_sale_auto_remove_zero_quantity_lines.py
Labels: approved, ready to merge, bot is merging ⏳
