Repository OCA/sale-workflow, pull requests merged in 2024-01, with the labels that each got.

#2823 [ADD] sale_order_invoicing_picking_filter: create invoices from sale orders filtered by pickings
  sale_order_invoicing_picking_filter/README.rst
  sale_order_invoicing_picking_filter/__init__.py
  sale_order_invoicing_picking_filter/__manifest__.py
  sale_order_invoicing_picking_filter/models/__init__.py
  sale_order_invoicing_picking_filter/models/sale_order.py
  sale_order_invoicing_picking_filter/models/sale_order_line.py
  sale_order_invoicing_picking_filter/models/stock_picking.py
  sale_order_invoicing_picking_filter/readme/CONTRIBUTORS.rst
  sale_order_invoicing_picking_filter/readme/DESCRIPTION.rst
  sale_order_invoicing_picking_filter/readme/USAGE.rst
  sale_order_invoicing_picking_filter/static/description/icon.png
  sale_order_invoicing_picking_filter/static/description/index.html
  sale_order_invoicing_picking_filter/tests/__init__.py
  sale_order_invoicing_picking_filter/tests/test_sale_order_invoicing_picking_filter.py
  sale_order_invoicing_picking_filter/views/stock_picking_views.xml
  sale_order_invoicing_picking_filter/wizard/__init__.py
  sale_order_invoicing_picking_filter/wizard/sale_advance_payment_inv.py
  sale_order_invoicing_picking_filter/wizard/sale_make_invoice_advanced_views.xml
  setup/sale_order_invoicing_picking_filter/odoo/addons/sale_order_invoicing_picking_filter
  setup/sale_order_invoicing_picking_filter/setup.py
Labels: approved, bot is merging ⏳

#2390 [15.0][FIX] sale_planner_calendar: Do not send invitation attendees emails when reassign user to calendar.event
  sale_planner_calendar/wizard/sale_planner_calendar_reassign.py
Labels: approved, bot is merging ⏳

#2883 [FIX][16.0] sale_quotation_number: deprecated call to Savepointcase
  sale_quotation_number/tests/test_sale_order.py
Labels: bot is merging ⏳

#2870 [FIX] sale_order_product_recommendation: smaller heading on wizard
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: needs review, approved, bot is merging ⏳

#2880 [15.0][IMP] sale_order_secondary_unit: Require secondary_uom_id when secondary_uom_qty is filled
  sale_order_secondary_unit/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#2888 [17.0][FIX] Update copier template
  .copier-answers.yml
  .pre-commit-config.yaml
  .ruff.toml
  README.md
Labels: bot is merging ⏳

#1809 [13.0][MIG] sale_order_line_menu + exclude section and note order lines filter
  sale_order_line_menu/README.rst
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  sale_order_line_menu/readme/CONTRIBUTORS.rst
  sale_order_line_menu/readme/DESCRIPTION.rst
  sale_order_line_menu/readme/USAGE.rst
  sale_order_line_menu/static/description/icon.png
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/views/sale_order_line_views.xml
  setup/sale_order_line_menu/odoo/addons/sale_order_line_menu
  setup/sale_order_line_menu/setup.py
Labels: bot is merging ⏳, stale

#2329 [16.0][ADD] sale_procurement_customer
  sale_procurement_customer/README.rst
  sale_procurement_customer/__init__.py
  sale_procurement_customer/__manifest__.py
  sale_procurement_customer/models/__init__.py
  sale_procurement_customer/models/sale_order_line.py
  sale_procurement_customer/readme/CONTRIBUTORS.rst
  sale_procurement_customer/readme/DESCRIPTION.rst
  sale_procurement_customer/readme/USAGE.rst
  sale_procurement_customer/static/description/icon.png
  sale_procurement_customer/static/description/index.html
  sale_procurement_customer/tests/__init__.py
  sale_procurement_customer/tests/test_procurement_customer.py
  setup/sale_procurement_customer/odoo/addons/sale_procurement_customer
  setup/sale_procurement_customer/setup.py
Labels: needs review, approved, bot is merging ⏳

#2783 [14.0] Fix pricelist_cache concurrent update issues
  pricelist_cache/README.rst
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/readme/ROADMAP.rst
  pricelist_cache/static/description/index.html
  pricelist_cache/tests/__init__.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_methods.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
Labels: approved, ready to merge, bot is merging ⏳

#2687 [16.0][MIG] sale_order_line_input: Migration to version 16.0
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/it.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/readme/CONTRIBUTORS.rst
  sale_order_line_input/readme/DESCRIPTION.rst
  sale_order_line_input/readme/USAGE.rst
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
  setup/sale_order_line_input/odoo/addons/sale_order_line_input
  setup/sale_order_line_input/setup.py
Labels: needs review, migration, bot is merging ⏳

#2905 [FIX][16.0] sale_order_line_price_history: Set history price from wizard tree
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/readme/CONTRIBUTORS.rst
  sale_order_line_price_history/readme/ROADMAP.rst
  sale_order_line_price_history/readme/USAGE.rst
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
  sale_order_line_price_history/static/src/js/set_price_to_line_widget.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/static/src/xml/set_price_to_line_widget.xml
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: needs review, approved, bot is merging ⏳

#2904 [16.0][MIG] sale_pricelist_technical
  sale_pricelist_technical/README.rst
  sale_pricelist_technical/__init__.py
  sale_pricelist_technical/__manifest__.py
  sale_pricelist_technical/demo/product_pricelist.xml
  sale_pricelist_technical/i18n/fr.po
  sale_pricelist_technical/i18n/sale_pricelist_technical.pot
  sale_pricelist_technical/models/__init__.py
  sale_pricelist_technical/models/product_pricelist.py
  sale_pricelist_technical/models/res_partner.py
  sale_pricelist_technical/models/sale_order.py
  sale_pricelist_technical/readme/CONFIGURE.rst
  sale_pricelist_technical/readme/CONTRIBUTORS.rst
  sale_pricelist_technical/readme/DESCRIPTION.rst
  sale_pricelist_technical/static/description/icon.png
  sale_pricelist_technical/static/description/index.html
  sale_pricelist_technical/static/description/product_pricelist_form.png
  sale_pricelist_technical/views/view_product_pricelist.xml
  setup/sale_pricelist_technical/odoo/addons/sale_pricelist_technical
  setup/sale_pricelist_technical/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2829 [FIX] sale_order_line_date: format style of commitment_date
  sale_order_line_date/reports/sale_order_report.xml
Labels: approved, ready to merge, bot is merging ⏳

#2509 [16.0][MIG] sale_blanket_order: Migration to 16.0
  sale_blanket_order/README.rst
  sale_blanket_order/__init__.py
  sale_blanket_order/__manifest__.py
  sale_blanket_order/data/ir_cron.xml
  sale_blanket_order/data/sequence.xml
  sale_blanket_order/i18n/de.po
  sale_blanket_order/i18n/es.po
  sale_blanket_order/i18n/fr.po
  sale_blanket_order/i18n/fr_FR.po
  sale_blanket_order/i18n/pt.po
  sale_blanket_order/i18n/sale_blanket_order.pot
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/readme/CONTRIBUTORS.rst
  sale_blanket_order/readme/CREDITS.rst
  sale_blanket_order/readme/DESCRIPTION.rst
  sale_blanket_order/readme/USAGE.rst
  sale_blanket_order/report/report.xml
  sale_blanket_order/report/templates.xml
  sale_blanket_order/security/ir.model.access.csv
  sale_blanket_order/security/security.xml
  sale_blanket_order/static/description/BO_actions.png
  sale_blanket_order/static/description/BO_form.png
  sale_blanket_order/static/description/BO_lines.png
  sale_blanket_order/static/description/BO_menu.png
  sale_blanket_order/static/description/PO_BOLine.png
  sale_blanket_order/static/description/PO_from_BO.png
  sale_blanket_order/static/description/icon.png
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/__init__.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_blanket_order/views/sale_blanket_order_line_views.xml
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/views/sale_order_views.xml
  sale_blanket_order/wizard/__init__.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order/wizard/create_sale_orders.xml
  setup/sale_blanket_order/odoo/addons/sale_blanket_order
  setup/sale_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#2878 [ADD] sale_order_product_recommendation_quick_add
  sale_order_product_recommendation_quick_add/README.rst
  sale_order_product_recommendation_quick_add/__init__.py
  sale_order_product_recommendation_quick_add/__manifest__.py
  sale_order_product_recommendation_quick_add/i18n/fr.po
  sale_order_product_recommendation_quick_add/i18n/sale_order_product_recommendation_quick_add.pot
  sale_order_product_recommendation_quick_add/models/__init__.py
  sale_order_product_recommendation_quick_add/models/sale_order.py
  sale_order_product_recommendation_quick_add/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation_quick_add/readme/DESCRIPTION.rst
  sale_order_product_recommendation_quick_add/static/description/index.html
  sale_order_product_recommendation_quick_add/tests/__init__.py
  sale_order_product_recommendation_quick_add/tests/test_recomendation_quick_add.py
  sale_order_product_recommendation_quick_add/views/sale_order_view.xml
  setup/sale_order_product_recommendation_quick_add/odoo/addons/sale_order_product_recommendation_quick_add
  setup/sale_order_product_recommendation_quick_add/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2914 [FIX] sale_order_line_price_history: OWL component with onchange
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.js
Labels: approved, bot is merging ⏳

#2913 [IMP] sale_order_product_recommendation: choose order on mobile
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/readme/USAGE.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: needs review, approved, bot is merging ⏳

#2897 [14.0] [IMP] sale_blanket_order: add taxes and subtotal columns
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/static/description/index.html
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2919 [ADD] sale_stock_product_recommendation: stock info on sale recommendations
  sale_stock_product_recommendation/README.rst
  sale_stock_product_recommendation/__init__.py
  sale_stock_product_recommendation/__manifest__.py
  sale_stock_product_recommendation/i18n/es.po
  sale_stock_product_recommendation/i18n/sale_stock_product_recommendation.pot
  sale_stock_product_recommendation/readme/CONTRIBUTORS.md
  sale_stock_product_recommendation/readme/CREDITS.md
  sale_stock_product_recommendation/readme/DESCRIPTION.md
  sale_stock_product_recommendation/readme/ROADMAP.md
  sale_stock_product_recommendation/readme/USAGE.md
  sale_stock_product_recommendation/static/description/icon.png
  sale_stock_product_recommendation/static/description/index.html
  sale_stock_product_recommendation/wizards/__init__.py
  sale_stock_product_recommendation/wizards/sale_order_recommendation.py
  sale_stock_product_recommendation/wizards/sale_order_recommendation_view.xml
  setup/sale_stock_product_recommendation/odoo/addons/sale_stock_product_recommendation
  setup/sale_stock_product_recommendation/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2921 [14.0] [IMP] sale_blanket_order: add customer in search
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2923 [IMP] sale_order_product_recommendation: sort separately by product name or code
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: needs review, approved, bot is merging ⏳

#2929 [fix] sale_manual_delivery: wrong route_id model
  sale_manual_delivery/wizard/manual_delivery.py
Labels: bot is merging ⏳

#2832 [16.0][ADD] sale_loyalty_exclude
  sale_loyalty_exclude/README.rst
  sale_loyalty_exclude/__init__.py
  sale_loyalty_exclude/__manifest__.py
  sale_loyalty_exclude/models/__init__.py
  sale_loyalty_exclude/models/product_template.py
  sale_loyalty_exclude/models/sale_order.py
  sale_loyalty_exclude/readme/CONTRIBUTORS.rst
  sale_loyalty_exclude/readme/DESCRIPTION.rst
  sale_loyalty_exclude/readme/USAGE.rst
  sale_loyalty_exclude/static/description/index.html
  sale_loyalty_exclude/tests/__init__.py
  sale_loyalty_exclude/tests/test_sale_loyalty_exclude.py
  sale_loyalty_exclude/views/product_views.xml
  setup/sale_loyalty_exclude/odoo/addons/sale_loyalty_exclude
  setup/sale_loyalty_exclude/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2533 [MIG] sale_order_carrier_auto_assign: Migration to 16.0
  sale_order_carrier_auto_assign/README.rst
  sale_order_carrier_auto_assign/__init__.py
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/i18n/es.po
  sale_order_carrier_auto_assign/i18n/sale_order_carrier_auto_assign.pot
  sale_order_carrier_auto_assign/models/__init__.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/readme/CONTRIBUTORS.rst
  sale_order_carrier_auto_assign/readme/CREDITS.rst
  sale_order_carrier_auto_assign/readme/DESCRIPTION.rst
  sale_order_carrier_auto_assign/static/description/icon.png
  sale_order_carrier_auto_assign/static/description/index.html
  sale_order_carrier_auto_assign/tests/__init__.py
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
  setup/sale_order_carrier_auto_assign/odoo/addons/sale_order_carrier_auto_assign
  setup/sale_order_carrier_auto_assign/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#2613 [15.0][ADD] sale_purchase_procurement_group_by_line: new module
  sale_purchase_procurement_group_by_line/README.rst
  sale_purchase_procurement_group_by_line/__init__.py
  sale_purchase_procurement_group_by_line/__manifest__.py
  sale_purchase_procurement_group_by_line/models/__init__.py
  sale_purchase_procurement_group_by_line/models/sale_order.py
  sale_purchase_procurement_group_by_line/readme/CONTRIBUTORS.rst
  sale_purchase_procurement_group_by_line/readme/DESCRIPTION.rst
  sale_purchase_procurement_group_by_line/static/description/index.html
  setup/sale_purchase_procurement_group_by_line/odoo/addons/sale_purchase_procurement_group_by_line
  setup/sale_purchase_procurement_group_by_line/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2917 [ADD] sale_auto_remove_zero_quantity_lines
  sale_auto_remove_zero_quantity_lines/README.rst
  sale_auto_remove_zero_quantity_lines/__init__.py
  sale_auto_remove_zero_quantity_lines/__manifest__.py
  sale_auto_remove_zero_quantity_lines/i18n/de.po
  sale_auto_remove_zero_quantity_lines/i18n/fr.po
  sale_auto_remove_zero_quantity_lines/i18n/sale_auto_remove_zero_quantity_lines.pot
  sale_auto_remove_zero_quantity_lines/models/__init__.py
  sale_auto_remove_zero_quantity_lines/models/res_company.py
  sale_auto_remove_zero_quantity_lines/models/res_config_settings.py
  sale_auto_remove_zero_quantity_lines/models/sale_order.py
  sale_auto_remove_zero_quantity_lines/readme/CONFIGURE.rst
  sale_auto_remove_zero_quantity_lines/readme/CONTRIBUTORS.rst
  sale_auto_remove_zero_quantity_lines/readme/DESCRIPTION.rst
  sale_auto_remove_zero_quantity_lines/static/description/index.html
  sale_auto_remove_zero_quantity_lines/tests/__init__.py
  sale_auto_remove_zero_quantity_lines/tests/test_sale_auto_remove_zero_quantity_lines.py
  sale_auto_remove_zero_quantity_lines/views/res_config_settings_views.xml
  setup/sale_auto_remove_zero_quantity_lines/odoo/addons/sale_auto_remove_zero_quantity_lines
  setup/sale_auto_remove_zero_quantity_lines/setup.py
Labels: needs review, approved, bot is merging ⏳

#2936 [FIX] sale_order_product_recommendation: AccessError when getting recommendations
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation_elaboration/tests/test_sale_order_recommendation.py
Labels: bug, approved, bot is merging ⏳
