Repository OCA/sale-workflow, pull requests merged in 2024-09, with the labels that each got.

#3296 [17.0][IMP] sale_order_line_sequence: attrs removed
  sale_order_line_sequence/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#3302 [17.0][FIX] sale_blanket_order: not require taxes on blanket orders
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3303 [15.0][FIX] sale_order_line_input: Remove parent defined in tree view
  sale_order_line_input/views/sale_order_line_view.xml
Labels: approved, bot is merging ⏳

#3285 [14.0][IMP] sale_delivery_state: migration script
  sale_delivery_state/migrations/14.0.2.0.0/pre-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#3297 [15.0][FIX] sale_elaboration, product_supplierinfo_for_customer_elaboration: Set elaboration note with a onchange instead of compute method
  product_supplierinfo_for_customer_elaboration/models/sale_order_line.py
  sale_elaboration/models/product_elaboration_mixin.py
  sale_elaboration/tests/test_sale_elaboration.py
Labels: approved, ready to merge, bot is merging ⏳

#2916 [17.0][MIG] sale_sourced_by_line
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale.py
  sale_sourced_by_line/pyproject.toml
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3312 [15.0][FIX] sale_order_type: Empty analytic account when sale order is duplicated
  sale_order_type/models/sale.py
  sale_order_type/tests/test_sale_order_type.py
Labels: approved, bot is merging ⏳

#3282 [15.0][FIX] product_supplierinfo_for_customer_sale
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/models/sale_order_line.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/static/description/index.html
Labels: enhancement, needs review, approved, bot is merging ⏳

#3306 [IMP] sale_loyalty_exclude: Avoid to select excluded products in rul…
  sale_loyalty_exclude/models/__init__.py
  sale_loyalty_exclude/models/loyalty_reward.py
  sale_loyalty_exclude/views/product_views.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3030 [17.0][MIG] sale_order_general_discount: 17.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/pt_BR.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/product_product.py
  sale_order_general_discount/models/product_template.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/pyproject.toml
  sale_order_general_discount/readme/CONTRIBUTORS.rst
  sale_order_general_discount/readme/DESCRIPTION.rst
  sale_order_general_discount/readme/INSTALL.rst
  sale_order_general_discount/readme/USAGE.rst
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/product_view.xml
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3047 [14.0][IMP] sale_product_multi_add: pricelist compatibility
  sale_product_multi_add/tests/test_sale.py
  sale_product_multi_add/wizards/sale_import_products.py
Labels: enhancement, approved, bot is merging ⏳

#3315 [15.0][FIX] sale_fully_invoiced: tests not being called
  sale_fully_invoiced/tests/__init__.py
  sale_fully_invoiced/tests/test_sale_fully_invoiced.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3304 [16.0][MIG]sale_validity_auto_cancel: Migration to 16.0
  sale_validity_auto_cancel/README.rst
  sale_validity_auto_cancel/__init__.py
  sale_validity_auto_cancel/__manifest__.py
  sale_validity_auto_cancel/data/ir_cron.xml
  sale_validity_auto_cancel/i18n/it.po
  sale_validity_auto_cancel/i18n/sale_validity_auto_cancel.pot
  sale_validity_auto_cancel/models/__init__.py
  sale_validity_auto_cancel/models/res_company.py
  sale_validity_auto_cancel/models/res_config_settings.py
  sale_validity_auto_cancel/models/res_partner.py
  sale_validity_auto_cancel/models/sale_order.py
  sale_validity_auto_cancel/pyproject.toml
  sale_validity_auto_cancel/readme/CONFIGURE.md
  sale_validity_auto_cancel/readme/CONTRIBUTORS.md
  sale_validity_auto_cancel/readme/DESCRIPTION.md
  sale_validity_auto_cancel/readme/USAGE.md
  sale_validity_auto_cancel/static/description/icon.png
  sale_validity_auto_cancel/static/description/index.html
  sale_validity_auto_cancel/tests/__init__.py
  sale_validity_auto_cancel/tests/test_sale_validity_auto_cancel.py
  sale_validity_auto_cancel/views/res_config_settings.xml
  sale_validity_auto_cancel/views/res_partner_views.xml
  setup/sale_validity_auto_cancel/odoo/addons/sale_validity_auto_cancel
  setup/sale_validity_auto_cancel/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3044 [ADD] sale_stock_partner_warehouse
  sale_stock_partner_warehouse/README.rst
  sale_stock_partner_warehouse/__init__.py
  sale_stock_partner_warehouse/__manifest__.py
  sale_stock_partner_warehouse/models/__init__.py
  sale_stock_partner_warehouse/models/res_partner.py
  sale_stock_partner_warehouse/models/sale_order.py
  sale_stock_partner_warehouse/readme/CONFIGURE.rst
  sale_stock_partner_warehouse/readme/CONTRIBUTORS.rst
  sale_stock_partner_warehouse/readme/DESCRIPTION.rst
  sale_stock_partner_warehouse/readme/USAGE.rst
  sale_stock_partner_warehouse/static/description/index.html
  sale_stock_partner_warehouse/tests/__init__.py
  sale_stock_partner_warehouse/tests/test_sale_stock_partner_warehouse.py
  sale_stock_partner_warehouse/views/partner_view.xml
  setup/sale_stock_partner_warehouse/odoo/addons/sale_stock_partner_warehouse
  setup/sale_stock_partner_warehouse/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3142 [15.0][IMP] product_supplierinfo_for_customer_sale: menu for customer info
  product_supplierinfo_for_customer_sale/README.rst
  product_supplierinfo_for_customer_sale/models/__init__.py
  product_supplierinfo_for_customer_sale/models/product_customerinfo.py
  product_supplierinfo_for_customer_sale/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale/readme/USAGE.rst
  product_supplierinfo_for_customer_sale/static/description/index.html
  product_supplierinfo_for_customer_sale/views/sale_view.xml
Labels: enhancement, approved, bot is merging ⏳

#3318 [15.0][IMP] sale_delivery_state: migration script
  sale_delivery_state/migrations/15.0.2.0.0/pre-migration.py
Labels: approved

#3319 [FIX] pricelist_cache: item expiration fix
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_methods.py
  pricelist_cache/tests/test_pricelist_cache.py
Labels: approved, bot is merging ⏳

#3325 [16.0][FIX] sale_triple_discount: Remove call to deprecated
  sale_triple_discount/models/sale_order_line.py
Labels: enhancement, approved, bot is merging ⏳

#3232 [17.0][MIG]sale_order_line_input: Migration to version 17.0
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/it.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/pyproject.toml
  sale_order_line_input/readme/CONTRIBUTORS.md
  sale_order_line_input/readme/DESCRIPTION.md
  sale_order_line_input/readme/USAGE.md
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
Labels: approved, bot is merging ⏳

#3326 [16.0][FIX] sale_order_line_input: New id for the _get_lang method
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/tests/test_sale_order_line_input.py
Labels: approved, bot is merging ⏳

#3301 [17.0][FIX] sale_order_type: Ensure sale_type_id is computed correctly
  sale_order_type/models/account_move.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3313 [16.0][IMP] sale_order_line_menu : improve Readme
  sale_order_line_menu/readme/CONTEXT.md
  sale_order_line_menu/readme/DESCRIPTION.md
  sale_order_line_menu/readme/USAGE.md
  sale_order_line_menu/static/description/sale_order_line_menu.png
  sale_order_line_menu/static/description/sales_order_lines.png
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
