Repository OCA/sale-workflow, pull requests merged in 2024-02, with the labels that each got.

#2935 [14.0] [IMP] sale_blanket_order: make some BOL columns optional
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: approved, bot is merging ⏳

#2893 [14.0][ADD] sale_quick_blanket_order: mass line addition/update in blanket SO
  sale_quick_blanket_order/README.rst
  sale_quick_blanket_order/__init__.py
  sale_quick_blanket_order/__manifest__.py
  sale_quick_blanket_order/models/__init__.py
  sale_quick_blanket_order/models/product_product.py
  sale_quick_blanket_order/models/sale_blanket_order.py
  sale_quick_blanket_order/readme/CONTRIBUTORS.rst
  sale_quick_blanket_order/readme/DESCRIPTION.rst
  sale_quick_blanket_order/readme/USAGE.rst
  sale_quick_blanket_order/static/description/index.html
  sale_quick_blanket_order/tests/__init__.py
  sale_quick_blanket_order/tests/test_quick_blanket_sale.py
  sale_quick_blanket_order/views/sale_blanket_order_view.xml
  setup/sale_quick_blanket_order/odoo/addons/sale_quick_blanket_order
  setup/sale_quick_blanket_order/setup.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#2898 [FIX] sale_product_multi_add: fix discount
  sale_product_multi_add/__manifest__.py
  sale_product_multi_add/wizards/sale_import_products.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2922 [16.0][IMP] sale_partner_selectable_option
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/__manifest__.py
  sale_partner_selectable_option/data/ir_config_parameter.xml
  sale_partner_selectable_option/models/res_partner.py
  sale_partner_selectable_option/readme/CONFIGURE.rst
  sale_partner_selectable_option/static/description/index.html
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2881 [16.0][IMP] sale_tier_validation: simplify tests
  sale_tier_validation/tests/test_tier_validation.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2918 [16.0][IMP]sale_exception: set context param for unlocking an order
  sale_exception/models/sale_order.py
  sale_exception/tests/test_sale_exception.py
Labels: bug, needs review, approved, bot is merging ⏳

#2942 [14.0][FIX]sale_blanket_order: revert problematic changes
  .pre-commit-config.yaml
  sale_blanket_order/README.rst
  sale_blanket_order/__manifest__.py
  sale_blanket_order/migrations/14.0.1.2.2/pre-migrate.py
  sale_blanket_order/models/__init__.py
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/models/res_company.py
  sale_blanket_order/models/sale_config_settings.py
  sale_blanket_order/static/description/index.html
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/views/sale_config_settings.xml
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order_revision/__manifest__.py
  setup/sale_blanket_order_revision/odoo/addons/sale_blanket_order_revision
  setup/sale_blanket_order_revision/setup.py
Labels: bot is merging ⏳

#2900 [14.0][IMP] pricelist_cache: add some indexes
  pricelist_cache/models/product_pricelist_item.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2944 [14.0][FIX]sale_blanket_order: fix button action access for salesman
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/tests/test_blanket_orders.py
Labels: enhancement, needs fixing, approved, bot is merging ⏳

#2926 [16.0][ADD] sale_order_amount_to_invoice: Add module
  sale_order_amount_to_invoice/README.rst
  sale_order_amount_to_invoice/__init__.py
  sale_order_amount_to_invoice/__manifest__.py
  sale_order_amount_to_invoice/models/__init__.py
  sale_order_amount_to_invoice/models/sale_order.py
  sale_order_amount_to_invoice/readme/CONFIGURE.md
  sale_order_amount_to_invoice/readme/CONTEXT.md
  sale_order_amount_to_invoice/readme/CONTRIBUTORS.md
  sale_order_amount_to_invoice/readme/DESCRIPTION.md
  sale_order_amount_to_invoice/readme/USAGE.md
  sale_order_amount_to_invoice/static/description/icon.png
  sale_order_amount_to_invoice/static/description/index.html
  sale_order_amount_to_invoice/tests/__init__.py
  sale_order_amount_to_invoice/tests/test_sale_order_invoice_amount.py
  sale_order_amount_to_invoice/views/sale_order_view.xml
  setup/sale_order_amount_to_invoice/odoo/addons/sale_order_amount_to_invoice
  setup/sale_order_amount_to_invoice/setup.py
Labels: needs review, bot is merging ⏳

#2943 [15.0][FIX] sale_invoice_plan: add permission menu invoice plan
  sale_invoice_plan/views/sale_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2456 [16.0][MIG] sale_shipping_info_helper
  sale_shipping_info_helper/README.rst
  sale_shipping_info_helper/__init__.py
  sale_shipping_info_helper/__manifest__.py
  sale_shipping_info_helper/i18n/ca.po
  sale_shipping_info_helper/i18n/de.po
  sale_shipping_info_helper/i18n/el_GR.po
  sale_shipping_info_helper/i18n/es.po
  sale_shipping_info_helper/i18n/es_ES.po
  sale_shipping_info_helper/i18n/es_VE.po
  sale_shipping_info_helper/i18n/fi.po
  sale_shipping_info_helper/i18n/fr.po
  sale_shipping_info_helper/i18n/hr.po
  sale_shipping_info_helper/i18n/hr_HR.po
  sale_shipping_info_helper/i18n/hu.po
  sale_shipping_info_helper/i18n/it.po
  sale_shipping_info_helper/i18n/nl.po
  sale_shipping_info_helper/i18n/nl_NL.po
  sale_shipping_info_helper/i18n/pt.po
  sale_shipping_info_helper/i18n/pt_BR.po
  sale_shipping_info_helper/i18n/ro.po
  sale_shipping_info_helper/i18n/sale_shipping_info_helper.pot
  sale_shipping_info_helper/i18n/sk.po
  sale_shipping_info_helper/i18n/sl.po
  sale_shipping_info_helper/i18n/tr.po
  sale_shipping_info_helper/i18n/tr_TR.po
  sale_shipping_info_helper/i18n/vi_VN.po
  sale_shipping_info_helper/i18n/zh_CN.po
  sale_shipping_info_helper/models/__init__.py
  sale_shipping_info_helper/models/sale_order.py
  sale_shipping_info_helper/readme/CONTRIBUTORS.rst
  sale_shipping_info_helper/readme/DESCRIPTION.rst
  sale_shipping_info_helper/static/description/icon.png
  sale_shipping_info_helper/static/description/index.html
  sale_shipping_info_helper/tests/__init__.py
  sale_shipping_info_helper/tests/test_sale_shipping_info_helper.py
  setup/sale_shipping_info_helper/odoo/addons/sale_shipping_info_helper
  setup/sale_shipping_info_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2854 [15.0][IMP] sale_planner_calendar: Allow delete recurrence as it can be done from calendar view
  sale_planner_calendar/README.rst
  sale_planner_calendar/__manifest__.py
  sale_planner_calendar/models/res_partner.py
  sale_planner_calendar/static/description/index.html
  sale_planner_calendar/static/src/js/basic_controller.js
  sale_planner_calendar/views/calendar_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2955 [FIX] sale_order_product_recommendation: make UoM work
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: bug, approved, bot is merging ⏳

#2368 [15.0][MIG] sale_missing_cart_tracking_tier_validation > sale_missing_tracking_tier_validation: Migration to version 15.0
  sale_missing_tracking_tier_validation/README.rst
  sale_missing_tracking_tier_validation/__init__.py
  sale_missing_tracking_tier_validation/__manifest__.py
  sale_missing_tracking_tier_validation/models/__init__.py
  sale_missing_tracking_tier_validation/models/sale_missing_tracking_exception.py
  sale_missing_tracking_tier_validation/models/tier_definition.py
  sale_missing_tracking_tier_validation/readme/CONFIGURE.rst
  sale_missing_tracking_tier_validation/readme/CONTRIBUTORS.rst
  sale_missing_tracking_tier_validation/readme/DESCRIPTION.rst
  sale_missing_tracking_tier_validation/readme/USAGE.rst
  sale_missing_tracking_tier_validation/static/description/icon.png
  sale_missing_tracking_tier_validation/static/description/index.html
  sale_missing_tracking_tier_validation/tests/__init__.py
  sale_missing_tracking_tier_validation/tests/test_sale_missing_tracking_tier_validation.py
  sale_missing_tracking_tier_validation/views/sale_missing_tracking_exception_view.xml
  setup/sale_missing_tracking_tier_validation/odoo/addons/sale_missing_tracking_tier_validation
  setup/sale_missing_tracking_tier_validation/setup.py
Labels: needs review, migration, bot is merging ⏳

#2874 [17.0][MIG] sale_tier_validation: Migration to 17.0
  sale_tier_validation/README.rst
  sale_tier_validation/__init__.py
  sale_tier_validation/__manifest__.py
  sale_tier_validation/data/mail_data.xml
  sale_tier_validation/i18n/es.po
  sale_tier_validation/i18n/es_MX.po
  sale_tier_validation/i18n/it.po
  sale_tier_validation/i18n/sale_tier_validation.pot
  sale_tier_validation/i18n/sv.po
  sale_tier_validation/i18n/tr.po
  sale_tier_validation/i18n/zh_CN.po
  sale_tier_validation/models/__init__.py
  sale_tier_validation/models/sale_order.py
  sale_tier_validation/models/tier_definition.py
  sale_tier_validation/pyproject.toml
  sale_tier_validation/readme/CONFIGURE.md
  sale_tier_validation/readme/CONTRIBUTORS.md
  sale_tier_validation/readme/DESCRIPTION.md
  sale_tier_validation/readme/INSTALL.md
  sale_tier_validation/readme/ROADMAP.md
  sale_tier_validation/readme/USAGE.md
  sale_tier_validation/static/description/icon.png
  sale_tier_validation/static/description/index.html
  sale_tier_validation/tests/__init__.py
  sale_tier_validation/tests/test_tier_validation.py
  sale_tier_validation/views/sale_order_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2959 [16.0] sale_packaging_default: make packaging lookup reusable
  sale_packaging_default/models/sale_order_line.py
Labels: bot is merging ⏳

#2957 [15.0][IMP] sale_discount_display_amount: Show total discount on sale report.
  sale_discount_display_amount/README.rst
  sale_discount_display_amount/__manifest__.py
  sale_discount_display_amount/readme/CONTRIBUTORS.rst
  sale_discount_display_amount/report/sale_report_template.xml
  sale_discount_display_amount/static/description/index.html
Labels: approved, bot is merging ⏳

#2774 [14.0][FIX] sale_force_invoiced: Proper tagging tests with post_install
  sale_force_invoiced/README.rst
  sale_force_invoiced/readme/CONTRIBUTORS.rst
  sale_force_invoiced/static/description/index.html
  sale_force_invoiced/tests/test_sale_force_invoiced.py
Labels: approved, bot is merging ⏳

#2947 [14.0][FIX] sale_mrp_bom: accept BoMs without variant
  sale_mrp_bom/models/sale_order_line.py
  sale_mrp_bom/tests/test_sale_mrp_bom.py
Labels: approved, bot is merging ⏳

#2938 [17.0][MIG] sale_start_end_dates
  sale_start_end_dates/README.rst
  sale_start_end_dates/__init__.py
  sale_start_end_dates/__manifest__.py
  sale_start_end_dates/i18n/ca.po
  sale_start_end_dates/i18n/de.po
  sale_start_end_dates/i18n/el_GR.po
  sale_start_end_dates/i18n/es.po
  sale_start_end_dates/i18n/es_ES.po
  sale_start_end_dates/i18n/es_VE.po
  sale_start_end_dates/i18n/fi.po
  sale_start_end_dates/i18n/fr.po
  sale_start_end_dates/i18n/hr.po
  sale_start_end_dates/i18n/hr_HR.po
  sale_start_end_dates/i18n/hu.po
  sale_start_end_dates/i18n/it.po
  sale_start_end_dates/i18n/nl.po
  sale_start_end_dates/i18n/nl_NL.po
  sale_start_end_dates/i18n/pt.po
  sale_start_end_dates/i18n/pt_BR.po
  sale_start_end_dates/i18n/ro.po
  sale_start_end_dates/i18n/sale_start_end_dates.pot
  sale_start_end_dates/i18n/sk.po
  sale_start_end_dates/i18n/sl.po
  sale_start_end_dates/i18n/tr.po
  sale_start_end_dates/i18n/tr_TR.po
  sale_start_end_dates/i18n/vi_VN.po
  sale_start_end_dates/i18n/zh_CN.po
  sale_start_end_dates/models/__init__.py
  sale_start_end_dates/models/sale_order.py
  sale_start_end_dates/pyproject.toml
  sale_start_end_dates/readme/CONTRIBUTORS.md
  sale_start_end_dates/readme/DESCRIPTION.md
  sale_start_end_dates/static/description/icon.png
  sale_start_end_dates/static/description/index.html
  sale_start_end_dates/tests/__init__.py
  sale_start_end_dates/tests/test_sale_start_end_dates.py
  sale_start_end_dates/views/sale_order.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2966 [15.0][ADD] sale_custom_rounding: Custom taxes rounding method in sale orders
  sale_custom_rounding/README.rst
  sale_custom_rounding/__init__.py
  sale_custom_rounding/__manifest__.py
  sale_custom_rounding/models/__init__.py
  sale_custom_rounding/models/sale_order.py
  sale_custom_rounding/readme/CONFIGURE.rst
  sale_custom_rounding/readme/CONTRIBUTORS.rst
  sale_custom_rounding/readme/DESCRIPTION.rst
  sale_custom_rounding/readme/USAGE.rst
  sale_custom_rounding/static/description/icon.png
  sale_custom_rounding/static/description/index.html
  sale_custom_rounding/tests/__init__.py
  sale_custom_rounding/tests/test_sale_custom_rounding.py
  sale_custom_rounding/views/sale_views.xml
  setup/sale_custom_rounding/odoo/addons/sale_custom_rounding
  setup/sale_custom_rounding/setup.py
Labels: approved, bot is merging ⏳

#2979 [15.0][FIX] sale_planner_calendar: Avoid infinite loop recursion when recurrence end is forever
  sale_planner_calendar/models/calendar.py
Labels: approved, bot is merging ⏳

#2924 [14.0] [ADD] product_supplierinfo_for_customer_sale_blanket_order
  product_supplierinfo_for_customer_sale_blanket_order/README.rst
  product_supplierinfo_for_customer_sale_blanket_order/__init__.py
  product_supplierinfo_for_customer_sale_blanket_order/__manifest__.py
  product_supplierinfo_for_customer_sale_blanket_order/models/__init__.py
  product_supplierinfo_for_customer_sale_blanket_order/models/sale_blanket_order_line.py
  product_supplierinfo_for_customer_sale_blanket_order/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer_sale_blanket_order/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer_sale_blanket_order/static/description/index.html
  product_supplierinfo_for_customer_sale_blanket_order/tests/__init__.py
  product_supplierinfo_for_customer_sale_blanket_order/tests/test_product_supplierinfo_for_customer_sale_blanket_order.py
  product_supplierinfo_for_customer_sale_blanket_order/views/sale_blanket_order_line_views.xml
  product_supplierinfo_for_customer_sale_blanket_order/views/sale_blanket_order_views.xml
  product_supplierinfo_for_customer_sale_blanket_order/wizard/__init__.py
  product_supplierinfo_for_customer_sale_blanket_order/wizard/create_sale_orders.py
  setup/product_supplierinfo_for_customer_sale_blanket_order/odoo/addons/product_supplierinfo_for_customer_sale_blanket_order
  setup/product_supplierinfo_for_customer_sale_blanket_order/setup.py
Labels: needs review, approved, bot is merging ⏳

#2974 [FIX] sale_order_general_discount: fix compute_discount
  sale_order_general_discount/models/sale_order_line.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
