Repository OCA/sale-workflow, pull requests merged in 2025-05, with the labels that each got.

#2896 Add sale_order_line_not_billable
  sale_order_line_not_billable/README.rst
  sale_order_line_not_billable/__init__.py
  sale_order_line_not_billable/__manifest__.py
  sale_order_line_not_billable/i18n/de.po
  sale_order_line_not_billable/models/__init__.py
  sale_order_line_not_billable/models/product_template.py
  sale_order_line_not_billable/models/sale_order.py
  sale_order_line_not_billable/models/sale_order_line.py
  sale_order_line_not_billable/readme/CONTRIBUTORS.rst
  sale_order_line_not_billable/readme/CREDITS.rst
  sale_order_line_not_billable/readme/DESCRIPTION.rst
  sale_order_line_not_billable/readme/USAGE.rst
  sale_order_line_not_billable/static/description/index.html
  sale_order_line_not_billable/views/product_template.xml
  setup/sale_order_line_not_billable/odoo/addons/sale_order_line_not_billable
  setup/sale_order_line_not_billable/setup.py
Labels: approved, ready to merge

#3488 [18.0][MIG] sale_order_general_discount: Migration to 18.0
  sale_order_general_discount/README.rst
  sale_order_general_discount/__init__.py
  sale_order_general_discount/__manifest__.py
  sale_order_general_discount/i18n/de.po
  sale_order_general_discount/i18n/es.po
  sale_order_general_discount/i18n/it.po
  sale_order_general_discount/i18n/pt_BR.po
  sale_order_general_discount/i18n/sale_order_general_discount.pot
  sale_order_general_discount/i18n/zh_CN.po
  sale_order_general_discount/models/__init__.py
  sale_order_general_discount/models/product_product.py
  sale_order_general_discount/models/product_template.py
  sale_order_general_discount/models/res_partner.py
  sale_order_general_discount/models/sale_order.py
  sale_order_general_discount/models/sale_order_line.py
  sale_order_general_discount/pyproject.toml
  sale_order_general_discount/readme/CONTRIBUTORS.md
  sale_order_general_discount/readme/DESCRIPTION.md
  sale_order_general_discount/readme/INSTALL.md
  sale_order_general_discount/readme/USAGE.md
  sale_order_general_discount/static/description/icon.png
  sale_order_general_discount/static/description/index.html
  sale_order_general_discount/tests/__init__.py
  sale_order_general_discount/tests/test_sale_order_general_discount.py
  sale_order_general_discount/views/product_view.xml
  sale_order_general_discount/views/res_partner_view.xml
  sale_order_general_discount/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3065 [15.0][ADD] sale_lead_time_range
  sale_lead_time_range/README.rst
  sale_lead_time_range/__init__.py
  sale_lead_time_range/__manifest__.py
  sale_lead_time_range/init_hook.py
  sale_lead_time_range/models/__init__.py
  sale_lead_time_range/models/product.py
  sale_lead_time_range/models/sale_order_line.py
  sale_lead_time_range/readme/CONTRIBUTORS.rst
  sale_lead_time_range/readme/DESCRIPTION.rst
  sale_lead_time_range/readme/USAGE.rst
  sale_lead_time_range/static/description/index.html
  sale_lead_time_range/tests/__init__.py
  sale_lead_time_range/tests/test_sale_lead_time_range.py
  sale_lead_time_range/views/product_views.xml
  sale_lead_time_range/views/sale_order_line.xml
  setup/sale_lead_time_range/odoo/addons/sale_lead_time_range
  setup/sale_lead_time_range/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3238 [17.0][MIG] sale_stock_secondary_unit: Migration to 17.0
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/i18n/de.po
  sale_stock_secondary_unit/i18n/es.po
  sale_stock_secondary_unit/i18n/it.po
  sale_stock_secondary_unit/i18n/sale_stock_secondary_unit.pot
  sale_stock_secondary_unit/i18n/zh_CN.po
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/stock_rule.py
  sale_stock_secondary_unit/pyproject.toml
  sale_stock_secondary_unit/readme/CONTRIBUTORS.md
  sale_stock_secondary_unit/readme/DESCRIPTION.md
  sale_stock_secondary_unit/readme/USAGE.md
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3294 [17.0][FIX] sale_blanket_order: set analytic distribution on created sale lines
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/tests/test_sale_order.py
  sale_blanket_order/wizard/create_sale_orders.py
  sale_blanket_order/wizard/create_sale_orders.xml
Labels: approved, ready to merge, bot is merging ⏳

#3594 [ADD] [16.0] sale_stock_expiry_date_on_qty_at_date_widget
  .copier-answers.yml
  .github/workflows/test.yml
  sale_stock_expiry_date_on_qty_at_date_widget/README.rst
  sale_stock_expiry_date_on_qty_at_date_widget/__init__.py
  sale_stock_expiry_date_on_qty_at_date_widget/__manifest__.py
  sale_stock_expiry_date_on_qty_at_date_widget/i18n/es.po
  sale_stock_expiry_date_on_qty_at_date_widget/i18n/sale_stock_expiry_date_on_qty_at_date_widget.pot
  sale_stock_expiry_date_on_qty_at_date_widget/models/__init__.py
  sale_stock_expiry_date_on_qty_at_date_widget/models/sale_order_line.py
  sale_stock_expiry_date_on_qty_at_date_widget/readme/CONFIGURE.md
  sale_stock_expiry_date_on_qty_at_date_widget/readme/CONTEXT.md
  sale_stock_expiry_date_on_qty_at_date_widget/readme/CONTRIBUTORS.md
  sale_stock_expiry_date_on_qty_at_date_widget/readme/DESCRIPTION.md
  sale_stock_expiry_date_on_qty_at_date_widget/readme/INSTALL.md
  sale_stock_expiry_date_on_qty_at_date_widget/readme/USAGE.md
  sale_stock_expiry_date_on_qty_at_date_widget/static/description/exp_date_widget.png
  sale_stock_expiry_date_on_qty_at_date_widget/static/description/icon.png
  sale_stock_expiry_date_on_qty_at_date_widget/static/description/index.html
  sale_stock_expiry_date_on_qty_at_date_widget/static/src/widgets/qty_at_date_widget.esm.js
  sale_stock_expiry_date_on_qty_at_date_widget/static/src/widgets/qty_at_date_widget.xml
  sale_stock_expiry_date_on_qty_at_date_widget/tests/__init__.py
  sale_stock_expiry_date_on_qty_at_date_widget/tests/test_predicted_expiry_date.py
  sale_stock_expiry_date_on_qty_at_date_widget/views/sale_order_line_view.xml
  sale_stock_expiry_date_on_qty_at_date_widget/views/stock_quant_view.xml
  setup/sale_stock_expiry_date_on_qty_at_date_widget/odoo/addons/sale_stock_expiry_date_on_qty_at_date_widget
  setup/sale_stock_expiry_date_on_qty_at_date_widget/setup.py
Labels: needs review, approved, bot is merging ⏳

#3620 [16.0][FIX] sale_blanket_order: SO from Blanket Order disable adding lines
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#3577 [18.0][MIG] sale_stock_return_request: Migration to version 18.0
  sale_stock_return_request/README.rst
  sale_stock_return_request/__init__.py
  sale_stock_return_request/__manifest__.py
  sale_stock_return_request/i18n/ca.po
  sale_stock_return_request/i18n/es.po
  sale_stock_return_request/i18n/fr.po
  sale_stock_return_request/i18n/sale_stock_return_request.pot
  sale_stock_return_request/models/__init__.py
  sale_stock_return_request/models/sale_order.py
  sale_stock_return_request/models/stock_return_request.py
  sale_stock_return_request/pyproject.toml
  sale_stock_return_request/readme/CONTRIBUTORS.md
  sale_stock_return_request/readme/DESCRIPTION.md
  sale_stock_return_request/readme/USAGE.md
  sale_stock_return_request/static/description/icon.png
  sale_stock_return_request/static/description/index.html
  sale_stock_return_request/tests/__init__.py
  sale_stock_return_request/tests/test_stock_return_request.py
  sale_stock_return_request/views/sale_order_views.xml
  sale_stock_return_request/views/sale_return_request_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3702 [15.0][FIX] sale_order_product_assortment: Add compute_sudo in has_allowed_products
  sale_order_product_assortment/models/sale_order.py
Labels: approved, bot is merging ⏳

#3712 [18.0][mig] sale_delivery_state
  sale_delivery_state/README.rst
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/demo/sale_demo.xml
  sale_delivery_state/i18n/es.po
  sale_delivery_state/i18n/it.po
  sale_delivery_state/i18n/sale_delivery_state.pot
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/pyproject.toml
  sale_delivery_state/readme/CONTRIBUTORS.md
  sale_delivery_state/readme/DESCRIPTION.md
  sale_delivery_state/static/description/icon.png
  sale_delivery_state/static/description/index.html
  sale_delivery_state/tests/__init__.py
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/sale_order_views.xml
Labels: bot is merging ⏳

#3025 [17.0][MIG] sale_global_discount: standard migration to 17.0
  sale_global_discount/README.rst
  sale_global_discount/__init__.py
  sale_global_discount/__manifest__.py
  sale_global_discount/hooks.py
  sale_global_discount/i18n/es.po
  sale_global_discount/i18n/it.po
  sale_global_discount/i18n/pt.po
  sale_global_discount/i18n/sale_global_discount.pot
  sale_global_discount/models/__init__.py
  sale_global_discount/models/account_tax.py
  sale_global_discount/models/sale_order.py
  sale_global_discount/models/sale_order_line.py
  sale_global_discount/pyproject.toml
  sale_global_discount/readme/CONFIGURE.md
  sale_global_discount/readme/CONTRIBUTORS.md
  sale_global_discount/readme/DESCRIPTION.md
  sale_global_discount/readme/ROADMAP.md
  sale_global_discount/readme/USAGE.md
  sale_global_discount/static/description/icon.png
  sale_global_discount/static/description/icon.svg
  sale_global_discount/static/description/index.html
  sale_global_discount/tests/__init__.py
  sale_global_discount/tests/test_sale_global_discount.py
  sale_global_discount/views/report_sale_order.xml
  sale_global_discount/views/sale_order_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3428 [17.0][FIX] sale_procurement_group_by_line: update to odoo
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved, ready to merge, bot is merging ⏳

#3554 [18.0][MIG] sale_order_product_assortment
  sale_order_product_assortment/README.rst
  sale_order_product_assortment/__init__.py
  sale_order_product_assortment/__manifest__.py
  sale_order_product_assortment/i18n/ca.po
  sale_order_product_assortment/i18n/es.po
  sale_order_product_assortment/i18n/it.po
  sale_order_product_assortment/i18n/nl.po
  sale_order_product_assortment/i18n/sale_order_product_assortment.pot
  sale_order_product_assortment/models/__init__.py
  sale_order_product_assortment/models/sale_order.py
  sale_order_product_assortment/pyproject.toml
  sale_order_product_assortment/readme/CONFIGURE.md
  sale_order_product_assortment/readme/CONTRIBUTORS.md
  sale_order_product_assortment/readme/DESCRIPTION.md
  sale_order_product_assortment/readme/ROADMAP.md
  sale_order_product_assortment/readme/USAGE.md
  sale_order_product_assortment/static/description/icon.png
  sale_order_product_assortment/static/description/index.html
  sale_order_product_assortment/tests/__init__.py
  sale_order_product_assortment/tests/test_sale_order_product_assortment.py
  sale_order_product_assortment/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3685 [18.0] [MIG] sale_company_currency: Migration to 18.0
  sale_company_currency/README.rst
  sale_company_currency/__init__.py
  sale_company_currency/__manifest__.py
  sale_company_currency/i18n/ca.po
  sale_company_currency/i18n/de.po
  sale_company_currency/i18n/el_GR.po
  sale_company_currency/i18n/es.po
  sale_company_currency/i18n/es_ES.po
  sale_company_currency/i18n/es_VE.po
  sale_company_currency/i18n/fi.po
  sale_company_currency/i18n/fr.po
  sale_company_currency/i18n/hr.po
  sale_company_currency/i18n/hr_HR.po
  sale_company_currency/i18n/hu.po
  sale_company_currency/i18n/it.po
  sale_company_currency/i18n/nl.po
  sale_company_currency/i18n/nl_NL.po
  sale_company_currency/i18n/pt.po
  sale_company_currency/i18n/pt_BR.po
  sale_company_currency/i18n/ro.po
  sale_company_currency/i18n/sale_company_currency.pot
  sale_company_currency/i18n/sk.po
  sale_company_currency/i18n/sl.po
  sale_company_currency/i18n/tr.po
  sale_company_currency/i18n/tr_TR.po
  sale_company_currency/i18n/vi_VN.po
  sale_company_currency/i18n/zh_CN.po
  sale_company_currency/models/__init__.py
  sale_company_currency/models/sale_order.py
  sale_company_currency/pyproject.toml
  sale_company_currency/readme/CONTRIBUTORS.md
  sale_company_currency/readme/DESCRIPTION.md
  sale_company_currency/static/description/icon.png
  sale_company_currency/static/description/index.html
  sale_company_currency/tests/__init__.py
  sale_company_currency/tests/test_sale_company_currency.py
  sale_company_currency/views/sale_order_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#2629 [16.0][ADD] sale_pricelist_display_surcharge
  sale_pricelist_display_surcharge/README.rst
  sale_pricelist_display_surcharge/__init__.py
  sale_pricelist_display_surcharge/__manifest__.py
  sale_pricelist_display_surcharge/models/__init__.py
  sale_pricelist_display_surcharge/models/product_pricelist_item.py
  sale_pricelist_display_surcharge/models/sale_order_line.py
  sale_pricelist_display_surcharge/readme/CONTRIBUTORS.rst
  sale_pricelist_display_surcharge/readme/DESCRIPTION.rst
  sale_pricelist_display_surcharge/readme/USAGE.rst
  sale_pricelist_display_surcharge/static/description/index.html
  sale_pricelist_display_surcharge/tests/__init__.py
  sale_pricelist_display_surcharge/tests/test_sale_pricelist_display_surcharge.py
  sale_pricelist_display_surcharge/views/product_pricelist_item_views.xml
  setup/sale_pricelist_display_surcharge/odoo/addons/sale_pricelist_display_surcharge
  setup/sale_pricelist_display_surcharge/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#2459 [14.0][ADD] sale_production_state
  sale_production_state/__init__.py
  sale_production_state/__manifest__.py
  sale_production_state/models/__init__.py
  sale_production_state/models/sale_order.py
  sale_production_state/models/sale_order_line.py
  sale_production_state/readme/CONTRIBUTORS.rst
  sale_production_state/readme/DESCRIPTION.rst
  sale_production_state/tests/__init__.py
  sale_production_state/tests/test_production_state.py
  sale_production_state/views/sale_order.xml
  setup/sale_production_state/odoo/addons/sale_production_state
  setup/sale_production_state/setup.py
Labels: needs review, approved, bot is merging ⏳

#3279 [17.0][MIG] sale_order_lot_generator: Migration to 17.0
  sale_order_lot_generator/README.rst
  sale_order_lot_generator/__init__.py
  sale_order_lot_generator/__manifest__.py
  sale_order_lot_generator/i18n/ca.po
  sale_order_lot_generator/i18n/de.po
  sale_order_lot_generator/i18n/el_GR.po
  sale_order_lot_generator/i18n/es.po
  sale_order_lot_generator/i18n/es_ES.po
  sale_order_lot_generator/i18n/es_VE.po
  sale_order_lot_generator/i18n/fi.po
  sale_order_lot_generator/i18n/fr.po
  sale_order_lot_generator/i18n/hr.po
  sale_order_lot_generator/i18n/hr_HR.po
  sale_order_lot_generator/i18n/hu.po
  sale_order_lot_generator/i18n/it.po
  sale_order_lot_generator/i18n/nl.po
  sale_order_lot_generator/i18n/nl_NL.po
  sale_order_lot_generator/i18n/pt.po
  sale_order_lot_generator/i18n/pt_BR.po
  sale_order_lot_generator/i18n/ro.po
  sale_order_lot_generator/i18n/sale_order_lot_generator.pot
  sale_order_lot_generator/i18n/sk.po
  sale_order_lot_generator/i18n/sl.po
  sale_order_lot_generator/i18n/tr.po
  sale_order_lot_generator/i18n/tr_TR.po
  sale_order_lot_generator/i18n/vi_VN.po
  sale_order_lot_generator/i18n/zh_CN.po
  sale_order_lot_generator/models/__init__.py
  sale_order_lot_generator/models/product_template.py
  sale_order_lot_generator/models/sale_order.py
  sale_order_lot_generator/models/sale_order_line.py
  sale_order_lot_generator/pyproject.toml
  sale_order_lot_generator/readme/CONFIGURE.md
  sale_order_lot_generator/readme/CONTRIBUTORS.md
  sale_order_lot_generator/readme/DESCRIPTION.md
  sale_order_lot_generator/readme/USAGE.md
  sale_order_lot_generator/static/description/icon.png
  sale_order_lot_generator/static/description/index.html
  sale_order_lot_generator/tests/__init__.py
  sale_order_lot_generator/tests/test_sale_order_lot_generator.py
  sale_order_lot_generator/views/product_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3461 [18.0][ADD] sale_automatic_workflow_stock_job
  sale_automatic_workflow_stock_job/README.rst
  sale_automatic_workflow_stock_job/__init__.py
  sale_automatic_workflow_stock_job/__manifest__.py
  sale_automatic_workflow_stock_job/data/queue_job_data.xml
  sale_automatic_workflow_stock_job/models/__init__.py
  sale_automatic_workflow_stock_job/models/automatic_workflow_job.py
  sale_automatic_workflow_stock_job/pyproject.toml
  sale_automatic_workflow_stock_job/readme/CONTRIBUTORS.md
  sale_automatic_workflow_stock_job/readme/CREDITS.md
  sale_automatic_workflow_stock_job/readme/DESCRIPTION.md
  sale_automatic_workflow_stock_job/static/description/index.html
  sale_automatic_workflow_stock_job/tests/__init__.py
  sale_automatic_workflow_stock_job/tests/test_auto_workflow_stock_job.py
Labels: approved, ready to merge, bot is merging ⏳

#2852 [16.0][MIG] sale_order_mass_action: Migration to 16.0
  sale_order_mass_action/README.rst
  sale_order_mass_action/__init__.py
  sale_order_mass_action/__manifest__.py
  sale_order_mass_action/i18n/fr.po
  sale_order_mass_action/i18n/sale_order_mass_action.pot
  sale_order_mass_action/readme/CONTRIBUTORS.rst
  sale_order_mass_action/readme/DESCRIPTION.rst
  sale_order_mass_action/readme/ROADMAP.rst
  sale_order_mass_action/readme/USAGE.rst
  sale_order_mass_action/security/security.xml
  sale_order_mass_action/static/description/icon.png
  sale_order_mass_action/static/description/index.html
  sale_order_mass_action/tests/__init__.py
  sale_order_mass_action/tests/test_sale_order_mass_action.py
  sale_order_mass_action/wizards/__init__.py
  sale_order_mass_action/wizards/sale_order_mass_action_view.xml
  sale_order_mass_action/wizards/sale_order_mass_action_wizard.py
  setup/sale_order_mass_action/odoo/addons/sale_order_mass_action
  setup/sale_order_mass_action/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#3721 [17.0][FIX ]sale_order_secondary_unit: fix test conflicts when used with product_matrix
  sale_order_secondary_unit/tests/test_product_template.py
  sale_order_secondary_unit/tests/test_sale_order.py
Labels: approved, bot is merging ⏳

#3599 [16.0][ADD] sale_order_country_allowed_product: Restrict products by country in sales
  sale_order_country_allowed_product/README.rst
  sale_order_country_allowed_product/__init__.py
  sale_order_country_allowed_product/__manifest__.py
  sale_order_country_allowed_product/models/__init__.py
  sale_order_country_allowed_product/models/product_product.py
  sale_order_country_allowed_product/models/product_template.py
  sale_order_country_allowed_product/models/sale_order.py
  sale_order_country_allowed_product/models/sale_order_line.py
  sale_order_country_allowed_product/readme/CONFIGURE.rst
  sale_order_country_allowed_product/readme/CONTRIBUTORS.rst
  sale_order_country_allowed_product/readme/DESCRIPTION.rst
  sale_order_country_allowed_product/readme/USAGE.rst
  sale_order_country_allowed_product/security/res_groups.xml
  sale_order_country_allowed_product/static/description/index.html
  sale_order_country_allowed_product/tests/__init__.py
  sale_order_country_allowed_product/tests/test_sale_order_country_allowed_product.py
  sale_order_country_allowed_product/views/product_views.xml
  sale_order_country_allowed_product/views/sale_order_views.xml
  setup/sale_order_country_allowed_product/odoo/addons/sale_order_country_allowed_product
  setup/sale_order_country_allowed_product/setup.py
Labels: approved, ready to merge

#3666 [16.0][PERF] sale_order_line_cancel: Speed up installtion
  sale_order_line_cancel/__init__.py
  sale_order_line_cancel/__manifest__.py
  sale_order_line_cancel/hooks.py
  sale_order_line_cancel/readme/CONTRIBUTORS.rst
Labels: enhancement, needs review, approved, merged 🎉

#3626 [FIX] sale_order_line_cancel: fix compute depends
  sale_order_line_cancel/models/sale_order_line.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3713 [18.0][FWD][IMP] sale_delivery_state: Skip sale order lines for delivery state + misc fixes
  .oca/oca-port/blacklist/sale_delivery_state.json
  sale_delivery_state/__init__.py
  sale_delivery_state/__manifest__.py
  sale_delivery_state/hooks.py
  sale_delivery_state/migrations/18.0.1.1.0/pre-migration.py
  sale_delivery_state/models/__init__.py
  sale_delivery_state/models/res_company.py
  sale_delivery_state/models/res_config_settings.py
  sale_delivery_state/models/sale_order.py
  sale_delivery_state/models/sale_order_line.py
  sale_delivery_state/readme/CONFIGURE.md
  sale_delivery_state/readme/CONTRIBUTORS.md
  sale_delivery_state/readme/DESCRIPTION.md
  sale_delivery_state/tests/test_delivery_state.py
  sale_delivery_state/views/res_config_settings_views.xml
  sale_delivery_state/views/sale_order_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3719 [MIG] sale_stock_delivery_state: Migration to 18.0
  sale_stock_delivery_state/README.rst
  sale_stock_delivery_state/__init__.py
  sale_stock_delivery_state/__manifest__.py
  sale_stock_delivery_state/i18n/it.po
  sale_stock_delivery_state/i18n/sale_stock_delivery_state.pot
  sale_stock_delivery_state/models/__init__.py
  sale_stock_delivery_state/models/sale_order.py
  sale_stock_delivery_state/pyproject.toml
  sale_stock_delivery_state/readme/CONTRIBUTORS.md
  sale_stock_delivery_state/readme/CREDITS.md
  sale_stock_delivery_state/readme/DESCRIPTION.md
  sale_stock_delivery_state/static/description/icon.png
  sale_stock_delivery_state/static/description/index.html
  sale_stock_delivery_state/views/sale_order_views.xml
Labels: migration, bot is merging ⏳

#3660 [16.0][FIX] sale_order_product_recommendation: recommendations on sales with section or notes
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3711 [18.0] [MIG] sale_block_no_stock: Migration to 18.0
  sale_block_no_stock/README.rst
  sale_block_no_stock/__init__.py
  sale_block_no_stock/__manifest__.py
  sale_block_no_stock/i18n/es.po
  sale_block_no_stock/i18n/it.po
  sale_block_no_stock/i18n/sale_block_no_stock.pot
  sale_block_no_stock/models/__init__.py
  sale_block_no_stock/models/res_company.py
  sale_block_no_stock/models/res_config_settings.py
  sale_block_no_stock/models/sale_order.py
  sale_block_no_stock/pyproject.toml
  sale_block_no_stock/readme/CONFIGURE.md
  sale_block_no_stock/readme/CONTEXT.md
  sale_block_no_stock/readme/CONTRIBUTORS.md
  sale_block_no_stock/readme/CREDITS.md
  sale_block_no_stock/readme/DESCRIPTION.md
  sale_block_no_stock/readme/USAGE.md
  sale_block_no_stock/security/ir.model.access.csv
  sale_block_no_stock/static/description/icon.png
  sale_block_no_stock/static/description/index.html
  sale_block_no_stock/tests/__init__.py
  sale_block_no_stock/tests/test_sale_block_no_stock.py
  sale_block_no_stock/views/res_config_settings_views.xml
  sale_block_no_stock/wizard/__init__.py
  sale_block_no_stock/wizard/sale_order_block_wizard.py
  sale_block_no_stock/wizard/sale_order_block_wizard_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3508 [18.0] [MIG] sale_quotation_number: Migration to 18.0
  sale_quotation_number/README.rst
  sale_quotation_number/__init__.py
  sale_quotation_number/__manifest__.py
  sale_quotation_number/data/ir_sequence_data.xml
  sale_quotation_number/i18n/ca.po
  sale_quotation_number/i18n/de.po
  sale_quotation_number/i18n/es.po
  sale_quotation_number/i18n/es_ES.po
  sale_quotation_number/i18n/fi.po
  sale_quotation_number/i18n/fr.po
  sale_quotation_number/i18n/hr.po
  sale_quotation_number/i18n/hu.po
  sale_quotation_number/i18n/it.po
  sale_quotation_number/i18n/nl.po
  sale_quotation_number/i18n/nl_NL.po
  sale_quotation_number/i18n/pt_BR.po
  sale_quotation_number/i18n/ro.po
  sale_quotation_number/i18n/sale_quotation_number.pot
  sale_quotation_number/i18n/sk.po
  sale_quotation_number/i18n/sl.po
  sale_quotation_number/i18n/tr.po
  sale_quotation_number/i18n/tr_TR.po
  sale_quotation_number/i18n/zh_CN.po
  sale_quotation_number/models/__init__.py
  sale_quotation_number/models/res_company.py
  sale_quotation_number/models/sale_order.py
  sale_quotation_number/pyproject.toml
  sale_quotation_number/readme/CONFIGURE.md
  sale_quotation_number/readme/CONTRIBUTORS.md
  sale_quotation_number/readme/CREDITS.md
  sale_quotation_number/readme/DESCRIPTION.md
  sale_quotation_number/static/description/icon.png
  sale_quotation_number/static/description/index.html
  sale_quotation_number/tests/__init__.py
  sale_quotation_number/tests/test_sale_order.py
  sale_quotation_number/views/sales_config.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3723 [18.0][FIX] sale_stock_picking_blocking: copy method returns multiple records
  sale_stock_picking_blocking/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#3710 [17.0][FIX] sale_order_carrier_auto_assign: preserve carrier on confirm
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/readme/CONFIGURE.md
  sale_order_carrier_auto_assign/readme/CONTRIBUTORS.md
  sale_order_carrier_auto_assign/readme/DESCRIPTION.md
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
Labels: approved, ready to merge, bot is merging ⏳

#3701 [17.0][MIG] sales_team_invoiced_target_domain: Migration to 17.0
  sales_team_invoiced_target_domain/README.rst
  sales_team_invoiced_target_domain/__init__.py
  sales_team_invoiced_target_domain/__manifest__.py
  sales_team_invoiced_target_domain/i18n/sales_team_invoiced_target_domain.pot
  sales_team_invoiced_target_domain/model/__init__.py
  sales_team_invoiced_target_domain/model/crm_team.py
  sales_team_invoiced_target_domain/model/res_company.py
  sales_team_invoiced_target_domain/model/res_config_settings.py
  sales_team_invoiced_target_domain/pyproject.toml
  sales_team_invoiced_target_domain/readme/CONTRIBUTORS.md
  sales_team_invoiced_target_domain/readme/DESCRIPTION.md
  sales_team_invoiced_target_domain/readme/USAGE.md
  sales_team_invoiced_target_domain/static/description/icon.png
  sales_team_invoiced_target_domain/static/description/index.html
  sales_team_invoiced_target_domain/tests/__init__.py
  sales_team_invoiced_target_domain/tests/test_crm_team.py
  sales_team_invoiced_target_domain/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3703 [16.0][FIX] sale_blanket_order: SO blanket_order_id computation
  sale_blanket_order/models/sale_orders.py
  sale_blanket_order/tests/test_sale_order.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3731 [MIG] [18.0] sale_invoice_frequency
  sale_invoice_frequency/README.rst
  sale_invoice_frequency/__init__.py
  sale_invoice_frequency/__manifest__.py
  sale_invoice_frequency/data/sale_invoice_frequency_data.xml
  sale_invoice_frequency/i18n/de.po
  sale_invoice_frequency/i18n/es.po
  sale_invoice_frequency/i18n/fr.po
  sale_invoice_frequency/i18n/it.po
  sale_invoice_frequency/i18n/sale_invoice_frequency.pot
  sale_invoice_frequency/models/__init__.py
  sale_invoice_frequency/models/res_partner.py
  sale_invoice_frequency/models/sale_invoice_frequency.py
  sale_invoice_frequency/models/sale_order.py
  sale_invoice_frequency/pyproject.toml
  sale_invoice_frequency/readme/CONTRIBUTORS.md
  sale_invoice_frequency/readme/DESCRIPTION.md
  sale_invoice_frequency/readme/ROADMAP.md
  sale_invoice_frequency/readme/USAGE.md
  sale_invoice_frequency/security/ir.model.access.csv
  sale_invoice_frequency/static/description/icon.png
  sale_invoice_frequency/static/description/index.html
  sale_invoice_frequency/views/res_partner_view.xml
  sale_invoice_frequency/views/sale_invoice_frequency_view.xml
  sale_invoice_frequency/views/sale_order_view.xml
Labels: approved, migration, bot is merging ⏳

#3414 [16.0][MIG] sale_order_ordered_weight: Migration to 16.0 (from 12.0)
  sale_order_ordered_weight/README.rst
  sale_order_ordered_weight/__init__.py
  sale_order_ordered_weight/__manifest__.py
  sale_order_ordered_weight/i18n/es.po
  sale_order_ordered_weight/i18n/fr.po
  sale_order_ordered_weight/i18n/pt.po
  sale_order_ordered_weight/i18n/sale_order_ordered_weight.pot
  sale_order_ordered_weight/migrations/16.0.1.0.0/pre-migration.py
  sale_order_ordered_weight/models/__init__.py
  sale_order_ordered_weight/models/res_company.py
  sale_order_ordered_weight/models/res_config_settings.py
  sale_order_ordered_weight/models/sale_order.py
  sale_order_ordered_weight/models/sale_order_line.py
  sale_order_ordered_weight/pre_init_hook.py
  sale_order_ordered_weight/readme/CONFIGURE.rst
  sale_order_ordered_weight/readme/CONTRIBUTORS.rst
  sale_order_ordered_weight/readme/DESCRIPTION.rst
  sale_order_ordered_weight/readme/USAGE.rst
  sale_order_ordered_weight/reports/report_sale_order.xml
  sale_order_ordered_weight/static/description/configuration.png
  sale_order_ordered_weight/static/description/icon.png
  sale_order_ordered_weight/static/description/index.html
  sale_order_ordered_weight/static/description/sale_order_form.png
  sale_order_ordered_weight/static/description/sale_order_report.png
  sale_order_ordered_weight/tests/__init__.py
  sale_order_ordered_weight/tests/test_sale_order_ordered_weight.py
  sale_order_ordered_weight/views/res_config_settings_view.xml
  sale_order_ordered_weight/views/sale_order_view.xml
  setup/sale_order_ordered_weight/odoo/addons/sale_order_ordered_weight
  setup/sale_order_ordered_weight/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#3396 [17.0][FIX] sale_order_line_sequence: fix SingletonError in rare cases
  sale_order_line_sequence/models/account_move_line.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3374 [ADD][16.0] Sale Margin Update
  sale_margin_update/README.rst
  sale_margin_update/__init__.py
  sale_margin_update/__manifest__.py
  sale_margin_update/i18n/es.po
  sale_margin_update/models/__init__.py
  sale_margin_update/models/sale_order.py
  sale_margin_update/models/sale_order_line.py
  sale_margin_update/security/ir.model.access.csv
  sale_margin_update/static/description/icon.png
  sale_margin_update/static/description/index.html
  sale_margin_update/tests/__init__.py
  sale_margin_update/tests/test_recalculate_price_margin.py
  sale_margin_update/views/sale_order_views.xml
  sale_margin_update/wizard/__init__.py
  sale_margin_update/wizard/recalculate_price_margin.py
  sale_margin_update/wizard/recalculate_price_margin.xml
  setup/sale_margin_update/odoo/addons/sale_margin_update
  setup/sale_margin_update/setup.py
Labels: approved, ready to merge, bot is merging ⏳
