Repository OCA/sale-workflow, pull requests merged in 2025-04, with the labels that each got.

#3613 [18.0][ADD] sale_order_requested_delivery
  sale_order_requested_delivery/README.rst
  sale_order_requested_delivery/__init__.py
  sale_order_requested_delivery/__manifest__.py
  sale_order_requested_delivery/models/__init__.py
  sale_order_requested_delivery/models/sale_order.py
  sale_order_requested_delivery/models/sale_order_line.py
  sale_order_requested_delivery/pyproject.toml
  sale_order_requested_delivery/readme/CONTRIBUTORS.md
  sale_order_requested_delivery/readme/DESCRIPTION.md
  sale_order_requested_delivery/static/description/index.html
  sale_order_requested_delivery/tests/__init__.py
  sale_order_requested_delivery/tests/test_sale_order.py
  sale_order_requested_delivery/tests/test_sale_order_line.py
  sale_order_requested_delivery/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#3274 [17.0][MIG] sale_elaboration: Migration to 17.0
  sale_elaboration/README.rst
  sale_elaboration/__init__.py
  sale_elaboration/__manifest__.py
  sale_elaboration/hooks.py
  sale_elaboration/i18n/de.po
  sale_elaboration/i18n/es.po
  sale_elaboration/i18n/it.po
  sale_elaboration/i18n/sale_elaboration.pot
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_elaboration.py
  sale_elaboration/models/product_elaboration_mixin.py
  sale_elaboration/models/product_elaboration_profile.py
  sale_elaboration/models/product_template.py
  sale_elaboration/models/res_config_settings.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/models/stock_move.py
  sale_elaboration/models/stock_picking.py
  sale_elaboration/models/stock_rule.py
  sale_elaboration/pyproject.toml
  sale_elaboration/readme/CONFIGURE.md
  sale_elaboration/readme/CONTRIBUTORS.md
  sale_elaboration/readme/DESCRIPTION.md
  sale_elaboration/readme/USAGE.md
  sale_elaboration/reports/report_base.xml
  sale_elaboration/reports/report_deliveryslip.xml
  sale_elaboration/reports/report_picking_operations.xml
  sale_elaboration/security/ir.model.access.csv
  sale_elaboration/security/security.xml
  sale_elaboration/static/description/icon.png
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/__init__.py
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_views.xml
  sale_elaboration/views/res_config_settings_views.xml
  sale_elaboration/views/sale_elaboration_profile_views.xml
  sale_elaboration/views/sale_elaboration_report_views.xml
  sale_elaboration/views/sale_elaboration_views.xml
  sale_elaboration/views/sale_order_views.xml
  sale_elaboration/views/stock_move_line_views.xml
  sale_elaboration/views/stock_move_views.xml
  sale_elaboration/views/stock_picking_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3663 [17.0][IMP-FIX] sale_order_secondary_unit: Avoid constraint violation when creating product attributes
  sale_order_secondary_unit/tests/test_product_template.py
Labels: enhancement, needs review, bot is merging ⏳

#3460 [18.0][MIG] sale_automatic_workflow_job: Migration to 18.0
  sale_automatic_workflow/tests/common.py
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow_job/README.rst
  sale_automatic_workflow_job/__init__.py
  sale_automatic_workflow_job/__manifest__.py
  sale_automatic_workflow_job/data/queue_job_data.xml
  sale_automatic_workflow_job/i18n/es.po
  sale_automatic_workflow_job/i18n/it.po
  sale_automatic_workflow_job/i18n/sale_automatic_workflow_job.pot
  sale_automatic_workflow_job/models/__init__.py
  sale_automatic_workflow_job/models/automatic_workflow_job.py
  sale_automatic_workflow_job/models/queue_job.py
  sale_automatic_workflow_job/pyproject.toml
  sale_automatic_workflow_job/readme/CONTRIBUTORS.md
  sale_automatic_workflow_job/readme/CREDITS.md
  sale_automatic_workflow_job/readme/DESCRIPTION.md
  sale_automatic_workflow_job/static/description/icon.png
  sale_automatic_workflow_job/static/description/index.html
  sale_automatic_workflow_job/tests/__init__.py
  sale_automatic_workflow_job/tests/test_auto_workflow_job.py
  sale_automatic_workflow_periodicity/tests/test_auto_workflow_periodicity.py
Labels: approved, merged 🎉

#3582 [15.0][ADD] sales_team_invoiced_target_domain: New module
  sales_team_invoiced_target_domain/README.rst
  sales_team_invoiced_target_domain/__init__.py
  sales_team_invoiced_target_domain/__manifest__.py
  sales_team_invoiced_target_domain/model/__init__.py
  sales_team_invoiced_target_domain/model/crm_team.py
  sales_team_invoiced_target_domain/model/res_company.py
  sales_team_invoiced_target_domain/model/res_config_settings.py
  sales_team_invoiced_target_domain/readme/CONTRIBUTORS.rst
  sales_team_invoiced_target_domain/readme/DESCRIPTION.rst
  sales_team_invoiced_target_domain/readme/USAGE.rst
  sales_team_invoiced_target_domain/static/description/icon.png
  sales_team_invoiced_target_domain/static/description/index.html
  sales_team_invoiced_target_domain/tests/__init__.py
  sales_team_invoiced_target_domain/tests/test_crm_team.py
  sales_team_invoiced_target_domain/views/res_config_settings_views.xml
  setup/sales_team_invoiced_target_domain/odoo/addons/sales_team_invoiced_target_domain
  setup/sales_team_invoiced_target_domain/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3491 [18.0][MIG] sale_partner_incoterm: Migration to 18.0
  sale_partner_incoterm/README.rst
  sale_partner_incoterm/__init__.py
  sale_partner_incoterm/__manifest__.py
  sale_partner_incoterm/i18n/ca.po
  sale_partner_incoterm/i18n/de.po
  sale_partner_incoterm/i18n/es.po
  sale_partner_incoterm/i18n/fi.po
  sale_partner_incoterm/i18n/fr.po
  sale_partner_incoterm/i18n/it.po
  sale_partner_incoterm/i18n/nl.po
  sale_partner_incoterm/i18n/sale_partner_incoterm.pot
  sale_partner_incoterm/i18n/sl.po
  sale_partner_incoterm/i18n/tr.po
  sale_partner_incoterm/i18n/zh_CN.po
  sale_partner_incoterm/models/__init__.py
  sale_partner_incoterm/models/res_partner.py
  sale_partner_incoterm/models/sale_order.py
  sale_partner_incoterm/pyproject.toml
  sale_partner_incoterm/readme/CONTRIBUTORS.md
  sale_partner_incoterm/readme/DESCRIPTION.md
  sale_partner_incoterm/static/description/icon.png
  sale_partner_incoterm/static/description/index.html
  sale_partner_incoterm/tests/__init__.py
  sale_partner_incoterm/tests/test_sale_partner_incoterm.py
  sale_partner_incoterm/views/res_partner.xml
  sale_partner_incoterm/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#3651 [18.0][MIG] sale_stock_picking_note: Migration to 18.0
  sale_stock_picking_note/README.rst
  sale_stock_picking_note/__init__.py
  sale_stock_picking_note/__manifest__.py
  sale_stock_picking_note/i18n/ca.po
  sale_stock_picking_note/i18n/de.po
  sale_stock_picking_note/i18n/es.po
  sale_stock_picking_note/i18n/fr.po
  sale_stock_picking_note/i18n/it.po
  sale_stock_picking_note/i18n/sale_stock_picking_note.pot
  sale_stock_picking_note/models/__init__.py
  sale_stock_picking_note/models/res_partner.py
  sale_stock_picking_note/models/sale_order.py
  sale_stock_picking_note/models/stock_picking.py
  sale_stock_picking_note/pyproject.toml
  sale_stock_picking_note/readme/CONTRIBUTORS.md
  sale_stock_picking_note/readme/DESCRIPTION.md
  sale_stock_picking_note/readme/USAGE.md
  sale_stock_picking_note/static/description/icon.png
  sale_stock_picking_note/static/description/index.html
  sale_stock_picking_note/tests/__init__.py
  sale_stock_picking_note/tests/test_sale_stock_picking_note.py
  sale_stock_picking_note/views/report_deliveryslip.xml
  sale_stock_picking_note/views/res_partner_view.xml
  sale_stock_picking_note/views/sale_order_view.xml
  sale_stock_picking_note/views/stock_picking_view.xml
Labels: needs review, approved, migration, ready to merge

#3657 [18.0][MIG] sale_order_price_recalculation
  sale_order_price_recalculation/README.rst
  sale_order_price_recalculation/__init__.py
  sale_order_price_recalculation/__manifest__.py
  sale_order_price_recalculation/i18n/ca.po
  sale_order_price_recalculation/i18n/de.po
  sale_order_price_recalculation/i18n/el_GR.po
  sale_order_price_recalculation/i18n/es.po
  sale_order_price_recalculation/i18n/es_ES.po
  sale_order_price_recalculation/i18n/es_VE.po
  sale_order_price_recalculation/i18n/fi.po
  sale_order_price_recalculation/i18n/fr.po
  sale_order_price_recalculation/i18n/hr.po
  sale_order_price_recalculation/i18n/hr_HR.po
  sale_order_price_recalculation/i18n/hu.po
  sale_order_price_recalculation/i18n/it.po
  sale_order_price_recalculation/i18n/nl.po
  sale_order_price_recalculation/i18n/nl_NL.po
  sale_order_price_recalculation/i18n/pt.po
  sale_order_price_recalculation/i18n/pt_BR.po
  sale_order_price_recalculation/i18n/ro.po
  sale_order_price_recalculation/i18n/sale_order_price_recalculation.pot
  sale_order_price_recalculation/i18n/sl.po
  sale_order_price_recalculation/i18n/tr.po
  sale_order_price_recalculation/i18n/tr_TR.po
  sale_order_price_recalculation/i18n/vi_VN.po
  sale_order_price_recalculation/i18n/zh_CN.po
  sale_order_price_recalculation/models/__init__.py
  sale_order_price_recalculation/models/sale_order.py
  sale_order_price_recalculation/pyproject.toml
  sale_order_price_recalculation/readme/CONTRIBUTORS.md
  sale_order_price_recalculation/readme/DESCRIPTION.md
  sale_order_price_recalculation/readme/INSTALL.md
  sale_order_price_recalculation/readme/ROADMAP.md
  sale_order_price_recalculation/readme/USAGE.md
  sale_order_price_recalculation/static/description/icon.png
  sale_order_price_recalculation/static/description/index.html
  sale_order_price_recalculation/static/description/sale_order_price_recalculation.drawio.png
  sale_order_price_recalculation/tests/__init__.py
  sale_order_price_recalculation/tests/test_sale_order_price_recalculation.py
  sale_order_price_recalculation/views/sale_order_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3494 [18.0][MOV] product_set_sell_only_by_packaging: Migration to 18.0
  product_set_sell_only_by_packaging/README.rst
  product_set_sell_only_by_packaging/__init__.py
  product_set_sell_only_by_packaging/__manifest__.py
  product_set_sell_only_by_packaging/data/ir_cron.xml
  product_set_sell_only_by_packaging/i18n/es.po
  product_set_sell_only_by_packaging/i18n/product_set_sell_only_by_packaging.pot
  product_set_sell_only_by_packaging/models/__init__.py
  product_set_sell_only_by_packaging/models/product_product.py
  product_set_sell_only_by_packaging/models/product_set_line.py
  product_set_sell_only_by_packaging/models/product_template.py
  product_set_sell_only_by_packaging/pyproject.toml
  product_set_sell_only_by_packaging/readme/CONTRIBUTORS.md
  product_set_sell_only_by_packaging/readme/CREDITS.md
  product_set_sell_only_by_packaging/readme/DESCRIPTION.md
  product_set_sell_only_by_packaging/static/description/icon.png
  product_set_sell_only_by_packaging/static/description/index.html
  product_set_sell_only_by_packaging/tests/__init__.py
  product_set_sell_only_by_packaging/tests/test_product_set_packaging.py
  product_set_sell_only_by_packaging/views/product_set_line.xml
  product_set_sell_only_by_packaging/views/product_template.xml
Labels: bot is merging ⏳

#3656 [18.0] [MIG] pricelist_cache
  pricelist_cache/README.rst
  pricelist_cache/__init__.py
  pricelist_cache/__manifest__.py
  pricelist_cache/data/demo.xml
  pricelist_cache/data/ir_cron.xml
  pricelist_cache/data/ir_filters_data.xml
  pricelist_cache/data/queue_job.xml
  pricelist_cache/hooks.py
  pricelist_cache/i18n/es.po
  pricelist_cache/i18n/pricelist_cache.pot
  pricelist_cache/models/__init__.py
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/models/product_pricelist_item.py
  pricelist_cache/models/product_product.py
  pricelist_cache/models/res_partner.py
  pricelist_cache/pyproject.toml
  pricelist_cache/readme/CONTRIBUTORS.md
  pricelist_cache/readme/CREDITS.md
  pricelist_cache/readme/DESCRIPTION.md
  pricelist_cache/readme/ROADMAP.md
  pricelist_cache/security/ir.model.access.csv
  pricelist_cache/static/description/icon.png
  pricelist_cache/static/description/index.html
  pricelist_cache/tests/__init__.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_methods.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
  pricelist_cache/tests/test_pricelist_cache.py
  pricelist_cache/views/product_pricelist.xml
  pricelist_cache/views/product_pricelist_cache.xml
  pricelist_cache/views/res_partner.xml
  pricelist_cache/wizards/__init__.py
  pricelist_cache/wizards/pricelist_cache_wizard.py
  pricelist_cache/wizards/pricelist_cache_wizard.xml
Labels: approved, bot is merging ⏳

#3681 [18.0][FIX]product_form_sale_link: fixed logging in product template
  product_form_sale_link/models/product_template.py
Labels: bot is merging ⏳

#3635 [17.0][IMP] sale_order_carrier_auto_assign: Add delivery_auto_refresh changes
  sale_order_carrier_auto_assign/README.rst
  sale_order_carrier_auto_assign/__manifest__.py
  sale_order_carrier_auto_assign/models/res_company.py
  sale_order_carrier_auto_assign/models/res_config_settings.py
  sale_order_carrier_auto_assign/models/sale_order.py
  sale_order_carrier_auto_assign/static/description/index.html
  sale_order_carrier_auto_assign/tests/test_sale_order_carrier_auto_assign.py
  sale_order_carrier_auto_assign/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#3655 [17.0][FIX] sale_product_multi_add: avoid description overwrite
  sale_product_multi_add/wizards/sale_import_products.py
Labels: approved, ready to merge, bot is merging ⏳

#3202 [17.0][MIG] sale_promotion_rule
  sale_promotion_rule/README.rst
  sale_promotion_rule/__init__.py
  sale_promotion_rule/__manifest__.py
  sale_promotion_rule/demo/product.xml
  sale_promotion_rule/demo/sale_demo.xml
  sale_promotion_rule/i18n/ca.po
  sale_promotion_rule/i18n/es.po
  sale_promotion_rule/i18n/fr.po
  sale_promotion_rule/i18n/sale_promotion_rule.pot
  sale_promotion_rule/models/__init__.py
  sale_promotion_rule/models/sale_order.py
  sale_promotion_rule/models/sale_order_line.py
  sale_promotion_rule/models/sale_promotion_rule.py
  sale_promotion_rule/pyproject.toml
  sale_promotion_rule/readme/CONTRIBUTORS.md
  sale_promotion_rule/readme/DESCRIPTION.md
  sale_promotion_rule/readme/ROADMAP.md
  sale_promotion_rule/security/ir.model.access.csv
  sale_promotion_rule/security/sale_promotion_rule.xml
  sale_promotion_rule/static/description/icon.png
  sale_promotion_rule/static/description/index.html
  sale_promotion_rule/static/description/promotion_rule.png
  sale_promotion_rule/tests/__init__.py
  sale_promotion_rule/tests/test_promotion.py
  sale_promotion_rule/views/sale_order.xml
  sale_promotion_rule/views/sale_promotion_rule.xml
  sale_promotion_rule/wizards/__init__.py
  sale_promotion_rule/wizards/sale_order_add_coupon.py
  sale_promotion_rule/wizards/sale_order_add_coupon.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3677 [18.0][MIG] sale_order_product_recommendation: MIgration to 18.0
  sale_order_product_recommendation/README.rst
  sale_order_product_recommendation/__init__.py
  sale_order_product_recommendation/__manifest__.py
  sale_order_product_recommendation/i18n/es.po
  sale_order_product_recommendation/i18n/it.po
  sale_order_product_recommendation/i18n/pt_BR.po
  sale_order_product_recommendation/i18n/sale_order_product_recommendation.pot
  sale_order_product_recommendation/models/__init__.py
  sale_order_product_recommendation/models/res_company.py
  sale_order_product_recommendation/models/res_config_settings.py
  sale_order_product_recommendation/pyproject.toml
  sale_order_product_recommendation/readme/CONFIGURE.md
  sale_order_product_recommendation/readme/CONTRIBUTORS.md
  sale_order_product_recommendation/readme/DESCRIPTION.md
  sale_order_product_recommendation/readme/USAGE.md
  sale_order_product_recommendation/security/ir.model.access.csv
  sale_order_product_recommendation/static/description/icon.png
  sale_order_product_recommendation/static/description/index.html
  sale_order_product_recommendation/tests/__init__.py
  sale_order_product_recommendation/tests/test_recommendation.py
  sale_order_product_recommendation/tests/test_recommendation_common.py
  sale_order_product_recommendation/views/res_config_settings_views.xml
  sale_order_product_recommendation/views/sale_order_view.xml
  sale_order_product_recommendation/wizards/__init__.py
  sale_order_product_recommendation/wizards/sale_order_recommendation.py
  sale_order_product_recommendation/wizards/sale_order_recommendation_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3683 [15.0][FIX] sales_team_invoiced_target_domain: Remove CRM dependency
  sales_team_invoiced_target_domain/README.rst
  sales_team_invoiced_target_domain/__manifest__.py
  sales_team_invoiced_target_domain/migrations/15.0.1.0.1/pre-migration.py
  sales_team_invoiced_target_domain/model/crm_team.py
  sales_team_invoiced_target_domain/model/res_company.py
  sales_team_invoiced_target_domain/model/res_config_settings.py
  sales_team_invoiced_target_domain/readme/USAGE.rst
  sales_team_invoiced_target_domain/static/description/index.html
  sales_team_invoiced_target_domain/tests/test_crm_team.py
  sales_team_invoiced_target_domain/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#3593 [18.0][IMP] sale_force_invoiced: recompute invoice amounts when changing force boolean
  sale_force_invoiced/model/sale_order.py
  sale_force_invoiced/tests/test_sale_force_invoiced.py
Labels: bot is merging ⏳

#3676 [UPD] Copier + add rebel discount modules
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  sale_triple_discount/__manifest__.py
  setup/sale_triple_discount/setup.py
Labels: approved, bot is merging ⏳

#3687 [16.0][IMP] sale_order_product_recommendation_quick_add: add return keyword
  sale_order_product_recommendation_quick_add/README.rst
  sale_order_product_recommendation_quick_add/models/sale_order.py
  sale_order_product_recommendation_quick_add/readme/CONTRIBUTORS.rst
  sale_order_product_recommendation_quick_add/static/description/index.html
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#2986 [14.0][ADD] sale_stock_service_level
  sale_stock_service_level/README.rst
  sale_stock_service_level/__init__.py
  sale_stock_service_level/__manifest__.py
  sale_stock_service_level/i18n/fr.po
  sale_stock_service_level/i18n/sale_stock_service_level.pot
  sale_stock_service_level/models/__init__.py
  sale_stock_service_level/models/sale_order.py
  sale_stock_service_level/models/sale_order_line.py
  sale_stock_service_level/readme/CONTRIBUTORS.rst
  sale_stock_service_level/readme/DESCRIPTION.rst
  sale_stock_service_level/static/description/index.html
  sale_stock_service_level/tests/__init__.py
  sale_stock_service_level/tests/test_sale_stock_service_level.py
  sale_stock_service_level/views/sale_order_views.xml
  setup/sale_stock_service_level/odoo/addons/sale_stock_service_level
  setup/sale_stock_service_level/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3523 [16.0][MIG] sale_order_line_description
  sale_order_line_description/README.rst
  sale_order_line_description/__init__.py
  sale_order_line_description/__manifest__.py
  sale_order_line_description/i18n/ca.po
  sale_order_line_description/i18n/de.po
  sale_order_line_description/i18n/es.po
  sale_order_line_description/i18n/es_VE.po
  sale_order_line_description/i18n/fr.po
  sale_order_line_description/i18n/fr_FR.po
  sale_order_line_description/i18n/hr.po
  sale_order_line_description/i18n/it.po
  sale_order_line_description/i18n/nl_NL.po
  sale_order_line_description/i18n/pt_BR.po
  sale_order_line_description/i18n/ro.po
  sale_order_line_description/i18n/sale_order_line_description.pot
  sale_order_line_description/i18n/sl.po
  sale_order_line_description/i18n/tr.po
  sale_order_line_description/i18n/tr_TR.po
  sale_order_line_description/i18n/zh_CN.po
  sale_order_line_description/models/__init__.py
  sale_order_line_description/models/res_config_settings.py
  sale_order_line_description/models/sale_order_line.py
  sale_order_line_description/readme/CONFIGURE.rst
  sale_order_line_description/readme/CONTRIBUTORS.rst
  sale_order_line_description/readme/DESCRIPTION.rst
  sale_order_line_description/readme/USAGE.rst
  sale_order_line_description/security/sale_security.xml
  sale_order_line_description/static/description/icon.png
  sale_order_line_description/static/description/index.html
  sale_order_line_description/tests/__init__.py
  sale_order_line_description/tests/test_sale.py
  sale_order_line_description/views/res_config_settings_views.xml
  setup/sale_order_line_description/odoo/addons/sale_order_line_description
  setup/sale_order_line_description/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3645 [18.0][MIG] sale_order_tag: Migration to 18.0
  sale_order_tag/README.rst
  sale_order_tag/__init__.py
  sale_order_tag/__manifest__.py
  sale_order_tag/data/sale_order_tag_data.xml
  sale_order_tag/i18n/ca.po
  sale_order_tag/i18n/de.po
  sale_order_tag/i18n/es.po
  sale_order_tag/i18n/it.po
  sale_order_tag/i18n/sale_order_tag.pot
  sale_order_tag/i18n/tr.po
  sale_order_tag/models/__init__.py
  sale_order_tag/models/sale_order.py
  sale_order_tag/models/sale_order_tag.py
  sale_order_tag/pyproject.toml
  sale_order_tag/readme/CONTRIBUTORS.md
  sale_order_tag/readme/DESCRIPTION.md
  sale_order_tag/readme/USAGE.md
  sale_order_tag/security/ir.model.access.csv
  sale_order_tag/security/sale_order_tag_security.xml
  sale_order_tag/static/description/icon.png
  sale_order_tag/static/description/index.html
  sale_order_tag/views/sale_order.xml
  sale_order_tag/views/sale_order_tag.xml
Labels: needs review, migration, bot is merging ⏳

#3695 [16.0] sell_only_by_packaging: fix sell_only_by_packaging copy
  sell_only_by_packaging/models/product_template.py
Labels: bot is merging ⏳

#3643 [18.0][MIG] sale_require_po_doc: Migration to 18.0
  sale_require_po_doc/README.rst
  sale_require_po_doc/__init__.py
  sale_require_po_doc/__manifest__.py
  sale_require_po_doc/i18n/sale_require_po_doc.pot
  sale_require_po_doc/models/__init__.py
  sale_require_po_doc/models/res_partner.py
  sale_require_po_doc/models/sale_order.py
  sale_require_po_doc/pyproject.toml
  sale_require_po_doc/readme/CONTRIBUTORS.md
  sale_require_po_doc/readme/CREDITS.md
  sale_require_po_doc/readme/DESCRIPTION.md
  sale_require_po_doc/static/description/icon.png
  sale_require_po_doc/static/description/index.html
  sale_require_po_doc/tests/__init__.py
  sale_require_po_doc/tests/test_sale_require_po_doc.py
  sale_require_po_doc/views/res_partner_view.xml
  sale_require_po_doc/views/sale_order_view.xml
Labels: needs review, migration, bot is merging ⏳

#3625 [ADD] [16.0] sale_stock_reservation_issue_on_qty_at_date_widget
  sale_stock_reservation_issue_on_qty_at_date_widget/README.rst
  sale_stock_reservation_issue_on_qty_at_date_widget/__init__.py
  sale_stock_reservation_issue_on_qty_at_date_widget/__manifest__.py
  sale_stock_reservation_issue_on_qty_at_date_widget/readme/CONTEXT.md
  sale_stock_reservation_issue_on_qty_at_date_widget/readme/CONTRIBUTORS.md
  sale_stock_reservation_issue_on_qty_at_date_widget/readme/DESCRIPTION.md
  sale_stock_reservation_issue_on_qty_at_date_widget/readme/INSTALL.md
  sale_stock_reservation_issue_on_qty_at_date_widget/readme/USAGE.md
  sale_stock_reservation_issue_on_qty_at_date_widget/static/description/icon.png
  sale_stock_reservation_issue_on_qty_at_date_widget/static/description/index.html
  sale_stock_reservation_issue_on_qty_at_date_widget/static/description/reservation_issue_color.png
  sale_stock_reservation_issue_on_qty_at_date_widget/static/src/widgets/qty_at_date_widget.esm.js
  sale_stock_reservation_issue_on_qty_at_date_widget/static/src/widgets/qty_at_date_widget.xml
  setup/sale_stock_reservation_issue_on_qty_at_date_widget/odoo/addons/sale_stock_reservation_issue_on_qty_at_date_widget
  setup/sale_stock_reservation_issue_on_qty_at_date_widget/setup.py
Labels: needs review, bot is merging ⏳
