Repository OCA/sale-workflow, pull requests merged in 2025-09, with the labels that each got.

#3825 [16.0][IMP] sale_blanket_order: add tags and pass info to SO
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
  sale_blanket_order/wizard/create_sale_orders.py
Labels: approved, bot is merging ⏳

#3848 [16.0][MIG] sale_pricelist_item_advanced
  sale_pricelist_item_advanced/README.rst
  sale_pricelist_item_advanced/__init__.py
  sale_pricelist_item_advanced/__manifest__.py
  sale_pricelist_item_advanced/i18n/es.po
  sale_pricelist_item_advanced/i18n/it.po
  sale_pricelist_item_advanced/i18n/sale_pricelist_item_advanced.pot
  sale_pricelist_item_advanced/readme/CONTRIBUTORS.rst
  sale_pricelist_item_advanced/readme/DESCRIPTION.rst
  sale_pricelist_item_advanced/readme/HISTORY.rst
  sale_pricelist_item_advanced/readme/USAGE.rst
  sale_pricelist_item_advanced/static/description/icon.png
  sale_pricelist_item_advanced/static/description/index.html
  sale_pricelist_item_advanced/views/product_pricelist_item.xml
  setup/sale_pricelist_item_advanced/odoo/addons/sale_pricelist_item_advanced
  setup/sale_pricelist_item_advanced/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3749 [16.0][ADD] sale_order_minimum_amount
  sale_order_minimum_amount/README.rst
  sale_order_minimum_amount/__init__.py
  sale_order_minimum_amount/__manifest__.py
  sale_order_minimum_amount/models/__init__.py
  sale_order_minimum_amount/models/res_company.py
  sale_order_minimum_amount/models/res_config_settings.py
  sale_order_minimum_amount/models/sale_order.py
  sale_order_minimum_amount/readme/CONFIGURE.rst
  sale_order_minimum_amount/readme/CONTRIBUTORS.rst
  sale_order_minimum_amount/readme/CREDITS.rst
  sale_order_minimum_amount/readme/DESCRIPTION.rst
  sale_order_minimum_amount/readme/USAGE.rst
  sale_order_minimum_amount/static/description/index.html
  sale_order_minimum_amount/tests/__init__.py
  sale_order_minimum_amount/tests/test_sale_order.py
  sale_order_minimum_amount/views/res_config_settings_views.xml
  setup/sale_order_minimum_amount/odoo/addons/sale_order_minimum_amount
  setup/sale_order_minimum_amount/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3061 [FIX] sale_triple_discount: apply rounding
  sale_triple_discount/models/sale_order_line.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#2637 [16.0][MIG] sale_order_end_user
  sale_order_end_user/README.rst
  sale_order_end_user/__init__.py
  sale_order_end_user/__manifest__.py
  sale_order_end_user/models/__init__.py
  sale_order_end_user/models/sale_order.py
  sale_order_end_user/readme/CONTRIBUTORS.rst
  sale_order_end_user/readme/DESCRIPTION.rst
  sale_order_end_user/readme/USAGE.rst
  sale_order_end_user/static/description/icon.png
  sale_order_end_user/static/description/index.html
  sale_order_end_user/views/sale_order.xml
  setup/sale_order_end_user/odoo/addons/sale_order_end_user
  setup/sale_order_end_user/setup.py
Labels: needs review, migration, bot is merging ⏳

#3878 [18.0][MIG] sale_packaging_default: Migration to 18.0
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  eslint.config.cjs
  sale_packaging_default/README.rst
  sale_packaging_default/__init__.py
  sale_packaging_default/__manifest__.py
  sale_packaging_default/i18n/es.po
  sale_packaging_default/i18n/it.po
  sale_packaging_default/i18n/sale_packaging_default.pot
  sale_packaging_default/models/__init__.py
  sale_packaging_default/models/product_packaging.py
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/pyproject.toml
  sale_packaging_default/readme/CONFIGURE.md
  sale_packaging_default/readme/CONTEXT.md
  sale_packaging_default/readme/CONTRIBUTORS.md
  sale_packaging_default/readme/DESCRIPTION.md
  sale_packaging_default/readme/USAGE.md
  sale_packaging_default/static/description/icon.png
  sale_packaging_default/static/description/index.html
  sale_packaging_default/tests/__init__.py
  sale_packaging_default/tests/test_sale_packaging_default.py
  sale_packaging_default/views/sale_order_view.xml
Labels: bot is merging ⏳

#3871 [16.0][MIG] sale_order_secondary_unit
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/fi.po
  sale_order_secondary_unit/i18n/it.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/migrations/16.0.1.0.0/post-migration.py
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/pyproject.toml
  sale_order_secondary_unit/readme/CONFIGURE.md
  sale_order_secondary_unit/readme/CONTRIBUTORS.md
  sale_order_secondary_unit/readme/DESCRIPTION.md
  sale_order_secondary_unit/readme/USAGE.md
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_product_template.py
  sale_order_secondary_unit/tests/test_sale_order.py
  sale_order_secondary_unit/views/product_secondary_unit_views.xml
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
  setup/sale_order_secondary_unit/odoo/addons/sale_order_secondary_unit
  setup/sale_order_secondary_unit/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3527 [16.0][MIG] pricelist_cache: Migration to 16.0
  pricelist_cache/README.rst
  pricelist_cache/__init__.py
  pricelist_cache/__manifest__.py
  pricelist_cache/data/base_automation.xml
  pricelist_cache/data/demo.xml
  pricelist_cache/data/ir_cron.xml
  pricelist_cache/data/ir_filters_data.xml
  pricelist_cache/data/queue_job.xml
  pricelist_cache/hooks.py
  pricelist_cache/i18n/es.po
  pricelist_cache/i18n/pricelist_cache.pot
  pricelist_cache/models/__init__.py
  pricelist_cache/models/product_pricelist.py
  pricelist_cache/models/product_pricelist_cache.py
  pricelist_cache/models/product_pricelist_item.py
  pricelist_cache/models/product_product.py
  pricelist_cache/models/res_partner.py
  pricelist_cache/readme/CONTRIBUTORS.rst
  pricelist_cache/readme/CREDITS.rst
  pricelist_cache/readme/DESCRIPTION.rst
  pricelist_cache/readme/ROADMAP.rst
  pricelist_cache/security/ir.model.access.csv
  pricelist_cache/static/description/icon.png
  pricelist_cache/static/description/index.html
  pricelist_cache/tests/__init__.py
  pricelist_cache/tests/common.py
  pricelist_cache/tests/test_methods.py
  pricelist_cache/tests/test_partner_pricelist_cache.py
  pricelist_cache/tests/test_pricelist_cache.py
  pricelist_cache/views/product_pricelist.xml
  pricelist_cache/views/product_pricelist_cache.xml
  pricelist_cache/views/res_partner.xml
  pricelist_cache/wizards/__init__.py
  pricelist_cache/wizards/pricelist_cache_wizard.py
  pricelist_cache/wizards/pricelist_cache_wizard.xml
  setup/pricelist_cache/odoo/addons/pricelist_cache
  setup/pricelist_cache/setup.py
Labels: approved, bot is merging ⏳

#3886 [18.0][ADD] sale_product_identification
  sale_product_identification/README.rst
  sale_product_identification/__init__.py
  sale_product_identification/__manifest__.py
  sale_product_identification/i18n/es.po
  sale_product_identification/models/__init__.py
  sale_product_identification/models/product_template.py
  sale_product_identification/models/product_template_id_category.py
  sale_product_identification/models/res_partner_id_number.py
  sale_product_identification/models/sale_order.py
  sale_product_identification/pyproject.toml
  sale_product_identification/readme/CONTRIBUTORS.md
  sale_product_identification/readme/DESCRIPTION.md
  sale_product_identification/readme/USAGE.md
  sale_product_identification/security/ir.model.access.csv
  sale_product_identification/static/description/icon.png
  sale_product_identification/static/description/index.html
  sale_product_identification/static/img/readme/ADD_IDENTIFICATION.png
  sale_product_identification/static/img/readme/CATEGORIES_REQUIRED.png
  sale_product_identification/static/img/readme/CONFIRM_IDENTIFICATION.png
  sale_product_identification/tests/__init__.py
  sale_product_identification/tests/sale_product_identification_common.py
  sale_product_identification/tests/test_sale_product_identification.py
  sale_product_identification/views/product_template_views.xml
  sale_product_identification/wizards/__init__.py
  sale_product_identification/wizards/wizard_confirm_identification.py
  sale_product_identification/wizards/wizard_confirm_identification.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3899 [18.0][FIX] sale_order_type: Don't hide route_id field if no warehouse
  sale_order_type/views/sale_order_type_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3789 [18.0] [IMP] sale_exception: Confirm directly the sale order when ignoring exceptions
  sale_exception/tests/test_sale_exception.py
  sale_exception/wizard/sale_exception_confirm.py
  sale_exception/wizard/sale_exception_confirm_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#2903 [16.0][MIG] account_invoice_pricelist_technical
  account_invoice_pricelist_technical/README.rst
  account_invoice_pricelist_technical/__init__.py
  account_invoice_pricelist_technical/__manifest__.py
  account_invoice_pricelist_technical/i18n/account_invoice_pricelist_technical.pot
  account_invoice_pricelist_technical/i18n/fr.po
  account_invoice_pricelist_technical/models/__init__.py
  account_invoice_pricelist_technical/models/account_move.py
  account_invoice_pricelist_technical/readme/CONTRIBUTORS.rst
  account_invoice_pricelist_technical/readme/DESCRIPTION.rst
  account_invoice_pricelist_technical/static/description/icon.png
  account_invoice_pricelist_technical/static/description/index.html
  setup/account_invoice_pricelist_technical/odoo/addons/account_invoice_pricelist_technical
  setup/account_invoice_pricelist_technical/setup.py
Labels: approved, migration, bot is merging ⏳

#3804 [17.0] [MIG] sale_exception_holidays_public: Migration to 17.0
  sale_exception_holidays_public/README.rst
  sale_exception_holidays_public/__init__.py
  sale_exception_holidays_public/__manifest__.py
  sale_exception_holidays_public/data/sale_exception_data.xml
  sale_exception_holidays_public/i18n/es.po
  sale_exception_holidays_public/i18n/fr.po
  sale_exception_holidays_public/i18n/it.po
  sale_exception_holidays_public/i18n/sale_exception_holidays_public.pot
  sale_exception_holidays_public/models/__init__.py
  sale_exception_holidays_public/models/sale_order.py
  sale_exception_holidays_public/pyproject.toml
  sale_exception_holidays_public/readme/CONFIGURE.md
  sale_exception_holidays_public/readme/CONTRIBUTORS.md
  sale_exception_holidays_public/readme/CREDITS.md
  sale_exception_holidays_public/readme/DESCRIPTION.md
  sale_exception_holidays_public/readme/USAGE.md
  sale_exception_holidays_public/static/description/icon.png
  sale_exception_holidays_public/static/description/index.html
  sale_exception_holidays_public/tests/__init__.py
  sale_exception_holidays_public/tests/test_sale_exception.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3905 [18.0][FIX] sale_order_lot_selection: Add precompute=True to avoid side effects
  sale_order_lot_selection/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#3736 [17.0][MIG] sale_force_invoiced_quantity Migration to 17.0
  sale_force_invoiced_quantity/README.rst
  sale_force_invoiced_quantity/__init__.py
  sale_force_invoiced_quantity/__manifest__.py
  sale_force_invoiced_quantity/demo/demo_product.xml
  sale_force_invoiced_quantity/demo/demo_sale_order.xml
  sale_force_invoiced_quantity/i18n/it.po
  sale_force_invoiced_quantity/i18n/sale_force_invoiced_quantity.pot
  sale_force_invoiced_quantity/models/__init__.py
  sale_force_invoiced_quantity/models/sale_order_line.py
  sale_force_invoiced_quantity/pyproject.toml
  sale_force_invoiced_quantity/readme/CONFIGURE.md
  sale_force_invoiced_quantity/readme/CONTEXT.md
  sale_force_invoiced_quantity/readme/CONTRIBUTORS.md
  sale_force_invoiced_quantity/readme/DESCRIPTION.md
  sale_force_invoiced_quantity/readme/USAGE.md
  sale_force_invoiced_quantity/static/description/icon.png
  sale_force_invoiced_quantity/static/description/index.html
  sale_force_invoiced_quantity/tests/__init__.py
  sale_force_invoiced_quantity/tests/test_sale_force_invoiced_qty.py
  sale_force_invoiced_quantity/views/sale_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3650 [FIX] sale_manual_delivery: wrong way to access action requires admin rights
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/tests/test_manual_delivery.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3902 [18.0][FIX] sale_manual_delivery: wrong way to access action requires admin rights
  sale_manual_delivery/models/sale_order.py
  sale_manual_delivery/tests/test_manual_delivery.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3872 [16.0][MIG] sale_stock_secondary_unit
  sale_stock_secondary_unit/README.rst
  sale_stock_secondary_unit/__init__.py
  sale_stock_secondary_unit/__manifest__.py
  sale_stock_secondary_unit/i18n/de.po
  sale_stock_secondary_unit/i18n/es.po
  sale_stock_secondary_unit/i18n/it.po
  sale_stock_secondary_unit/i18n/sale_stock_secondary_unit.pot
  sale_stock_secondary_unit/i18n/zh_CN.po
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/stock_rule.py
  sale_stock_secondary_unit/pyproject.toml
  sale_stock_secondary_unit/readme/CONTRIBUTORS.md
  sale_stock_secondary_unit/readme/DESCRIPTION.md
  sale_stock_secondary_unit/readme/USAGE.md
  sale_stock_secondary_unit/static/description/icon.png
  sale_stock_secondary_unit/static/description/index.html
  sale_stock_secondary_unit/tests/__init__.py
  sale_stock_secondary_unit/tests/test_sale_stock_secondary_unit.py
  setup/sale_stock_secondary_unit/odoo/addons/sale_stock_secondary_unit
  setup/sale_stock_secondary_unit/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3906 [16.0][FIX] sale_stock_picking_blocking: Do not compute blocking_id on create()
  sale_stock_picking_blocking/models/sale_order.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#3843 [18.0][IMP] sale_delivery_state: add delivery status field to search views
  sale_delivery_state/views/sale_order_views.xml
Labels: enhancement, approved, bot is merging ⏳

#3888 [18.0][MIG] sale_order_line_remove
  sale_order_line_remove/README.rst
  sale_order_line_remove/__init__.py
  sale_order_line_remove/__manifest__.py
  sale_order_line_remove/i18n/sale_order_line_remove.pot
  sale_order_line_remove/models/__init__.py
  sale_order_line_remove/models/res_config_settings.py
  sale_order_line_remove/models/sale_order.py
  sale_order_line_remove/pyproject.toml
  sale_order_line_remove/readme/CONTRIBUTORS.md
  sale_order_line_remove/readme/DESCRIPTION.md
  sale_order_line_remove/readme/USAGE.md
  sale_order_line_remove/static/description/icon.png
  sale_order_line_remove/static/description/index.html
  sale_order_line_remove/tests/__init__.py
  sale_order_line_remove/tests/test_sale_order_line.py
  sale_order_line_remove/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3911 [17.0][FWP][IMP] sale_order_line_date: commitment_date copy False
  sale_order_line_date/models/sale_order_line.py
  sale_order_line_date/tests/test_sale_order_line_date.py
Labels: enhancement, approved, bot is merging ⏳

#3316 [16.0][MIG] sale_fully_invoiced: Migration to v16
  sale_fully_invoiced/README.rst
  sale_fully_invoiced/__init__.py
  sale_fully_invoiced/__manifest__.py
  sale_fully_invoiced/i18n/sale_fully_invoiced.pot
  sale_fully_invoiced/models/__init__.py
  sale_fully_invoiced/models/sale.py
  sale_fully_invoiced/readme/CONTRIBUTORS.rst
  sale_fully_invoiced/readme/DESCRIPTION.rst
  sale_fully_invoiced/readme/USAGE.rst
  sale_fully_invoiced/static/description/icon.png
  sale_fully_invoiced/static/description/index.html
  sale_fully_invoiced/tests/__init__.py
  sale_fully_invoiced/tests/test_sale_fully_invoiced.py
  sale_fully_invoiced/views/sale_views.xml
  setup/sale_fully_invoiced/odoo/addons/sale_fully_invoiced
  setup/sale_fully_invoiced/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#3863 [16.0][FIX] sale_advance_payment: fix invoice paid amount
  sale_advance_payment/models/sale.py
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, needs review, bot is merging ⏳

#3537 [17.0] [MIG] sale_order_invoice_amount
  sale_order_invoice_amount/README.rst
  sale_order_invoice_amount/__init__.py
  sale_order_invoice_amount/__manifest__.py
  sale_order_invoice_amount/i18n/es.po
  sale_order_invoice_amount/i18n/fr.po
  sale_order_invoice_amount/i18n/it.po
  sale_order_invoice_amount/i18n/sale_order_invoice_amount.pot
  sale_order_invoice_amount/migrations/17.0.1.0.0/post-migration.py
  sale_order_invoice_amount/migrations/17.0.1.0.0/pre-migration.py
  sale_order_invoice_amount/models/__init__.py
  sale_order_invoice_amount/models/res_company.py
  sale_order_invoice_amount/models/sale_order.py
  sale_order_invoice_amount/models/sale_order_config_settings.py
  sale_order_invoice_amount/pyproject.toml
  sale_order_invoice_amount/readme/CONTRIBUTORS.md
  sale_order_invoice_amount/readme/DESCRIPTION.md
  sale_order_invoice_amount/static/description/icon.png
  sale_order_invoice_amount/static/description/index.html
  sale_order_invoice_amount/static/src/xml/tax_totals.xml
  sale_order_invoice_amount/tests/__init__.py
  sale_order_invoice_amount/tests/test_sale_order_invoice_amount.py
  sale_order_invoice_amount/views/sale_order_config_settings.xml
  sale_order_invoice_amount/views/sale_order_view.xml
Labels: needs review, migration, bot is merging ⏳
