Repository OCA/sale-workflow, pull requests merged in 2025-01, with the labels that each got.

#3504 [MIG] sale_commercial_partner: Migration to 18.0
  sale_commercial_partner/README.rst
  sale_commercial_partner/__init__.py
  sale_commercial_partner/__manifest__.py
  sale_commercial_partner/i18n/ca.po
  sale_commercial_partner/i18n/ca_ES.po
  sale_commercial_partner/i18n/de.po
  sale_commercial_partner/i18n/el_GR.po
  sale_commercial_partner/i18n/es.po
  sale_commercial_partner/i18n/es_MX.po
  sale_commercial_partner/i18n/es_VE.po
  sale_commercial_partner/i18n/fi.po
  sale_commercial_partner/i18n/fr.po
  sale_commercial_partner/i18n/fr_FR.po
  sale_commercial_partner/i18n/hr.po
  sale_commercial_partner/i18n/hu.po
  sale_commercial_partner/i18n/it.po
  sale_commercial_partner/i18n/nl.po
  sale_commercial_partner/i18n/pt_BR.po
  sale_commercial_partner/i18n/ro.po
  sale_commercial_partner/i18n/sale_commercial_partner.pot
  sale_commercial_partner/i18n/sl_SI.po
  sale_commercial_partner/i18n/tr.po
  sale_commercial_partner/i18n/vi_VN.po
  sale_commercial_partner/i18n/zh_CN.po
  sale_commercial_partner/models/__init__.py
  sale_commercial_partner/models/sale_order.py
  sale_commercial_partner/pyproject.toml
  sale_commercial_partner/readme/CONTRIBUTORS.md
  sale_commercial_partner/readme/CREDITS.md
  sale_commercial_partner/readme/DESCRIPTION.md
  sale_commercial_partner/readme/USAGE.md
  sale_commercial_partner/static/description/icon.png
  sale_commercial_partner/static/description/index.html
  sale_commercial_partner/tests/__init__.py
  sale_commercial_partner/tests/test_sale_commercial_partner.py
  sale_commercial_partner/views/sale_order.xml
  sale_commercial_partner/views/sale_report.xml
Labels: approved, bot is merging ⏳

#3385 [17.0][MIG] sale_order_secondary_unit: Migration to 17.0
  sale_order_secondary_unit/README.rst
  sale_order_secondary_unit/__init__.py
  sale_order_secondary_unit/__manifest__.py
  sale_order_secondary_unit/i18n/de.po
  sale_order_secondary_unit/i18n/es.po
  sale_order_secondary_unit/i18n/fi.po
  sale_order_secondary_unit/i18n/sale_order_secondary_unit.pot
  sale_order_secondary_unit/i18n/zh_CN.po
  sale_order_secondary_unit/migrations/15.0.2.0.0/post-migration.py
  sale_order_secondary_unit/models/__init__.py
  sale_order_secondary_unit/models/product.py
  sale_order_secondary_unit/models/product_template.py
  sale_order_secondary_unit/models/sale_order.py
  sale_order_secondary_unit/pyproject.toml
  sale_order_secondary_unit/readme/CONFIGURE.md
  sale_order_secondary_unit/readme/CONTRIBUTORS.md
  sale_order_secondary_unit/readme/DESCRIPTION.md
  sale_order_secondary_unit/readme/USAGE.md
  sale_order_secondary_unit/report/sale_report_templates.xml
  sale_order_secondary_unit/static/description/icon.png
  sale_order_secondary_unit/static/description/index.html
  sale_order_secondary_unit/tests/__init__.py
  sale_order_secondary_unit/tests/test_product_template.py
  sale_order_secondary_unit/tests/test_sale_order.py
  sale_order_secondary_unit/views/product_secondary_unit_views.xml
  sale_order_secondary_unit/views/product_views.xml
  sale_order_secondary_unit/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#3503 [FIX] sale_exception: Don't order by main exception
  sale_exception/models/sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3420 [18.0][MIG] sale_procurement_group_by_line: Migration to 18.0.
  sale_procurement_group_by_line/README.rst
  sale_procurement_group_by_line/__init__.py
  sale_procurement_group_by_line/__manifest__.py
  sale_procurement_group_by_line/i18n/ca.po
  sale_procurement_group_by_line/i18n/de.po
  sale_procurement_group_by_line/i18n/el_GR.po
  sale_procurement_group_by_line/i18n/es.po
  sale_procurement_group_by_line/i18n/es_ES.po
  sale_procurement_group_by_line/i18n/es_VE.po
  sale_procurement_group_by_line/i18n/fi.po
  sale_procurement_group_by_line/i18n/fr.po
  sale_procurement_group_by_line/i18n/hr.po
  sale_procurement_group_by_line/i18n/hr_HR.po
  sale_procurement_group_by_line/i18n/hu.po
  sale_procurement_group_by_line/i18n/it.po
  sale_procurement_group_by_line/i18n/nl.po
  sale_procurement_group_by_line/i18n/nl_NL.po
  sale_procurement_group_by_line/i18n/pt.po
  sale_procurement_group_by_line/i18n/pt_BR.po
  sale_procurement_group_by_line/i18n/ro.po
  sale_procurement_group_by_line/i18n/sale_procurement_group_by_line.pot
  sale_procurement_group_by_line/i18n/sk.po
  sale_procurement_group_by_line/i18n/sl.po
  sale_procurement_group_by_line/i18n/tr.po
  sale_procurement_group_by_line/i18n/tr_TR.po
  sale_procurement_group_by_line/i18n/vi_VN.po
  sale_procurement_group_by_line/i18n/zh_CN.po
  sale_procurement_group_by_line/model/__init__.py
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/model/stock_move.py
  sale_procurement_group_by_line/pyproject.toml
  sale_procurement_group_by_line/readme/CONTRIBUTORS.md
  sale_procurement_group_by_line/readme/DESCRIPTION.md
  sale_procurement_group_by_line/static/description/icon.png
  sale_procurement_group_by_line/static/description/index.html
  sale_procurement_group_by_line/tests/__init__.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#3427 [16.0][FIX] sale_procurement_group_by_line: update to odoo
  sale_procurement_group_by_line/model/sale.py
  sale_procurement_group_by_line/tests/test_sale_procurement_group_by_line.py
Labels: approved, ready to merge, bot is merging ⏳

#3535 [17.0][FIX]sale_quotation_number: get_quotation_seq method
  sale_quotation_number/models/sale_order.py
Labels: approved, bot is merging ⏳

#3534 [17.0][IMP]sale_quotation_number: Boolean to determine whether quotation sequence has been used
  sale_quotation_number/migrations/17.0.1.1.1/post-migration.py
  sale_quotation_number/models/sale_order.py
Labels: approved, bot is merging ⏳

#3447 [18.0][MIG] sale_automatic_workflow_stock: Migration to 18.0
  sale_automatic_workflow_stock/README.rst
  sale_automatic_workflow_stock/__init__.py
  sale_automatic_workflow_stock/__manifest__.py
  sale_automatic_workflow_stock/data/automatic_workflow_data.xml
  sale_automatic_workflow_stock/i18n/it.po
  sale_automatic_workflow_stock/i18n/sale_automatic_workflow_stock.pot
  sale_automatic_workflow_stock/models/__init__.py
  sale_automatic_workflow_stock/models/automatic_workflow_job.py
  sale_automatic_workflow_stock/models/sale_order.py
  sale_automatic_workflow_stock/models/sale_workflow_process.py
  sale_automatic_workflow_stock/models/stock_move.py
  sale_automatic_workflow_stock/models/stock_picking.py
  sale_automatic_workflow_stock/pyproject.toml
  sale_automatic_workflow_stock/readme/CONTRIBUTORS.md
  sale_automatic_workflow_stock/readme/CREDITS.md
  sale_automatic_workflow_stock/readme/DESCRIPTION.md
  sale_automatic_workflow_stock/static/description/icon.png
  sale_automatic_workflow_stock/static/description/index.html
  sale_automatic_workflow_stock/tests/__init__.py
  sale_automatic_workflow_stock/tests/common.py
  sale_automatic_workflow_stock/tests/test_automatic_workflow.py
  sale_automatic_workflow_stock/tests/test_multicompany.py
  sale_automatic_workflow_stock/views/sale_order_views.xml
  sale_automatic_workflow_stock/views/sale_workflow_process_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3543 [17.0][MIG] sale_order_line_price_history: Migration to 17.0
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__init__.py
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/i18n/de.po
  sale_order_line_price_history/i18n/es.po
  sale_order_line_price_history/i18n/it.po
  sale_order_line_price_history/i18n/pt.po
  sale_order_line_price_history/i18n/pt_BR.po
  sale_order_line_price_history/i18n/sale_order_line_price_history.pot
  sale_order_line_price_history/i18n/zh_CN.po
  sale_order_line_price_history/models/__init__.py
  sale_order_line_price_history/models/sale_order_line.py
  sale_order_line_price_history/pyproject.toml
  sale_order_line_price_history/readme/CONTRIBUTORS.md
  sale_order_line_price_history/readme/DESCRIPTION.md
  sale_order_line_price_history/readme/ROADMAP.md
  sale_order_line_price_history/readme/USAGE.md
  sale_order_line_price_history/security/ir.model.access.csv
  sale_order_line_price_history/static/description/icon.png
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/static/src/js/sale_line_price_history_widget.esm.js
  sale_order_line_price_history/static/src/js/set_price_to_line_widget.esm.js
  sale_order_line_price_history/static/src/xml/sale_line_price_history_widget.xml
  sale_order_line_price_history/static/src/xml/set_price_to_line_widget.xml
  sale_order_line_price_history/tests/__init__.py
  sale_order_line_price_history/tests/test_sale_order_line_price_history.py
  sale_order_line_price_history/views/sale_views.xml
  sale_order_line_price_history/wizards/__init__.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.py
  sale_order_line_price_history/wizards/sale_order_line_price_history.xml
Labels: approved, bot is merging ⏳

#3548 [17.0][FIX] sale_order_line_price_history: Add button to kanban view
  sale_order_line_price_history/README.rst
  sale_order_line_price_history/__manifest__.py
  sale_order_line_price_history/static/description/index.html
  sale_order_line_price_history/views/sale_views.xml
Labels: approved, bot is merging ⏳

#3430 [17.0] [MIG] sales_team_security_sale: Migration to 17.0
  sales_team_security_sale/README.rst
  sales_team_security_sale/__init__.py
  sales_team_security_sale/__manifest__.py
  sales_team_security_sale/i18n/sales_team_security_sale.pot
  sales_team_security_sale/pyproject.toml
  sales_team_security_sale/readme/CONFIGURE.md
  sales_team_security_sale/readme/CONTRIBUTORS.md
  sales_team_security_sale/readme/DESCRIPTION.md
  sales_team_security_sale/security/security.xml
  sales_team_security_sale/static/description/icon.png
  sales_team_security_sale/static/description/index.html
  sales_team_security_sale/tests/__init__.py
  sales_team_security_sale/tests/test_sales_team_security_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#3429 [17.0][MIG] sales_team_security_crm: Migration to 17.0
  sales_team_security_crm/README.rst
  sales_team_security_crm/__init__.py
  sales_team_security_crm/__manifest__.py
  sales_team_security_crm/i18n/sales_team_security_crm.pot
  sales_team_security_crm/pyproject.toml
  sales_team_security_crm/readme/CONTRIBUTORS.md
  sales_team_security_crm/readme/DESCRIPTION.md
  sales_team_security_crm/security/security.xml
  sales_team_security_crm/static/description/icon.png
  sales_team_security_crm/static/description/index.html
  sales_team_security_crm/tests/__init__.py
  sales_team_security_crm/tests/test_sales_team_security_crm.py
Labels: bot is merging ⏳

#3470 [18.0] [MIG] sale_order_line_menu: Migration to 18.0
  sale_order_line_menu/README.rst
  sale_order_line_menu/__init__.py
  sale_order_line_menu/__manifest__.py
  sale_order_line_menu/i18n/de.po
  sale_order_line_menu/i18n/es.po
  sale_order_line_menu/i18n/fr.po
  sale_order_line_menu/i18n/fr_BE.po
  sale_order_line_menu/i18n/fr_FR.po
  sale_order_line_menu/i18n/hr.po
  sale_order_line_menu/i18n/it.po
  sale_order_line_menu/i18n/pt_BR.po
  sale_order_line_menu/i18n/sale_order_line_menu.pot
  sale_order_line_menu/models/__init__.py
  sale_order_line_menu/models/sale_order_line.py
  sale_order_line_menu/pyproject.toml
  sale_order_line_menu/readme/CONTRIBUTORS.md
  sale_order_line_menu/readme/DESCRIPTION.md
  sale_order_line_menu/readme/USAGE.md
  sale_order_line_menu/static/description/icon.png
  sale_order_line_menu/static/description/index.html
  sale_order_line_menu/views/sale_order_line_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3496 [18.0][MIG] sale_sourced_by_line: Migration to 18.0
  sale_sourced_by_line/README.rst
  sale_sourced_by_line/__init__.py
  sale_sourced_by_line/__manifest__.py
  sale_sourced_by_line/i18n/ca.po
  sale_sourced_by_line/i18n/de.po
  sale_sourced_by_line/i18n/el_GR.po
  sale_sourced_by_line/i18n/es.po
  sale_sourced_by_line/i18n/es_ES.po
  sale_sourced_by_line/i18n/es_VE.po
  sale_sourced_by_line/i18n/fi.po
  sale_sourced_by_line/i18n/fr.po
  sale_sourced_by_line/i18n/hr.po
  sale_sourced_by_line/i18n/hr_HR.po
  sale_sourced_by_line/i18n/hu.po
  sale_sourced_by_line/i18n/it.po
  sale_sourced_by_line/i18n/nl.po
  sale_sourced_by_line/i18n/nl_NL.po
  sale_sourced_by_line/i18n/pt.po
  sale_sourced_by_line/i18n/pt_BR.po
  sale_sourced_by_line/i18n/ro.po
  sale_sourced_by_line/i18n/sale_sourced_by_line.pot
  sale_sourced_by_line/i18n/sk.po
  sale_sourced_by_line/i18n/sl.po
  sale_sourced_by_line/i18n/tr.po
  sale_sourced_by_line/i18n/tr_TR.po
  sale_sourced_by_line/i18n/vi_VN.po
  sale_sourced_by_line/i18n/zh_CN.po
  sale_sourced_by_line/model/__init__.py
  sale_sourced_by_line/model/sale.py
  sale_sourced_by_line/pyproject.toml
  sale_sourced_by_line/static/description/icon.png
  sale_sourced_by_line/tests/__init__.py
  sale_sourced_by_line/tests/test_sale_sourced_by_line.py
  sale_sourced_by_line/view/sale_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2357 [16.0][ADD] - sale_order_line_cancel
  sale_order_line_cancel/README.rst
  sale_order_line_cancel/__init__.py
  sale_order_line_cancel/__manifest__.py
  sale_order_line_cancel/models/__init__.py
  sale_order_line_cancel/models/sale_order.py
  sale_order_line_cancel/models/sale_order_line.py
  sale_order_line_cancel/models/stock_move.py
  sale_order_line_cancel/readme/CONTRIBUTORS.rst
  sale_order_line_cancel/readme/DESCRIPTION.rst
  sale_order_line_cancel/security/sale_order_line_cancel.xml
  sale_order_line_cancel/static/description/index.html
  sale_order_line_cancel/tests/__init__.py
  sale_order_line_cancel/tests/common.py
  sale_order_line_cancel/tests/test_sale_order_line_cancel.py
  sale_order_line_cancel/views/sale_order.xml
  sale_order_line_cancel/views/sale_order_line.xml
  sale_order_line_cancel/wizards/__init__.py
  sale_order_line_cancel/wizards/sale_order_line_cancel.py
  sale_order_line_cancel/wizards/sale_order_line_cancel.xml
  setup/sale_order_line_cancel/odoo/addons/sale_order_line_cancel
  setup/sale_order_line_cancel/setup.py
Labels: needs review, approved, bot is merging ⏳

#2416 [FIX] sale_blanket_order: do not use supplier_taxes_id
  sale_blanket_order/models/blanket_orders.py
Labels: enhancement, bot is merging ⏳

#2335 [15.0][mig]-sale_validity_auto_cancel
  sale_validity_auto_cancel/README.rst
  sale_validity_auto_cancel/__init__.py
  sale_validity_auto_cancel/__manifest__.py
  sale_validity_auto_cancel/data/ir_cron.xml
  sale_validity_auto_cancel/models/__init__.py
  sale_validity_auto_cancel/models/res_company.py
  sale_validity_auto_cancel/models/res_config_settings.py
  sale_validity_auto_cancel/models/sale_order.py
  sale_validity_auto_cancel/readme/CONFIGURE.rst
  sale_validity_auto_cancel/readme/CONTRIBUTORS.rst
  sale_validity_auto_cancel/readme/DESCRIPTION.rst
  sale_validity_auto_cancel/readme/USAGE.rst
  sale_validity_auto_cancel/static/description/icon.png
  sale_validity_auto_cancel/static/description/index.html
  sale_validity_auto_cancel/tests/__init__.py
  sale_validity_auto_cancel/tests/test_sale_validity_auto_cancel.py
  sale_validity_auto_cancel/views/res_config_settings.xml
  setup/sale_validity_auto_cancel/odoo/addons/sale_validity_auto_cancel
  setup/sale_validity_auto_cancel/setup.py
Labels: needs review, migration, bot is merging ⏳
