Repository OCA/sale-workflow, pull requests merged in 2025-08, with the labels that each got.

#3689 [17.0][IMP] sale_automatic_workflow: add option for default payment journal
  sale_automatic_workflow/README.rst
  sale_automatic_workflow/models/automatic_workflow_job.py
  sale_automatic_workflow/models/sale_workflow_process.py
  sale_automatic_workflow/readme/CONTRIBUTORS.md
  sale_automatic_workflow/static/description/index.html
  sale_automatic_workflow/tests/test_automatic_workflow.py
  sale_automatic_workflow/views/sale_workflow_process_views.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3809 [16.0][IMP] sale_elaboration: set products profile from its categories
  sale_elaboration/README.rst
  sale_elaboration/__manifest__.py
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_category.py
  sale_elaboration/models/product_template.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/readme/CONFIGURE.rst
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_category_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#3851 [16.0][IMP] sale_order_safe_commitment_date: delivery date helper
  sale_order_safe_commitment_date/models/sale_order.py
  sale_order_safe_commitment_date/views/sale_order_views.xml
Labels: needs review, approved, bot is merging ⏳

#3860 [18.0][MIG] portal_sale_order_search: Migration to version 18.0
  portal_sale_order_search/README.rst
  portal_sale_order_search/__init__.py
  portal_sale_order_search/__manifest__.py
  portal_sale_order_search/controllers/__init__.py
  portal_sale_order_search/controllers/main.py
  portal_sale_order_search/i18n/es.po
  portal_sale_order_search/i18n/portal_sale_order_search.pot
  portal_sale_order_search/pyproject.toml
  portal_sale_order_search/readme/CONTRIBUTORS.md
  portal_sale_order_search/readme/DESCRIPTION.md
  portal_sale_order_search/static/description/icon.png
  portal_sale_order_search/static/description/index.html
Labels: approved, bot is merging ⏳

#3857 [18.0][IMP] sale_elaboration: elaboration profile from product category
  sale_elaboration/README.rst
  sale_elaboration/__manifest__.py
  sale_elaboration/models/__init__.py
  sale_elaboration/models/product.py
  sale_elaboration/models/product_category.py
  sale_elaboration/models/product_template.py
  sale_elaboration/models/sale_order.py
  sale_elaboration/readme/CONFIGURE.md
  sale_elaboration/static/description/index.html
  sale_elaboration/tests/test_sale_elaboration.py
  sale_elaboration/views/product_category_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3856 [16.0][IMP] sale_order_line_sequence: Reduce column size through label + optional
  sale_order_line_sequence/views/sale_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3801 [16.0][IMP] sale_order_line_cancel: On sale.order action_cancel do not decrease sale.order.line's product_uom_qty
  sale_order_line_cancel/models/sale_order.py
  sale_order_line_cancel/models/stock_move.py
  sale_order_line_cancel/tests/test_sale_order_line_cancel.py
Labels: approved, ready to merge, bot is merging ⏳

#3822 [17.0] [MIG] sale_attached_product: Migration to 17.0
  sale_attached_product/README.rst
  sale_attached_product/__init__.py
  sale_attached_product/__manifest__.py
  sale_attached_product/i18n/es.po
  sale_attached_product/i18n/it.po
  sale_attached_product/i18n/sale_attached_product.pot
  sale_attached_product/models/__init__.py
  sale_attached_product/models/product_template.py
  sale_attached_product/models/sale_attached_product_mixin.py
  sale_attached_product/models/sale_order.py
  sale_attached_product/pyproject.toml
  sale_attached_product/readme/CONFIGURE.md
  sale_attached_product/readme/CONTRIBUTORS.md
  sale_attached_product/readme/DESCRIPTION.md
  sale_attached_product/readme/USAGE.md
  sale_attached_product/static/description/icon.png
  sale_attached_product/static/description/index.html
  sale_attached_product/tests/__init__.py
  sale_attached_product/tests/test_sale_attached_product.py
  sale_attached_product/views/product_template_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#3868 [FIX] sell_only_by_packaging crash
  sell_only_by_packaging/models/product_template.py
Labels: approved, bot is merging ⏳

#3803 [18.0][MIG] product_supplierinfo_for_customer_elaboration: Migration to version 18.0, renamed to product_customerinfo_elaboration
  product_customerinfo_elaboration/README.rst
  product_customerinfo_elaboration/__init__.py
  product_customerinfo_elaboration/__manifest__.py
  product_customerinfo_elaboration/i18n/es.po
  product_customerinfo_elaboration/i18n/product_supplierinfo_for_customer_elaboration.pot
  product_customerinfo_elaboration/models/__init__.py
  product_customerinfo_elaboration/models/product_customerinfo.py
  product_customerinfo_elaboration/models/sale_order_line.py
  product_customerinfo_elaboration/pyproject.toml
  product_customerinfo_elaboration/readme/CONFIGURE.md
  product_customerinfo_elaboration/readme/CONTRIBUTORS.md
  product_customerinfo_elaboration/readme/DESCRIPTION.md
  product_customerinfo_elaboration/readme/USAGE.md
  product_customerinfo_elaboration/security/ir.model.access.csv
  product_customerinfo_elaboration/static/description/icon.png
  product_customerinfo_elaboration/static/description/index.html
  product_customerinfo_elaboration/tests/__init__.py
  product_customerinfo_elaboration/tests/test_customerinfo_elaboration.py
  product_customerinfo_elaboration/views/product_views.xml
Labels: approved, bot is merging ⏳

#3288 [17.0][FIX] sale_blanket_order: filter default taxes by company for all users
  sale_blanket_order/models/blanket_orders.py
  sale_blanket_order/tests/test_blanket_orders.py
  sale_blanket_order/views/sale_blanket_order_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3841 [17.0][MIG] sale_order_partner_no_autofollow: Migration to 17.0
  sale_order_partner_no_autofollow/README.rst
  sale_order_partner_no_autofollow/__init__.py
  sale_order_partner_no_autofollow/__manifest__.py
  sale_order_partner_no_autofollow/i18n/it.po
  sale_order_partner_no_autofollow/i18n/sale_order_partner_no_autofollow.pot
  sale_order_partner_no_autofollow/models/__init__.py
  sale_order_partner_no_autofollow/models/res_config_settings.py
  sale_order_partner_no_autofollow/models/sale_order.py
  sale_order_partner_no_autofollow/pyproject.toml
  sale_order_partner_no_autofollow/readme/CONFIGURE.md
  sale_order_partner_no_autofollow/readme/DESCRIPTION.md
  sale_order_partner_no_autofollow/static/description/icon.png
  sale_order_partner_no_autofollow/static/description/index.html
  sale_order_partner_no_autofollow/tests/__init__.py
  sale_order_partner_no_autofollow/tests/common.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_disabled.py
  sale_order_partner_no_autofollow/tests/test_no_autofollow_enabled.py
  sale_order_partner_no_autofollow/views/res_config_settings.xml
Labels: approved, migration, ready to merge, bot is merging ⏳
