Repository OCA/sale-workflow, pull requests merged in 2025-06, with the labels that each got.

#3597 [14.0][IMP][sale_order_lot_selection] add lot_id index True
  sale_order_lot_selection/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#3675 [16.0][FIX]sale_quotation_number: get_quotation_seq method
  sale_quotation_number/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#3722 [16.0][ADD] sale_order_safe_commitment_date: New module
  sale_order_safe_commitment_date/README.rst
  sale_order_safe_commitment_date/__init__.py
  sale_order_safe_commitment_date/__manifest__.py
  sale_order_safe_commitment_date/i18n/es.po
  sale_order_safe_commitment_date/i18n/sale_order_safe_commitment_date.pot
  sale_order_safe_commitment_date/models/__init__.py
  sale_order_safe_commitment_date/models/sale_order.py
  sale_order_safe_commitment_date/readme/CONFIGURE.md
  sale_order_safe_commitment_date/readme/CONTEXT.md
  sale_order_safe_commitment_date/readme/CONTRIBUTORS.md
  sale_order_safe_commitment_date/readme/DESCRIPTION.md
  sale_order_safe_commitment_date/readme/ROADMAP.md
  sale_order_safe_commitment_date/readme/USAGE.md
  sale_order_safe_commitment_date/static/description/index.html
  sale_order_safe_commitment_date/tests/__init__.py
  sale_order_safe_commitment_date/tests/test_sale_order_safe_commitment_date.py
  sale_order_safe_commitment_date/views/sale_order_views.xml
  setup/sale_order_safe_commitment_date/odoo/addons/sale_order_safe_commitment_date
  setup/sale_order_safe_commitment_date/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3579 [16.0] [ADD] sale_invoice_split_payment: Add module
  sale_invoice_split_payment/README.rst
  sale_invoice_split_payment/__init__.py
  sale_invoice_split_payment/__manifest__.py
  sale_invoice_split_payment/models/__init__.py
  sale_invoice_split_payment/models/sale_order.py
  sale_invoice_split_payment/readme/CONTRIBUTORS.md
  sale_invoice_split_payment/readme/DESCRIPTION.md
  sale_invoice_split_payment/readme/USAGE.md
  sale_invoice_split_payment/static/description/icon.png
  sale_invoice_split_payment/static/description/index.html
  sale_invoice_split_payment/tests/__init__.py
  sale_invoice_split_payment/tests/test_sale_order.py
  setup/sale_invoice_split_payment/odoo/addons/sale_invoice_split_payment
  setup/sale_invoice_split_payment/setup.py
Labels: needs review, approved, bot is merging ⏳

#3357 [16.0][ADD]sale_order_line_multi_warehouse: Split sale order in multiple pickings
  sale_order_line_multi_warehouse/README.rst
  sale_order_line_multi_warehouse/__init__.py
  sale_order_line_multi_warehouse/__manifest__.py
  sale_order_line_multi_warehouse/models/__init__.py
  sale_order_line_multi_warehouse/models/res_company.py
  sale_order_line_multi_warehouse/models/res_config_settings.py
  sale_order_line_multi_warehouse/models/sale_order.py
  sale_order_line_multi_warehouse/models/sale_order_line.py
  sale_order_line_multi_warehouse/models/sale_order_line_warehouse.py
  sale_order_line_multi_warehouse/models/stock_move.py
  sale_order_line_multi_warehouse/models/stock_rule.py
  sale_order_line_multi_warehouse/models/stock_warehouse.py
  sale_order_line_multi_warehouse/readme/CONFIGURE.rst
  sale_order_line_multi_warehouse/readme/CONTRIBUTORS.rst
  sale_order_line_multi_warehouse/readme/DESCRIPTION.rst
  sale_order_line_multi_warehouse/readme/ROADMAP.rst
  sale_order_line_multi_warehouse/readme/USAGE.rst
  sale_order_line_multi_warehouse/security/ir.model.access.csv
  sale_order_line_multi_warehouse/static/description/icon.png
  sale_order_line_multi_warehouse/static/description/index.html
  sale_order_line_multi_warehouse/tests/__init__.py
  sale_order_line_multi_warehouse/tests/test_so_line_multiwarehouse.py
  sale_order_line_multi_warehouse/views/res_config_settings_views.xml
  sale_order_line_multi_warehouse/views/sale_order_line_warehouse_views.xml
  sale_order_line_multi_warehouse/views/sale_order_views.xml
  sale_order_line_multi_warehouse/views/stock_warehouse_views.xml
  sale_order_line_multi_warehouse/wizard/__init__.py
  sale_order_line_multi_warehouse/wizard/so_multi_warehouse_change_line_wizard.py
  sale_order_line_multi_warehouse/wizard/so_multi_warehouse_change_wizard.py
  sale_order_line_multi_warehouse/wizard/so_multi_warehouse_change_wizard_views.xml
  setup/sale_order_line_multi_warehouse/odoo/addons/sale_order_line_multi_warehouse
  setup/sale_order_line_multi_warehouse/setup.py
Labels: needs review, approved, bot is merging ⏳

#3331 [17.0] [MIG] sale_invoice_frequency: Migration to 17.0
  sale_invoice_frequency/README.rst
  sale_invoice_frequency/__init__.py
  sale_invoice_frequency/__manifest__.py
  sale_invoice_frequency/data/sale_invoice_frequency_data.xml
  sale_invoice_frequency/i18n/de.po
  sale_invoice_frequency/i18n/es.po
  sale_invoice_frequency/i18n/it.po
  sale_invoice_frequency/i18n/sale_invoice_frequency.pot
  sale_invoice_frequency/models/__init__.py
  sale_invoice_frequency/models/res_partner.py
  sale_invoice_frequency/models/sale_invoice_frequency.py
  sale_invoice_frequency/models/sale_order.py
  sale_invoice_frequency/pyproject.toml
  sale_invoice_frequency/readme/CONTRIBUTORS.md
  sale_invoice_frequency/readme/DESCRIPTION.md
  sale_invoice_frequency/readme/ROADMAP.md
  sale_invoice_frequency/readme/USAGE.md
  sale_invoice_frequency/security/ir.model.access.csv
  sale_invoice_frequency/static/description/icon.png
  sale_invoice_frequency/static/description/index.html
  sale_invoice_frequency/tests/__init__.py
  sale_invoice_frequency/tests/test_sale_invoice_frequency.py
  sale_invoice_frequency/views/res_partner_view.xml
  sale_invoice_frequency/views/sale_invoice_frequency_view.xml
  sale_invoice_frequency/views/sale_order_view.xml
Labels: needs review, migration, bot is merging ⏳

#3595 [16.0][FIX] sale_payment_sheet + sale_order_type + sale_force_invoiced + sale_order_invoicing_finished_task + sale_order_line_sequence: Post-install test + fallback to load CoA
  sale_order_invoicing_finished_task/tests/test_sale_order_invoicing_finished_task.py
  sale_order_line_sequence/tests/test_sale_order_line_sequence.py
  sale_order_type/tests/test_sale_order_type.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
Labels: bot is merging ⏳

#3765 [18.0][FIX] sale_order_lot_selection/sale_order_product_availability_inline: Don't use demo data for tests / fix display
  sale_order_lot_selection/tests/test_sale_order_lot_selection.py
  sale_order_product_availability_inline/models/__init__.py
  sale_order_product_availability_inline/models/product_template.py
  sale_order_product_availability_inline/models/sale.py
  sale_order_product_availability_inline/views/sale_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#3774 [17.0][IMP] sale_order_secondary_unit: context for skipping default sec. unit
  sale_order_secondary_unit/models/sale_order.py
Labels: bot is merging ⏳

#3743 [18.0][FIX] sale_exception: update rule due to product type change
  sale_exception/data/sale_exception_data.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3592 [16.0][ADD]sale_order_warehouse_location: Set warehouse in sale order based on delivery country and state
  sale_order_warehouse_location/README.rst
  sale_order_warehouse_location/__init__.py
  sale_order_warehouse_location/__manifest__.py
  sale_order_warehouse_location/models/__init__.py
  sale_order_warehouse_location/models/sale_order.py
  sale_order_warehouse_location/models/stock_warehouse.py
  sale_order_warehouse_location/readme/CONFIGURE.md
  sale_order_warehouse_location/readme/CONTRIBUTORS.md
  sale_order_warehouse_location/readme/DESCRIPTION.md
  sale_order_warehouse_location/readme/USAGE.md
  sale_order_warehouse_location/static/description/icon.png
  sale_order_warehouse_location/static/description/index.html
  sale_order_warehouse_location/tests/__init__.py
  sale_order_warehouse_location/tests/test_sale_order_warehouse_location.py
  sale_order_warehouse_location/views/stock_warehouse_views.xml
  setup/sale_order_warehouse_location/odoo/addons/sale_order_warehouse_location
  setup/sale_order_warehouse_location/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3776 [16.0][FIX] sale_advance_payment: Amount residual with signed invoice amount
  sale_advance_payment/models/sale.py
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: approved, bot is merging ⏳

#3696 [18.0] [MIG] portal_sale_personal_data_only: Migration to 18.0
  portal_sale_personal_data_only/README.rst
  portal_sale_personal_data_only/__init__.py
  portal_sale_personal_data_only/__manifest__.py
  portal_sale_personal_data_only/hooks.py
  portal_sale_personal_data_only/i18n/de.po
  portal_sale_personal_data_only/i18n/es.po
  portal_sale_personal_data_only/i18n/it.po
  portal_sale_personal_data_only/i18n/portal_sale_personal_data_only.pot
  portal_sale_personal_data_only/i18n/zh_CN.po
  portal_sale_personal_data_only/pyproject.toml
  portal_sale_personal_data_only/readme/CONTRIBUTORS.md
  portal_sale_personal_data_only/readme/DESCRIPTION.md
  portal_sale_personal_data_only/readme/USAGE.md
  portal_sale_personal_data_only/security/security.xml
  portal_sale_personal_data_only/static/description/icon.png
  portal_sale_personal_data_only/static/description/index.html
  portal_sale_personal_data_only/tests/__init__.py
  portal_sale_personal_data_only/tests/test_partner_access.py
Labels: approved, bot is merging ⏳

#3278 [17.0][MIG] sale_payment_sheet: Migration to 17.0
  sale_payment_sheet/README.rst
  sale_payment_sheet/__init__.py
  sale_payment_sheet/__manifest__.py
  sale_payment_sheet/i18n/es.po
  sale_payment_sheet/i18n/it.po
  sale_payment_sheet/i18n/sale_payment_sheet.pot
  sale_payment_sheet/models/__init__.py
  sale_payment_sheet/models/res_users.py
  sale_payment_sheet/models/sale_payment_sheet.py
  sale_payment_sheet/pyproject.toml
  sale_payment_sheet/readme/CONFIGURE.md
  sale_payment_sheet/readme/CONTRIBUTORS.md
  sale_payment_sheet/readme/DESCRIPTION.md
  sale_payment_sheet/readme/USAGE.md
  sale_payment_sheet/report/report_sale_payment_sheet_summary.xml
  sale_payment_sheet/report/sale_payment_sheet_report.xml
  sale_payment_sheet/security/ir.model.access.csv
  sale_payment_sheet/security/security.xml
  sale_payment_sheet/static/description/icon.png
  sale_payment_sheet/static/description/index.html
  sale_payment_sheet/tests/__init__.py
  sale_payment_sheet/tests/test_sale_payment_sheet.py
  sale_payment_sheet/views/res_users_views.xml
  sale_payment_sheet/views/sale_payment_sheet_menu.xml
  sale_payment_sheet/views/sale_payment_sheet_views.xml
  sale_payment_sheet/wizards/__init__.py
  sale_payment_sheet/wizards/sale_invoice_payment.py
  sale_payment_sheet/wizards/sale_invoice_payment_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3746 [18.0][IMP] sale_invoice_policy: automatic invoice
  requirements.txt
  sale_invoice_policy/__manifest__.py
  sale_invoice_policy/models/sale_order.py
  sale_invoice_policy/readme/CONTRIBUTORS.md
  sale_invoice_policy/tests/test_sale_invoice_policy.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#3777 [17.0] [FIX] sale_advance_payment: Amount residual with signed invoice amount
  sale_advance_payment/tests/test_sale_advance_payment.py
Labels: enhancement, approved, bot is merging ⏳

#3739 [18.0][MIG] sale_transaction_form_link: Migration to 18.0
  sale_transaction_form_link/README.rst
  sale_transaction_form_link/__init__.py
  sale_transaction_form_link/__manifest__.py
  sale_transaction_form_link/demo/payment_transaction.xml
  sale_transaction_form_link/i18n/es.po
  sale_transaction_form_link/i18n/it.po
  sale_transaction_form_link/i18n/sale_transaction_form_link.pot
  sale_transaction_form_link/models/__init__.py
  sale_transaction_form_link/models/sale_order.py
  sale_transaction_form_link/pyproject.toml
  sale_transaction_form_link/readme/CONTRIBUTORS.md
  sale_transaction_form_link/readme/DESCRIPTION.md
  sale_transaction_form_link/readme/USAGE.md
  sale_transaction_form_link/static/description/icon.png
  sale_transaction_form_link/static/description/index.html
  sale_transaction_form_link/tests/__init__.py
  sale_transaction_form_link/tests/test_sale_order.py
  sale_transaction_form_link/views/sale_order.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
