Repository OCA/sale-workflow, pull requests merged in 2025-07, with the labels that each got.

#3782 [17.0][FIX] sale_order_secondary_unit: fix tests when run alongside sale_stock
  sale_order_secondary_unit/tests/test_sale_order.py
Labels: approved, bot is merging ⏳

#3619 [16.0][IMP] sale_tier_validation: Hide Confirm button if the validation is pending or rejected
  sale_tier_validation/README.rst
  sale_tier_validation/readme/ROADMAP.md
  sale_tier_validation/static/description/index.html
  sale_tier_validation/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3784 [16.0][IMP] sale_order_safe_commitment_date: unsafe delivery date as expected
  sale_order_safe_commitment_date/README.rst
  sale_order_safe_commitment_date/models/sale_order.py
  sale_order_safe_commitment_date/readme/USAGE.md
  sale_order_safe_commitment_date/static/description/index.html
  sale_order_safe_commitment_date/tests/test_sale_order_safe_commitment_date.py
Labels: approved, bot is merging ⏳

#3787 17.0 mig sale invoice plan
  sale_invoice_plan/README.rst
  sale_invoice_plan/__init__.py
  sale_invoice_plan/__manifest__.py
  sale_invoice_plan/data/sale_data.xml
  sale_invoice_plan/i18n/es.po
  sale_invoice_plan/i18n/fr.po
  sale_invoice_plan/i18n/it.po
  sale_invoice_plan/i18n/nl_NL.po
  sale_invoice_plan/i18n/sale_invoice_plan.pot
  sale_invoice_plan/i18n/zh_CN.po
  sale_invoice_plan/models/__init__.py
  sale_invoice_plan/models/sale.py
  sale_invoice_plan/models/sale_invoice_plan.py
  sale_invoice_plan/pyproject.toml
  sale_invoice_plan/readme/CONTRIBUTORS.md
  sale_invoice_plan/readme/CREDITS.md
  sale_invoice_plan/readme/DESCRIPTION.md
  sale_invoice_plan/readme/HISTORY.md
  sale_invoice_plan/readme/INSTALL.md
  sale_invoice_plan/readme/USAGE.md
  sale_invoice_plan/security/ir.model.access.csv
  sale_invoice_plan/static/description/icon.png
  sale_invoice_plan/static/description/index.html
  sale_invoice_plan/tests/__init__.py
  sale_invoice_plan/tests/test_sale_invoice_plan.py
  sale_invoice_plan/views/sale_view.xml
  sale_invoice_plan/wizard/__init__.py
  sale_invoice_plan/wizard/sale_create_invoice_plan.py
  sale_invoice_plan/wizard/sale_create_invoice_plan_view.xml
  sale_invoice_plan/wizard/sale_make_invoice_advance.py
  sale_invoice_plan/wizard/sale_make_planned_invoice.py
  sale_invoice_plan/wizard/sale_make_planned_invoice_view.xml
Labels: bot is merging ⏳

#3485 [18.0][MIG] partner_sale_pivot: Migration to 18.0
  partner_sale_pivot/README.rst
  partner_sale_pivot/__init__.py
  partner_sale_pivot/__manifest__.py
  partner_sale_pivot/i18n/ca.po
  partner_sale_pivot/i18n/ca_ES.po
  partner_sale_pivot/i18n/de.po
  partner_sale_pivot/i18n/es.po
  partner_sale_pivot/i18n/hr.po
  partner_sale_pivot/i18n/it.po
  partner_sale_pivot/i18n/partner_sale_pivot.pot
  partner_sale_pivot/pyproject.toml
  partner_sale_pivot/readme/CONTRIBUTORS.md
  partner_sale_pivot/readme/DESCRIPTION.md
  partner_sale_pivot/readme/USAGE.md
  partner_sale_pivot/static/description/icon.png
  partner_sale_pivot/static/description/index.html
  partner_sale_pivot/views/res_partner_views.xml
  partner_sale_pivot/views/sale_report_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3798 [15.0][IMP] sale_stock_secondary_unit: Avoid dependency from sale_purchase_secondary_unit
  sale_stock_secondary_unit/models/__init__.py
  sale_stock_secondary_unit/models/stock_rule.py
Labels: approved, bot is merging ⏳

#3791 [FIX] sale_exception: 'ignore_exception' field visibility by group
  sale_exception/views/sale_view.xml
Labels: enhancement, approved, merged 🎉

#3757 [16.0][IMP] sale_order_line_cancel: Allow to decrease product_uom_qty on line cancel
  sale_order_line_cancel/__manifest__.py
  sale_order_line_cancel/models/__init__.py
  sale_order_line_cancel/models/res_company.py
  sale_order_line_cancel/models/res_config_settings.py
  sale_order_line_cancel/models/sale_order_line.py
  sale_order_line_cancel/tests/test_sale_order_line_cancel.py
  sale_order_line_cancel/views/res_config_settings_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#3795 [18.0][MIG] sale_order_line_input: Migration to 18.0
  sale_order_line_input/README.rst
  sale_order_line_input/__init__.py
  sale_order_line_input/__manifest__.py
  sale_order_line_input/i18n/de.po
  sale_order_line_input/i18n/es.po
  sale_order_line_input/i18n/it.po
  sale_order_line_input/i18n/sale_order_line_input.pot
  sale_order_line_input/i18n/tr.po
  sale_order_line_input/i18n/zh_CN.po
  sale_order_line_input/models/__init__.py
  sale_order_line_input/models/sale_order.py
  sale_order_line_input/pyproject.toml
  sale_order_line_input/readme/CONTRIBUTORS.md
  sale_order_line_input/readme/DESCRIPTION.md
  sale_order_line_input/readme/USAGE.md
  sale_order_line_input/static/description/icon.png
  sale_order_line_input/static/description/index.html
  sale_order_line_input/tests/__init__.py
  sale_order_line_input/tests/test_sale_order_line_input.py
  sale_order_line_input/views/sale_order_line_view.xml
Labels: approved, bot is merging ⏳

#3805 [17.0][IMP] sale_blanket_order: context in readme
  sale_blanket_order/README.rst
  sale_blanket_order/readme/CONTEXT.md
  sale_blanket_order/static/description/index.html
Labels: enhancement, bot is merging ⏳

#3796 [18.0][ADD] sale_order_line_stock_move_history: New module sale_order_line_stock_move_history
  sale_order_line_stock_move_history/README.rst
  sale_order_line_stock_move_history/__init__.py
  sale_order_line_stock_move_history/__manifest__.py
  sale_order_line_stock_move_history/i18n/es.po
  sale_order_line_stock_move_history/i18n/sale_order_line_stock_move_history.pot
  sale_order_line_stock_move_history/models/__init__.py
  sale_order_line_stock_move_history/models/sale_order_line.py
  sale_order_line_stock_move_history/pyproject.toml
  sale_order_line_stock_move_history/readme/CONTRIBUTORS.md
  sale_order_line_stock_move_history/readme/DESCRIPTION.md
  sale_order_line_stock_move_history/readme/USAGE.md
  sale_order_line_stock_move_history/static/description/icon.png
  sale_order_line_stock_move_history/static/description/index.html
  sale_order_line_stock_move_history/views/sale_order_views.xml
  sale_order_line_stock_move_history/views/stock_move_views.xml
Labels: approved, bot is merging ⏳

#3826 [17.0][MIG] sale_order_warn_message: Migration to version 17.0
  sale_order_warn_message/README.rst
  sale_order_warn_message/__init__.py
  sale_order_warn_message/__manifest__.py
  sale_order_warn_message/i18n/es.po
  sale_order_warn_message/i18n/it.po
  sale_order_warn_message/i18n/sale_order_warn_message.pot
  sale_order_warn_message/models/__init__.py
  sale_order_warn_message/models/sale_order.py
  sale_order_warn_message/pyproject.toml
  sale_order_warn_message/readme/CONTRIBUTORS.md
  sale_order_warn_message/readme/DESCRIPTION.md
  sale_order_warn_message/static/description/icon.png
  sale_order_warn_message/static/description/index.html
  sale_order_warn_message/tests/__init__.py
  sale_order_warn_message/tests/test_sale_order_warn_message.py
  sale_order_warn_message/views/sale_order.xml
Labels: bot is merging ⏳

#3581 [18.0][MIG] sale_substate: Migration to 18.0
  sale_substate/README.rst
  sale_substate/__init__.py
  sale_substate/__manifest__.py
  sale_substate/data/sale_substate_data.xml
  sale_substate/data/sale_substate_demo.xml
  sale_substate/data/sale_substate_mail_template_data.xml
  sale_substate/i18n/es.po
  sale_substate/i18n/it.po
  sale_substate/i18n/sale_substate.pot
  sale_substate/models/__init__.py
  sale_substate/models/sale_order.py
  sale_substate/pyproject.toml
  sale_substate/readme/CONTRIBUTORS.md
  sale_substate/readme/DESCRIPTION.md
  sale_substate/readme/USAGE.md
  sale_substate/static/description/icon.png
  sale_substate/static/description/index.html
  sale_substate/tests/__init__.py
  sale_substate/tests/test_sale_substate.py
  sale_substate/views/sale_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3828 [FIX] sale_partner_selectable_option: Don't allow to create or edit orders when a partner not selectable is added.
  sale_partner_selectable_option/README.rst
  sale_partner_selectable_option/i18n/es.po
  sale_partner_selectable_option/i18n/sale_partner_selectable_option.pot
  sale_partner_selectable_option/models/sale_order.py
  sale_partner_selectable_option/readme/CONTRIBUTORS.rst
  sale_partner_selectable_option/static/description/index.html
Labels: approved, bot is merging ⏳

#3830 [16.0][ADD] portal_sale_order_search: Add new module
  portal_sale_order_search/README.rst
  portal_sale_order_search/__init__.py
  portal_sale_order_search/__manifest__.py
  portal_sale_order_search/controllers/__init__.py
  portal_sale_order_search/controllers/main.py
  portal_sale_order_search/i18n/es.po
  portal_sale_order_search/i18n/portal_sale_order_search.pot
  portal_sale_order_search/readme/CONTRIBUTORS.rst
  portal_sale_order_search/readme/DESCRIPTION.rst
  portal_sale_order_search/static/description/icon.png
  portal_sale_order_search/static/description/index.html
  setup/portal_sale_order_search/odoo/addons/portal_sale_order_search
  setup/portal_sale_order_search/setup.py
Labels: approved, bot is merging ⏳

#3836 [FIX] sale_packaging_default: Don't use modulo operator to check if qty is a multiple
  sale_packaging_default/README.rst
  sale_packaging_default/models/sale_order_line.py
  sale_packaging_default/readme/CONTRIBUTORS.md
  sale_packaging_default/static/description/index.html
  sale_packaging_default/tests/test_sale_packaging_default.py
Labels: bot is merging ⏳

#3509 [IMP] sale_manual_delivery: enable multiple deliveries
  sale_manual_delivery/models/sale_order.py
Labels: approved, bot is merging ⏳

#3772 [17.0][IMP] sale_delivery_state: add delivery status field to search views
  sale_delivery_state/views/sale_order_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
